/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.hitss.layer.model.impl;

import com.hitss.layer.model.LogOperaciones;
import com.hitss.layer.model.LogOperacionesModel;
import com.hitss.layer.model.LogOperacionesSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the LogOperaciones service. Represents a row in the &quot;LogOperaciones&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.hitss.layer.model.LogOperacionesModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LogOperacionesImpl}.
 * </p>
 *
 * @author Danielle Delgado
 * @see LogOperacionesImpl
 * @see com.hitss.layer.model.LogOperaciones
 * @see com.hitss.layer.model.LogOperacionesModel
 * @generated
 */
@JSON(strict = true)
public class LogOperacionesModelImpl extends BaseModelImpl<LogOperaciones>
	implements LogOperacionesModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a log operaciones model instance should use the {@link com.hitss.layer.model.LogOperaciones} interface instead.
	 */
	public static final String TABLE_NAME = "LogOperaciones";
	public static final Object[][] TABLE_COLUMNS = {
			{ "logOperacionesId", Types.BIGINT },
			{ "tipoActividad", Types.BIGINT },
			{ "actividad", Types.VARCHAR },
			{ "usuario", Types.VARCHAR },
			{ "activo", Types.BOOLEAN },
			{ "usuariocrea", Types.BIGINT },
			{ "fechacrea", Types.TIMESTAMP },
			{ "usuariomodifica", Types.BIGINT },
			{ "fechacreamodifica", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table LogOperaciones (logOperacionesId LONG not null primary key,tipoActividad LONG,actividad VARCHAR(75) null,usuario VARCHAR(75) null,activo BOOLEAN,usuariocrea LONG,fechacrea DATE null,usuariomodifica LONG,fechacreamodifica DATE null)";
	public static final String TABLE_SQL_DROP = "drop table LogOperaciones";
	public static final String ORDER_BY_JPQL = " ORDER BY logOperaciones.fechacreamodifica ASC";
	public static final String ORDER_BY_SQL = " ORDER BY LogOperaciones.fechacreamodifica ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.hitss.layer.model.LogOperaciones"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.hitss.layer.model.LogOperaciones"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static LogOperaciones toModel(LogOperacionesSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		LogOperaciones model = new LogOperacionesImpl();

		model.setLogOperacionesId(soapModel.getLogOperacionesId());
		model.setTipoActividad(soapModel.getTipoActividad());
		model.setActividad(soapModel.getActividad());
		model.setUsuario(soapModel.getUsuario());
		model.setActivo(soapModel.getActivo());
		model.setUsuariocrea(soapModel.getUsuariocrea());
		model.setFechacrea(soapModel.getFechacrea());
		model.setUsuariomodifica(soapModel.getUsuariomodifica());
		model.setFechacreamodifica(soapModel.getFechacreamodifica());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<LogOperaciones> toModels(LogOperacionesSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<LogOperaciones> models = new ArrayList<LogOperaciones>(soapModels.length);

		for (LogOperacionesSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.hitss.layer.model.LogOperaciones"));

	public LogOperacionesModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _logOperacionesId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLogOperacionesId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _logOperacionesId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LogOperaciones.class;
	}

	@Override
	public String getModelClassName() {
		return LogOperaciones.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("logOperacionesId", getLogOperacionesId());
		attributes.put("tipoActividad", getTipoActividad());
		attributes.put("actividad", getActividad());
		attributes.put("usuario", getUsuario());
		attributes.put("activo", getActivo());
		attributes.put("usuariocrea", getUsuariocrea());
		attributes.put("fechacrea", getFechacrea());
		attributes.put("usuariomodifica", getUsuariomodifica());
		attributes.put("fechacreamodifica", getFechacreamodifica());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long logOperacionesId = (Long)attributes.get("logOperacionesId");

		if (logOperacionesId != null) {
			setLogOperacionesId(logOperacionesId);
		}

		Long tipoActividad = (Long)attributes.get("tipoActividad");

		if (tipoActividad != null) {
			setTipoActividad(tipoActividad);
		}

		String actividad = (String)attributes.get("actividad");

		if (actividad != null) {
			setActividad(actividad);
		}

		String usuario = (String)attributes.get("usuario");

		if (usuario != null) {
			setUsuario(usuario);
		}

		Boolean activo = (Boolean)attributes.get("activo");

		if (activo != null) {
			setActivo(activo);
		}

		Long usuariocrea = (Long)attributes.get("usuariocrea");

		if (usuariocrea != null) {
			setUsuariocrea(usuariocrea);
		}

		Date fechacrea = (Date)attributes.get("fechacrea");

		if (fechacrea != null) {
			setFechacrea(fechacrea);
		}

		Long usuariomodifica = (Long)attributes.get("usuariomodifica");

		if (usuariomodifica != null) {
			setUsuariomodifica(usuariomodifica);
		}

		Date fechacreamodifica = (Date)attributes.get("fechacreamodifica");

		if (fechacreamodifica != null) {
			setFechacreamodifica(fechacreamodifica);
		}
	}

	@JSON
	@Override
	public long getLogOperacionesId() {
		return _logOperacionesId;
	}

	@Override
	public void setLogOperacionesId(long logOperacionesId) {
		_logOperacionesId = logOperacionesId;
	}

	@JSON
	@Override
	public long getTipoActividad() {
		return _tipoActividad;
	}

	@Override
	public void setTipoActividad(long tipoActividad) {
		_tipoActividad = tipoActividad;
	}

	@JSON
	@Override
	public String getActividad() {
		if (_actividad == null) {
			return StringPool.BLANK;
		}
		else {
			return _actividad;
		}
	}

	@Override
	public void setActividad(String actividad) {
		_actividad = actividad;
	}

	@JSON
	@Override
	public String getUsuario() {
		if (_usuario == null) {
			return StringPool.BLANK;
		}
		else {
			return _usuario;
		}
	}

	@Override
	public void setUsuario(String usuario) {
		_usuario = usuario;
	}

	@JSON
	@Override
	public boolean getActivo() {
		return _activo;
	}

	@Override
	public boolean isActivo() {
		return _activo;
	}

	@Override
	public void setActivo(boolean activo) {
		_activo = activo;
	}

	@JSON
	@Override
	public long getUsuariocrea() {
		return _usuariocrea;
	}

	@Override
	public void setUsuariocrea(long usuariocrea) {
		_usuariocrea = usuariocrea;
	}

	@JSON
	@Override
	public Date getFechacrea() {
		return _fechacrea;
	}

	@Override
	public void setFechacrea(Date fechacrea) {
		_fechacrea = fechacrea;
	}

	@JSON
	@Override
	public long getUsuariomodifica() {
		return _usuariomodifica;
	}

	@Override
	public void setUsuariomodifica(long usuariomodifica) {
		_usuariomodifica = usuariomodifica;
	}

	@JSON
	@Override
	public Date getFechacreamodifica() {
		return _fechacreamodifica;
	}

	@Override
	public void setFechacreamodifica(Date fechacreamodifica) {
		_fechacreamodifica = fechacreamodifica;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			LogOperaciones.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LogOperaciones toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (LogOperaciones)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LogOperacionesImpl logOperacionesImpl = new LogOperacionesImpl();

		logOperacionesImpl.setLogOperacionesId(getLogOperacionesId());
		logOperacionesImpl.setTipoActividad(getTipoActividad());
		logOperacionesImpl.setActividad(getActividad());
		logOperacionesImpl.setUsuario(getUsuario());
		logOperacionesImpl.setActivo(getActivo());
		logOperacionesImpl.setUsuariocrea(getUsuariocrea());
		logOperacionesImpl.setFechacrea(getFechacrea());
		logOperacionesImpl.setUsuariomodifica(getUsuariomodifica());
		logOperacionesImpl.setFechacreamodifica(getFechacreamodifica());

		logOperacionesImpl.resetOriginalValues();

		return logOperacionesImpl;
	}

	@Override
	public int compareTo(LogOperaciones logOperaciones) {
		int value = 0;

		value = DateUtil.compareTo(getFechacreamodifica(),
				logOperaciones.getFechacreamodifica());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof LogOperaciones)) {
			return false;
		}

		LogOperaciones logOperaciones = (LogOperaciones)obj;

		long primaryKey = logOperaciones.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<LogOperaciones> toCacheModel() {
		LogOperacionesCacheModel logOperacionesCacheModel = new LogOperacionesCacheModel();

		logOperacionesCacheModel.logOperacionesId = getLogOperacionesId();

		logOperacionesCacheModel.tipoActividad = getTipoActividad();

		logOperacionesCacheModel.actividad = getActividad();

		String actividad = logOperacionesCacheModel.actividad;

		if ((actividad != null) && (actividad.length() == 0)) {
			logOperacionesCacheModel.actividad = null;
		}

		logOperacionesCacheModel.usuario = getUsuario();

		String usuario = logOperacionesCacheModel.usuario;

		if ((usuario != null) && (usuario.length() == 0)) {
			logOperacionesCacheModel.usuario = null;
		}

		logOperacionesCacheModel.activo = getActivo();

		logOperacionesCacheModel.usuariocrea = getUsuariocrea();

		Date fechacrea = getFechacrea();

		if (fechacrea != null) {
			logOperacionesCacheModel.fechacrea = fechacrea.getTime();
		}
		else {
			logOperacionesCacheModel.fechacrea = Long.MIN_VALUE;
		}

		logOperacionesCacheModel.usuariomodifica = getUsuariomodifica();

		Date fechacreamodifica = getFechacreamodifica();

		if (fechacreamodifica != null) {
			logOperacionesCacheModel.fechacreamodifica = fechacreamodifica.getTime();
		}
		else {
			logOperacionesCacheModel.fechacreamodifica = Long.MIN_VALUE;
		}

		return logOperacionesCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{logOperacionesId=");
		sb.append(getLogOperacionesId());
		sb.append(", tipoActividad=");
		sb.append(getTipoActividad());
		sb.append(", actividad=");
		sb.append(getActividad());
		sb.append(", usuario=");
		sb.append(getUsuario());
		sb.append(", activo=");
		sb.append(getActivo());
		sb.append(", usuariocrea=");
		sb.append(getUsuariocrea());
		sb.append(", fechacrea=");
		sb.append(getFechacrea());
		sb.append(", usuariomodifica=");
		sb.append(getUsuariomodifica());
		sb.append(", fechacreamodifica=");
		sb.append(getFechacreamodifica());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.hitss.layer.model.LogOperaciones");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>logOperacionesId</column-name><column-value><![CDATA[");
		sb.append(getLogOperacionesId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tipoActividad</column-name><column-value><![CDATA[");
		sb.append(getTipoActividad());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>actividad</column-name><column-value><![CDATA[");
		sb.append(getActividad());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>usuario</column-name><column-value><![CDATA[");
		sb.append(getUsuario());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>activo</column-name><column-value><![CDATA[");
		sb.append(getActivo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>usuariocrea</column-name><column-value><![CDATA[");
		sb.append(getUsuariocrea());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fechacrea</column-name><column-value><![CDATA[");
		sb.append(getFechacrea());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>usuariomodifica</column-name><column-value><![CDATA[");
		sb.append(getUsuariomodifica());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fechacreamodifica</column-name><column-value><![CDATA[");
		sb.append(getFechacreamodifica());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = LogOperaciones.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			LogOperaciones.class
		};
	private long _logOperacionesId;
	private long _tipoActividad;
	private String _actividad;
	private String _usuario;
	private boolean _activo;
	private long _usuariocrea;
	private Date _fechacrea;
	private long _usuariomodifica;
	private Date _fechacreamodifica;
	private LogOperaciones _escapedModel;
}