/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rec.hitss.layer.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import com.rec.hitss.layer.model.FuncionUsuario;
import com.rec.hitss.layer.service.FuncionUsuarioService;
import com.rec.hitss.layer.service.persistence.ActividadPlanPersistence;
import com.rec.hitss.layer.service.persistence.ActividadesPersistence;
import com.rec.hitss.layer.service.persistence.CertificadoPersistence;
import com.rec.hitss.layer.service.persistence.ConocimientoPersistence;
import com.rec.hitss.layer.service.persistence.ContratoPersistence;
import com.rec.hitss.layer.service.persistence.CriteriosEvaluacionPersistence;
import com.rec.hitss.layer.service.persistence.CronogramaEvaluacionPersonalPersistence;
import com.rec.hitss.layer.service.persistence.EntrevistaPersistence;
import com.rec.hitss.layer.service.persistence.EstudioPersistence;
import com.rec.hitss.layer.service.persistence.EtiquetaPersistence;
import com.rec.hitss.layer.service.persistence.EvaluacionPersistence;
import com.rec.hitss.layer.service.persistence.EvaluacionPreguntaPersistence;
import com.rec.hitss.layer.service.persistence.ExperienciaPersistence;
import com.rec.hitss.layer.service.persistence.FuncionPersistence;
import com.rec.hitss.layer.service.persistence.FuncionRequerimientoPersistence;
import com.rec.hitss.layer.service.persistence.FuncionUsuarioPersistence;
import com.rec.hitss.layer.service.persistence.InformeRetroalimentacionPersistence;
import com.rec.hitss.layer.service.persistence.ParametroPersistence;
import com.rec.hitss.layer.service.persistence.PlanAccionPersistence;
import com.rec.hitss.layer.service.persistence.PreguntaPersistence;
import com.rec.hitss.layer.service.persistence.PrioridadEquiposPersistence;
import com.rec.hitss.layer.service.persistence.PuestoPersistence;
import com.rec.hitss.layer.service.persistence.ReferenciaPersistence;
import com.rec.hitss.layer.service.persistence.RequerimientoRecursoPersistence;
import com.rec.hitss.layer.service.persistence.RequisitoPersistence;
import com.rec.hitss.layer.service.persistence.RespuestaPersistence;
import com.rec.hitss.layer.service.persistence.ResultadoEvaluacionPersistence;
import com.rec.hitss.layer.service.persistence.SolicitudEvaluacionDesempenoPersistence;
import com.rec.hitss.layer.service.persistence.SolicitudRequerimientoPersonalPersistence;
import com.rec.hitss.layer.service.persistence.UsuarioGrupoPersistence;
import com.rec.hitss.layer.service.persistence.UsuarioHitssPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the funcion usuario remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.rec.hitss.layer.service.impl.FuncionUsuarioServiceImpl}.
 * </p>
 *
 * @author Crossfire
 * @see com.rec.hitss.layer.service.impl.FuncionUsuarioServiceImpl
 * @see com.rec.hitss.layer.service.FuncionUsuarioServiceUtil
 * @generated
 */
public abstract class FuncionUsuarioServiceBaseImpl extends BaseServiceImpl
	implements FuncionUsuarioService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.rec.hitss.layer.service.FuncionUsuarioServiceUtil} to access the funcion usuario remote service.
	 */

	/**
	 * Returns the actividades local service.
	 *
	 * @return the actividades local service
	 */
	public com.rec.hitss.layer.service.ActividadesLocalService getActividadesLocalService() {
		return actividadesLocalService;
	}

	/**
	 * Sets the actividades local service.
	 *
	 * @param actividadesLocalService the actividades local service
	 */
	public void setActividadesLocalService(
		com.rec.hitss.layer.service.ActividadesLocalService actividadesLocalService) {
		this.actividadesLocalService = actividadesLocalService;
	}

	/**
	 * Returns the actividades remote service.
	 *
	 * @return the actividades remote service
	 */
	public com.rec.hitss.layer.service.ActividadesService getActividadesService() {
		return actividadesService;
	}

	/**
	 * Sets the actividades remote service.
	 *
	 * @param actividadesService the actividades remote service
	 */
	public void setActividadesService(
		com.rec.hitss.layer.service.ActividadesService actividadesService) {
		this.actividadesService = actividadesService;
	}

	/**
	 * Returns the actividades persistence.
	 *
	 * @return the actividades persistence
	 */
	public ActividadesPersistence getActividadesPersistence() {
		return actividadesPersistence;
	}

	/**
	 * Sets the actividades persistence.
	 *
	 * @param actividadesPersistence the actividades persistence
	 */
	public void setActividadesPersistence(
		ActividadesPersistence actividadesPersistence) {
		this.actividadesPersistence = actividadesPersistence;
	}

	/**
	 * Returns the actividad plan local service.
	 *
	 * @return the actividad plan local service
	 */
	public com.rec.hitss.layer.service.ActividadPlanLocalService getActividadPlanLocalService() {
		return actividadPlanLocalService;
	}

	/**
	 * Sets the actividad plan local service.
	 *
	 * @param actividadPlanLocalService the actividad plan local service
	 */
	public void setActividadPlanLocalService(
		com.rec.hitss.layer.service.ActividadPlanLocalService actividadPlanLocalService) {
		this.actividadPlanLocalService = actividadPlanLocalService;
	}

	/**
	 * Returns the actividad plan remote service.
	 *
	 * @return the actividad plan remote service
	 */
	public com.rec.hitss.layer.service.ActividadPlanService getActividadPlanService() {
		return actividadPlanService;
	}

	/**
	 * Sets the actividad plan remote service.
	 *
	 * @param actividadPlanService the actividad plan remote service
	 */
	public void setActividadPlanService(
		com.rec.hitss.layer.service.ActividadPlanService actividadPlanService) {
		this.actividadPlanService = actividadPlanService;
	}

	/**
	 * Returns the actividad plan persistence.
	 *
	 * @return the actividad plan persistence
	 */
	public ActividadPlanPersistence getActividadPlanPersistence() {
		return actividadPlanPersistence;
	}

	/**
	 * Sets the actividad plan persistence.
	 *
	 * @param actividadPlanPersistence the actividad plan persistence
	 */
	public void setActividadPlanPersistence(
		ActividadPlanPersistence actividadPlanPersistence) {
		this.actividadPlanPersistence = actividadPlanPersistence;
	}

	/**
	 * Returns the certificado local service.
	 *
	 * @return the certificado local service
	 */
	public com.rec.hitss.layer.service.CertificadoLocalService getCertificadoLocalService() {
		return certificadoLocalService;
	}

	/**
	 * Sets the certificado local service.
	 *
	 * @param certificadoLocalService the certificado local service
	 */
	public void setCertificadoLocalService(
		com.rec.hitss.layer.service.CertificadoLocalService certificadoLocalService) {
		this.certificadoLocalService = certificadoLocalService;
	}

	/**
	 * Returns the certificado remote service.
	 *
	 * @return the certificado remote service
	 */
	public com.rec.hitss.layer.service.CertificadoService getCertificadoService() {
		return certificadoService;
	}

	/**
	 * Sets the certificado remote service.
	 *
	 * @param certificadoService the certificado remote service
	 */
	public void setCertificadoService(
		com.rec.hitss.layer.service.CertificadoService certificadoService) {
		this.certificadoService = certificadoService;
	}

	/**
	 * Returns the certificado persistence.
	 *
	 * @return the certificado persistence
	 */
	public CertificadoPersistence getCertificadoPersistence() {
		return certificadoPersistence;
	}

	/**
	 * Sets the certificado persistence.
	 *
	 * @param certificadoPersistence the certificado persistence
	 */
	public void setCertificadoPersistence(
		CertificadoPersistence certificadoPersistence) {
		this.certificadoPersistence = certificadoPersistence;
	}

	/**
	 * Returns the conocimiento local service.
	 *
	 * @return the conocimiento local service
	 */
	public com.rec.hitss.layer.service.ConocimientoLocalService getConocimientoLocalService() {
		return conocimientoLocalService;
	}

	/**
	 * Sets the conocimiento local service.
	 *
	 * @param conocimientoLocalService the conocimiento local service
	 */
	public void setConocimientoLocalService(
		com.rec.hitss.layer.service.ConocimientoLocalService conocimientoLocalService) {
		this.conocimientoLocalService = conocimientoLocalService;
	}

	/**
	 * Returns the conocimiento remote service.
	 *
	 * @return the conocimiento remote service
	 */
	public com.rec.hitss.layer.service.ConocimientoService getConocimientoService() {
		return conocimientoService;
	}

	/**
	 * Sets the conocimiento remote service.
	 *
	 * @param conocimientoService the conocimiento remote service
	 */
	public void setConocimientoService(
		com.rec.hitss.layer.service.ConocimientoService conocimientoService) {
		this.conocimientoService = conocimientoService;
	}

	/**
	 * Returns the conocimiento persistence.
	 *
	 * @return the conocimiento persistence
	 */
	public ConocimientoPersistence getConocimientoPersistence() {
		return conocimientoPersistence;
	}

	/**
	 * Sets the conocimiento persistence.
	 *
	 * @param conocimientoPersistence the conocimiento persistence
	 */
	public void setConocimientoPersistence(
		ConocimientoPersistence conocimientoPersistence) {
		this.conocimientoPersistence = conocimientoPersistence;
	}

	/**
	 * Returns the contrato local service.
	 *
	 * @return the contrato local service
	 */
	public com.rec.hitss.layer.service.ContratoLocalService getContratoLocalService() {
		return contratoLocalService;
	}

	/**
	 * Sets the contrato local service.
	 *
	 * @param contratoLocalService the contrato local service
	 */
	public void setContratoLocalService(
		com.rec.hitss.layer.service.ContratoLocalService contratoLocalService) {
		this.contratoLocalService = contratoLocalService;
	}

	/**
	 * Returns the contrato remote service.
	 *
	 * @return the contrato remote service
	 */
	public com.rec.hitss.layer.service.ContratoService getContratoService() {
		return contratoService;
	}

	/**
	 * Sets the contrato remote service.
	 *
	 * @param contratoService the contrato remote service
	 */
	public void setContratoService(
		com.rec.hitss.layer.service.ContratoService contratoService) {
		this.contratoService = contratoService;
	}

	/**
	 * Returns the contrato persistence.
	 *
	 * @return the contrato persistence
	 */
	public ContratoPersistence getContratoPersistence() {
		return contratoPersistence;
	}

	/**
	 * Sets the contrato persistence.
	 *
	 * @param contratoPersistence the contrato persistence
	 */
	public void setContratoPersistence(ContratoPersistence contratoPersistence) {
		this.contratoPersistence = contratoPersistence;
	}

	/**
	 * Returns the criterios evaluacion local service.
	 *
	 * @return the criterios evaluacion local service
	 */
	public com.rec.hitss.layer.service.CriteriosEvaluacionLocalService getCriteriosEvaluacionLocalService() {
		return criteriosEvaluacionLocalService;
	}

	/**
	 * Sets the criterios evaluacion local service.
	 *
	 * @param criteriosEvaluacionLocalService the criterios evaluacion local service
	 */
	public void setCriteriosEvaluacionLocalService(
		com.rec.hitss.layer.service.CriteriosEvaluacionLocalService criteriosEvaluacionLocalService) {
		this.criteriosEvaluacionLocalService = criteriosEvaluacionLocalService;
	}

	/**
	 * Returns the criterios evaluacion remote service.
	 *
	 * @return the criterios evaluacion remote service
	 */
	public com.rec.hitss.layer.service.CriteriosEvaluacionService getCriteriosEvaluacionService() {
		return criteriosEvaluacionService;
	}

	/**
	 * Sets the criterios evaluacion remote service.
	 *
	 * @param criteriosEvaluacionService the criterios evaluacion remote service
	 */
	public void setCriteriosEvaluacionService(
		com.rec.hitss.layer.service.CriteriosEvaluacionService criteriosEvaluacionService) {
		this.criteriosEvaluacionService = criteriosEvaluacionService;
	}

	/**
	 * Returns the criterios evaluacion persistence.
	 *
	 * @return the criterios evaluacion persistence
	 */
	public CriteriosEvaluacionPersistence getCriteriosEvaluacionPersistence() {
		return criteriosEvaluacionPersistence;
	}

	/**
	 * Sets the criterios evaluacion persistence.
	 *
	 * @param criteriosEvaluacionPersistence the criterios evaluacion persistence
	 */
	public void setCriteriosEvaluacionPersistence(
		CriteriosEvaluacionPersistence criteriosEvaluacionPersistence) {
		this.criteriosEvaluacionPersistence = criteriosEvaluacionPersistence;
	}

	/**
	 * Returns the cronograma evaluacion personal local service.
	 *
	 * @return the cronograma evaluacion personal local service
	 */
	public com.rec.hitss.layer.service.CronogramaEvaluacionPersonalLocalService getCronogramaEvaluacionPersonalLocalService() {
		return cronogramaEvaluacionPersonalLocalService;
	}

	/**
	 * Sets the cronograma evaluacion personal local service.
	 *
	 * @param cronogramaEvaluacionPersonalLocalService the cronograma evaluacion personal local service
	 */
	public void setCronogramaEvaluacionPersonalLocalService(
		com.rec.hitss.layer.service.CronogramaEvaluacionPersonalLocalService cronogramaEvaluacionPersonalLocalService) {
		this.cronogramaEvaluacionPersonalLocalService = cronogramaEvaluacionPersonalLocalService;
	}

	/**
	 * Returns the cronograma evaluacion personal remote service.
	 *
	 * @return the cronograma evaluacion personal remote service
	 */
	public com.rec.hitss.layer.service.CronogramaEvaluacionPersonalService getCronogramaEvaluacionPersonalService() {
		return cronogramaEvaluacionPersonalService;
	}

	/**
	 * Sets the cronograma evaluacion personal remote service.
	 *
	 * @param cronogramaEvaluacionPersonalService the cronograma evaluacion personal remote service
	 */
	public void setCronogramaEvaluacionPersonalService(
		com.rec.hitss.layer.service.CronogramaEvaluacionPersonalService cronogramaEvaluacionPersonalService) {
		this.cronogramaEvaluacionPersonalService = cronogramaEvaluacionPersonalService;
	}

	/**
	 * Returns the cronograma evaluacion personal persistence.
	 *
	 * @return the cronograma evaluacion personal persistence
	 */
	public CronogramaEvaluacionPersonalPersistence getCronogramaEvaluacionPersonalPersistence() {
		return cronogramaEvaluacionPersonalPersistence;
	}

	/**
	 * Sets the cronograma evaluacion personal persistence.
	 *
	 * @param cronogramaEvaluacionPersonalPersistence the cronograma evaluacion personal persistence
	 */
	public void setCronogramaEvaluacionPersonalPersistence(
		CronogramaEvaluacionPersonalPersistence cronogramaEvaluacionPersonalPersistence) {
		this.cronogramaEvaluacionPersonalPersistence = cronogramaEvaluacionPersonalPersistence;
	}

	/**
	 * Returns the entrevista local service.
	 *
	 * @return the entrevista local service
	 */
	public com.rec.hitss.layer.service.EntrevistaLocalService getEntrevistaLocalService() {
		return entrevistaLocalService;
	}

	/**
	 * Sets the entrevista local service.
	 *
	 * @param entrevistaLocalService the entrevista local service
	 */
	public void setEntrevistaLocalService(
		com.rec.hitss.layer.service.EntrevistaLocalService entrevistaLocalService) {
		this.entrevistaLocalService = entrevistaLocalService;
	}

	/**
	 * Returns the entrevista remote service.
	 *
	 * @return the entrevista remote service
	 */
	public com.rec.hitss.layer.service.EntrevistaService getEntrevistaService() {
		return entrevistaService;
	}

	/**
	 * Sets the entrevista remote service.
	 *
	 * @param entrevistaService the entrevista remote service
	 */
	public void setEntrevistaService(
		com.rec.hitss.layer.service.EntrevistaService entrevistaService) {
		this.entrevistaService = entrevistaService;
	}

	/**
	 * Returns the entrevista persistence.
	 *
	 * @return the entrevista persistence
	 */
	public EntrevistaPersistence getEntrevistaPersistence() {
		return entrevistaPersistence;
	}

	/**
	 * Sets the entrevista persistence.
	 *
	 * @param entrevistaPersistence the entrevista persistence
	 */
	public void setEntrevistaPersistence(
		EntrevistaPersistence entrevistaPersistence) {
		this.entrevistaPersistence = entrevistaPersistence;
	}

	/**
	 * Returns the estudio local service.
	 *
	 * @return the estudio local service
	 */
	public com.rec.hitss.layer.service.EstudioLocalService getEstudioLocalService() {
		return estudioLocalService;
	}

	/**
	 * Sets the estudio local service.
	 *
	 * @param estudioLocalService the estudio local service
	 */
	public void setEstudioLocalService(
		com.rec.hitss.layer.service.EstudioLocalService estudioLocalService) {
		this.estudioLocalService = estudioLocalService;
	}

	/**
	 * Returns the estudio remote service.
	 *
	 * @return the estudio remote service
	 */
	public com.rec.hitss.layer.service.EstudioService getEstudioService() {
		return estudioService;
	}

	/**
	 * Sets the estudio remote service.
	 *
	 * @param estudioService the estudio remote service
	 */
	public void setEstudioService(
		com.rec.hitss.layer.service.EstudioService estudioService) {
		this.estudioService = estudioService;
	}

	/**
	 * Returns the estudio persistence.
	 *
	 * @return the estudio persistence
	 */
	public EstudioPersistence getEstudioPersistence() {
		return estudioPersistence;
	}

	/**
	 * Sets the estudio persistence.
	 *
	 * @param estudioPersistence the estudio persistence
	 */
	public void setEstudioPersistence(EstudioPersistence estudioPersistence) {
		this.estudioPersistence = estudioPersistence;
	}

	/**
	 * Returns the etiqueta local service.
	 *
	 * @return the etiqueta local service
	 */
	public com.rec.hitss.layer.service.EtiquetaLocalService getEtiquetaLocalService() {
		return etiquetaLocalService;
	}

	/**
	 * Sets the etiqueta local service.
	 *
	 * @param etiquetaLocalService the etiqueta local service
	 */
	public void setEtiquetaLocalService(
		com.rec.hitss.layer.service.EtiquetaLocalService etiquetaLocalService) {
		this.etiquetaLocalService = etiquetaLocalService;
	}

	/**
	 * Returns the etiqueta remote service.
	 *
	 * @return the etiqueta remote service
	 */
	public com.rec.hitss.layer.service.EtiquetaService getEtiquetaService() {
		return etiquetaService;
	}

	/**
	 * Sets the etiqueta remote service.
	 *
	 * @param etiquetaService the etiqueta remote service
	 */
	public void setEtiquetaService(
		com.rec.hitss.layer.service.EtiquetaService etiquetaService) {
		this.etiquetaService = etiquetaService;
	}

	/**
	 * Returns the etiqueta persistence.
	 *
	 * @return the etiqueta persistence
	 */
	public EtiquetaPersistence getEtiquetaPersistence() {
		return etiquetaPersistence;
	}

	/**
	 * Sets the etiqueta persistence.
	 *
	 * @param etiquetaPersistence the etiqueta persistence
	 */
	public void setEtiquetaPersistence(EtiquetaPersistence etiquetaPersistence) {
		this.etiquetaPersistence = etiquetaPersistence;
	}

	/**
	 * Returns the evaluacion local service.
	 *
	 * @return the evaluacion local service
	 */
	public com.rec.hitss.layer.service.EvaluacionLocalService getEvaluacionLocalService() {
		return evaluacionLocalService;
	}

	/**
	 * Sets the evaluacion local service.
	 *
	 * @param evaluacionLocalService the evaluacion local service
	 */
	public void setEvaluacionLocalService(
		com.rec.hitss.layer.service.EvaluacionLocalService evaluacionLocalService) {
		this.evaluacionLocalService = evaluacionLocalService;
	}

	/**
	 * Returns the evaluacion remote service.
	 *
	 * @return the evaluacion remote service
	 */
	public com.rec.hitss.layer.service.EvaluacionService getEvaluacionService() {
		return evaluacionService;
	}

	/**
	 * Sets the evaluacion remote service.
	 *
	 * @param evaluacionService the evaluacion remote service
	 */
	public void setEvaluacionService(
		com.rec.hitss.layer.service.EvaluacionService evaluacionService) {
		this.evaluacionService = evaluacionService;
	}

	/**
	 * Returns the evaluacion persistence.
	 *
	 * @return the evaluacion persistence
	 */
	public EvaluacionPersistence getEvaluacionPersistence() {
		return evaluacionPersistence;
	}

	/**
	 * Sets the evaluacion persistence.
	 *
	 * @param evaluacionPersistence the evaluacion persistence
	 */
	public void setEvaluacionPersistence(
		EvaluacionPersistence evaluacionPersistence) {
		this.evaluacionPersistence = evaluacionPersistence;
	}

	/**
	 * Returns the evaluacion pregunta local service.
	 *
	 * @return the evaluacion pregunta local service
	 */
	public com.rec.hitss.layer.service.EvaluacionPreguntaLocalService getEvaluacionPreguntaLocalService() {
		return evaluacionPreguntaLocalService;
	}

	/**
	 * Sets the evaluacion pregunta local service.
	 *
	 * @param evaluacionPreguntaLocalService the evaluacion pregunta local service
	 */
	public void setEvaluacionPreguntaLocalService(
		com.rec.hitss.layer.service.EvaluacionPreguntaLocalService evaluacionPreguntaLocalService) {
		this.evaluacionPreguntaLocalService = evaluacionPreguntaLocalService;
	}

	/**
	 * Returns the evaluacion pregunta remote service.
	 *
	 * @return the evaluacion pregunta remote service
	 */
	public com.rec.hitss.layer.service.EvaluacionPreguntaService getEvaluacionPreguntaService() {
		return evaluacionPreguntaService;
	}

	/**
	 * Sets the evaluacion pregunta remote service.
	 *
	 * @param evaluacionPreguntaService the evaluacion pregunta remote service
	 */
	public void setEvaluacionPreguntaService(
		com.rec.hitss.layer.service.EvaluacionPreguntaService evaluacionPreguntaService) {
		this.evaluacionPreguntaService = evaluacionPreguntaService;
	}

	/**
	 * Returns the evaluacion pregunta persistence.
	 *
	 * @return the evaluacion pregunta persistence
	 */
	public EvaluacionPreguntaPersistence getEvaluacionPreguntaPersistence() {
		return evaluacionPreguntaPersistence;
	}

	/**
	 * Sets the evaluacion pregunta persistence.
	 *
	 * @param evaluacionPreguntaPersistence the evaluacion pregunta persistence
	 */
	public void setEvaluacionPreguntaPersistence(
		EvaluacionPreguntaPersistence evaluacionPreguntaPersistence) {
		this.evaluacionPreguntaPersistence = evaluacionPreguntaPersistence;
	}

	/**
	 * Returns the experiencia local service.
	 *
	 * @return the experiencia local service
	 */
	public com.rec.hitss.layer.service.ExperienciaLocalService getExperienciaLocalService() {
		return experienciaLocalService;
	}

	/**
	 * Sets the experiencia local service.
	 *
	 * @param experienciaLocalService the experiencia local service
	 */
	public void setExperienciaLocalService(
		com.rec.hitss.layer.service.ExperienciaLocalService experienciaLocalService) {
		this.experienciaLocalService = experienciaLocalService;
	}

	/**
	 * Returns the experiencia remote service.
	 *
	 * @return the experiencia remote service
	 */
	public com.rec.hitss.layer.service.ExperienciaService getExperienciaService() {
		return experienciaService;
	}

	/**
	 * Sets the experiencia remote service.
	 *
	 * @param experienciaService the experiencia remote service
	 */
	public void setExperienciaService(
		com.rec.hitss.layer.service.ExperienciaService experienciaService) {
		this.experienciaService = experienciaService;
	}

	/**
	 * Returns the experiencia persistence.
	 *
	 * @return the experiencia persistence
	 */
	public ExperienciaPersistence getExperienciaPersistence() {
		return experienciaPersistence;
	}

	/**
	 * Sets the experiencia persistence.
	 *
	 * @param experienciaPersistence the experiencia persistence
	 */
	public void setExperienciaPersistence(
		ExperienciaPersistence experienciaPersistence) {
		this.experienciaPersistence = experienciaPersistence;
	}

	/**
	 * Returns the funcion local service.
	 *
	 * @return the funcion local service
	 */
	public com.rec.hitss.layer.service.FuncionLocalService getFuncionLocalService() {
		return funcionLocalService;
	}

	/**
	 * Sets the funcion local service.
	 *
	 * @param funcionLocalService the funcion local service
	 */
	public void setFuncionLocalService(
		com.rec.hitss.layer.service.FuncionLocalService funcionLocalService) {
		this.funcionLocalService = funcionLocalService;
	}

	/**
	 * Returns the funcion remote service.
	 *
	 * @return the funcion remote service
	 */
	public com.rec.hitss.layer.service.FuncionService getFuncionService() {
		return funcionService;
	}

	/**
	 * Sets the funcion remote service.
	 *
	 * @param funcionService the funcion remote service
	 */
	public void setFuncionService(
		com.rec.hitss.layer.service.FuncionService funcionService) {
		this.funcionService = funcionService;
	}

	/**
	 * Returns the funcion persistence.
	 *
	 * @return the funcion persistence
	 */
	public FuncionPersistence getFuncionPersistence() {
		return funcionPersistence;
	}

	/**
	 * Sets the funcion persistence.
	 *
	 * @param funcionPersistence the funcion persistence
	 */
	public void setFuncionPersistence(FuncionPersistence funcionPersistence) {
		this.funcionPersistence = funcionPersistence;
	}

	/**
	 * Returns the funcion requerimiento local service.
	 *
	 * @return the funcion requerimiento local service
	 */
	public com.rec.hitss.layer.service.FuncionRequerimientoLocalService getFuncionRequerimientoLocalService() {
		return funcionRequerimientoLocalService;
	}

	/**
	 * Sets the funcion requerimiento local service.
	 *
	 * @param funcionRequerimientoLocalService the funcion requerimiento local service
	 */
	public void setFuncionRequerimientoLocalService(
		com.rec.hitss.layer.service.FuncionRequerimientoLocalService funcionRequerimientoLocalService) {
		this.funcionRequerimientoLocalService = funcionRequerimientoLocalService;
	}

	/**
	 * Returns the funcion requerimiento remote service.
	 *
	 * @return the funcion requerimiento remote service
	 */
	public com.rec.hitss.layer.service.FuncionRequerimientoService getFuncionRequerimientoService() {
		return funcionRequerimientoService;
	}

	/**
	 * Sets the funcion requerimiento remote service.
	 *
	 * @param funcionRequerimientoService the funcion requerimiento remote service
	 */
	public void setFuncionRequerimientoService(
		com.rec.hitss.layer.service.FuncionRequerimientoService funcionRequerimientoService) {
		this.funcionRequerimientoService = funcionRequerimientoService;
	}

	/**
	 * Returns the funcion requerimiento persistence.
	 *
	 * @return the funcion requerimiento persistence
	 */
	public FuncionRequerimientoPersistence getFuncionRequerimientoPersistence() {
		return funcionRequerimientoPersistence;
	}

	/**
	 * Sets the funcion requerimiento persistence.
	 *
	 * @param funcionRequerimientoPersistence the funcion requerimiento persistence
	 */
	public void setFuncionRequerimientoPersistence(
		FuncionRequerimientoPersistence funcionRequerimientoPersistence) {
		this.funcionRequerimientoPersistence = funcionRequerimientoPersistence;
	}

	/**
	 * Returns the funcion usuario local service.
	 *
	 * @return the funcion usuario local service
	 */
	public com.rec.hitss.layer.service.FuncionUsuarioLocalService getFuncionUsuarioLocalService() {
		return funcionUsuarioLocalService;
	}

	/**
	 * Sets the funcion usuario local service.
	 *
	 * @param funcionUsuarioLocalService the funcion usuario local service
	 */
	public void setFuncionUsuarioLocalService(
		com.rec.hitss.layer.service.FuncionUsuarioLocalService funcionUsuarioLocalService) {
		this.funcionUsuarioLocalService = funcionUsuarioLocalService;
	}

	/**
	 * Returns the funcion usuario remote service.
	 *
	 * @return the funcion usuario remote service
	 */
	public com.rec.hitss.layer.service.FuncionUsuarioService getFuncionUsuarioService() {
		return funcionUsuarioService;
	}

	/**
	 * Sets the funcion usuario remote service.
	 *
	 * @param funcionUsuarioService the funcion usuario remote service
	 */
	public void setFuncionUsuarioService(
		com.rec.hitss.layer.service.FuncionUsuarioService funcionUsuarioService) {
		this.funcionUsuarioService = funcionUsuarioService;
	}

	/**
	 * Returns the funcion usuario persistence.
	 *
	 * @return the funcion usuario persistence
	 */
	public FuncionUsuarioPersistence getFuncionUsuarioPersistence() {
		return funcionUsuarioPersistence;
	}

	/**
	 * Sets the funcion usuario persistence.
	 *
	 * @param funcionUsuarioPersistence the funcion usuario persistence
	 */
	public void setFuncionUsuarioPersistence(
		FuncionUsuarioPersistence funcionUsuarioPersistence) {
		this.funcionUsuarioPersistence = funcionUsuarioPersistence;
	}

	/**
	 * Returns the informe retroalimentacion local service.
	 *
	 * @return the informe retroalimentacion local service
	 */
	public com.rec.hitss.layer.service.InformeRetroalimentacionLocalService getInformeRetroalimentacionLocalService() {
		return informeRetroalimentacionLocalService;
	}

	/**
	 * Sets the informe retroalimentacion local service.
	 *
	 * @param informeRetroalimentacionLocalService the informe retroalimentacion local service
	 */
	public void setInformeRetroalimentacionLocalService(
		com.rec.hitss.layer.service.InformeRetroalimentacionLocalService informeRetroalimentacionLocalService) {
		this.informeRetroalimentacionLocalService = informeRetroalimentacionLocalService;
	}

	/**
	 * Returns the informe retroalimentacion remote service.
	 *
	 * @return the informe retroalimentacion remote service
	 */
	public com.rec.hitss.layer.service.InformeRetroalimentacionService getInformeRetroalimentacionService() {
		return informeRetroalimentacionService;
	}

	/**
	 * Sets the informe retroalimentacion remote service.
	 *
	 * @param informeRetroalimentacionService the informe retroalimentacion remote service
	 */
	public void setInformeRetroalimentacionService(
		com.rec.hitss.layer.service.InformeRetroalimentacionService informeRetroalimentacionService) {
		this.informeRetroalimentacionService = informeRetroalimentacionService;
	}

	/**
	 * Returns the informe retroalimentacion persistence.
	 *
	 * @return the informe retroalimentacion persistence
	 */
	public InformeRetroalimentacionPersistence getInformeRetroalimentacionPersistence() {
		return informeRetroalimentacionPersistence;
	}

	/**
	 * Sets the informe retroalimentacion persistence.
	 *
	 * @param informeRetroalimentacionPersistence the informe retroalimentacion persistence
	 */
	public void setInformeRetroalimentacionPersistence(
		InformeRetroalimentacionPersistence informeRetroalimentacionPersistence) {
		this.informeRetroalimentacionPersistence = informeRetroalimentacionPersistence;
	}

	/**
	 * Returns the parametro local service.
	 *
	 * @return the parametro local service
	 */
	public com.rec.hitss.layer.service.ParametroLocalService getParametroLocalService() {
		return parametroLocalService;
	}

	/**
	 * Sets the parametro local service.
	 *
	 * @param parametroLocalService the parametro local service
	 */
	public void setParametroLocalService(
		com.rec.hitss.layer.service.ParametroLocalService parametroLocalService) {
		this.parametroLocalService = parametroLocalService;
	}

	/**
	 * Returns the parametro remote service.
	 *
	 * @return the parametro remote service
	 */
	public com.rec.hitss.layer.service.ParametroService getParametroService() {
		return parametroService;
	}

	/**
	 * Sets the parametro remote service.
	 *
	 * @param parametroService the parametro remote service
	 */
	public void setParametroService(
		com.rec.hitss.layer.service.ParametroService parametroService) {
		this.parametroService = parametroService;
	}

	/**
	 * Returns the parametro persistence.
	 *
	 * @return the parametro persistence
	 */
	public ParametroPersistence getParametroPersistence() {
		return parametroPersistence;
	}

	/**
	 * Sets the parametro persistence.
	 *
	 * @param parametroPersistence the parametro persistence
	 */
	public void setParametroPersistence(
		ParametroPersistence parametroPersistence) {
		this.parametroPersistence = parametroPersistence;
	}

	/**
	 * Returns the plan accion local service.
	 *
	 * @return the plan accion local service
	 */
	public com.rec.hitss.layer.service.PlanAccionLocalService getPlanAccionLocalService() {
		return planAccionLocalService;
	}

	/**
	 * Sets the plan accion local service.
	 *
	 * @param planAccionLocalService the plan accion local service
	 */
	public void setPlanAccionLocalService(
		com.rec.hitss.layer.service.PlanAccionLocalService planAccionLocalService) {
		this.planAccionLocalService = planAccionLocalService;
	}

	/**
	 * Returns the plan accion remote service.
	 *
	 * @return the plan accion remote service
	 */
	public com.rec.hitss.layer.service.PlanAccionService getPlanAccionService() {
		return planAccionService;
	}

	/**
	 * Sets the plan accion remote service.
	 *
	 * @param planAccionService the plan accion remote service
	 */
	public void setPlanAccionService(
		com.rec.hitss.layer.service.PlanAccionService planAccionService) {
		this.planAccionService = planAccionService;
	}

	/**
	 * Returns the plan accion persistence.
	 *
	 * @return the plan accion persistence
	 */
	public PlanAccionPersistence getPlanAccionPersistence() {
		return planAccionPersistence;
	}

	/**
	 * Sets the plan accion persistence.
	 *
	 * @param planAccionPersistence the plan accion persistence
	 */
	public void setPlanAccionPersistence(
		PlanAccionPersistence planAccionPersistence) {
		this.planAccionPersistence = planAccionPersistence;
	}

	/**
	 * Returns the pregunta local service.
	 *
	 * @return the pregunta local service
	 */
	public com.rec.hitss.layer.service.PreguntaLocalService getPreguntaLocalService() {
		return preguntaLocalService;
	}

	/**
	 * Sets the pregunta local service.
	 *
	 * @param preguntaLocalService the pregunta local service
	 */
	public void setPreguntaLocalService(
		com.rec.hitss.layer.service.PreguntaLocalService preguntaLocalService) {
		this.preguntaLocalService = preguntaLocalService;
	}

	/**
	 * Returns the pregunta remote service.
	 *
	 * @return the pregunta remote service
	 */
	public com.rec.hitss.layer.service.PreguntaService getPreguntaService() {
		return preguntaService;
	}

	/**
	 * Sets the pregunta remote service.
	 *
	 * @param preguntaService the pregunta remote service
	 */
	public void setPreguntaService(
		com.rec.hitss.layer.service.PreguntaService preguntaService) {
		this.preguntaService = preguntaService;
	}

	/**
	 * Returns the pregunta persistence.
	 *
	 * @return the pregunta persistence
	 */
	public PreguntaPersistence getPreguntaPersistence() {
		return preguntaPersistence;
	}

	/**
	 * Sets the pregunta persistence.
	 *
	 * @param preguntaPersistence the pregunta persistence
	 */
	public void setPreguntaPersistence(PreguntaPersistence preguntaPersistence) {
		this.preguntaPersistence = preguntaPersistence;
	}

	/**
	 * Returns the prioridad equipos local service.
	 *
	 * @return the prioridad equipos local service
	 */
	public com.rec.hitss.layer.service.PrioridadEquiposLocalService getPrioridadEquiposLocalService() {
		return prioridadEquiposLocalService;
	}

	/**
	 * Sets the prioridad equipos local service.
	 *
	 * @param prioridadEquiposLocalService the prioridad equipos local service
	 */
	public void setPrioridadEquiposLocalService(
		com.rec.hitss.layer.service.PrioridadEquiposLocalService prioridadEquiposLocalService) {
		this.prioridadEquiposLocalService = prioridadEquiposLocalService;
	}

	/**
	 * Returns the prioridad equipos remote service.
	 *
	 * @return the prioridad equipos remote service
	 */
	public com.rec.hitss.layer.service.PrioridadEquiposService getPrioridadEquiposService() {
		return prioridadEquiposService;
	}

	/**
	 * Sets the prioridad equipos remote service.
	 *
	 * @param prioridadEquiposService the prioridad equipos remote service
	 */
	public void setPrioridadEquiposService(
		com.rec.hitss.layer.service.PrioridadEquiposService prioridadEquiposService) {
		this.prioridadEquiposService = prioridadEquiposService;
	}

	/**
	 * Returns the prioridad equipos persistence.
	 *
	 * @return the prioridad equipos persistence
	 */
	public PrioridadEquiposPersistence getPrioridadEquiposPersistence() {
		return prioridadEquiposPersistence;
	}

	/**
	 * Sets the prioridad equipos persistence.
	 *
	 * @param prioridadEquiposPersistence the prioridad equipos persistence
	 */
	public void setPrioridadEquiposPersistence(
		PrioridadEquiposPersistence prioridadEquiposPersistence) {
		this.prioridadEquiposPersistence = prioridadEquiposPersistence;
	}

	/**
	 * Returns the puesto local service.
	 *
	 * @return the puesto local service
	 */
	public com.rec.hitss.layer.service.PuestoLocalService getPuestoLocalService() {
		return puestoLocalService;
	}

	/**
	 * Sets the puesto local service.
	 *
	 * @param puestoLocalService the puesto local service
	 */
	public void setPuestoLocalService(
		com.rec.hitss.layer.service.PuestoLocalService puestoLocalService) {
		this.puestoLocalService = puestoLocalService;
	}

	/**
	 * Returns the puesto remote service.
	 *
	 * @return the puesto remote service
	 */
	public com.rec.hitss.layer.service.PuestoService getPuestoService() {
		return puestoService;
	}

	/**
	 * Sets the puesto remote service.
	 *
	 * @param puestoService the puesto remote service
	 */
	public void setPuestoService(
		com.rec.hitss.layer.service.PuestoService puestoService) {
		this.puestoService = puestoService;
	}

	/**
	 * Returns the puesto persistence.
	 *
	 * @return the puesto persistence
	 */
	public PuestoPersistence getPuestoPersistence() {
		return puestoPersistence;
	}

	/**
	 * Sets the puesto persistence.
	 *
	 * @param puestoPersistence the puesto persistence
	 */
	public void setPuestoPersistence(PuestoPersistence puestoPersistence) {
		this.puestoPersistence = puestoPersistence;
	}

	/**
	 * Returns the referencia local service.
	 *
	 * @return the referencia local service
	 */
	public com.rec.hitss.layer.service.ReferenciaLocalService getReferenciaLocalService() {
		return referenciaLocalService;
	}

	/**
	 * Sets the referencia local service.
	 *
	 * @param referenciaLocalService the referencia local service
	 */
	public void setReferenciaLocalService(
		com.rec.hitss.layer.service.ReferenciaLocalService referenciaLocalService) {
		this.referenciaLocalService = referenciaLocalService;
	}

	/**
	 * Returns the referencia remote service.
	 *
	 * @return the referencia remote service
	 */
	public com.rec.hitss.layer.service.ReferenciaService getReferenciaService() {
		return referenciaService;
	}

	/**
	 * Sets the referencia remote service.
	 *
	 * @param referenciaService the referencia remote service
	 */
	public void setReferenciaService(
		com.rec.hitss.layer.service.ReferenciaService referenciaService) {
		this.referenciaService = referenciaService;
	}

	/**
	 * Returns the referencia persistence.
	 *
	 * @return the referencia persistence
	 */
	public ReferenciaPersistence getReferenciaPersistence() {
		return referenciaPersistence;
	}

	/**
	 * Sets the referencia persistence.
	 *
	 * @param referenciaPersistence the referencia persistence
	 */
	public void setReferenciaPersistence(
		ReferenciaPersistence referenciaPersistence) {
		this.referenciaPersistence = referenciaPersistence;
	}

	/**
	 * Returns the requerimiento recurso local service.
	 *
	 * @return the requerimiento recurso local service
	 */
	public com.rec.hitss.layer.service.RequerimientoRecursoLocalService getRequerimientoRecursoLocalService() {
		return requerimientoRecursoLocalService;
	}

	/**
	 * Sets the requerimiento recurso local service.
	 *
	 * @param requerimientoRecursoLocalService the requerimiento recurso local service
	 */
	public void setRequerimientoRecursoLocalService(
		com.rec.hitss.layer.service.RequerimientoRecursoLocalService requerimientoRecursoLocalService) {
		this.requerimientoRecursoLocalService = requerimientoRecursoLocalService;
	}

	/**
	 * Returns the requerimiento recurso persistence.
	 *
	 * @return the requerimiento recurso persistence
	 */
	public RequerimientoRecursoPersistence getRequerimientoRecursoPersistence() {
		return requerimientoRecursoPersistence;
	}

	/**
	 * Sets the requerimiento recurso persistence.
	 *
	 * @param requerimientoRecursoPersistence the requerimiento recurso persistence
	 */
	public void setRequerimientoRecursoPersistence(
		RequerimientoRecursoPersistence requerimientoRecursoPersistence) {
		this.requerimientoRecursoPersistence = requerimientoRecursoPersistence;
	}

	/**
	 * Returns the requisito local service.
	 *
	 * @return the requisito local service
	 */
	public com.rec.hitss.layer.service.RequisitoLocalService getRequisitoLocalService() {
		return requisitoLocalService;
	}

	/**
	 * Sets the requisito local service.
	 *
	 * @param requisitoLocalService the requisito local service
	 */
	public void setRequisitoLocalService(
		com.rec.hitss.layer.service.RequisitoLocalService requisitoLocalService) {
		this.requisitoLocalService = requisitoLocalService;
	}

	/**
	 * Returns the requisito persistence.
	 *
	 * @return the requisito persistence
	 */
	public RequisitoPersistence getRequisitoPersistence() {
		return requisitoPersistence;
	}

	/**
	 * Sets the requisito persistence.
	 *
	 * @param requisitoPersistence the requisito persistence
	 */
	public void setRequisitoPersistence(
		RequisitoPersistence requisitoPersistence) {
		this.requisitoPersistence = requisitoPersistence;
	}

	/**
	 * Returns the respuesta local service.
	 *
	 * @return the respuesta local service
	 */
	public com.rec.hitss.layer.service.RespuestaLocalService getRespuestaLocalService() {
		return respuestaLocalService;
	}

	/**
	 * Sets the respuesta local service.
	 *
	 * @param respuestaLocalService the respuesta local service
	 */
	public void setRespuestaLocalService(
		com.rec.hitss.layer.service.RespuestaLocalService respuestaLocalService) {
		this.respuestaLocalService = respuestaLocalService;
	}

	/**
	 * Returns the respuesta remote service.
	 *
	 * @return the respuesta remote service
	 */
	public com.rec.hitss.layer.service.RespuestaService getRespuestaService() {
		return respuestaService;
	}

	/**
	 * Sets the respuesta remote service.
	 *
	 * @param respuestaService the respuesta remote service
	 */
	public void setRespuestaService(
		com.rec.hitss.layer.service.RespuestaService respuestaService) {
		this.respuestaService = respuestaService;
	}

	/**
	 * Returns the respuesta persistence.
	 *
	 * @return the respuesta persistence
	 */
	public RespuestaPersistence getRespuestaPersistence() {
		return respuestaPersistence;
	}

	/**
	 * Sets the respuesta persistence.
	 *
	 * @param respuestaPersistence the respuesta persistence
	 */
	public void setRespuestaPersistence(
		RespuestaPersistence respuestaPersistence) {
		this.respuestaPersistence = respuestaPersistence;
	}

	/**
	 * Returns the resultado evaluacion local service.
	 *
	 * @return the resultado evaluacion local service
	 */
	public com.rec.hitss.layer.service.ResultadoEvaluacionLocalService getResultadoEvaluacionLocalService() {
		return resultadoEvaluacionLocalService;
	}

	/**
	 * Sets the resultado evaluacion local service.
	 *
	 * @param resultadoEvaluacionLocalService the resultado evaluacion local service
	 */
	public void setResultadoEvaluacionLocalService(
		com.rec.hitss.layer.service.ResultadoEvaluacionLocalService resultadoEvaluacionLocalService) {
		this.resultadoEvaluacionLocalService = resultadoEvaluacionLocalService;
	}

	/**
	 * Returns the resultado evaluacion remote service.
	 *
	 * @return the resultado evaluacion remote service
	 */
	public com.rec.hitss.layer.service.ResultadoEvaluacionService getResultadoEvaluacionService() {
		return resultadoEvaluacionService;
	}

	/**
	 * Sets the resultado evaluacion remote service.
	 *
	 * @param resultadoEvaluacionService the resultado evaluacion remote service
	 */
	public void setResultadoEvaluacionService(
		com.rec.hitss.layer.service.ResultadoEvaluacionService resultadoEvaluacionService) {
		this.resultadoEvaluacionService = resultadoEvaluacionService;
	}

	/**
	 * Returns the resultado evaluacion persistence.
	 *
	 * @return the resultado evaluacion persistence
	 */
	public ResultadoEvaluacionPersistence getResultadoEvaluacionPersistence() {
		return resultadoEvaluacionPersistence;
	}

	/**
	 * Sets the resultado evaluacion persistence.
	 *
	 * @param resultadoEvaluacionPersistence the resultado evaluacion persistence
	 */
	public void setResultadoEvaluacionPersistence(
		ResultadoEvaluacionPersistence resultadoEvaluacionPersistence) {
		this.resultadoEvaluacionPersistence = resultadoEvaluacionPersistence;
	}

	/**
	 * Returns the solicitud evaluacion desempeno local service.
	 *
	 * @return the solicitud evaluacion desempeno local service
	 */
	public com.rec.hitss.layer.service.SolicitudEvaluacionDesempenoLocalService getSolicitudEvaluacionDesempenoLocalService() {
		return solicitudEvaluacionDesempenoLocalService;
	}

	/**
	 * Sets the solicitud evaluacion desempeno local service.
	 *
	 * @param solicitudEvaluacionDesempenoLocalService the solicitud evaluacion desempeno local service
	 */
	public void setSolicitudEvaluacionDesempenoLocalService(
		com.rec.hitss.layer.service.SolicitudEvaluacionDesempenoLocalService solicitudEvaluacionDesempenoLocalService) {
		this.solicitudEvaluacionDesempenoLocalService = solicitudEvaluacionDesempenoLocalService;
	}

	/**
	 * Returns the solicitud evaluacion desempeno remote service.
	 *
	 * @return the solicitud evaluacion desempeno remote service
	 */
	public com.rec.hitss.layer.service.SolicitudEvaluacionDesempenoService getSolicitudEvaluacionDesempenoService() {
		return solicitudEvaluacionDesempenoService;
	}

	/**
	 * Sets the solicitud evaluacion desempeno remote service.
	 *
	 * @param solicitudEvaluacionDesempenoService the solicitud evaluacion desempeno remote service
	 */
	public void setSolicitudEvaluacionDesempenoService(
		com.rec.hitss.layer.service.SolicitudEvaluacionDesempenoService solicitudEvaluacionDesempenoService) {
		this.solicitudEvaluacionDesempenoService = solicitudEvaluacionDesempenoService;
	}

	/**
	 * Returns the solicitud evaluacion desempeno persistence.
	 *
	 * @return the solicitud evaluacion desempeno persistence
	 */
	public SolicitudEvaluacionDesempenoPersistence getSolicitudEvaluacionDesempenoPersistence() {
		return solicitudEvaluacionDesempenoPersistence;
	}

	/**
	 * Sets the solicitud evaluacion desempeno persistence.
	 *
	 * @param solicitudEvaluacionDesempenoPersistence the solicitud evaluacion desempeno persistence
	 */
	public void setSolicitudEvaluacionDesempenoPersistence(
		SolicitudEvaluacionDesempenoPersistence solicitudEvaluacionDesempenoPersistence) {
		this.solicitudEvaluacionDesempenoPersistence = solicitudEvaluacionDesempenoPersistence;
	}

	/**
	 * Returns the solicitud requerimiento personal local service.
	 *
	 * @return the solicitud requerimiento personal local service
	 */
	public com.rec.hitss.layer.service.SolicitudRequerimientoPersonalLocalService getSolicitudRequerimientoPersonalLocalService() {
		return solicitudRequerimientoPersonalLocalService;
	}

	/**
	 * Sets the solicitud requerimiento personal local service.
	 *
	 * @param solicitudRequerimientoPersonalLocalService the solicitud requerimiento personal local service
	 */
	public void setSolicitudRequerimientoPersonalLocalService(
		com.rec.hitss.layer.service.SolicitudRequerimientoPersonalLocalService solicitudRequerimientoPersonalLocalService) {
		this.solicitudRequerimientoPersonalLocalService = solicitudRequerimientoPersonalLocalService;
	}

	/**
	 * Returns the solicitud requerimiento personal persistence.
	 *
	 * @return the solicitud requerimiento personal persistence
	 */
	public SolicitudRequerimientoPersonalPersistence getSolicitudRequerimientoPersonalPersistence() {
		return solicitudRequerimientoPersonalPersistence;
	}

	/**
	 * Sets the solicitud requerimiento personal persistence.
	 *
	 * @param solicitudRequerimientoPersonalPersistence the solicitud requerimiento personal persistence
	 */
	public void setSolicitudRequerimientoPersonalPersistence(
		SolicitudRequerimientoPersonalPersistence solicitudRequerimientoPersonalPersistence) {
		this.solicitudRequerimientoPersonalPersistence = solicitudRequerimientoPersonalPersistence;
	}

	/**
	 * Returns the usuario grupo local service.
	 *
	 * @return the usuario grupo local service
	 */
	public com.rec.hitss.layer.service.UsuarioGrupoLocalService getUsuarioGrupoLocalService() {
		return usuarioGrupoLocalService;
	}

	/**
	 * Sets the usuario grupo local service.
	 *
	 * @param usuarioGrupoLocalService the usuario grupo local service
	 */
	public void setUsuarioGrupoLocalService(
		com.rec.hitss.layer.service.UsuarioGrupoLocalService usuarioGrupoLocalService) {
		this.usuarioGrupoLocalService = usuarioGrupoLocalService;
	}

	/**
	 * Returns the usuario grupo remote service.
	 *
	 * @return the usuario grupo remote service
	 */
	public com.rec.hitss.layer.service.UsuarioGrupoService getUsuarioGrupoService() {
		return usuarioGrupoService;
	}

	/**
	 * Sets the usuario grupo remote service.
	 *
	 * @param usuarioGrupoService the usuario grupo remote service
	 */
	public void setUsuarioGrupoService(
		com.rec.hitss.layer.service.UsuarioGrupoService usuarioGrupoService) {
		this.usuarioGrupoService = usuarioGrupoService;
	}

	/**
	 * Returns the usuario grupo persistence.
	 *
	 * @return the usuario grupo persistence
	 */
	public UsuarioGrupoPersistence getUsuarioGrupoPersistence() {
		return usuarioGrupoPersistence;
	}

	/**
	 * Sets the usuario grupo persistence.
	 *
	 * @param usuarioGrupoPersistence the usuario grupo persistence
	 */
	public void setUsuarioGrupoPersistence(
		UsuarioGrupoPersistence usuarioGrupoPersistence) {
		this.usuarioGrupoPersistence = usuarioGrupoPersistence;
	}

	/**
	 * Returns the usuario hitss local service.
	 *
	 * @return the usuario hitss local service
	 */
	public com.rec.hitss.layer.service.UsuarioHitssLocalService getUsuarioHitssLocalService() {
		return usuarioHitssLocalService;
	}

	/**
	 * Sets the usuario hitss local service.
	 *
	 * @param usuarioHitssLocalService the usuario hitss local service
	 */
	public void setUsuarioHitssLocalService(
		com.rec.hitss.layer.service.UsuarioHitssLocalService usuarioHitssLocalService) {
		this.usuarioHitssLocalService = usuarioHitssLocalService;
	}

	/**
	 * Returns the usuario hitss remote service.
	 *
	 * @return the usuario hitss remote service
	 */
	public com.rec.hitss.layer.service.UsuarioHitssService getUsuarioHitssService() {
		return usuarioHitssService;
	}

	/**
	 * Sets the usuario hitss remote service.
	 *
	 * @param usuarioHitssService the usuario hitss remote service
	 */
	public void setUsuarioHitssService(
		com.rec.hitss.layer.service.UsuarioHitssService usuarioHitssService) {
		this.usuarioHitssService = usuarioHitssService;
	}

	/**
	 * Returns the usuario hitss persistence.
	 *
	 * @return the usuario hitss persistence
	 */
	public UsuarioHitssPersistence getUsuarioHitssPersistence() {
		return usuarioHitssPersistence;
	}

	/**
	 * Sets the usuario hitss persistence.
	 *
	 * @param usuarioHitssPersistence the usuario hitss persistence
	 */
	public void setUsuarioHitssPersistence(
		UsuarioHitssPersistence usuarioHitssPersistence) {
		this.usuarioHitssPersistence = usuarioHitssPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return FuncionUsuario.class;
	}

	protected String getModelClassName() {
		return FuncionUsuario.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = funcionUsuarioPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.rec.hitss.layer.service.ActividadesLocalService.class)
	protected com.rec.hitss.layer.service.ActividadesLocalService actividadesLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.ActividadesService.class)
	protected com.rec.hitss.layer.service.ActividadesService actividadesService;
	@BeanReference(type = ActividadesPersistence.class)
	protected ActividadesPersistence actividadesPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.ActividadPlanLocalService.class)
	protected com.rec.hitss.layer.service.ActividadPlanLocalService actividadPlanLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.ActividadPlanService.class)
	protected com.rec.hitss.layer.service.ActividadPlanService actividadPlanService;
	@BeanReference(type = ActividadPlanPersistence.class)
	protected ActividadPlanPersistence actividadPlanPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.CertificadoLocalService.class)
	protected com.rec.hitss.layer.service.CertificadoLocalService certificadoLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.CertificadoService.class)
	protected com.rec.hitss.layer.service.CertificadoService certificadoService;
	@BeanReference(type = CertificadoPersistence.class)
	protected CertificadoPersistence certificadoPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.ConocimientoLocalService.class)
	protected com.rec.hitss.layer.service.ConocimientoLocalService conocimientoLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.ConocimientoService.class)
	protected com.rec.hitss.layer.service.ConocimientoService conocimientoService;
	@BeanReference(type = ConocimientoPersistence.class)
	protected ConocimientoPersistence conocimientoPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.ContratoLocalService.class)
	protected com.rec.hitss.layer.service.ContratoLocalService contratoLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.ContratoService.class)
	protected com.rec.hitss.layer.service.ContratoService contratoService;
	@BeanReference(type = ContratoPersistence.class)
	protected ContratoPersistence contratoPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.CriteriosEvaluacionLocalService.class)
	protected com.rec.hitss.layer.service.CriteriosEvaluacionLocalService criteriosEvaluacionLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.CriteriosEvaluacionService.class)
	protected com.rec.hitss.layer.service.CriteriosEvaluacionService criteriosEvaluacionService;
	@BeanReference(type = CriteriosEvaluacionPersistence.class)
	protected CriteriosEvaluacionPersistence criteriosEvaluacionPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.CronogramaEvaluacionPersonalLocalService.class)
	protected com.rec.hitss.layer.service.CronogramaEvaluacionPersonalLocalService cronogramaEvaluacionPersonalLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.CronogramaEvaluacionPersonalService.class)
	protected com.rec.hitss.layer.service.CronogramaEvaluacionPersonalService cronogramaEvaluacionPersonalService;
	@BeanReference(type = CronogramaEvaluacionPersonalPersistence.class)
	protected CronogramaEvaluacionPersonalPersistence cronogramaEvaluacionPersonalPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.EntrevistaLocalService.class)
	protected com.rec.hitss.layer.service.EntrevistaLocalService entrevistaLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.EntrevistaService.class)
	protected com.rec.hitss.layer.service.EntrevistaService entrevistaService;
	@BeanReference(type = EntrevistaPersistence.class)
	protected EntrevistaPersistence entrevistaPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.EstudioLocalService.class)
	protected com.rec.hitss.layer.service.EstudioLocalService estudioLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.EstudioService.class)
	protected com.rec.hitss.layer.service.EstudioService estudioService;
	@BeanReference(type = EstudioPersistence.class)
	protected EstudioPersistence estudioPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.EtiquetaLocalService.class)
	protected com.rec.hitss.layer.service.EtiquetaLocalService etiquetaLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.EtiquetaService.class)
	protected com.rec.hitss.layer.service.EtiquetaService etiquetaService;
	@BeanReference(type = EtiquetaPersistence.class)
	protected EtiquetaPersistence etiquetaPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.EvaluacionLocalService.class)
	protected com.rec.hitss.layer.service.EvaluacionLocalService evaluacionLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.EvaluacionService.class)
	protected com.rec.hitss.layer.service.EvaluacionService evaluacionService;
	@BeanReference(type = EvaluacionPersistence.class)
	protected EvaluacionPersistence evaluacionPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.EvaluacionPreguntaLocalService.class)
	protected com.rec.hitss.layer.service.EvaluacionPreguntaLocalService evaluacionPreguntaLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.EvaluacionPreguntaService.class)
	protected com.rec.hitss.layer.service.EvaluacionPreguntaService evaluacionPreguntaService;
	@BeanReference(type = EvaluacionPreguntaPersistence.class)
	protected EvaluacionPreguntaPersistence evaluacionPreguntaPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.ExperienciaLocalService.class)
	protected com.rec.hitss.layer.service.ExperienciaLocalService experienciaLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.ExperienciaService.class)
	protected com.rec.hitss.layer.service.ExperienciaService experienciaService;
	@BeanReference(type = ExperienciaPersistence.class)
	protected ExperienciaPersistence experienciaPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.FuncionLocalService.class)
	protected com.rec.hitss.layer.service.FuncionLocalService funcionLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.FuncionService.class)
	protected com.rec.hitss.layer.service.FuncionService funcionService;
	@BeanReference(type = FuncionPersistence.class)
	protected FuncionPersistence funcionPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.FuncionRequerimientoLocalService.class)
	protected com.rec.hitss.layer.service.FuncionRequerimientoLocalService funcionRequerimientoLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.FuncionRequerimientoService.class)
	protected com.rec.hitss.layer.service.FuncionRequerimientoService funcionRequerimientoService;
	@BeanReference(type = FuncionRequerimientoPersistence.class)
	protected FuncionRequerimientoPersistence funcionRequerimientoPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.FuncionUsuarioLocalService.class)
	protected com.rec.hitss.layer.service.FuncionUsuarioLocalService funcionUsuarioLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.FuncionUsuarioService.class)
	protected com.rec.hitss.layer.service.FuncionUsuarioService funcionUsuarioService;
	@BeanReference(type = FuncionUsuarioPersistence.class)
	protected FuncionUsuarioPersistence funcionUsuarioPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.InformeRetroalimentacionLocalService.class)
	protected com.rec.hitss.layer.service.InformeRetroalimentacionLocalService informeRetroalimentacionLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.InformeRetroalimentacionService.class)
	protected com.rec.hitss.layer.service.InformeRetroalimentacionService informeRetroalimentacionService;
	@BeanReference(type = InformeRetroalimentacionPersistence.class)
	protected InformeRetroalimentacionPersistence informeRetroalimentacionPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.ParametroLocalService.class)
	protected com.rec.hitss.layer.service.ParametroLocalService parametroLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.ParametroService.class)
	protected com.rec.hitss.layer.service.ParametroService parametroService;
	@BeanReference(type = ParametroPersistence.class)
	protected ParametroPersistence parametroPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.PlanAccionLocalService.class)
	protected com.rec.hitss.layer.service.PlanAccionLocalService planAccionLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.PlanAccionService.class)
	protected com.rec.hitss.layer.service.PlanAccionService planAccionService;
	@BeanReference(type = PlanAccionPersistence.class)
	protected PlanAccionPersistence planAccionPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.PreguntaLocalService.class)
	protected com.rec.hitss.layer.service.PreguntaLocalService preguntaLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.PreguntaService.class)
	protected com.rec.hitss.layer.service.PreguntaService preguntaService;
	@BeanReference(type = PreguntaPersistence.class)
	protected PreguntaPersistence preguntaPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.PrioridadEquiposLocalService.class)
	protected com.rec.hitss.layer.service.PrioridadEquiposLocalService prioridadEquiposLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.PrioridadEquiposService.class)
	protected com.rec.hitss.layer.service.PrioridadEquiposService prioridadEquiposService;
	@BeanReference(type = PrioridadEquiposPersistence.class)
	protected PrioridadEquiposPersistence prioridadEquiposPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.PuestoLocalService.class)
	protected com.rec.hitss.layer.service.PuestoLocalService puestoLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.PuestoService.class)
	protected com.rec.hitss.layer.service.PuestoService puestoService;
	@BeanReference(type = PuestoPersistence.class)
	protected PuestoPersistence puestoPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.ReferenciaLocalService.class)
	protected com.rec.hitss.layer.service.ReferenciaLocalService referenciaLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.ReferenciaService.class)
	protected com.rec.hitss.layer.service.ReferenciaService referenciaService;
	@BeanReference(type = ReferenciaPersistence.class)
	protected ReferenciaPersistence referenciaPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.RequerimientoRecursoLocalService.class)
	protected com.rec.hitss.layer.service.RequerimientoRecursoLocalService requerimientoRecursoLocalService;
	@BeanReference(type = RequerimientoRecursoPersistence.class)
	protected RequerimientoRecursoPersistence requerimientoRecursoPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.RequisitoLocalService.class)
	protected com.rec.hitss.layer.service.RequisitoLocalService requisitoLocalService;
	@BeanReference(type = RequisitoPersistence.class)
	protected RequisitoPersistence requisitoPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.RespuestaLocalService.class)
	protected com.rec.hitss.layer.service.RespuestaLocalService respuestaLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.RespuestaService.class)
	protected com.rec.hitss.layer.service.RespuestaService respuestaService;
	@BeanReference(type = RespuestaPersistence.class)
	protected RespuestaPersistence respuestaPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.ResultadoEvaluacionLocalService.class)
	protected com.rec.hitss.layer.service.ResultadoEvaluacionLocalService resultadoEvaluacionLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.ResultadoEvaluacionService.class)
	protected com.rec.hitss.layer.service.ResultadoEvaluacionService resultadoEvaluacionService;
	@BeanReference(type = ResultadoEvaluacionPersistence.class)
	protected ResultadoEvaluacionPersistence resultadoEvaluacionPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.SolicitudEvaluacionDesempenoLocalService.class)
	protected com.rec.hitss.layer.service.SolicitudEvaluacionDesempenoLocalService solicitudEvaluacionDesempenoLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.SolicitudEvaluacionDesempenoService.class)
	protected com.rec.hitss.layer.service.SolicitudEvaluacionDesempenoService solicitudEvaluacionDesempenoService;
	@BeanReference(type = SolicitudEvaluacionDesempenoPersistence.class)
	protected SolicitudEvaluacionDesempenoPersistence solicitudEvaluacionDesempenoPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.SolicitudRequerimientoPersonalLocalService.class)
	protected com.rec.hitss.layer.service.SolicitudRequerimientoPersonalLocalService solicitudRequerimientoPersonalLocalService;
	@BeanReference(type = SolicitudRequerimientoPersonalPersistence.class)
	protected SolicitudRequerimientoPersonalPersistence solicitudRequerimientoPersonalPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.UsuarioGrupoLocalService.class)
	protected com.rec.hitss.layer.service.UsuarioGrupoLocalService usuarioGrupoLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.UsuarioGrupoService.class)
	protected com.rec.hitss.layer.service.UsuarioGrupoService usuarioGrupoService;
	@BeanReference(type = UsuarioGrupoPersistence.class)
	protected UsuarioGrupoPersistence usuarioGrupoPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.UsuarioHitssLocalService.class)
	protected com.rec.hitss.layer.service.UsuarioHitssLocalService usuarioHitssLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.UsuarioHitssService.class)
	protected com.rec.hitss.layer.service.UsuarioHitssService usuarioHitssService;
	@BeanReference(type = UsuarioHitssPersistence.class)
	protected UsuarioHitssPersistence usuarioHitssPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private FuncionUsuarioServiceClpInvoker _clpInvoker = new FuncionUsuarioServiceClpInvoker();
}