/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.hitss.layer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Contrato service. Represents a row in the &quot;Contrato&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.hitss.layer.model.impl.ContratoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.hitss.layer.model.impl.ContratoImpl}.
 * </p>
 *
 * @author Danielle Delgado
 * @see Contrato
 * @see com.hitss.layer.model.impl.ContratoImpl
 * @see com.hitss.layer.model.impl.ContratoModelImpl
 * @generated
 */
public interface ContratoModel extends BaseModel<Contrato> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a contrato model instance should use the {@link Contrato} interface instead.
	 */

	/**
	 * Returns the primary key of this contrato.
	 *
	 * @return the primary key of this contrato
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this contrato.
	 *
	 * @param primaryKey the primary key of this contrato
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the contrato ID of this contrato.
	 *
	 * @return the contrato ID of this contrato
	 */
	public long getContratoId();

	/**
	 * Sets the contrato ID of this contrato.
	 *
	 * @param contratoId the contrato ID of this contrato
	 */
	public void setContratoId(long contratoId);

	/**
	 * Returns the usuario ID of this contrato.
	 *
	 * @return the usuario ID of this contrato
	 */
	public long getUsuarioId();

	/**
	 * Sets the usuario ID of this contrato.
	 *
	 * @param usuarioId the usuario ID of this contrato
	 */
	public void setUsuarioId(long usuarioId);

	/**
	 * Returns the motivo of this contrato.
	 *
	 * @return the motivo of this contrato
	 */
	@AutoEscape
	public String getMotivo();

	/**
	 * Sets the motivo of this contrato.
	 *
	 * @param motivo the motivo of this contrato
	 */
	public void setMotivo(String motivo);

	/**
	 * Returns the descripcion of this contrato.
	 *
	 * @return the descripcion of this contrato
	 */
	@AutoEscape
	public String getDescripcion();

	/**
	 * Sets the descripcion of this contrato.
	 *
	 * @param descripcion the descripcion of this contrato
	 */
	public void setDescripcion(String descripcion);

	/**
	 * Returns the titulo of this contrato.
	 *
	 * @return the titulo of this contrato
	 */
	@AutoEscape
	public String getTitulo();

	/**
	 * Sets the titulo of this contrato.
	 *
	 * @param titulo the titulo of this contrato
	 */
	public void setTitulo(String titulo);

	/**
	 * Returns the activo of this contrato.
	 *
	 * @return the activo of this contrato
	 */
	public boolean getActivo();

	/**
	 * Returns <code>true</code> if this contrato is activo.
	 *
	 * @return <code>true</code> if this contrato is activo; <code>false</code> otherwise
	 */
	public boolean isActivo();

	/**
	 * Sets whether this contrato is activo.
	 *
	 * @param activo the activo of this contrato
	 */
	public void setActivo(boolean activo);

	/**
	 * Returns the usuariocrea of this contrato.
	 *
	 * @return the usuariocrea of this contrato
	 */
	public long getUsuariocrea();

	/**
	 * Sets the usuariocrea of this contrato.
	 *
	 * @param usuariocrea the usuariocrea of this contrato
	 */
	public void setUsuariocrea(long usuariocrea);

	/**
	 * Returns the fechacrea of this contrato.
	 *
	 * @return the fechacrea of this contrato
	 */
	public Date getFechacrea();

	/**
	 * Sets the fechacrea of this contrato.
	 *
	 * @param fechacrea the fechacrea of this contrato
	 */
	public void setFechacrea(Date fechacrea);

	/**
	 * Returns the usuariomodifica of this contrato.
	 *
	 * @return the usuariomodifica of this contrato
	 */
	public long getUsuariomodifica();

	/**
	 * Sets the usuariomodifica of this contrato.
	 *
	 * @param usuariomodifica the usuariomodifica of this contrato
	 */
	public void setUsuariomodifica(long usuariomodifica);

	/**
	 * Returns the fechacreamodifica of this contrato.
	 *
	 * @return the fechacreamodifica of this contrato
	 */
	public Date getFechacreamodifica();

	/**
	 * Sets the fechacreamodifica of this contrato.
	 *
	 * @param fechacreamodifica the fechacreamodifica of this contrato
	 */
	public void setFechacreamodifica(Date fechacreamodifica);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.hitss.layer.model.Contrato contrato);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.hitss.layer.model.Contrato> toCacheModel();

	@Override
	public com.hitss.layer.model.Contrato toEscapedModel();

	@Override
	public com.hitss.layer.model.Contrato toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}