/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.hitss.layer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Cronograma service. Represents a row in the &quot;Cronograma&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.hitss.layer.model.impl.CronogramaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.hitss.layer.model.impl.CronogramaImpl}.
 * </p>
 *
 * @author Danielle Delgado
 * @see Cronograma
 * @see com.hitss.layer.model.impl.CronogramaImpl
 * @see com.hitss.layer.model.impl.CronogramaModelImpl
 * @generated
 */
public interface CronogramaModel extends BaseModel<Cronograma> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cronograma model instance should use the {@link Cronograma} interface instead.
	 */

	/**
	 * Returns the primary key of this cronograma.
	 *
	 * @return the primary key of this cronograma
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cronograma.
	 *
	 * @param primaryKey the primary key of this cronograma
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the cronograma ID of this cronograma.
	 *
	 * @return the cronograma ID of this cronograma
	 */
	public long getCronogramaId();

	/**
	 * Sets the cronograma ID of this cronograma.
	 *
	 * @param cronogramaId the cronograma ID of this cronograma
	 */
	public void setCronogramaId(long cronogramaId);

	/**
	 * Returns the solicitud evaluacion desempenno ID of this cronograma.
	 *
	 * @return the solicitud evaluacion desempenno ID of this cronograma
	 */
	public long getSolicitudEvaluacionDesempennoId();

	/**
	 * Sets the solicitud evaluacion desempenno ID of this cronograma.
	 *
	 * @param solicitudEvaluacionDesempennoId the solicitud evaluacion desempenno ID of this cronograma
	 */
	public void setSolicitudEvaluacionDesempennoId(
		long solicitudEvaluacionDesempennoId);

	/**
	 * Returns the descripcion of this cronograma.
	 *
	 * @return the descripcion of this cronograma
	 */
	@AutoEscape
	public String getDescripcion();

	/**
	 * Sets the descripcion of this cronograma.
	 *
	 * @param descripcion the descripcion of this cronograma
	 */
	public void setDescripcion(String descripcion);

	/**
	 * Returns the estado of this cronograma.
	 *
	 * @return the estado of this cronograma
	 */
	public long getEstado();

	/**
	 * Sets the estado of this cronograma.
	 *
	 * @param estado the estado of this cronograma
	 */
	public void setEstado(long estado);

	/**
	 * Returns the activo of this cronograma.
	 *
	 * @return the activo of this cronograma
	 */
	public boolean getActivo();

	/**
	 * Returns <code>true</code> if this cronograma is activo.
	 *
	 * @return <code>true</code> if this cronograma is activo; <code>false</code> otherwise
	 */
	public boolean isActivo();

	/**
	 * Sets whether this cronograma is activo.
	 *
	 * @param activo the activo of this cronograma
	 */
	public void setActivo(boolean activo);

	/**
	 * Returns the usuariocrea of this cronograma.
	 *
	 * @return the usuariocrea of this cronograma
	 */
	public long getUsuariocrea();

	/**
	 * Sets the usuariocrea of this cronograma.
	 *
	 * @param usuariocrea the usuariocrea of this cronograma
	 */
	public void setUsuariocrea(long usuariocrea);

	/**
	 * Returns the fechacrea of this cronograma.
	 *
	 * @return the fechacrea of this cronograma
	 */
	public Date getFechacrea();

	/**
	 * Sets the fechacrea of this cronograma.
	 *
	 * @param fechacrea the fechacrea of this cronograma
	 */
	public void setFechacrea(Date fechacrea);

	/**
	 * Returns the usuariomodifica of this cronograma.
	 *
	 * @return the usuariomodifica of this cronograma
	 */
	public long getUsuariomodifica();

	/**
	 * Sets the usuariomodifica of this cronograma.
	 *
	 * @param usuariomodifica the usuariomodifica of this cronograma
	 */
	public void setUsuariomodifica(long usuariomodifica);

	/**
	 * Returns the fechacreamodifica of this cronograma.
	 *
	 * @return the fechacreamodifica of this cronograma
	 */
	public Date getFechacreamodifica();

	/**
	 * Sets the fechacreamodifica of this cronograma.
	 *
	 * @param fechacreamodifica the fechacreamodifica of this cronograma
	 */
	public void setFechacreamodifica(Date fechacreamodifica);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.hitss.layer.model.Cronograma cronograma);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.hitss.layer.model.Cronograma> toCacheModel();

	@Override
	public com.hitss.layer.model.Cronograma toEscapedModel();

	@Override
	public com.hitss.layer.model.Cronograma toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}