/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.hitss.layer.model;

import com.hitss.layer.service.persistence.EvaluacionPreguntaPK;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the EvaluacionPregunta service. Represents a row in the &quot;EvaluacionPregunta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.hitss.layer.model.impl.EvaluacionPreguntaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.hitss.layer.model.impl.EvaluacionPreguntaImpl}.
 * </p>
 *
 * @author Danielle Delgado
 * @see EvaluacionPregunta
 * @see com.hitss.layer.model.impl.EvaluacionPreguntaImpl
 * @see com.hitss.layer.model.impl.EvaluacionPreguntaModelImpl
 * @generated
 */
public interface EvaluacionPreguntaModel extends BaseModel<EvaluacionPregunta> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a evaluacion pregunta model instance should use the {@link EvaluacionPregunta} interface instead.
	 */

	/**
	 * Returns the primary key of this evaluacion pregunta.
	 *
	 * @return the primary key of this evaluacion pregunta
	 */
	public EvaluacionPreguntaPK getPrimaryKey();

	/**
	 * Sets the primary key of this evaluacion pregunta.
	 *
	 * @param primaryKey the primary key of this evaluacion pregunta
	 */
	public void setPrimaryKey(EvaluacionPreguntaPK primaryKey);

	/**
	 * Returns the evaluacion ID of this evaluacion pregunta.
	 *
	 * @return the evaluacion ID of this evaluacion pregunta
	 */
	public long getEvaluacionId();

	/**
	 * Sets the evaluacion ID of this evaluacion pregunta.
	 *
	 * @param evaluacionId the evaluacion ID of this evaluacion pregunta
	 */
	public void setEvaluacionId(long evaluacionId);

	/**
	 * Returns the pregunta ID of this evaluacion pregunta.
	 *
	 * @return the pregunta ID of this evaluacion pregunta
	 */
	public long getPreguntaId();

	/**
	 * Sets the pregunta ID of this evaluacion pregunta.
	 *
	 * @param preguntaId the pregunta ID of this evaluacion pregunta
	 */
	public void setPreguntaId(long preguntaId);

	/**
	 * Returns the nivel of this evaluacion pregunta.
	 *
	 * @return the nivel of this evaluacion pregunta
	 */
	public long getNivel();

	/**
	 * Sets the nivel of this evaluacion pregunta.
	 *
	 * @param nivel the nivel of this evaluacion pregunta
	 */
	public void setNivel(long nivel);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.hitss.layer.model.EvaluacionPregunta evaluacionPregunta);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.hitss.layer.model.EvaluacionPregunta> toCacheModel();

	@Override
	public com.hitss.layer.model.EvaluacionPregunta toEscapedModel();

	@Override
	public com.hitss.layer.model.EvaluacionPregunta toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}