/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rec.hitss.layer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Conocimiento service. Represents a row in the &quot;Conocimiento&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rec.hitss.layer.model.impl.ConocimientoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rec.hitss.layer.model.impl.ConocimientoImpl}.
 * </p>
 *
 * @author Crossfire
 * @see Conocimiento
 * @see com.rec.hitss.layer.model.impl.ConocimientoImpl
 * @see com.rec.hitss.layer.model.impl.ConocimientoModelImpl
 * @generated
 */
public interface ConocimientoModel extends BaseModel<Conocimiento> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a conocimiento model instance should use the {@link Conocimiento} interface instead.
	 */

	/**
	 * Returns the primary key of this conocimiento.
	 *
	 * @return the primary key of this conocimiento
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this conocimiento.
	 *
	 * @param primaryKey the primary key of this conocimiento
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the conocimiento ID of this conocimiento.
	 *
	 * @return the conocimiento ID of this conocimiento
	 */
	public long getConocimientoId();

	/**
	 * Sets the conocimiento ID of this conocimiento.
	 *
	 * @param conocimientoId the conocimiento ID of this conocimiento
	 */
	public void setConocimientoId(long conocimientoId);

	/**
	 * Returns the descripcion of this conocimiento.
	 *
	 * @return the descripcion of this conocimiento
	 */
	@AutoEscape
	public String getDescripcion();

	/**
	 * Sets the descripcion of this conocimiento.
	 *
	 * @param descripcion the descripcion of this conocimiento
	 */
	public void setDescripcion(String descripcion);

	/**
	 * Returns the etiqueta ID of this conocimiento.
	 *
	 * @return the etiqueta ID of this conocimiento
	 */
	public long getEtiquetaId();

	/**
	 * Sets the etiqueta ID of this conocimiento.
	 *
	 * @param etiquetaId the etiqueta ID of this conocimiento
	 */
	public void setEtiquetaId(long etiquetaId);

	/**
	 * Returns the nivel of this conocimiento.
	 *
	 * @return the nivel of this conocimiento
	 */
	@AutoEscape
	public String getNivel();

	/**
	 * Sets the nivel of this conocimiento.
	 *
	 * @param nivel the nivel of this conocimiento
	 */
	public void setNivel(String nivel);

	/**
	 * Returns the herramiento of this conocimiento.
	 *
	 * @return the herramiento of this conocimiento
	 */
	@AutoEscape
	public String getHerramiento();

	/**
	 * Sets the herramiento of this conocimiento.
	 *
	 * @param herramiento the herramiento of this conocimiento
	 */
	public void setHerramiento(String herramiento);

	/**
	 * Returns the implementacion of this conocimiento.
	 *
	 * @return the implementacion of this conocimiento
	 */
	@AutoEscape
	public String getImplementacion();

	/**
	 * Sets the implementacion of this conocimiento.
	 *
	 * @param implementacion the implementacion of this conocimiento
	 */
	public void setImplementacion(String implementacion);

	/**
	 * Returns the activo of this conocimiento.
	 *
	 * @return the activo of this conocimiento
	 */
	public boolean getActivo();

	/**
	 * Returns <code>true</code> if this conocimiento is activo.
	 *
	 * @return <code>true</code> if this conocimiento is activo; <code>false</code> otherwise
	 */
	public boolean isActivo();

	/**
	 * Sets whether this conocimiento is activo.
	 *
	 * @param activo the activo of this conocimiento
	 */
	public void setActivo(boolean activo);

	/**
	 * Returns the usuariocrea of this conocimiento.
	 *
	 * @return the usuariocrea of this conocimiento
	 */
	public long getUsuariocrea();

	/**
	 * Sets the usuariocrea of this conocimiento.
	 *
	 * @param usuariocrea the usuariocrea of this conocimiento
	 */
	public void setUsuariocrea(long usuariocrea);

	/**
	 * Returns the fechacrea of this conocimiento.
	 *
	 * @return the fechacrea of this conocimiento
	 */
	public Date getFechacrea();

	/**
	 * Sets the fechacrea of this conocimiento.
	 *
	 * @param fechacrea the fechacrea of this conocimiento
	 */
	public void setFechacrea(Date fechacrea);

	/**
	 * Returns the usuariomodifica of this conocimiento.
	 *
	 * @return the usuariomodifica of this conocimiento
	 */
	public long getUsuariomodifica();

	/**
	 * Sets the usuariomodifica of this conocimiento.
	 *
	 * @param usuariomodifica the usuariomodifica of this conocimiento
	 */
	public void setUsuariomodifica(long usuariomodifica);

	/**
	 * Returns the fechacreamodifica of this conocimiento.
	 *
	 * @return the fechacreamodifica of this conocimiento
	 */
	public Date getFechacreamodifica();

	/**
	 * Sets the fechacreamodifica of this conocimiento.
	 *
	 * @param fechacreamodifica the fechacreamodifica of this conocimiento
	 */
	public void setFechacreamodifica(Date fechacreamodifica);

	/**
	 * Returns the usuario hitss ID of this conocimiento.
	 *
	 * @return the usuario hitss ID of this conocimiento
	 */
	public long getUsuarioHitssId();

	/**
	 * Sets the usuario hitss ID of this conocimiento.
	 *
	 * @param usuarioHitssId the usuario hitss ID of this conocimiento
	 */
	public void setUsuarioHitssId(long usuarioHitssId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.rec.hitss.layer.model.Conocimiento conocimiento);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rec.hitss.layer.model.Conocimiento> toCacheModel();

	@Override
	public com.rec.hitss.layer.model.Conocimiento toEscapedModel();

	@Override
	public com.rec.hitss.layer.model.Conocimiento toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}