/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rec.hitss.layer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CriteriosEvaluacion service. Represents a row in the &quot;CriteriosEvaluacion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rec.hitss.layer.model.impl.CriteriosEvaluacionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rec.hitss.layer.model.impl.CriteriosEvaluacionImpl}.
 * </p>
 *
 * @author Crossfire
 * @see CriteriosEvaluacion
 * @see com.rec.hitss.layer.model.impl.CriteriosEvaluacionImpl
 * @see com.rec.hitss.layer.model.impl.CriteriosEvaluacionModelImpl
 * @generated
 */
public interface CriteriosEvaluacionModel extends BaseModel<CriteriosEvaluacion> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a criterios evaluacion model instance should use the {@link CriteriosEvaluacion} interface instead.
	 */

	/**
	 * Returns the primary key of this criterios evaluacion.
	 *
	 * @return the primary key of this criterios evaluacion
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this criterios evaluacion.
	 *
	 * @param primaryKey the primary key of this criterios evaluacion
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the criterios evaluacion ID of this criterios evaluacion.
	 *
	 * @return the criterios evaluacion ID of this criterios evaluacion
	 */
	public long getCriteriosEvaluacionId();

	/**
	 * Sets the criterios evaluacion ID of this criterios evaluacion.
	 *
	 * @param criteriosEvaluacionId the criterios evaluacion ID of this criterios evaluacion
	 */
	public void setCriteriosEvaluacionId(long criteriosEvaluacionId);

	/**
	 * Returns the nombre of this criterios evaluacion.
	 *
	 * @return the nombre of this criterios evaluacion
	 */
	@AutoEscape
	public String getNombre();

	/**
	 * Sets the nombre of this criterios evaluacion.
	 *
	 * @param nombre the nombre of this criterios evaluacion
	 */
	public void setNombre(String nombre);

	/**
	 * Returns the nivel criterio of this criterios evaluacion.
	 *
	 * @return the nivel criterio of this criterios evaluacion
	 */
	@AutoEscape
	public String getNivelCriterio();

	/**
	 * Sets the nivel criterio of this criterios evaluacion.
	 *
	 * @param nivelCriterio the nivel criterio of this criterios evaluacion
	 */
	public void setNivelCriterio(String nivelCriterio);

	/**
	 * Returns the observacion of this criterios evaluacion.
	 *
	 * @return the observacion of this criterios evaluacion
	 */
	@AutoEscape
	public String getObservacion();

	/**
	 * Sets the observacion of this criterios evaluacion.
	 *
	 * @param observacion the observacion of this criterios evaluacion
	 */
	public void setObservacion(String observacion);

	/**
	 * Returns the parametro padre ID of this criterios evaluacion.
	 *
	 * @return the parametro padre ID of this criterios evaluacion
	 */
	public long getParametroPadreId();

	/**
	 * Sets the parametro padre ID of this criterios evaluacion.
	 *
	 * @param parametroPadreId the parametro padre ID of this criterios evaluacion
	 */
	public void setParametroPadreId(long parametroPadreId);

	/**
	 * Returns the evaluacion ID of this criterios evaluacion.
	 *
	 * @return the evaluacion ID of this criterios evaluacion
	 */
	public long getEvaluacionId();

	/**
	 * Sets the evaluacion ID of this criterios evaluacion.
	 *
	 * @param evaluacionId the evaluacion ID of this criterios evaluacion
	 */
	public void setEvaluacionId(long evaluacionId);

	/**
	 * Returns the activo of this criterios evaluacion.
	 *
	 * @return the activo of this criterios evaluacion
	 */
	public boolean getActivo();

	/**
	 * Returns <code>true</code> if this criterios evaluacion is activo.
	 *
	 * @return <code>true</code> if this criterios evaluacion is activo; <code>false</code> otherwise
	 */
	public boolean isActivo();

	/**
	 * Sets whether this criterios evaluacion is activo.
	 *
	 * @param activo the activo of this criterios evaluacion
	 */
	public void setActivo(boolean activo);

	/**
	 * Returns the usuariocrea of this criterios evaluacion.
	 *
	 * @return the usuariocrea of this criterios evaluacion
	 */
	public long getUsuariocrea();

	/**
	 * Sets the usuariocrea of this criterios evaluacion.
	 *
	 * @param usuariocrea the usuariocrea of this criterios evaluacion
	 */
	public void setUsuariocrea(long usuariocrea);

	/**
	 * Returns the fechacrea of this criterios evaluacion.
	 *
	 * @return the fechacrea of this criterios evaluacion
	 */
	public Date getFechacrea();

	/**
	 * Sets the fechacrea of this criterios evaluacion.
	 *
	 * @param fechacrea the fechacrea of this criterios evaluacion
	 */
	public void setFechacrea(Date fechacrea);

	/**
	 * Returns the usuariomodifica of this criterios evaluacion.
	 *
	 * @return the usuariomodifica of this criterios evaluacion
	 */
	public long getUsuariomodifica();

	/**
	 * Sets the usuariomodifica of this criterios evaluacion.
	 *
	 * @param usuariomodifica the usuariomodifica of this criterios evaluacion
	 */
	public void setUsuariomodifica(long usuariomodifica);

	/**
	 * Returns the fechacreamodifica of this criterios evaluacion.
	 *
	 * @return the fechacreamodifica of this criterios evaluacion
	 */
	public Date getFechacreamodifica();

	/**
	 * Sets the fechacreamodifica of this criterios evaluacion.
	 *
	 * @param fechacreamodifica the fechacreamodifica of this criterios evaluacion
	 */
	public void setFechacreamodifica(Date fechacreamodifica);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.rec.hitss.layer.model.CriteriosEvaluacion criteriosEvaluacion);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rec.hitss.layer.model.CriteriosEvaluacion> toCacheModel();

	@Override
	public com.rec.hitss.layer.model.CriteriosEvaluacion toEscapedModel();

	@Override
	public com.rec.hitss.layer.model.CriteriosEvaluacion toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}