/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rec.hitss.layer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CronogramaEvaluacionPersonal service. Represents a row in the &quot;CronogramaEvaluacionPersonal&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rec.hitss.layer.model.impl.CronogramaEvaluacionPersonalModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rec.hitss.layer.model.impl.CronogramaEvaluacionPersonalImpl}.
 * </p>
 *
 * @author Crossfire
 * @see CronogramaEvaluacionPersonal
 * @see com.rec.hitss.layer.model.impl.CronogramaEvaluacionPersonalImpl
 * @see com.rec.hitss.layer.model.impl.CronogramaEvaluacionPersonalModelImpl
 * @generated
 */
public interface CronogramaEvaluacionPersonalModel extends BaseModel<CronogramaEvaluacionPersonal> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cronograma evaluacion personal model instance should use the {@link CronogramaEvaluacionPersonal} interface instead.
	 */

	/**
	 * Returns the primary key of this cronograma evaluacion personal.
	 *
	 * @return the primary key of this cronograma evaluacion personal
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cronograma evaluacion personal.
	 *
	 * @param primaryKey the primary key of this cronograma evaluacion personal
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the cronograma evaluacion personal ID of this cronograma evaluacion personal.
	 *
	 * @return the cronograma evaluacion personal ID of this cronograma evaluacion personal
	 */
	public long getCronogramaEvaluacionPersonalId();

	/**
	 * Sets the cronograma evaluacion personal ID of this cronograma evaluacion personal.
	 *
	 * @param cronogramaEvaluacionPersonalId the cronograma evaluacion personal ID of this cronograma evaluacion personal
	 */
	public void setCronogramaEvaluacionPersonalId(
		long cronogramaEvaluacionPersonalId);

	/**
	 * Returns the solicitud evaluacion desempeno ID of this cronograma evaluacion personal.
	 *
	 * @return the solicitud evaluacion desempeno ID of this cronograma evaluacion personal
	 */
	public long getSolicitudEvaluacionDesempenoId();

	/**
	 * Sets the solicitud evaluacion desempeno ID of this cronograma evaluacion personal.
	 *
	 * @param solicitudEvaluacionDesempenoId the solicitud evaluacion desempeno ID of this cronograma evaluacion personal
	 */
	public void setSolicitudEvaluacionDesempenoId(
		long solicitudEvaluacionDesempenoId);

	/**
	 * Returns the descripcion of this cronograma evaluacion personal.
	 *
	 * @return the descripcion of this cronograma evaluacion personal
	 */
	@AutoEscape
	public String getDescripcion();

	/**
	 * Sets the descripcion of this cronograma evaluacion personal.
	 *
	 * @param descripcion the descripcion of this cronograma evaluacion personal
	 */
	public void setDescripcion(String descripcion);

	/**
	 * Returns the estado of this cronograma evaluacion personal.
	 *
	 * @return the estado of this cronograma evaluacion personal
	 */
	@AutoEscape
	public String getEstado();

	/**
	 * Sets the estado of this cronograma evaluacion personal.
	 *
	 * @param estado the estado of this cronograma evaluacion personal
	 */
	public void setEstado(String estado);

	/**
	 * Returns the observacion of this cronograma evaluacion personal.
	 *
	 * @return the observacion of this cronograma evaluacion personal
	 */
	@AutoEscape
	public String getObservacion();

	/**
	 * Sets the observacion of this cronograma evaluacion personal.
	 *
	 * @param observacion the observacion of this cronograma evaluacion personal
	 */
	public void setObservacion(String observacion);

	/**
	 * Returns the activo of this cronograma evaluacion personal.
	 *
	 * @return the activo of this cronograma evaluacion personal
	 */
	public boolean getActivo();

	/**
	 * Returns <code>true</code> if this cronograma evaluacion personal is activo.
	 *
	 * @return <code>true</code> if this cronograma evaluacion personal is activo; <code>false</code> otherwise
	 */
	public boolean isActivo();

	/**
	 * Sets whether this cronograma evaluacion personal is activo.
	 *
	 * @param activo the activo of this cronograma evaluacion personal
	 */
	public void setActivo(boolean activo);

	/**
	 * Returns the usuariocrea of this cronograma evaluacion personal.
	 *
	 * @return the usuariocrea of this cronograma evaluacion personal
	 */
	public long getUsuariocrea();

	/**
	 * Sets the usuariocrea of this cronograma evaluacion personal.
	 *
	 * @param usuariocrea the usuariocrea of this cronograma evaluacion personal
	 */
	public void setUsuariocrea(long usuariocrea);

	/**
	 * Returns the fechacrea of this cronograma evaluacion personal.
	 *
	 * @return the fechacrea of this cronograma evaluacion personal
	 */
	public Date getFechacrea();

	/**
	 * Sets the fechacrea of this cronograma evaluacion personal.
	 *
	 * @param fechacrea the fechacrea of this cronograma evaluacion personal
	 */
	public void setFechacrea(Date fechacrea);

	/**
	 * Returns the usuariomodifica of this cronograma evaluacion personal.
	 *
	 * @return the usuariomodifica of this cronograma evaluacion personal
	 */
	public long getUsuariomodifica();

	/**
	 * Sets the usuariomodifica of this cronograma evaluacion personal.
	 *
	 * @param usuariomodifica the usuariomodifica of this cronograma evaluacion personal
	 */
	public void setUsuariomodifica(long usuariomodifica);

	/**
	 * Returns the fechacreamodifica of this cronograma evaluacion personal.
	 *
	 * @return the fechacreamodifica of this cronograma evaluacion personal
	 */
	public Date getFechacreamodifica();

	/**
	 * Sets the fechacreamodifica of this cronograma evaluacion personal.
	 *
	 * @param fechacreamodifica the fechacreamodifica of this cronograma evaluacion personal
	 */
	public void setFechacreamodifica(Date fechacreamodifica);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.rec.hitss.layer.model.CronogramaEvaluacionPersonal cronogramaEvaluacionPersonal);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rec.hitss.layer.model.CronogramaEvaluacionPersonal> toCacheModel();

	@Override
	public com.rec.hitss.layer.model.CronogramaEvaluacionPersonal toEscapedModel();

	@Override
	public com.rec.hitss.layer.model.CronogramaEvaluacionPersonal toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}