/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rec.hitss.layer.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Etiqueta service. Represents a row in the &quot;Etiqueta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rec.hitss.layer.model.impl.EtiquetaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rec.hitss.layer.model.impl.EtiquetaImpl}.
 * </p>
 *
 * @author Crossfire
 * @see Etiqueta
 * @see com.rec.hitss.layer.model.impl.EtiquetaImpl
 * @see com.rec.hitss.layer.model.impl.EtiquetaModelImpl
 * @generated
 */
public interface EtiquetaModel extends BaseModel<Etiqueta> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a etiqueta model instance should use the {@link Etiqueta} interface instead.
	 */

	/**
	 * Returns the primary key of this etiqueta.
	 *
	 * @return the primary key of this etiqueta
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this etiqueta.
	 *
	 * @param primaryKey the primary key of this etiqueta
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the etiqueta ID of this etiqueta.
	 *
	 * @return the etiqueta ID of this etiqueta
	 */
	public long getEtiquetaId();

	/**
	 * Sets the etiqueta ID of this etiqueta.
	 *
	 * @param etiquetaId the etiqueta ID of this etiqueta
	 */
	public void setEtiquetaId(long etiquetaId);

	/**
	 * Returns the tag ID of this etiqueta.
	 *
	 * @return the tag ID of this etiqueta
	 */
	public long getTagId();

	/**
	 * Sets the tag ID of this etiqueta.
	 *
	 * @param tagId the tag ID of this etiqueta
	 */
	public void setTagId(long tagId);

	/**
	 * Returns the group ID of this etiqueta.
	 *
	 * @return the group ID of this etiqueta
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this etiqueta.
	 *
	 * @param groupId the group ID of this etiqueta
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this etiqueta.
	 *
	 * @return the company ID of this etiqueta
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this etiqueta.
	 *
	 * @param companyId the company ID of this etiqueta
	 */
	public void setCompanyId(long companyId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.rec.hitss.layer.model.Etiqueta etiqueta);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rec.hitss.layer.model.Etiqueta> toCacheModel();

	@Override
	public com.rec.hitss.layer.model.Etiqueta toEscapedModel();

	@Override
	public com.rec.hitss.layer.model.Etiqueta toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}