/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rec.hitss.layer.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Evaluacion service. Represents a row in the &quot;Evaluacion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rec.hitss.layer.model.impl.EvaluacionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rec.hitss.layer.model.impl.EvaluacionImpl}.
 * </p>
 *
 * @author Crossfire
 * @see Evaluacion
 * @see com.rec.hitss.layer.model.impl.EvaluacionImpl
 * @see com.rec.hitss.layer.model.impl.EvaluacionModelImpl
 * @generated
 */
public interface EvaluacionModel extends BaseModel<Evaluacion> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a evaluacion model instance should use the {@link Evaluacion} interface instead.
	 */

	/**
	 * Returns the primary key of this evaluacion.
	 *
	 * @return the primary key of this evaluacion
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this evaluacion.
	 *
	 * @param primaryKey the primary key of this evaluacion
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the evaluacion ID of this evaluacion.
	 *
	 * @return the evaluacion ID of this evaluacion
	 */
	public long getEvaluacionId();

	/**
	 * Sets the evaluacion ID of this evaluacion.
	 *
	 * @param evaluacionId the evaluacion ID of this evaluacion
	 */
	public void setEvaluacionId(long evaluacionId);

	/**
	 * Returns the tiempo minuto of this evaluacion.
	 *
	 * @return the tiempo minuto of this evaluacion
	 */
	public long getTiempoMinuto();

	/**
	 * Sets the tiempo minuto of this evaluacion.
	 *
	 * @param tiempoMinuto the tiempo minuto of this evaluacion
	 */
	public void setTiempoMinuto(long tiempoMinuto);

	/**
	 * Returns the enfoque of this evaluacion.
	 *
	 * @return the enfoque of this evaluacion
	 */
	public long getEnfoque();

	/**
	 * Sets the enfoque of this evaluacion.
	 *
	 * @param enfoque the enfoque of this evaluacion
	 */
	public void setEnfoque(long enfoque);

	/**
	 * Returns the puesto evaluacion of this evaluacion.
	 *
	 * @return the puesto evaluacion of this evaluacion
	 */
	public long getPuestoEvaluacion();

	/**
	 * Sets the puesto evaluacion of this evaluacion.
	 *
	 * @param puestoEvaluacion the puesto evaluacion of this evaluacion
	 */
	public void setPuestoEvaluacion(long puestoEvaluacion);

	/**
	 * Returns the tiempo puesto of this evaluacion.
	 *
	 * @return the tiempo puesto of this evaluacion
	 */
	public long getTiempoPuesto();

	/**
	 * Sets the tiempo puesto of this evaluacion.
	 *
	 * @param tiempoPuesto the tiempo puesto of this evaluacion
	 */
	public void setTiempoPuesto(long tiempoPuesto);

	/**
	 * Returns the tipo evaluacion of this evaluacion.
	 *
	 * @return the tipo evaluacion of this evaluacion
	 */
	public long getTipoEvaluacion();

	/**
	 * Sets the tipo evaluacion of this evaluacion.
	 *
	 * @param TipoEvaluacion the tipo evaluacion of this evaluacion
	 */
	public void setTipoEvaluacion(long TipoEvaluacion);

	/**
	 * Returns the activo of this evaluacion.
	 *
	 * @return the activo of this evaluacion
	 */
	public boolean getActivo();

	/**
	 * Returns <code>true</code> if this evaluacion is activo.
	 *
	 * @return <code>true</code> if this evaluacion is activo; <code>false</code> otherwise
	 */
	public boolean isActivo();

	/**
	 * Sets whether this evaluacion is activo.
	 *
	 * @param activo the activo of this evaluacion
	 */
	public void setActivo(boolean activo);

	/**
	 * Returns the usuariocrea of this evaluacion.
	 *
	 * @return the usuariocrea of this evaluacion
	 */
	public long getUsuariocrea();

	/**
	 * Sets the usuariocrea of this evaluacion.
	 *
	 * @param usuariocrea the usuariocrea of this evaluacion
	 */
	public void setUsuariocrea(long usuariocrea);

	/**
	 * Returns the fechacrea of this evaluacion.
	 *
	 * @return the fechacrea of this evaluacion
	 */
	public Date getFechacrea();

	/**
	 * Sets the fechacrea of this evaluacion.
	 *
	 * @param fechacrea the fechacrea of this evaluacion
	 */
	public void setFechacrea(Date fechacrea);

	/**
	 * Returns the usuariomodifica of this evaluacion.
	 *
	 * @return the usuariomodifica of this evaluacion
	 */
	public long getUsuariomodifica();

	/**
	 * Sets the usuariomodifica of this evaluacion.
	 *
	 * @param usuariomodifica the usuariomodifica of this evaluacion
	 */
	public void setUsuariomodifica(long usuariomodifica);

	/**
	 * Returns the fechacreamodifica of this evaluacion.
	 *
	 * @return the fechacreamodifica of this evaluacion
	 */
	public Date getFechacreamodifica();

	/**
	 * Sets the fechacreamodifica of this evaluacion.
	 *
	 * @param fechacreamodifica the fechacreamodifica of this evaluacion
	 */
	public void setFechacreamodifica(Date fechacreamodifica);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.rec.hitss.layer.model.Evaluacion evaluacion);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rec.hitss.layer.model.Evaluacion> toCacheModel();

	@Override
	public com.rec.hitss.layer.model.Evaluacion toEscapedModel();

	@Override
	public com.rec.hitss.layer.model.Evaluacion toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}