/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rec.hitss.layer.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the FuncionRequerimiento service. Represents a row in the &quot;FuncionRequerimiento&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rec.hitss.layer.model.impl.FuncionRequerimientoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rec.hitss.layer.model.impl.FuncionRequerimientoImpl}.
 * </p>
 *
 * @author Crossfire
 * @see FuncionRequerimiento
 * @see com.rec.hitss.layer.model.impl.FuncionRequerimientoImpl
 * @see com.rec.hitss.layer.model.impl.FuncionRequerimientoModelImpl
 * @generated
 */
public interface FuncionRequerimientoModel extends BaseModel<FuncionRequerimiento> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a funcion requerimiento model instance should use the {@link FuncionRequerimiento} interface instead.
	 */

	/**
	 * Returns the primary key of this funcion requerimiento.
	 *
	 * @return the primary key of this funcion requerimiento
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this funcion requerimiento.
	 *
	 * @param primaryKey the primary key of this funcion requerimiento
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the funcion ID of this funcion requerimiento.
	 *
	 * @return the funcion ID of this funcion requerimiento
	 */
	public long getFuncionId();

	/**
	 * Sets the funcion ID of this funcion requerimiento.
	 *
	 * @param funcionId the funcion ID of this funcion requerimiento
	 */
	public void setFuncionId(long funcionId);

	/**
	 * Returns the requerimiento recurso ID of this funcion requerimiento.
	 *
	 * @return the requerimiento recurso ID of this funcion requerimiento
	 */
	public long getRequerimientoRecursoId();

	/**
	 * Sets the requerimiento recurso ID of this funcion requerimiento.
	 *
	 * @param requerimientoRecursoId the requerimiento recurso ID of this funcion requerimiento
	 */
	public void setRequerimientoRecursoId(long requerimientoRecursoId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.rec.hitss.layer.model.FuncionRequerimiento funcionRequerimiento);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rec.hitss.layer.model.FuncionRequerimiento> toCacheModel();

	@Override
	public com.rec.hitss.layer.model.FuncionRequerimiento toEscapedModel();

	@Override
	public com.rec.hitss.layer.model.FuncionRequerimiento toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}