/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rec.hitss.layer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Parametro service. Represents a row in the &quot;Parametro&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rec.hitss.layer.model.impl.ParametroModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rec.hitss.layer.model.impl.ParametroImpl}.
 * </p>
 *
 * @author Crossfire
 * @see Parametro
 * @see com.rec.hitss.layer.model.impl.ParametroImpl
 * @see com.rec.hitss.layer.model.impl.ParametroModelImpl
 * @generated
 */
public interface ParametroModel extends BaseModel<Parametro> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a parametro model instance should use the {@link Parametro} interface instead.
	 */

	/**
	 * Returns the primary key of this parametro.
	 *
	 * @return the primary key of this parametro
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this parametro.
	 *
	 * @param primaryKey the primary key of this parametro
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the parametro ID of this parametro.
	 *
	 * @return the parametro ID of this parametro
	 */
	public long getParametroId();

	/**
	 * Sets the parametro ID of this parametro.
	 *
	 * @param parametroId the parametro ID of this parametro
	 */
	public void setParametroId(long parametroId);

	/**
	 * Returns the descripcion of this parametro.
	 *
	 * @return the descripcion of this parametro
	 */
	@AutoEscape
	public String getDescripcion();

	/**
	 * Sets the descripcion of this parametro.
	 *
	 * @param descripcion the descripcion of this parametro
	 */
	public void setDescripcion(String descripcion);

	/**
	 * Returns the llave of this parametro.
	 *
	 * @return the llave of this parametro
	 */
	@AutoEscape
	public String getLlave();

	/**
	 * Sets the llave of this parametro.
	 *
	 * @param llave the llave of this parametro
	 */
	public void setLlave(String llave);

	/**
	 * Returns the valor of this parametro.
	 *
	 * @return the valor of this parametro
	 */
	@AutoEscape
	public String getValor();

	/**
	 * Sets the valor of this parametro.
	 *
	 * @param valor the valor of this parametro
	 */
	public void setValor(String valor);

	/**
	 * Returns the parametro padre ID of this parametro.
	 *
	 * @return the parametro padre ID of this parametro
	 */
	public long getParametroPadreId();

	/**
	 * Sets the parametro padre ID of this parametro.
	 *
	 * @param parametroPadreId the parametro padre ID of this parametro
	 */
	public void setParametroPadreId(long parametroPadreId);

	/**
	 * Returns the activo of this parametro.
	 *
	 * @return the activo of this parametro
	 */
	public boolean getActivo();

	/**
	 * Returns <code>true</code> if this parametro is activo.
	 *
	 * @return <code>true</code> if this parametro is activo; <code>false</code> otherwise
	 */
	public boolean isActivo();

	/**
	 * Sets whether this parametro is activo.
	 *
	 * @param activo the activo of this parametro
	 */
	public void setActivo(boolean activo);

	/**
	 * Returns the usuariocrea of this parametro.
	 *
	 * @return the usuariocrea of this parametro
	 */
	public long getUsuariocrea();

	/**
	 * Sets the usuariocrea of this parametro.
	 *
	 * @param usuariocrea the usuariocrea of this parametro
	 */
	public void setUsuariocrea(long usuariocrea);

	/**
	 * Returns the fechacrea of this parametro.
	 *
	 * @return the fechacrea of this parametro
	 */
	public Date getFechacrea();

	/**
	 * Sets the fechacrea of this parametro.
	 *
	 * @param fechacrea the fechacrea of this parametro
	 */
	public void setFechacrea(Date fechacrea);

	/**
	 * Returns the usuariomodifica of this parametro.
	 *
	 * @return the usuariomodifica of this parametro
	 */
	public long getUsuariomodifica();

	/**
	 * Sets the usuariomodifica of this parametro.
	 *
	 * @param usuariomodifica the usuariomodifica of this parametro
	 */
	public void setUsuariomodifica(long usuariomodifica);

	/**
	 * Returns the fechacreamodifica of this parametro.
	 *
	 * @return the fechacreamodifica of this parametro
	 */
	public Date getFechacreamodifica();

	/**
	 * Sets the fechacreamodifica of this parametro.
	 *
	 * @param fechacreamodifica the fechacreamodifica of this parametro
	 */
	public void setFechacreamodifica(Date fechacreamodifica);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.rec.hitss.layer.model.Parametro parametro);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rec.hitss.layer.model.Parametro> toCacheModel();

	@Override
	public com.rec.hitss.layer.model.Parametro toEscapedModel();

	@Override
	public com.rec.hitss.layer.model.Parametro toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}