/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rec.hitss.layer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PlanAccion service. Represents a row in the &quot;PlanAccion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rec.hitss.layer.model.impl.PlanAccionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rec.hitss.layer.model.impl.PlanAccionImpl}.
 * </p>
 *
 * @author Crossfire
 * @see PlanAccion
 * @see com.rec.hitss.layer.model.impl.PlanAccionImpl
 * @see com.rec.hitss.layer.model.impl.PlanAccionModelImpl
 * @generated
 */
public interface PlanAccionModel extends BaseModel<PlanAccion> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a plan accion model instance should use the {@link PlanAccion} interface instead.
	 */

	/**
	 * Returns the primary key of this plan accion.
	 *
	 * @return the primary key of this plan accion
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this plan accion.
	 *
	 * @param primaryKey the primary key of this plan accion
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the plan accion ID of this plan accion.
	 *
	 * @return the plan accion ID of this plan accion
	 */
	public long getPlanAccionId();

	/**
	 * Sets the plan accion ID of this plan accion.
	 *
	 * @param planAccionId the plan accion ID of this plan accion
	 */
	public void setPlanAccionId(long planAccionId);

	/**
	 * Returns the actividades ID of this plan accion.
	 *
	 * @return the actividades ID of this plan accion
	 */
	public long getActividadesId();

	/**
	 * Sets the actividades ID of this plan accion.
	 *
	 * @param actividadesId the actividades ID of this plan accion
	 */
	public void setActividadesId(long actividadesId);

	/**
	 * Returns the responsable of this plan accion.
	 *
	 * @return the responsable of this plan accion
	 */
	@AutoEscape
	public String getResponsable();

	/**
	 * Sets the responsable of this plan accion.
	 *
	 * @param responsable the responsable of this plan accion
	 */
	public void setResponsable(String responsable);

	/**
	 * Returns the fecha emitida of this plan accion.
	 *
	 * @return the fecha emitida of this plan accion
	 */
	public Date getFechaEmitida();

	/**
	 * Sets the fecha emitida of this plan accion.
	 *
	 * @param fechaEmitida the fecha emitida of this plan accion
	 */
	public void setFechaEmitida(Date fechaEmitida);

	/**
	 * Returns the fecha programada of this plan accion.
	 *
	 * @return the fecha programada of this plan accion
	 */
	public Date getFechaProgramada();

	/**
	 * Sets the fecha programada of this plan accion.
	 *
	 * @param fechaProgramada the fecha programada of this plan accion
	 */
	public void setFechaProgramada(Date fechaProgramada);

	/**
	 * Returns the aprobador colaborador of this plan accion.
	 *
	 * @return the aprobador colaborador of this plan accion
	 */
	public boolean getAprobadorColaborador();

	/**
	 * Returns <code>true</code> if this plan accion is aprobador colaborador.
	 *
	 * @return <code>true</code> if this plan accion is aprobador colaborador; <code>false</code> otherwise
	 */
	public boolean isAprobadorColaborador();

	/**
	 * Sets whether this plan accion is aprobador colaborador.
	 *
	 * @param aprobadorColaborador the aprobador colaborador of this plan accion
	 */
	public void setAprobadorColaborador(boolean aprobadorColaborador);

	/**
	 * Returns the aprobador lideres of this plan accion.
	 *
	 * @return the aprobador lideres of this plan accion
	 */
	public boolean getAprobadorLideres();

	/**
	 * Returns <code>true</code> if this plan accion is aprobador lideres.
	 *
	 * @return <code>true</code> if this plan accion is aprobador lideres; <code>false</code> otherwise
	 */
	public boolean isAprobadorLideres();

	/**
	 * Sets whether this plan accion is aprobador lideres.
	 *
	 * @param aprobadorLideres the aprobador lideres of this plan accion
	 */
	public void setAprobadorLideres(boolean aprobadorLideres);

	/**
	 * Returns the activo of this plan accion.
	 *
	 * @return the activo of this plan accion
	 */
	public boolean getActivo();

	/**
	 * Returns <code>true</code> if this plan accion is activo.
	 *
	 * @return <code>true</code> if this plan accion is activo; <code>false</code> otherwise
	 */
	public boolean isActivo();

	/**
	 * Sets whether this plan accion is activo.
	 *
	 * @param activo the activo of this plan accion
	 */
	public void setActivo(boolean activo);

	/**
	 * Returns the usuariocrea of this plan accion.
	 *
	 * @return the usuariocrea of this plan accion
	 */
	public long getUsuariocrea();

	/**
	 * Sets the usuariocrea of this plan accion.
	 *
	 * @param usuariocrea the usuariocrea of this plan accion
	 */
	public void setUsuariocrea(long usuariocrea);

	/**
	 * Returns the fechacrea of this plan accion.
	 *
	 * @return the fechacrea of this plan accion
	 */
	public Date getFechacrea();

	/**
	 * Sets the fechacrea of this plan accion.
	 *
	 * @param fechacrea the fechacrea of this plan accion
	 */
	public void setFechacrea(Date fechacrea);

	/**
	 * Returns the usuariomodifica of this plan accion.
	 *
	 * @return the usuariomodifica of this plan accion
	 */
	public long getUsuariomodifica();

	/**
	 * Sets the usuariomodifica of this plan accion.
	 *
	 * @param usuariomodifica the usuariomodifica of this plan accion
	 */
	public void setUsuariomodifica(long usuariomodifica);

	/**
	 * Returns the fechacreamodifica of this plan accion.
	 *
	 * @return the fechacreamodifica of this plan accion
	 */
	public Date getFechacreamodifica();

	/**
	 * Sets the fechacreamodifica of this plan accion.
	 *
	 * @param fechacreamodifica the fechacreamodifica of this plan accion
	 */
	public void setFechacreamodifica(Date fechacreamodifica);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.rec.hitss.layer.model.PlanAccion planAccion);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rec.hitss.layer.model.PlanAccion> toCacheModel();

	@Override
	public com.rec.hitss.layer.model.PlanAccion toEscapedModel();

	@Override
	public com.rec.hitss.layer.model.PlanAccion toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}