/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rec.hitss.layer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Requisito service. Represents a row in the &quot;Requisito&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rec.hitss.layer.model.impl.RequisitoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rec.hitss.layer.model.impl.RequisitoImpl}.
 * </p>
 *
 * @author Crossfire
 * @see Requisito
 * @see com.rec.hitss.layer.model.impl.RequisitoImpl
 * @see com.rec.hitss.layer.model.impl.RequisitoModelImpl
 * @generated
 */
public interface RequisitoModel extends BaseModel<Requisito> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a requisito model instance should use the {@link Requisito} interface instead.
	 */

	/**
	 * Returns the primary key of this requisito.
	 *
	 * @return the primary key of this requisito
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this requisito.
	 *
	 * @param primaryKey the primary key of this requisito
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the requisito ID of this requisito.
	 *
	 * @return the requisito ID of this requisito
	 */
	public long getRequisitoId();

	/**
	 * Sets the requisito ID of this requisito.
	 *
	 * @param requisitoId the requisito ID of this requisito
	 */
	public void setRequisitoId(long requisitoId);

	/**
	 * Returns the descripcion of this requisito.
	 *
	 * @return the descripcion of this requisito
	 */
	@AutoEscape
	public String getDescripcion();

	/**
	 * Sets the descripcion of this requisito.
	 *
	 * @param descripcion the descripcion of this requisito
	 */
	public void setDescripcion(String descripcion);

	/**
	 * Returns the nivel of this requisito.
	 *
	 * @return the nivel of this requisito
	 */
	public long getNivel();

	/**
	 * Sets the nivel of this requisito.
	 *
	 * @param nivel the nivel of this requisito
	 */
	public void setNivel(long nivel);

	/**
	 * Returns the exigible of this requisito.
	 *
	 * @return the exigible of this requisito
	 */
	public boolean getExigible();

	/**
	 * Returns <code>true</code> if this requisito is exigible.
	 *
	 * @return <code>true</code> if this requisito is exigible; <code>false</code> otherwise
	 */
	public boolean isExigible();

	/**
	 * Sets whether this requisito is exigible.
	 *
	 * @param exigible the exigible of this requisito
	 */
	public void setExigible(boolean exigible);

	/**
	 * Returns the herramienta of this requisito.
	 *
	 * @return the herramienta of this requisito
	 */
	public long getHerramienta();

	/**
	 * Sets the herramienta of this requisito.
	 *
	 * @param herramienta the herramienta of this requisito
	 */
	public void setHerramienta(long herramienta);

	/**
	 * Returns the tipo requisito of this requisito.
	 *
	 * @return the tipo requisito of this requisito
	 */
	public long getTipoRequisito();

	/**
	 * Sets the tipo requisito of this requisito.
	 *
	 * @param tipoRequisito the tipo requisito of this requisito
	 */
	public void setTipoRequisito(long tipoRequisito);

	/**
	 * Returns the activo of this requisito.
	 *
	 * @return the activo of this requisito
	 */
	public boolean getActivo();

	/**
	 * Returns <code>true</code> if this requisito is activo.
	 *
	 * @return <code>true</code> if this requisito is activo; <code>false</code> otherwise
	 */
	public boolean isActivo();

	/**
	 * Sets whether this requisito is activo.
	 *
	 * @param activo the activo of this requisito
	 */
	public void setActivo(boolean activo);

	/**
	 * Returns the usuariocrea of this requisito.
	 *
	 * @return the usuariocrea of this requisito
	 */
	public long getUsuariocrea();

	/**
	 * Sets the usuariocrea of this requisito.
	 *
	 * @param usuariocrea the usuariocrea of this requisito
	 */
	public void setUsuariocrea(long usuariocrea);

	/**
	 * Returns the fechacrea of this requisito.
	 *
	 * @return the fechacrea of this requisito
	 */
	public Date getFechacrea();

	/**
	 * Sets the fechacrea of this requisito.
	 *
	 * @param fechacrea the fechacrea of this requisito
	 */
	public void setFechacrea(Date fechacrea);

	/**
	 * Returns the usuariomodifica of this requisito.
	 *
	 * @return the usuariomodifica of this requisito
	 */
	public long getUsuariomodifica();

	/**
	 * Sets the usuariomodifica of this requisito.
	 *
	 * @param usuariomodifica the usuariomodifica of this requisito
	 */
	public void setUsuariomodifica(long usuariomodifica);

	/**
	 * Returns the fechacreamodifica of this requisito.
	 *
	 * @return the fechacreamodifica of this requisito
	 */
	public Date getFechacreamodifica();

	/**
	 * Sets the fechacreamodifica of this requisito.
	 *
	 * @param fechacreamodifica the fechacreamodifica of this requisito
	 */
	public void setFechacreamodifica(Date fechacreamodifica);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.rec.hitss.layer.model.Requisito requisito);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rec.hitss.layer.model.Requisito> toCacheModel();

	@Override
	public com.rec.hitss.layer.model.Requisito toEscapedModel();

	@Override
	public com.rec.hitss.layer.model.Requisito toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}