/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rec.hitss.layer.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ResultadoEvaluacion service. Represents a row in the &quot;ResultadoEvaluacion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rec.hitss.layer.model.impl.ResultadoEvaluacionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rec.hitss.layer.model.impl.ResultadoEvaluacionImpl}.
 * </p>
 *
 * @author Crossfire
 * @see ResultadoEvaluacion
 * @see com.rec.hitss.layer.model.impl.ResultadoEvaluacionImpl
 * @see com.rec.hitss.layer.model.impl.ResultadoEvaluacionModelImpl
 * @generated
 */
public interface ResultadoEvaluacionModel extends BaseModel<ResultadoEvaluacion> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a resultado evaluacion model instance should use the {@link ResultadoEvaluacion} interface instead.
	 */

	/**
	 * Returns the primary key of this resultado evaluacion.
	 *
	 * @return the primary key of this resultado evaluacion
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this resultado evaluacion.
	 *
	 * @param primaryKey the primary key of this resultado evaluacion
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the resultado evaluacion ID of this resultado evaluacion.
	 *
	 * @return the resultado evaluacion ID of this resultado evaluacion
	 */
	public long getResultadoEvaluacionId();

	/**
	 * Sets the resultado evaluacion ID of this resultado evaluacion.
	 *
	 * @param resultadoEvaluacionId the resultado evaluacion ID of this resultado evaluacion
	 */
	public void setResultadoEvaluacionId(long resultadoEvaluacionId);

	/**
	 * Returns the respuesta selccionada of this resultado evaluacion.
	 *
	 * @return the respuesta selccionada of this resultado evaluacion
	 */
	public long getRespuestaSelccionada();

	/**
	 * Sets the respuesta selccionada of this resultado evaluacion.
	 *
	 * @param respuestaSelccionada the respuesta selccionada of this resultado evaluacion
	 */
	public void setRespuestaSelccionada(long respuestaSelccionada);

	/**
	 * Returns the habilidad cumplida of this resultado evaluacion.
	 *
	 * @return the habilidad cumplida of this resultado evaluacion
	 */
	public boolean getHabilidadCumplida();

	/**
	 * Returns <code>true</code> if this resultado evaluacion is habilidad cumplida.
	 *
	 * @return <code>true</code> if this resultado evaluacion is habilidad cumplida; <code>false</code> otherwise
	 */
	public boolean isHabilidadCumplida();

	/**
	 * Sets whether this resultado evaluacion is habilidad cumplida.
	 *
	 * @param habilidadCumplida the habilidad cumplida of this resultado evaluacion
	 */
	public void setHabilidadCumplida(boolean habilidadCumplida);

	/**
	 * Returns the evaluacion ID of this resultado evaluacion.
	 *
	 * @return the evaluacion ID of this resultado evaluacion
	 */
	public long getEvaluacionId();

	/**
	 * Sets the evaluacion ID of this resultado evaluacion.
	 *
	 * @param evaluacionId the evaluacion ID of this resultado evaluacion
	 */
	public void setEvaluacionId(long evaluacionId);

	/**
	 * Returns the usuario hitss ID of this resultado evaluacion.
	 *
	 * @return the usuario hitss ID of this resultado evaluacion
	 */
	public long getUsuarioHitssId();

	/**
	 * Sets the usuario hitss ID of this resultado evaluacion.
	 *
	 * @param usuarioHitssId the usuario hitss ID of this resultado evaluacion
	 */
	public void setUsuarioHitssId(long usuarioHitssId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.rec.hitss.layer.model.ResultadoEvaluacion resultadoEvaluacion);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rec.hitss.layer.model.ResultadoEvaluacion> toCacheModel();

	@Override
	public com.rec.hitss.layer.model.ResultadoEvaluacion toEscapedModel();

	@Override
	public com.rec.hitss.layer.model.ResultadoEvaluacion toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}