/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rec.hitss.layer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SolicitudRequerimientoPersonal service. Represents a row in the &quot;SolicitudRequerimientoPersonal&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rec.hitss.layer.model.impl.SolicitudRequerimientoPersonalModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rec.hitss.layer.model.impl.SolicitudRequerimientoPersonalImpl}.
 * </p>
 *
 * @author Crossfire
 * @see SolicitudRequerimientoPersonal
 * @see com.rec.hitss.layer.model.impl.SolicitudRequerimientoPersonalImpl
 * @see com.rec.hitss.layer.model.impl.SolicitudRequerimientoPersonalModelImpl
 * @generated
 */
public interface SolicitudRequerimientoPersonalModel extends BaseModel<SolicitudRequerimientoPersonal> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a solicitud requerimiento personal model instance should use the {@link SolicitudRequerimientoPersonal} interface instead.
	 */

	/**
	 * Returns the primary key of this solicitud requerimiento personal.
	 *
	 * @return the primary key of this solicitud requerimiento personal
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this solicitud requerimiento personal.
	 *
	 * @param primaryKey the primary key of this solicitud requerimiento personal
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the solicitud requerimiento personal ID of this solicitud requerimiento personal.
	 *
	 * @return the solicitud requerimiento personal ID of this solicitud requerimiento personal
	 */
	public long getSolicitudRequerimientoPersonalId();

	/**
	 * Sets the solicitud requerimiento personal ID of this solicitud requerimiento personal.
	 *
	 * @param solicitudRequerimientoPersonalId the solicitud requerimiento personal ID of this solicitud requerimiento personal
	 */
	public void setSolicitudRequerimientoPersonalId(
		long solicitudRequerimientoPersonalId);

	/**
	 * Returns the estado of this solicitud requerimiento personal.
	 *
	 * @return the estado of this solicitud requerimiento personal
	 */
	@AutoEscape
	public String getEstado();

	/**
	 * Sets the estado of this solicitud requerimiento personal.
	 *
	 * @param estado the estado of this solicitud requerimiento personal
	 */
	public void setEstado(String estado);

	/**
	 * Returns the puesto of this solicitud requerimiento personal.
	 *
	 * @return the puesto of this solicitud requerimiento personal
	 */
	@AutoEscape
	public String getPuesto();

	/**
	 * Sets the puesto of this solicitud requerimiento personal.
	 *
	 * @param puesto the puesto of this solicitud requerimiento personal
	 */
	public void setPuesto(String puesto);

	/**
	 * Returns the area solicitante of this solicitud requerimiento personal.
	 *
	 * @return the area solicitante of this solicitud requerimiento personal
	 */
	public long getAreaSolicitante();

	/**
	 * Sets the area solicitante of this solicitud requerimiento personal.
	 *
	 * @param areaSolicitante the area solicitante of this solicitud requerimiento personal
	 */
	public void setAreaSolicitante(long areaSolicitante);

	/**
	 * Returns the cantidad recursos of this solicitud requerimiento personal.
	 *
	 * @return the cantidad recursos of this solicitud requerimiento personal
	 */
	public long getCantidadRecursos();

	/**
	 * Sets the cantidad recursos of this solicitud requerimiento personal.
	 *
	 * @param cantidadRecursos the cantidad recursos of this solicitud requerimiento personal
	 */
	public void setCantidadRecursos(long cantidadRecursos);

	/**
	 * Returns the fecha limite of this solicitud requerimiento personal.
	 *
	 * @return the fecha limite of this solicitud requerimiento personal
	 */
	public Date getFechaLimite();

	/**
	 * Sets the fecha limite of this solicitud requerimiento personal.
	 *
	 * @param fechaLimite the fecha limite of this solicitud requerimiento personal
	 */
	public void setFechaLimite(Date fechaLimite);

	/**
	 * Returns the cargo of this solicitud requerimiento personal.
	 *
	 * @return the cargo of this solicitud requerimiento personal
	 */
	@AutoEscape
	public String getCargo();

	/**
	 * Sets the cargo of this solicitud requerimiento personal.
	 *
	 * @param cargo the cargo of this solicitud requerimiento personal
	 */
	public void setCargo(String cargo);

	/**
	 * Returns the tiempo contrato of this solicitud requerimiento personal.
	 *
	 * @return the tiempo contrato of this solicitud requerimiento personal
	 */
	public long getTiempoContrato();

	/**
	 * Sets the tiempo contrato of this solicitud requerimiento personal.
	 *
	 * @param tiempoContrato the tiempo contrato of this solicitud requerimiento personal
	 */
	public void setTiempoContrato(long tiempoContrato);

	/**
	 * Returns the tipo negocio of this solicitud requerimiento personal.
	 *
	 * @return the tipo negocio of this solicitud requerimiento personal
	 */
	public long getTipoNegocio();

	/**
	 * Sets the tipo negocio of this solicitud requerimiento personal.
	 *
	 * @param tipoNegocio the tipo negocio of this solicitud requerimiento personal
	 */
	public void setTipoNegocio(long tipoNegocio);

	/**
	 * Returns the presupuesto maximo of this solicitud requerimiento personal.
	 *
	 * @return the presupuesto maximo of this solicitud requerimiento personal
	 */
	public long getPresupuestoMaximo();

	/**
	 * Sets the presupuesto maximo of this solicitud requerimiento personal.
	 *
	 * @param presupuestoMaximo the presupuesto maximo of this solicitud requerimiento personal
	 */
	public void setPresupuestoMaximo(long presupuestoMaximo);

	/**
	 * Returns the presupuesto minimo of this solicitud requerimiento personal.
	 *
	 * @return the presupuesto minimo of this solicitud requerimiento personal
	 */
	public long getPresupuestoMinimo();

	/**
	 * Sets the presupuesto minimo of this solicitud requerimiento personal.
	 *
	 * @param presupuestoMinimo the presupuesto minimo of this solicitud requerimiento personal
	 */
	public void setPresupuestoMinimo(long presupuestoMinimo);

	/**
	 * Returns the cliente of this solicitud requerimiento personal.
	 *
	 * @return the cliente of this solicitud requerimiento personal
	 */
	public long getCliente();

	/**
	 * Sets the cliente of this solicitud requerimiento personal.
	 *
	 * @param cliente the cliente of this solicitud requerimiento personal
	 */
	public void setCliente(long cliente);

	/**
	 * Returns the activo of this solicitud requerimiento personal.
	 *
	 * @return the activo of this solicitud requerimiento personal
	 */
	public boolean getActivo();

	/**
	 * Returns <code>true</code> if this solicitud requerimiento personal is activo.
	 *
	 * @return <code>true</code> if this solicitud requerimiento personal is activo; <code>false</code> otherwise
	 */
	public boolean isActivo();

	/**
	 * Sets whether this solicitud requerimiento personal is activo.
	 *
	 * @param activo the activo of this solicitud requerimiento personal
	 */
	public void setActivo(boolean activo);

	/**
	 * Returns the usuariocrea of this solicitud requerimiento personal.
	 *
	 * @return the usuariocrea of this solicitud requerimiento personal
	 */
	public long getUsuariocrea();

	/**
	 * Sets the usuariocrea of this solicitud requerimiento personal.
	 *
	 * @param usuariocrea the usuariocrea of this solicitud requerimiento personal
	 */
	public void setUsuariocrea(long usuariocrea);

	/**
	 * Returns the fechacrea of this solicitud requerimiento personal.
	 *
	 * @return the fechacrea of this solicitud requerimiento personal
	 */
	public Date getFechacrea();

	/**
	 * Sets the fechacrea of this solicitud requerimiento personal.
	 *
	 * @param fechacrea the fechacrea of this solicitud requerimiento personal
	 */
	public void setFechacrea(Date fechacrea);

	/**
	 * Returns the usuariomodifica of this solicitud requerimiento personal.
	 *
	 * @return the usuariomodifica of this solicitud requerimiento personal
	 */
	public long getUsuariomodifica();

	/**
	 * Sets the usuariomodifica of this solicitud requerimiento personal.
	 *
	 * @param usuariomodifica the usuariomodifica of this solicitud requerimiento personal
	 */
	public void setUsuariomodifica(long usuariomodifica);

	/**
	 * Returns the fechacreamodifica of this solicitud requerimiento personal.
	 *
	 * @return the fechacreamodifica of this solicitud requerimiento personal
	 */
	public Date getFechacreamodifica();

	/**
	 * Sets the fechacreamodifica of this solicitud requerimiento personal.
	 *
	 * @param fechacreamodifica the fechacreamodifica of this solicitud requerimiento personal
	 */
	public void setFechacreamodifica(Date fechacreamodifica);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.rec.hitss.layer.model.SolicitudRequerimientoPersonal solicitudRequerimientoPersonal);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rec.hitss.layer.model.SolicitudRequerimientoPersonal> toCacheModel();

	@Override
	public com.rec.hitss.layer.model.SolicitudRequerimientoPersonal toEscapedModel();

	@Override
	public com.rec.hitss.layer.model.SolicitudRequerimientoPersonal toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}