/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rec.hitss.layer.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the UsuarioGrupo service. Represents a row in the &quot;UsuarioGrupo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rec.hitss.layer.model.impl.UsuarioGrupoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rec.hitss.layer.model.impl.UsuarioGrupoImpl}.
 * </p>
 *
 * @author Crossfire
 * @see UsuarioGrupo
 * @see com.rec.hitss.layer.model.impl.UsuarioGrupoImpl
 * @see com.rec.hitss.layer.model.impl.UsuarioGrupoModelImpl
 * @generated
 */
public interface UsuarioGrupoModel extends BaseModel<UsuarioGrupo> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a usuario grupo model instance should use the {@link UsuarioGrupo} interface instead.
	 */

	/**
	 * Returns the primary key of this usuario grupo.
	 *
	 * @return the primary key of this usuario grupo
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this usuario grupo.
	 *
	 * @param primaryKey the primary key of this usuario grupo
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the user group ID of this usuario grupo.
	 *
	 * @return the user group ID of this usuario grupo
	 */
	public long getUserGroupId();

	/**
	 * Sets the user group ID of this usuario grupo.
	 *
	 * @param userGroupId the user group ID of this usuario grupo
	 */
	public void setUserGroupId(long userGroupId);

	/**
	 * Returns the group ID of this usuario grupo.
	 *
	 * @return the group ID of this usuario grupo
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this usuario grupo.
	 *
	 * @param groupId the group ID of this usuario grupo
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this usuario grupo.
	 *
	 * @return the company ID of this usuario grupo
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this usuario grupo.
	 *
	 * @param companyId the company ID of this usuario grupo
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the prioridad equipos ID of this usuario grupo.
	 *
	 * @return the prioridad equipos ID of this usuario grupo
	 */
	public long getPrioridadEquiposId();

	/**
	 * Sets the prioridad equipos ID of this usuario grupo.
	 *
	 * @param prioridadEquiposId the prioridad equipos ID of this usuario grupo
	 */
	public void setPrioridadEquiposId(long prioridadEquiposId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.rec.hitss.layer.model.UsuarioGrupo usuarioGrupo);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rec.hitss.layer.model.UsuarioGrupo> toCacheModel();

	@Override
	public com.rec.hitss.layer.model.UsuarioGrupo toEscapedModel();

	@Override
	public com.rec.hitss.layer.model.UsuarioGrupo toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}