/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rec.hitss.layer.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import com.rec.hitss.layer.model.Funcion;
import com.rec.hitss.layer.service.FuncionService;
import com.rec.hitss.layer.service.persistence.ContratoPersistence;
import com.rec.hitss.layer.service.persistence.EstudioPersistence;
import com.rec.hitss.layer.service.persistence.EtiquetaRelacionadaPersistence;
import com.rec.hitss.layer.service.persistence.EvaluacionPersistence;
import com.rec.hitss.layer.service.persistence.EvaluacionPreguntaPersistence;
import com.rec.hitss.layer.service.persistence.ExperienciaPersistence;
import com.rec.hitss.layer.service.persistence.FasePostulacionPersistence;
import com.rec.hitss.layer.service.persistence.FuncionPersistence;
import com.rec.hitss.layer.service.persistence.PostulacionPersistence;
import com.rec.hitss.layer.service.persistence.PreguntaPersistence;
import com.rec.hitss.layer.service.persistence.PuestoPersistence;
import com.rec.hitss.layer.service.persistence.ReferenciaPersistence;
import com.rec.hitss.layer.service.persistence.RequisitoPersistence;
import com.rec.hitss.layer.service.persistence.RespuestaPersistence;
import com.rec.hitss.layer.service.persistence.ResultadoEvaluacionPersistence;
import com.rec.hitss.layer.service.persistence.SolicitudRequerimientoPersistence;
import com.rec.hitss.layer.service.persistence.SolicitudRequerimientoRequisitoPersistence;
import com.rec.hitss.layer.service.persistence.UsuarioPersistence;
import com.rec.hitss.layer.service.persistence.UsuarioRequisitoPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the funcion remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.rec.hitss.layer.service.impl.FuncionServiceImpl}.
 * </p>
 *
 * @author Crossfire
 * @see com.rec.hitss.layer.service.impl.FuncionServiceImpl
 * @see com.rec.hitss.layer.service.FuncionServiceUtil
 * @generated
 */
public abstract class FuncionServiceBaseImpl extends BaseServiceImpl
	implements FuncionService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.rec.hitss.layer.service.FuncionServiceUtil} to access the funcion remote service.
	 */

	/**
	 * Returns the contrato local service.
	 *
	 * @return the contrato local service
	 */
	public com.rec.hitss.layer.service.ContratoLocalService getContratoLocalService() {
		return contratoLocalService;
	}

	/**
	 * Sets the contrato local service.
	 *
	 * @param contratoLocalService the contrato local service
	 */
	public void setContratoLocalService(
		com.rec.hitss.layer.service.ContratoLocalService contratoLocalService) {
		this.contratoLocalService = contratoLocalService;
	}

	/**
	 * Returns the contrato remote service.
	 *
	 * @return the contrato remote service
	 */
	public com.rec.hitss.layer.service.ContratoService getContratoService() {
		return contratoService;
	}

	/**
	 * Sets the contrato remote service.
	 *
	 * @param contratoService the contrato remote service
	 */
	public void setContratoService(
		com.rec.hitss.layer.service.ContratoService contratoService) {
		this.contratoService = contratoService;
	}

	/**
	 * Returns the contrato persistence.
	 *
	 * @return the contrato persistence
	 */
	public ContratoPersistence getContratoPersistence() {
		return contratoPersistence;
	}

	/**
	 * Sets the contrato persistence.
	 *
	 * @param contratoPersistence the contrato persistence
	 */
	public void setContratoPersistence(ContratoPersistence contratoPersistence) {
		this.contratoPersistence = contratoPersistence;
	}

	/**
	 * Returns the estudio local service.
	 *
	 * @return the estudio local service
	 */
	public com.rec.hitss.layer.service.EstudioLocalService getEstudioLocalService() {
		return estudioLocalService;
	}

	/**
	 * Sets the estudio local service.
	 *
	 * @param estudioLocalService the estudio local service
	 */
	public void setEstudioLocalService(
		com.rec.hitss.layer.service.EstudioLocalService estudioLocalService) {
		this.estudioLocalService = estudioLocalService;
	}

	/**
	 * Returns the estudio remote service.
	 *
	 * @return the estudio remote service
	 */
	public com.rec.hitss.layer.service.EstudioService getEstudioService() {
		return estudioService;
	}

	/**
	 * Sets the estudio remote service.
	 *
	 * @param estudioService the estudio remote service
	 */
	public void setEstudioService(
		com.rec.hitss.layer.service.EstudioService estudioService) {
		this.estudioService = estudioService;
	}

	/**
	 * Returns the estudio persistence.
	 *
	 * @return the estudio persistence
	 */
	public EstudioPersistence getEstudioPersistence() {
		return estudioPersistence;
	}

	/**
	 * Sets the estudio persistence.
	 *
	 * @param estudioPersistence the estudio persistence
	 */
	public void setEstudioPersistence(EstudioPersistence estudioPersistence) {
		this.estudioPersistence = estudioPersistence;
	}

	/**
	 * Returns the etiqueta relacionada local service.
	 *
	 * @return the etiqueta relacionada local service
	 */
	public com.rec.hitss.layer.service.EtiquetaRelacionadaLocalService getEtiquetaRelacionadaLocalService() {
		return etiquetaRelacionadaLocalService;
	}

	/**
	 * Sets the etiqueta relacionada local service.
	 *
	 * @param etiquetaRelacionadaLocalService the etiqueta relacionada local service
	 */
	public void setEtiquetaRelacionadaLocalService(
		com.rec.hitss.layer.service.EtiquetaRelacionadaLocalService etiquetaRelacionadaLocalService) {
		this.etiquetaRelacionadaLocalService = etiquetaRelacionadaLocalService;
	}

	/**
	 * Returns the etiqueta relacionada remote service.
	 *
	 * @return the etiqueta relacionada remote service
	 */
	public com.rec.hitss.layer.service.EtiquetaRelacionadaService getEtiquetaRelacionadaService() {
		return etiquetaRelacionadaService;
	}

	/**
	 * Sets the etiqueta relacionada remote service.
	 *
	 * @param etiquetaRelacionadaService the etiqueta relacionada remote service
	 */
	public void setEtiquetaRelacionadaService(
		com.rec.hitss.layer.service.EtiquetaRelacionadaService etiquetaRelacionadaService) {
		this.etiquetaRelacionadaService = etiquetaRelacionadaService;
	}

	/**
	 * Returns the etiqueta relacionada persistence.
	 *
	 * @return the etiqueta relacionada persistence
	 */
	public EtiquetaRelacionadaPersistence getEtiquetaRelacionadaPersistence() {
		return etiquetaRelacionadaPersistence;
	}

	/**
	 * Sets the etiqueta relacionada persistence.
	 *
	 * @param etiquetaRelacionadaPersistence the etiqueta relacionada persistence
	 */
	public void setEtiquetaRelacionadaPersistence(
		EtiquetaRelacionadaPersistence etiquetaRelacionadaPersistence) {
		this.etiquetaRelacionadaPersistence = etiquetaRelacionadaPersistence;
	}

	/**
	 * Returns the evaluacion local service.
	 *
	 * @return the evaluacion local service
	 */
	public com.rec.hitss.layer.service.EvaluacionLocalService getEvaluacionLocalService() {
		return evaluacionLocalService;
	}

	/**
	 * Sets the evaluacion local service.
	 *
	 * @param evaluacionLocalService the evaluacion local service
	 */
	public void setEvaluacionLocalService(
		com.rec.hitss.layer.service.EvaluacionLocalService evaluacionLocalService) {
		this.evaluacionLocalService = evaluacionLocalService;
	}

	/**
	 * Returns the evaluacion remote service.
	 *
	 * @return the evaluacion remote service
	 */
	public com.rec.hitss.layer.service.EvaluacionService getEvaluacionService() {
		return evaluacionService;
	}

	/**
	 * Sets the evaluacion remote service.
	 *
	 * @param evaluacionService the evaluacion remote service
	 */
	public void setEvaluacionService(
		com.rec.hitss.layer.service.EvaluacionService evaluacionService) {
		this.evaluacionService = evaluacionService;
	}

	/**
	 * Returns the evaluacion persistence.
	 *
	 * @return the evaluacion persistence
	 */
	public EvaluacionPersistence getEvaluacionPersistence() {
		return evaluacionPersistence;
	}

	/**
	 * Sets the evaluacion persistence.
	 *
	 * @param evaluacionPersistence the evaluacion persistence
	 */
	public void setEvaluacionPersistence(
		EvaluacionPersistence evaluacionPersistence) {
		this.evaluacionPersistence = evaluacionPersistence;
	}

	/**
	 * Returns the evaluacion pregunta local service.
	 *
	 * @return the evaluacion pregunta local service
	 */
	public com.rec.hitss.layer.service.EvaluacionPreguntaLocalService getEvaluacionPreguntaLocalService() {
		return evaluacionPreguntaLocalService;
	}

	/**
	 * Sets the evaluacion pregunta local service.
	 *
	 * @param evaluacionPreguntaLocalService the evaluacion pregunta local service
	 */
	public void setEvaluacionPreguntaLocalService(
		com.rec.hitss.layer.service.EvaluacionPreguntaLocalService evaluacionPreguntaLocalService) {
		this.evaluacionPreguntaLocalService = evaluacionPreguntaLocalService;
	}

	/**
	 * Returns the evaluacion pregunta remote service.
	 *
	 * @return the evaluacion pregunta remote service
	 */
	public com.rec.hitss.layer.service.EvaluacionPreguntaService getEvaluacionPreguntaService() {
		return evaluacionPreguntaService;
	}

	/**
	 * Sets the evaluacion pregunta remote service.
	 *
	 * @param evaluacionPreguntaService the evaluacion pregunta remote service
	 */
	public void setEvaluacionPreguntaService(
		com.rec.hitss.layer.service.EvaluacionPreguntaService evaluacionPreguntaService) {
		this.evaluacionPreguntaService = evaluacionPreguntaService;
	}

	/**
	 * Returns the evaluacion pregunta persistence.
	 *
	 * @return the evaluacion pregunta persistence
	 */
	public EvaluacionPreguntaPersistence getEvaluacionPreguntaPersistence() {
		return evaluacionPreguntaPersistence;
	}

	/**
	 * Sets the evaluacion pregunta persistence.
	 *
	 * @param evaluacionPreguntaPersistence the evaluacion pregunta persistence
	 */
	public void setEvaluacionPreguntaPersistence(
		EvaluacionPreguntaPersistence evaluacionPreguntaPersistence) {
		this.evaluacionPreguntaPersistence = evaluacionPreguntaPersistence;
	}

	/**
	 * Returns the experiencia local service.
	 *
	 * @return the experiencia local service
	 */
	public com.rec.hitss.layer.service.ExperienciaLocalService getExperienciaLocalService() {
		return experienciaLocalService;
	}

	/**
	 * Sets the experiencia local service.
	 *
	 * @param experienciaLocalService the experiencia local service
	 */
	public void setExperienciaLocalService(
		com.rec.hitss.layer.service.ExperienciaLocalService experienciaLocalService) {
		this.experienciaLocalService = experienciaLocalService;
	}

	/**
	 * Returns the experiencia remote service.
	 *
	 * @return the experiencia remote service
	 */
	public com.rec.hitss.layer.service.ExperienciaService getExperienciaService() {
		return experienciaService;
	}

	/**
	 * Sets the experiencia remote service.
	 *
	 * @param experienciaService the experiencia remote service
	 */
	public void setExperienciaService(
		com.rec.hitss.layer.service.ExperienciaService experienciaService) {
		this.experienciaService = experienciaService;
	}

	/**
	 * Returns the experiencia persistence.
	 *
	 * @return the experiencia persistence
	 */
	public ExperienciaPersistence getExperienciaPersistence() {
		return experienciaPersistence;
	}

	/**
	 * Sets the experiencia persistence.
	 *
	 * @param experienciaPersistence the experiencia persistence
	 */
	public void setExperienciaPersistence(
		ExperienciaPersistence experienciaPersistence) {
		this.experienciaPersistence = experienciaPersistence;
	}

	/**
	 * Returns the fase postulacion local service.
	 *
	 * @return the fase postulacion local service
	 */
	public com.rec.hitss.layer.service.FasePostulacionLocalService getFasePostulacionLocalService() {
		return fasePostulacionLocalService;
	}

	/**
	 * Sets the fase postulacion local service.
	 *
	 * @param fasePostulacionLocalService the fase postulacion local service
	 */
	public void setFasePostulacionLocalService(
		com.rec.hitss.layer.service.FasePostulacionLocalService fasePostulacionLocalService) {
		this.fasePostulacionLocalService = fasePostulacionLocalService;
	}

	/**
	 * Returns the fase postulacion remote service.
	 *
	 * @return the fase postulacion remote service
	 */
	public com.rec.hitss.layer.service.FasePostulacionService getFasePostulacionService() {
		return fasePostulacionService;
	}

	/**
	 * Sets the fase postulacion remote service.
	 *
	 * @param fasePostulacionService the fase postulacion remote service
	 */
	public void setFasePostulacionService(
		com.rec.hitss.layer.service.FasePostulacionService fasePostulacionService) {
		this.fasePostulacionService = fasePostulacionService;
	}

	/**
	 * Returns the fase postulacion persistence.
	 *
	 * @return the fase postulacion persistence
	 */
	public FasePostulacionPersistence getFasePostulacionPersistence() {
		return fasePostulacionPersistence;
	}

	/**
	 * Sets the fase postulacion persistence.
	 *
	 * @param fasePostulacionPersistence the fase postulacion persistence
	 */
	public void setFasePostulacionPersistence(
		FasePostulacionPersistence fasePostulacionPersistence) {
		this.fasePostulacionPersistence = fasePostulacionPersistence;
	}

	/**
	 * Returns the funcion local service.
	 *
	 * @return the funcion local service
	 */
	public com.rec.hitss.layer.service.FuncionLocalService getFuncionLocalService() {
		return funcionLocalService;
	}

	/**
	 * Sets the funcion local service.
	 *
	 * @param funcionLocalService the funcion local service
	 */
	public void setFuncionLocalService(
		com.rec.hitss.layer.service.FuncionLocalService funcionLocalService) {
		this.funcionLocalService = funcionLocalService;
	}

	/**
	 * Returns the funcion remote service.
	 *
	 * @return the funcion remote service
	 */
	public com.rec.hitss.layer.service.FuncionService getFuncionService() {
		return funcionService;
	}

	/**
	 * Sets the funcion remote service.
	 *
	 * @param funcionService the funcion remote service
	 */
	public void setFuncionService(
		com.rec.hitss.layer.service.FuncionService funcionService) {
		this.funcionService = funcionService;
	}

	/**
	 * Returns the funcion persistence.
	 *
	 * @return the funcion persistence
	 */
	public FuncionPersistence getFuncionPersistence() {
		return funcionPersistence;
	}

	/**
	 * Sets the funcion persistence.
	 *
	 * @param funcionPersistence the funcion persistence
	 */
	public void setFuncionPersistence(FuncionPersistence funcionPersistence) {
		this.funcionPersistence = funcionPersistence;
	}

	/**
	 * Returns the postulacion local service.
	 *
	 * @return the postulacion local service
	 */
	public com.rec.hitss.layer.service.PostulacionLocalService getPostulacionLocalService() {
		return postulacionLocalService;
	}

	/**
	 * Sets the postulacion local service.
	 *
	 * @param postulacionLocalService the postulacion local service
	 */
	public void setPostulacionLocalService(
		com.rec.hitss.layer.service.PostulacionLocalService postulacionLocalService) {
		this.postulacionLocalService = postulacionLocalService;
	}

	/**
	 * Returns the postulacion remote service.
	 *
	 * @return the postulacion remote service
	 */
	public com.rec.hitss.layer.service.PostulacionService getPostulacionService() {
		return postulacionService;
	}

	/**
	 * Sets the postulacion remote service.
	 *
	 * @param postulacionService the postulacion remote service
	 */
	public void setPostulacionService(
		com.rec.hitss.layer.service.PostulacionService postulacionService) {
		this.postulacionService = postulacionService;
	}

	/**
	 * Returns the postulacion persistence.
	 *
	 * @return the postulacion persistence
	 */
	public PostulacionPersistence getPostulacionPersistence() {
		return postulacionPersistence;
	}

	/**
	 * Sets the postulacion persistence.
	 *
	 * @param postulacionPersistence the postulacion persistence
	 */
	public void setPostulacionPersistence(
		PostulacionPersistence postulacionPersistence) {
		this.postulacionPersistence = postulacionPersistence;
	}

	/**
	 * Returns the pregunta local service.
	 *
	 * @return the pregunta local service
	 */
	public com.rec.hitss.layer.service.PreguntaLocalService getPreguntaLocalService() {
		return preguntaLocalService;
	}

	/**
	 * Sets the pregunta local service.
	 *
	 * @param preguntaLocalService the pregunta local service
	 */
	public void setPreguntaLocalService(
		com.rec.hitss.layer.service.PreguntaLocalService preguntaLocalService) {
		this.preguntaLocalService = preguntaLocalService;
	}

	/**
	 * Returns the pregunta remote service.
	 *
	 * @return the pregunta remote service
	 */
	public com.rec.hitss.layer.service.PreguntaService getPreguntaService() {
		return preguntaService;
	}

	/**
	 * Sets the pregunta remote service.
	 *
	 * @param preguntaService the pregunta remote service
	 */
	public void setPreguntaService(
		com.rec.hitss.layer.service.PreguntaService preguntaService) {
		this.preguntaService = preguntaService;
	}

	/**
	 * Returns the pregunta persistence.
	 *
	 * @return the pregunta persistence
	 */
	public PreguntaPersistence getPreguntaPersistence() {
		return preguntaPersistence;
	}

	/**
	 * Sets the pregunta persistence.
	 *
	 * @param preguntaPersistence the pregunta persistence
	 */
	public void setPreguntaPersistence(PreguntaPersistence preguntaPersistence) {
		this.preguntaPersistence = preguntaPersistence;
	}

	/**
	 * Returns the puesto local service.
	 *
	 * @return the puesto local service
	 */
	public com.rec.hitss.layer.service.PuestoLocalService getPuestoLocalService() {
		return puestoLocalService;
	}

	/**
	 * Sets the puesto local service.
	 *
	 * @param puestoLocalService the puesto local service
	 */
	public void setPuestoLocalService(
		com.rec.hitss.layer.service.PuestoLocalService puestoLocalService) {
		this.puestoLocalService = puestoLocalService;
	}

	/**
	 * Returns the puesto remote service.
	 *
	 * @return the puesto remote service
	 */
	public com.rec.hitss.layer.service.PuestoService getPuestoService() {
		return puestoService;
	}

	/**
	 * Sets the puesto remote service.
	 *
	 * @param puestoService the puesto remote service
	 */
	public void setPuestoService(
		com.rec.hitss.layer.service.PuestoService puestoService) {
		this.puestoService = puestoService;
	}

	/**
	 * Returns the puesto persistence.
	 *
	 * @return the puesto persistence
	 */
	public PuestoPersistence getPuestoPersistence() {
		return puestoPersistence;
	}

	/**
	 * Sets the puesto persistence.
	 *
	 * @param puestoPersistence the puesto persistence
	 */
	public void setPuestoPersistence(PuestoPersistence puestoPersistence) {
		this.puestoPersistence = puestoPersistence;
	}

	/**
	 * Returns the referencia local service.
	 *
	 * @return the referencia local service
	 */
	public com.rec.hitss.layer.service.ReferenciaLocalService getReferenciaLocalService() {
		return referenciaLocalService;
	}

	/**
	 * Sets the referencia local service.
	 *
	 * @param referenciaLocalService the referencia local service
	 */
	public void setReferenciaLocalService(
		com.rec.hitss.layer.service.ReferenciaLocalService referenciaLocalService) {
		this.referenciaLocalService = referenciaLocalService;
	}

	/**
	 * Returns the referencia remote service.
	 *
	 * @return the referencia remote service
	 */
	public com.rec.hitss.layer.service.ReferenciaService getReferenciaService() {
		return referenciaService;
	}

	/**
	 * Sets the referencia remote service.
	 *
	 * @param referenciaService the referencia remote service
	 */
	public void setReferenciaService(
		com.rec.hitss.layer.service.ReferenciaService referenciaService) {
		this.referenciaService = referenciaService;
	}

	/**
	 * Returns the referencia persistence.
	 *
	 * @return the referencia persistence
	 */
	public ReferenciaPersistence getReferenciaPersistence() {
		return referenciaPersistence;
	}

	/**
	 * Sets the referencia persistence.
	 *
	 * @param referenciaPersistence the referencia persistence
	 */
	public void setReferenciaPersistence(
		ReferenciaPersistence referenciaPersistence) {
		this.referenciaPersistence = referenciaPersistence;
	}

	/**
	 * Returns the requisito local service.
	 *
	 * @return the requisito local service
	 */
	public com.rec.hitss.layer.service.RequisitoLocalService getRequisitoLocalService() {
		return requisitoLocalService;
	}

	/**
	 * Sets the requisito local service.
	 *
	 * @param requisitoLocalService the requisito local service
	 */
	public void setRequisitoLocalService(
		com.rec.hitss.layer.service.RequisitoLocalService requisitoLocalService) {
		this.requisitoLocalService = requisitoLocalService;
	}

	/**
	 * Returns the requisito remote service.
	 *
	 * @return the requisito remote service
	 */
	public com.rec.hitss.layer.service.RequisitoService getRequisitoService() {
		return requisitoService;
	}

	/**
	 * Sets the requisito remote service.
	 *
	 * @param requisitoService the requisito remote service
	 */
	public void setRequisitoService(
		com.rec.hitss.layer.service.RequisitoService requisitoService) {
		this.requisitoService = requisitoService;
	}

	/**
	 * Returns the requisito persistence.
	 *
	 * @return the requisito persistence
	 */
	public RequisitoPersistence getRequisitoPersistence() {
		return requisitoPersistence;
	}

	/**
	 * Sets the requisito persistence.
	 *
	 * @param requisitoPersistence the requisito persistence
	 */
	public void setRequisitoPersistence(
		RequisitoPersistence requisitoPersistence) {
		this.requisitoPersistence = requisitoPersistence;
	}

	/**
	 * Returns the respuesta local service.
	 *
	 * @return the respuesta local service
	 */
	public com.rec.hitss.layer.service.RespuestaLocalService getRespuestaLocalService() {
		return respuestaLocalService;
	}

	/**
	 * Sets the respuesta local service.
	 *
	 * @param respuestaLocalService the respuesta local service
	 */
	public void setRespuestaLocalService(
		com.rec.hitss.layer.service.RespuestaLocalService respuestaLocalService) {
		this.respuestaLocalService = respuestaLocalService;
	}

	/**
	 * Returns the respuesta remote service.
	 *
	 * @return the respuesta remote service
	 */
	public com.rec.hitss.layer.service.RespuestaService getRespuestaService() {
		return respuestaService;
	}

	/**
	 * Sets the respuesta remote service.
	 *
	 * @param respuestaService the respuesta remote service
	 */
	public void setRespuestaService(
		com.rec.hitss.layer.service.RespuestaService respuestaService) {
		this.respuestaService = respuestaService;
	}

	/**
	 * Returns the respuesta persistence.
	 *
	 * @return the respuesta persistence
	 */
	public RespuestaPersistence getRespuestaPersistence() {
		return respuestaPersistence;
	}

	/**
	 * Sets the respuesta persistence.
	 *
	 * @param respuestaPersistence the respuesta persistence
	 */
	public void setRespuestaPersistence(
		RespuestaPersistence respuestaPersistence) {
		this.respuestaPersistence = respuestaPersistence;
	}

	/**
	 * Returns the resultado evaluacion local service.
	 *
	 * @return the resultado evaluacion local service
	 */
	public com.rec.hitss.layer.service.ResultadoEvaluacionLocalService getResultadoEvaluacionLocalService() {
		return resultadoEvaluacionLocalService;
	}

	/**
	 * Sets the resultado evaluacion local service.
	 *
	 * @param resultadoEvaluacionLocalService the resultado evaluacion local service
	 */
	public void setResultadoEvaluacionLocalService(
		com.rec.hitss.layer.service.ResultadoEvaluacionLocalService resultadoEvaluacionLocalService) {
		this.resultadoEvaluacionLocalService = resultadoEvaluacionLocalService;
	}

	/**
	 * Returns the resultado evaluacion remote service.
	 *
	 * @return the resultado evaluacion remote service
	 */
	public com.rec.hitss.layer.service.ResultadoEvaluacionService getResultadoEvaluacionService() {
		return resultadoEvaluacionService;
	}

	/**
	 * Sets the resultado evaluacion remote service.
	 *
	 * @param resultadoEvaluacionService the resultado evaluacion remote service
	 */
	public void setResultadoEvaluacionService(
		com.rec.hitss.layer.service.ResultadoEvaluacionService resultadoEvaluacionService) {
		this.resultadoEvaluacionService = resultadoEvaluacionService;
	}

	/**
	 * Returns the resultado evaluacion persistence.
	 *
	 * @return the resultado evaluacion persistence
	 */
	public ResultadoEvaluacionPersistence getResultadoEvaluacionPersistence() {
		return resultadoEvaluacionPersistence;
	}

	/**
	 * Sets the resultado evaluacion persistence.
	 *
	 * @param resultadoEvaluacionPersistence the resultado evaluacion persistence
	 */
	public void setResultadoEvaluacionPersistence(
		ResultadoEvaluacionPersistence resultadoEvaluacionPersistence) {
		this.resultadoEvaluacionPersistence = resultadoEvaluacionPersistence;
	}

	/**
	 * Returns the solicitud requerimiento local service.
	 *
	 * @return the solicitud requerimiento local service
	 */
	public com.rec.hitss.layer.service.SolicitudRequerimientoLocalService getSolicitudRequerimientoLocalService() {
		return solicitudRequerimientoLocalService;
	}

	/**
	 * Sets the solicitud requerimiento local service.
	 *
	 * @param solicitudRequerimientoLocalService the solicitud requerimiento local service
	 */
	public void setSolicitudRequerimientoLocalService(
		com.rec.hitss.layer.service.SolicitudRequerimientoLocalService solicitudRequerimientoLocalService) {
		this.solicitudRequerimientoLocalService = solicitudRequerimientoLocalService;
	}

	/**
	 * Returns the solicitud requerimiento remote service.
	 *
	 * @return the solicitud requerimiento remote service
	 */
	public com.rec.hitss.layer.service.SolicitudRequerimientoService getSolicitudRequerimientoService() {
		return solicitudRequerimientoService;
	}

	/**
	 * Sets the solicitud requerimiento remote service.
	 *
	 * @param solicitudRequerimientoService the solicitud requerimiento remote service
	 */
	public void setSolicitudRequerimientoService(
		com.rec.hitss.layer.service.SolicitudRequerimientoService solicitudRequerimientoService) {
		this.solicitudRequerimientoService = solicitudRequerimientoService;
	}

	/**
	 * Returns the solicitud requerimiento persistence.
	 *
	 * @return the solicitud requerimiento persistence
	 */
	public SolicitudRequerimientoPersistence getSolicitudRequerimientoPersistence() {
		return solicitudRequerimientoPersistence;
	}

	/**
	 * Sets the solicitud requerimiento persistence.
	 *
	 * @param solicitudRequerimientoPersistence the solicitud requerimiento persistence
	 */
	public void setSolicitudRequerimientoPersistence(
		SolicitudRequerimientoPersistence solicitudRequerimientoPersistence) {
		this.solicitudRequerimientoPersistence = solicitudRequerimientoPersistence;
	}

	/**
	 * Returns the solicitud requerimiento requisito local service.
	 *
	 * @return the solicitud requerimiento requisito local service
	 */
	public com.rec.hitss.layer.service.SolicitudRequerimientoRequisitoLocalService getSolicitudRequerimientoRequisitoLocalService() {
		return solicitudRequerimientoRequisitoLocalService;
	}

	/**
	 * Sets the solicitud requerimiento requisito local service.
	 *
	 * @param solicitudRequerimientoRequisitoLocalService the solicitud requerimiento requisito local service
	 */
	public void setSolicitudRequerimientoRequisitoLocalService(
		com.rec.hitss.layer.service.SolicitudRequerimientoRequisitoLocalService solicitudRequerimientoRequisitoLocalService) {
		this.solicitudRequerimientoRequisitoLocalService = solicitudRequerimientoRequisitoLocalService;
	}

	/**
	 * Returns the solicitud requerimiento requisito remote service.
	 *
	 * @return the solicitud requerimiento requisito remote service
	 */
	public com.rec.hitss.layer.service.SolicitudRequerimientoRequisitoService getSolicitudRequerimientoRequisitoService() {
		return solicitudRequerimientoRequisitoService;
	}

	/**
	 * Sets the solicitud requerimiento requisito remote service.
	 *
	 * @param solicitudRequerimientoRequisitoService the solicitud requerimiento requisito remote service
	 */
	public void setSolicitudRequerimientoRequisitoService(
		com.rec.hitss.layer.service.SolicitudRequerimientoRequisitoService solicitudRequerimientoRequisitoService) {
		this.solicitudRequerimientoRequisitoService = solicitudRequerimientoRequisitoService;
	}

	/**
	 * Returns the solicitud requerimiento requisito persistence.
	 *
	 * @return the solicitud requerimiento requisito persistence
	 */
	public SolicitudRequerimientoRequisitoPersistence getSolicitudRequerimientoRequisitoPersistence() {
		return solicitudRequerimientoRequisitoPersistence;
	}

	/**
	 * Sets the solicitud requerimiento requisito persistence.
	 *
	 * @param solicitudRequerimientoRequisitoPersistence the solicitud requerimiento requisito persistence
	 */
	public void setSolicitudRequerimientoRequisitoPersistence(
		SolicitudRequerimientoRequisitoPersistence solicitudRequerimientoRequisitoPersistence) {
		this.solicitudRequerimientoRequisitoPersistence = solicitudRequerimientoRequisitoPersistence;
	}

	/**
	 * Returns the usuario local service.
	 *
	 * @return the usuario local service
	 */
	public com.rec.hitss.layer.service.UsuarioLocalService getUsuarioLocalService() {
		return usuarioLocalService;
	}

	/**
	 * Sets the usuario local service.
	 *
	 * @param usuarioLocalService the usuario local service
	 */
	public void setUsuarioLocalService(
		com.rec.hitss.layer.service.UsuarioLocalService usuarioLocalService) {
		this.usuarioLocalService = usuarioLocalService;
	}

	/**
	 * Returns the usuario remote service.
	 *
	 * @return the usuario remote service
	 */
	public com.rec.hitss.layer.service.UsuarioService getUsuarioService() {
		return usuarioService;
	}

	/**
	 * Sets the usuario remote service.
	 *
	 * @param usuarioService the usuario remote service
	 */
	public void setUsuarioService(
		com.rec.hitss.layer.service.UsuarioService usuarioService) {
		this.usuarioService = usuarioService;
	}

	/**
	 * Returns the usuario persistence.
	 *
	 * @return the usuario persistence
	 */
	public UsuarioPersistence getUsuarioPersistence() {
		return usuarioPersistence;
	}

	/**
	 * Sets the usuario persistence.
	 *
	 * @param usuarioPersistence the usuario persistence
	 */
	public void setUsuarioPersistence(UsuarioPersistence usuarioPersistence) {
		this.usuarioPersistence = usuarioPersistence;
	}

	/**
	 * Returns the usuario requisito local service.
	 *
	 * @return the usuario requisito local service
	 */
	public com.rec.hitss.layer.service.UsuarioRequisitoLocalService getUsuarioRequisitoLocalService() {
		return usuarioRequisitoLocalService;
	}

	/**
	 * Sets the usuario requisito local service.
	 *
	 * @param usuarioRequisitoLocalService the usuario requisito local service
	 */
	public void setUsuarioRequisitoLocalService(
		com.rec.hitss.layer.service.UsuarioRequisitoLocalService usuarioRequisitoLocalService) {
		this.usuarioRequisitoLocalService = usuarioRequisitoLocalService;
	}

	/**
	 * Returns the usuario requisito remote service.
	 *
	 * @return the usuario requisito remote service
	 */
	public com.rec.hitss.layer.service.UsuarioRequisitoService getUsuarioRequisitoService() {
		return usuarioRequisitoService;
	}

	/**
	 * Sets the usuario requisito remote service.
	 *
	 * @param usuarioRequisitoService the usuario requisito remote service
	 */
	public void setUsuarioRequisitoService(
		com.rec.hitss.layer.service.UsuarioRequisitoService usuarioRequisitoService) {
		this.usuarioRequisitoService = usuarioRequisitoService;
	}

	/**
	 * Returns the usuario requisito persistence.
	 *
	 * @return the usuario requisito persistence
	 */
	public UsuarioRequisitoPersistence getUsuarioRequisitoPersistence() {
		return usuarioRequisitoPersistence;
	}

	/**
	 * Sets the usuario requisito persistence.
	 *
	 * @param usuarioRequisitoPersistence the usuario requisito persistence
	 */
	public void setUsuarioRequisitoPersistence(
		UsuarioRequisitoPersistence usuarioRequisitoPersistence) {
		this.usuarioRequisitoPersistence = usuarioRequisitoPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return Funcion.class;
	}

	protected String getModelClassName() {
		return Funcion.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = funcionPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.rec.hitss.layer.service.ContratoLocalService.class)
	protected com.rec.hitss.layer.service.ContratoLocalService contratoLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.ContratoService.class)
	protected com.rec.hitss.layer.service.ContratoService contratoService;
	@BeanReference(type = ContratoPersistence.class)
	protected ContratoPersistence contratoPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.EstudioLocalService.class)
	protected com.rec.hitss.layer.service.EstudioLocalService estudioLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.EstudioService.class)
	protected com.rec.hitss.layer.service.EstudioService estudioService;
	@BeanReference(type = EstudioPersistence.class)
	protected EstudioPersistence estudioPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.EtiquetaRelacionadaLocalService.class)
	protected com.rec.hitss.layer.service.EtiquetaRelacionadaLocalService etiquetaRelacionadaLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.EtiquetaRelacionadaService.class)
	protected com.rec.hitss.layer.service.EtiquetaRelacionadaService etiquetaRelacionadaService;
	@BeanReference(type = EtiquetaRelacionadaPersistence.class)
	protected EtiquetaRelacionadaPersistence etiquetaRelacionadaPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.EvaluacionLocalService.class)
	protected com.rec.hitss.layer.service.EvaluacionLocalService evaluacionLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.EvaluacionService.class)
	protected com.rec.hitss.layer.service.EvaluacionService evaluacionService;
	@BeanReference(type = EvaluacionPersistence.class)
	protected EvaluacionPersistence evaluacionPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.EvaluacionPreguntaLocalService.class)
	protected com.rec.hitss.layer.service.EvaluacionPreguntaLocalService evaluacionPreguntaLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.EvaluacionPreguntaService.class)
	protected com.rec.hitss.layer.service.EvaluacionPreguntaService evaluacionPreguntaService;
	@BeanReference(type = EvaluacionPreguntaPersistence.class)
	protected EvaluacionPreguntaPersistence evaluacionPreguntaPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.ExperienciaLocalService.class)
	protected com.rec.hitss.layer.service.ExperienciaLocalService experienciaLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.ExperienciaService.class)
	protected com.rec.hitss.layer.service.ExperienciaService experienciaService;
	@BeanReference(type = ExperienciaPersistence.class)
	protected ExperienciaPersistence experienciaPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.FasePostulacionLocalService.class)
	protected com.rec.hitss.layer.service.FasePostulacionLocalService fasePostulacionLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.FasePostulacionService.class)
	protected com.rec.hitss.layer.service.FasePostulacionService fasePostulacionService;
	@BeanReference(type = FasePostulacionPersistence.class)
	protected FasePostulacionPersistence fasePostulacionPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.FuncionLocalService.class)
	protected com.rec.hitss.layer.service.FuncionLocalService funcionLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.FuncionService.class)
	protected com.rec.hitss.layer.service.FuncionService funcionService;
	@BeanReference(type = FuncionPersistence.class)
	protected FuncionPersistence funcionPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.PostulacionLocalService.class)
	protected com.rec.hitss.layer.service.PostulacionLocalService postulacionLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.PostulacionService.class)
	protected com.rec.hitss.layer.service.PostulacionService postulacionService;
	@BeanReference(type = PostulacionPersistence.class)
	protected PostulacionPersistence postulacionPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.PreguntaLocalService.class)
	protected com.rec.hitss.layer.service.PreguntaLocalService preguntaLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.PreguntaService.class)
	protected com.rec.hitss.layer.service.PreguntaService preguntaService;
	@BeanReference(type = PreguntaPersistence.class)
	protected PreguntaPersistence preguntaPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.PuestoLocalService.class)
	protected com.rec.hitss.layer.service.PuestoLocalService puestoLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.PuestoService.class)
	protected com.rec.hitss.layer.service.PuestoService puestoService;
	@BeanReference(type = PuestoPersistence.class)
	protected PuestoPersistence puestoPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.ReferenciaLocalService.class)
	protected com.rec.hitss.layer.service.ReferenciaLocalService referenciaLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.ReferenciaService.class)
	protected com.rec.hitss.layer.service.ReferenciaService referenciaService;
	@BeanReference(type = ReferenciaPersistence.class)
	protected ReferenciaPersistence referenciaPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.RequisitoLocalService.class)
	protected com.rec.hitss.layer.service.RequisitoLocalService requisitoLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.RequisitoService.class)
	protected com.rec.hitss.layer.service.RequisitoService requisitoService;
	@BeanReference(type = RequisitoPersistence.class)
	protected RequisitoPersistence requisitoPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.RespuestaLocalService.class)
	protected com.rec.hitss.layer.service.RespuestaLocalService respuestaLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.RespuestaService.class)
	protected com.rec.hitss.layer.service.RespuestaService respuestaService;
	@BeanReference(type = RespuestaPersistence.class)
	protected RespuestaPersistence respuestaPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.ResultadoEvaluacionLocalService.class)
	protected com.rec.hitss.layer.service.ResultadoEvaluacionLocalService resultadoEvaluacionLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.ResultadoEvaluacionService.class)
	protected com.rec.hitss.layer.service.ResultadoEvaluacionService resultadoEvaluacionService;
	@BeanReference(type = ResultadoEvaluacionPersistence.class)
	protected ResultadoEvaluacionPersistence resultadoEvaluacionPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.SolicitudRequerimientoLocalService.class)
	protected com.rec.hitss.layer.service.SolicitudRequerimientoLocalService solicitudRequerimientoLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.SolicitudRequerimientoService.class)
	protected com.rec.hitss.layer.service.SolicitudRequerimientoService solicitudRequerimientoService;
	@BeanReference(type = SolicitudRequerimientoPersistence.class)
	protected SolicitudRequerimientoPersistence solicitudRequerimientoPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.SolicitudRequerimientoRequisitoLocalService.class)
	protected com.rec.hitss.layer.service.SolicitudRequerimientoRequisitoLocalService solicitudRequerimientoRequisitoLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.SolicitudRequerimientoRequisitoService.class)
	protected com.rec.hitss.layer.service.SolicitudRequerimientoRequisitoService solicitudRequerimientoRequisitoService;
	@BeanReference(type = SolicitudRequerimientoRequisitoPersistence.class)
	protected SolicitudRequerimientoRequisitoPersistence solicitudRequerimientoRequisitoPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.UsuarioLocalService.class)
	protected com.rec.hitss.layer.service.UsuarioLocalService usuarioLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.UsuarioService.class)
	protected com.rec.hitss.layer.service.UsuarioService usuarioService;
	@BeanReference(type = UsuarioPersistence.class)
	protected UsuarioPersistence usuarioPersistence;
	@BeanReference(type = com.rec.hitss.layer.service.UsuarioRequisitoLocalService.class)
	protected com.rec.hitss.layer.service.UsuarioRequisitoLocalService usuarioRequisitoLocalService;
	@BeanReference(type = com.rec.hitss.layer.service.UsuarioRequisitoService.class)
	protected com.rec.hitss.layer.service.UsuarioRequisitoService usuarioRequisitoService;
	@BeanReference(type = UsuarioRequisitoPersistence.class)
	protected UsuarioRequisitoPersistence usuarioRequisitoPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private FuncionServiceClpInvoker _clpInvoker = new FuncionServiceClpInvoker();
}