/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rec.hitss.layer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the avanceEstadoSolicitudReclutamiento service. Represents a row in the &quot;AVANCE_ESTADO_SOLICITUD_RECLUTAMIENTO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rec.hitss.layer.model.impl.avanceEstadoSolicitudReclutamientoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rec.hitss.layer.model.impl.avanceEstadoSolicitudReclutamientoImpl}.
 * </p>
 *
 * @author Crossfire
 * @see avanceEstadoSolicitudReclutamiento
 * @see com.rec.hitss.layer.model.impl.avanceEstadoSolicitudReclutamientoImpl
 * @see com.rec.hitss.layer.model.impl.avanceEstadoSolicitudReclutamientoModelImpl
 * @generated
 */
public interface avanceEstadoSolicitudReclutamientoModel extends BaseModel<avanceEstadoSolicitudReclutamiento> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a avance estado solicitud reclutamiento model instance should use the {@link avanceEstadoSolicitudReclutamiento} interface instead.
	 */

	/**
	 * Returns the primary key of this avance estado solicitud reclutamiento.
	 *
	 * @return the primary key of this avance estado solicitud reclutamiento
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this avance estado solicitud reclutamiento.
	 *
	 * @param primaryKey the primary key of this avance estado solicitud reclutamiento
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the a e s r_ i d of this avance estado solicitud reclutamiento.
	 *
	 * @return the a e s r_ i d of this avance estado solicitud reclutamiento
	 */
	public long getAESR_ID();

	/**
	 * Sets the a e s r_ i d of this avance estado solicitud reclutamiento.
	 *
	 * @param AESR_ID the a e s r_ i d of this avance estado solicitud reclutamiento
	 */
	public void setAESR_ID(long AESR_ID);

	/**
	 * Returns the a e s r_ e s t a d o of this avance estado solicitud reclutamiento.
	 *
	 * @return the a e s r_ e s t a d o of this avance estado solicitud reclutamiento
	 */
	@AutoEscape
	public String getAESR_ESTADO();

	/**
	 * Sets the a e s r_ e s t a d o of this avance estado solicitud reclutamiento.
	 *
	 * @param AESR_ESTADO the a e s r_ e s t a d o of this avance estado solicitud reclutamiento
	 */
	public void setAESR_ESTADO(String AESR_ESTADO);

	/**
	 * Returns the a e s r_ a c t i v o of this avance estado solicitud reclutamiento.
	 *
	 * @return the a e s r_ a c t i v o of this avance estado solicitud reclutamiento
	 */
	@AutoEscape
	public String getAESR_ACTIVO();

	/**
	 * Sets the a e s r_ a c t i v o of this avance estado solicitud reclutamiento.
	 *
	 * @param AESR_ACTIVO the a e s r_ a c t i v o of this avance estado solicitud reclutamiento
	 */
	public void setAESR_ACTIVO(String AESR_ACTIVO);

	/**
	 * Returns the a e s r_ u s u a r i o_ c r e a of this avance estado solicitud reclutamiento.
	 *
	 * @return the a e s r_ u s u a r i o_ c r e a of this avance estado solicitud reclutamiento
	 */
	public long getAESR_USUARIO_CREA();

	/**
	 * Sets the a e s r_ u s u a r i o_ c r e a of this avance estado solicitud reclutamiento.
	 *
	 * @param AESR_USUARIO_CREA the a e s r_ u s u a r i o_ c r e a of this avance estado solicitud reclutamiento
	 */
	public void setAESR_USUARIO_CREA(long AESR_USUARIO_CREA);

	/**
	 * Returns the a e s r_ f e c h a_ c r e a of this avance estado solicitud reclutamiento.
	 *
	 * @return the a e s r_ f e c h a_ c r e a of this avance estado solicitud reclutamiento
	 */
	public Date getAESR_FECHA_CREA();

	/**
	 * Sets the a e s r_ f e c h a_ c r e a of this avance estado solicitud reclutamiento.
	 *
	 * @param AESR_FECHA_CREA the a e s r_ f e c h a_ c r e a of this avance estado solicitud reclutamiento
	 */
	public void setAESR_FECHA_CREA(Date AESR_FECHA_CREA);

	/**
	 * Returns the a e s r_ u s u a r i o_ m o d i f i c a of this avance estado solicitud reclutamiento.
	 *
	 * @return the a e s r_ u s u a r i o_ m o d i f i c a of this avance estado solicitud reclutamiento
	 */
	public long getAESR_USUARIO_MODIFICA();

	/**
	 * Sets the a e s r_ u s u a r i o_ m o d i f i c a of this avance estado solicitud reclutamiento.
	 *
	 * @param AESR_USUARIO_MODIFICA the a e s r_ u s u a r i o_ m o d i f i c a of this avance estado solicitud reclutamiento
	 */
	public void setAESR_USUARIO_MODIFICA(long AESR_USUARIO_MODIFICA);

	/**
	 * Returns the a e s r_ f e c h a_ m o d i f i c a of this avance estado solicitud reclutamiento.
	 *
	 * @return the a e s r_ f e c h a_ m o d i f i c a of this avance estado solicitud reclutamiento
	 */
	public Date getAESR_FECHA_MODIFICA();

	/**
	 * Sets the a e s r_ f e c h a_ m o d i f i c a of this avance estado solicitud reclutamiento.
	 *
	 * @param AESR_FECHA_MODIFICA the a e s r_ f e c h a_ m o d i f i c a of this avance estado solicitud reclutamiento
	 */
	public void setAESR_FECHA_MODIFICA(Date AESR_FECHA_MODIFICA);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.rec.hitss.layer.model.avanceEstadoSolicitudReclutamiento avanceEstadoSolicitudReclutamiento);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rec.hitss.layer.model.avanceEstadoSolicitudReclutamiento> toCacheModel();

	@Override
	public com.rec.hitss.layer.model.avanceEstadoSolicitudReclutamiento toEscapedModel();

	@Override
	public com.rec.hitss.layer.model.avanceEstadoSolicitudReclutamiento toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}