/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rec.hitss.layer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the curriculumVitae service. Represents a row in the &quot;CURRICULUM_VITAE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rec.hitss.layer.model.impl.curriculumVitaeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rec.hitss.layer.model.impl.curriculumVitaeImpl}.
 * </p>
 *
 * @author Crossfire
 * @see curriculumVitae
 * @see com.rec.hitss.layer.model.impl.curriculumVitaeImpl
 * @see com.rec.hitss.layer.model.impl.curriculumVitaeModelImpl
 * @generated
 */
public interface curriculumVitaeModel extends BaseModel<curriculumVitae> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a curriculum vitae model instance should use the {@link curriculumVitae} interface instead.
	 */

	/**
	 * Returns the primary key of this curriculum vitae.
	 *
	 * @return the primary key of this curriculum vitae
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this curriculum vitae.
	 *
	 * @param primaryKey the primary key of this curriculum vitae
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the c v_ i d of this curriculum vitae.
	 *
	 * @return the c v_ i d of this curriculum vitae
	 */
	public long getCV_ID();

	/**
	 * Sets the c v_ i d of this curriculum vitae.
	 *
	 * @param CV_ID the c v_ i d of this curriculum vitae
	 */
	public void setCV_ID(long CV_ID);

	/**
	 * Returns the c v_ e s t a d o of this curriculum vitae.
	 *
	 * @return the c v_ e s t a d o of this curriculum vitae
	 */
	@AutoEscape
	public String getCV_ESTADO();

	/**
	 * Sets the c v_ e s t a d o of this curriculum vitae.
	 *
	 * @param CV_ESTADO the c v_ e s t a d o of this curriculum vitae
	 */
	public void setCV_ESTADO(String CV_ESTADO);

	/**
	 * Returns the c v_ a c t i v o of this curriculum vitae.
	 *
	 * @return the c v_ a c t i v o of this curriculum vitae
	 */
	@AutoEscape
	public String getCV_ACTIVO();

	/**
	 * Sets the c v_ a c t i v o of this curriculum vitae.
	 *
	 * @param CV_ACTIVO the c v_ a c t i v o of this curriculum vitae
	 */
	public void setCV_ACTIVO(String CV_ACTIVO);

	/**
	 * Returns the c v_ u s u a r i o_ c r e a of this curriculum vitae.
	 *
	 * @return the c v_ u s u a r i o_ c r e a of this curriculum vitae
	 */
	public long getCV_USUARIO_CREA();

	/**
	 * Sets the c v_ u s u a r i o_ c r e a of this curriculum vitae.
	 *
	 * @param CV_USUARIO_CREA the c v_ u s u a r i o_ c r e a of this curriculum vitae
	 */
	public void setCV_USUARIO_CREA(long CV_USUARIO_CREA);

	/**
	 * Returns the c v_ f e c h a_ c r e a of this curriculum vitae.
	 *
	 * @return the c v_ f e c h a_ c r e a of this curriculum vitae
	 */
	public Date getCV_FECHA_CREA();

	/**
	 * Sets the c v_ f e c h a_ c r e a of this curriculum vitae.
	 *
	 * @param CV_FECHA_CREA the c v_ f e c h a_ c r e a of this curriculum vitae
	 */
	public void setCV_FECHA_CREA(Date CV_FECHA_CREA);

	/**
	 * Returns the c v_ u s u a r i o_ m o d i f i c a of this curriculum vitae.
	 *
	 * @return the c v_ u s u a r i o_ m o d i f i c a of this curriculum vitae
	 */
	public long getCV_USUARIO_MODIFICA();

	/**
	 * Sets the c v_ u s u a r i o_ m o d i f i c a of this curriculum vitae.
	 *
	 * @param CV_USUARIO_MODIFICA the c v_ u s u a r i o_ m o d i f i c a of this curriculum vitae
	 */
	public void setCV_USUARIO_MODIFICA(long CV_USUARIO_MODIFICA);

	/**
	 * Returns the c v_ f e c h a_ m o d i f i c a of this curriculum vitae.
	 *
	 * @return the c v_ f e c h a_ m o d i f i c a of this curriculum vitae
	 */
	public Date getCV_FECHA_MODIFICA();

	/**
	 * Sets the c v_ f e c h a_ m o d i f i c a of this curriculum vitae.
	 *
	 * @param CV_FECHA_MODIFICA the c v_ f e c h a_ m o d i f i c a of this curriculum vitae
	 */
	public void setCV_FECHA_MODIFICA(Date CV_FECHA_MODIFICA);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.rec.hitss.layer.model.curriculumVitae curriculumVitae);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rec.hitss.layer.model.curriculumVitae> toCacheModel();

	@Override
	public com.rec.hitss.layer.model.curriculumVitae toEscapedModel();

	@Override
	public com.rec.hitss.layer.model.curriculumVitae toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}