/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rec.hitss.layer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the nueveCuadrantes service. Represents a row in the &quot;NUEVE_CUADRANTES&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rec.hitss.layer.model.impl.nueveCuadrantesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rec.hitss.layer.model.impl.nueveCuadrantesImpl}.
 * </p>
 *
 * @author Crossfire
 * @see nueveCuadrantes
 * @see com.rec.hitss.layer.model.impl.nueveCuadrantesImpl
 * @see com.rec.hitss.layer.model.impl.nueveCuadrantesModelImpl
 * @generated
 */
public interface nueveCuadrantesModel extends BaseModel<nueveCuadrantes> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a nueve cuadrantes model instance should use the {@link nueveCuadrantes} interface instead.
	 */

	/**
	 * Returns the primary key of this nueve cuadrantes.
	 *
	 * @return the primary key of this nueve cuadrantes
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this nueve cuadrantes.
	 *
	 * @param primaryKey the primary key of this nueve cuadrantes
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the n c_ i d of this nueve cuadrantes.
	 *
	 * @return the n c_ i d of this nueve cuadrantes
	 */
	public long getNC_ID();

	/**
	 * Sets the n c_ i d of this nueve cuadrantes.
	 *
	 * @param NC_ID the n c_ i d of this nueve cuadrantes
	 */
	public void setNC_ID(long NC_ID);

	/**
	 * Returns the r e q_ e s t a d o of this nueve cuadrantes.
	 *
	 * @return the r e q_ e s t a d o of this nueve cuadrantes
	 */
	@AutoEscape
	public String getREQ_ESTADO();

	/**
	 * Sets the r e q_ e s t a d o of this nueve cuadrantes.
	 *
	 * @param REQ_ESTADO the r e q_ e s t a d o of this nueve cuadrantes
	 */
	public void setREQ_ESTADO(String REQ_ESTADO);

	/**
	 * Returns the r e q_ a c t i v o of this nueve cuadrantes.
	 *
	 * @return the r e q_ a c t i v o of this nueve cuadrantes
	 */
	@AutoEscape
	public String getREQ_ACTIVO();

	/**
	 * Sets the r e q_ a c t i v o of this nueve cuadrantes.
	 *
	 * @param REQ_ACTIVO the r e q_ a c t i v o of this nueve cuadrantes
	 */
	public void setREQ_ACTIVO(String REQ_ACTIVO);

	/**
	 * Returns the s r_ u s u a r i o_ c r e a of this nueve cuadrantes.
	 *
	 * @return the s r_ u s u a r i o_ c r e a of this nueve cuadrantes
	 */
	public long getSR_USUARIO_CREA();

	/**
	 * Sets the s r_ u s u a r i o_ c r e a of this nueve cuadrantes.
	 *
	 * @param SR_USUARIO_CREA the s r_ u s u a r i o_ c r e a of this nueve cuadrantes
	 */
	public void setSR_USUARIO_CREA(long SR_USUARIO_CREA);

	/**
	 * Returns the s r_ f e c h a_ c r e a of this nueve cuadrantes.
	 *
	 * @return the s r_ f e c h a_ c r e a of this nueve cuadrantes
	 */
	public Date getSR_FECHA_CREA();

	/**
	 * Sets the s r_ f e c h a_ c r e a of this nueve cuadrantes.
	 *
	 * @param SR_FECHA_CREA the s r_ f e c h a_ c r e a of this nueve cuadrantes
	 */
	public void setSR_FECHA_CREA(Date SR_FECHA_CREA);

	/**
	 * Returns the s r_ u s u a r i o_ m o d i f i c a of this nueve cuadrantes.
	 *
	 * @return the s r_ u s u a r i o_ m o d i f i c a of this nueve cuadrantes
	 */
	public long getSR_USUARIO_MODIFICA();

	/**
	 * Sets the s r_ u s u a r i o_ m o d i f i c a of this nueve cuadrantes.
	 *
	 * @param SR_USUARIO_MODIFICA the s r_ u s u a r i o_ m o d i f i c a of this nueve cuadrantes
	 */
	public void setSR_USUARIO_MODIFICA(long SR_USUARIO_MODIFICA);

	/**
	 * Returns the s r_ f e c h a_ m o d i f i c a of this nueve cuadrantes.
	 *
	 * @return the s r_ f e c h a_ m o d i f i c a of this nueve cuadrantes
	 */
	public Date getSR_FECHA_MODIFICA();

	/**
	 * Sets the s r_ f e c h a_ m o d i f i c a of this nueve cuadrantes.
	 *
	 * @param SR_FECHA_MODIFICA the s r_ f e c h a_ m o d i f i c a of this nueve cuadrantes
	 */
	public void setSR_FECHA_MODIFICA(Date SR_FECHA_MODIFICA);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.rec.hitss.layer.model.nueveCuadrantes nueveCuadrantes);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rec.hitss.layer.model.nueveCuadrantes> toCacheModel();

	@Override
	public com.rec.hitss.layer.model.nueveCuadrantes toEscapedModel();

	@Override
	public com.rec.hitss.layer.model.nueveCuadrantes toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}