/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rec.hitss.layer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the puestosLaborales service. Represents a row in the &quot;PUESTOS_LABORALES&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rec.hitss.layer.model.impl.puestosLaboralesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rec.hitss.layer.model.impl.puestosLaboralesImpl}.
 * </p>
 *
 * @author Crossfire
 * @see puestosLaborales
 * @see com.rec.hitss.layer.model.impl.puestosLaboralesImpl
 * @see com.rec.hitss.layer.model.impl.puestosLaboralesModelImpl
 * @generated
 */
public interface puestosLaboralesModel extends BaseModel<puestosLaborales> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a puestos laborales model instance should use the {@link puestosLaborales} interface instead.
	 */

	/**
	 * Returns the primary key of this puestos laborales.
	 *
	 * @return the primary key of this puestos laborales
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this puestos laborales.
	 *
	 * @param primaryKey the primary key of this puestos laborales
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the p l_ i d of this puestos laborales.
	 *
	 * @return the p l_ i d of this puestos laborales
	 */
	public long getPL_ID();

	/**
	 * Sets the p l_ i d of this puestos laborales.
	 *
	 * @param PL_ID the p l_ i d of this puestos laborales
	 */
	public void setPL_ID(long PL_ID);

	/**
	 * Returns the p l_ p u e s t o of this puestos laborales.
	 *
	 * @return the p l_ p u e s t o of this puestos laborales
	 */
	@AutoEscape
	public String getPL_PUESTO();

	/**
	 * Sets the p l_ p u e s t o of this puestos laborales.
	 *
	 * @param PL_PUESTO the p l_ p u e s t o of this puestos laborales
	 */
	public void setPL_PUESTO(String PL_PUESTO);

	/**
	 * Returns the p l_ e s t a d o of this puestos laborales.
	 *
	 * @return the p l_ e s t a d o of this puestos laborales
	 */
	@AutoEscape
	public String getPL_ESTADO();

	/**
	 * Sets the p l_ e s t a d o of this puestos laborales.
	 *
	 * @param PL_ESTADO the p l_ e s t a d o of this puestos laborales
	 */
	public void setPL_ESTADO(String PL_ESTADO);

	/**
	 * Returns the p l_ a c t i v o of this puestos laborales.
	 *
	 * @return the p l_ a c t i v o of this puestos laborales
	 */
	@AutoEscape
	public String getPL_ACTIVO();

	/**
	 * Sets the p l_ a c t i v o of this puestos laborales.
	 *
	 * @param PL_ACTIVO the p l_ a c t i v o of this puestos laborales
	 */
	public void setPL_ACTIVO(String PL_ACTIVO);

	/**
	 * Returns the p l_ u s u a r i o_ c r e a of this puestos laborales.
	 *
	 * @return the p l_ u s u a r i o_ c r e a of this puestos laborales
	 */
	public long getPL_USUARIO_CREA();

	/**
	 * Sets the p l_ u s u a r i o_ c r e a of this puestos laborales.
	 *
	 * @param PL_USUARIO_CREA the p l_ u s u a r i o_ c r e a of this puestos laborales
	 */
	public void setPL_USUARIO_CREA(long PL_USUARIO_CREA);

	/**
	 * Returns the p l_ f e c h a_ c r e a of this puestos laborales.
	 *
	 * @return the p l_ f e c h a_ c r e a of this puestos laborales
	 */
	public Date getPL_FECHA_CREA();

	/**
	 * Sets the p l_ f e c h a_ c r e a of this puestos laborales.
	 *
	 * @param PL_FECHA_CREA the p l_ f e c h a_ c r e a of this puestos laborales
	 */
	public void setPL_FECHA_CREA(Date PL_FECHA_CREA);

	/**
	 * Returns the p l_ u s u a r i o_ m o d i f i c a of this puestos laborales.
	 *
	 * @return the p l_ u s u a r i o_ m o d i f i c a of this puestos laborales
	 */
	public long getPL_USUARIO_MODIFICA();

	/**
	 * Sets the p l_ u s u a r i o_ m o d i f i c a of this puestos laborales.
	 *
	 * @param PL_USUARIO_MODIFICA the p l_ u s u a r i o_ m o d i f i c a of this puestos laborales
	 */
	public void setPL_USUARIO_MODIFICA(long PL_USUARIO_MODIFICA);

	/**
	 * Returns the p l_ f e c h a_ m o d i f i c a of this puestos laborales.
	 *
	 * @return the p l_ f e c h a_ m o d i f i c a of this puestos laborales
	 */
	public Date getPL_FECHA_MODIFICA();

	/**
	 * Sets the p l_ f e c h a_ m o d i f i c a of this puestos laborales.
	 *
	 * @param PL_FECHA_MODIFICA the p l_ f e c h a_ m o d i f i c a of this puestos laborales
	 */
	public void setPL_FECHA_MODIFICA(Date PL_FECHA_MODIFICA);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.rec.hitss.layer.model.puestosLaborales puestosLaborales);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rec.hitss.layer.model.puestosLaborales> toCacheModel();

	@Override
	public com.rec.hitss.layer.model.puestosLaborales toEscapedModel();

	@Override
	public com.rec.hitss.layer.model.puestosLaborales toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}