/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rec.hitss.layer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the requerimientoPersonal service. Represents a row in the &quot;REQUERIMIENTO_PERSONAL&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rec.hitss.layer.model.impl.requerimientoPersonalModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rec.hitss.layer.model.impl.requerimientoPersonalImpl}.
 * </p>
 *
 * @author Crossfire
 * @see requerimientoPersonal
 * @see com.rec.hitss.layer.model.impl.requerimientoPersonalImpl
 * @see com.rec.hitss.layer.model.impl.requerimientoPersonalModelImpl
 * @generated
 */
public interface requerimientoPersonalModel extends BaseModel<requerimientoPersonal> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a requerimiento personal model instance should use the {@link requerimientoPersonal} interface instead.
	 */

	/**
	 * Returns the primary key of this requerimiento personal.
	 *
	 * @return the primary key of this requerimiento personal
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this requerimiento personal.
	 *
	 * @param primaryKey the primary key of this requerimiento personal
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the r e q_ i d of this requerimiento personal.
	 *
	 * @return the r e q_ i d of this requerimiento personal
	 */
	public long getREQ_ID();

	/**
	 * Sets the r e q_ i d of this requerimiento personal.
	 *
	 * @param REQ_ID the r e q_ i d of this requerimiento personal
	 */
	public void setREQ_ID(long REQ_ID);

	/**
	 * Returns the r e q_ e s t a d o of this requerimiento personal.
	 *
	 * @return the r e q_ e s t a d o of this requerimiento personal
	 */
	@AutoEscape
	public String getREQ_ESTADO();

	/**
	 * Sets the r e q_ e s t a d o of this requerimiento personal.
	 *
	 * @param REQ_ESTADO the r e q_ e s t a d o of this requerimiento personal
	 */
	public void setREQ_ESTADO(String REQ_ESTADO);

	/**
	 * Returns the r e q_ a c t i v o of this requerimiento personal.
	 *
	 * @return the r e q_ a c t i v o of this requerimiento personal
	 */
	@AutoEscape
	public String getREQ_ACTIVO();

	/**
	 * Sets the r e q_ a c t i v o of this requerimiento personal.
	 *
	 * @param REQ_ACTIVO the r e q_ a c t i v o of this requerimiento personal
	 */
	public void setREQ_ACTIVO(String REQ_ACTIVO);

	/**
	 * Returns the r e q_ u s u a r i o_ c r e a of this requerimiento personal.
	 *
	 * @return the r e q_ u s u a r i o_ c r e a of this requerimiento personal
	 */
	public long getREQ_USUARIO_CREA();

	/**
	 * Sets the r e q_ u s u a r i o_ c r e a of this requerimiento personal.
	 *
	 * @param REQ_USUARIO_CREA the r e q_ u s u a r i o_ c r e a of this requerimiento personal
	 */
	public void setREQ_USUARIO_CREA(long REQ_USUARIO_CREA);

	/**
	 * Returns the r e q_ f e c h a_ c r e a of this requerimiento personal.
	 *
	 * @return the r e q_ f e c h a_ c r e a of this requerimiento personal
	 */
	public Date getREQ_FECHA_CREA();

	/**
	 * Sets the r e q_ f e c h a_ c r e a of this requerimiento personal.
	 *
	 * @param REQ_FECHA_CREA the r e q_ f e c h a_ c r e a of this requerimiento personal
	 */
	public void setREQ_FECHA_CREA(Date REQ_FECHA_CREA);

	/**
	 * Returns the r e q_ u s u a r i o_ m o d i f i c a of this requerimiento personal.
	 *
	 * @return the r e q_ u s u a r i o_ m o d i f i c a of this requerimiento personal
	 */
	public long getREQ_USUARIO_MODIFICA();

	/**
	 * Sets the r e q_ u s u a r i o_ m o d i f i c a of this requerimiento personal.
	 *
	 * @param REQ_USUARIO_MODIFICA the r e q_ u s u a r i o_ m o d i f i c a of this requerimiento personal
	 */
	public void setREQ_USUARIO_MODIFICA(long REQ_USUARIO_MODIFICA);

	/**
	 * Returns the r e q_ f e c h a_ m o d i f i c a of this requerimiento personal.
	 *
	 * @return the r e q_ f e c h a_ m o d i f i c a of this requerimiento personal
	 */
	public Date getREQ_FECHA_MODIFICA();

	/**
	 * Sets the r e q_ f e c h a_ m o d i f i c a of this requerimiento personal.
	 *
	 * @param REQ_FECHA_MODIFICA the r e q_ f e c h a_ m o d i f i c a of this requerimiento personal
	 */
	public void setREQ_FECHA_MODIFICA(Date REQ_FECHA_MODIFICA);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.rec.hitss.layer.model.requerimientoPersonal requerimientoPersonal);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rec.hitss.layer.model.requerimientoPersonal> toCacheModel();

	@Override
	public com.rec.hitss.layer.model.requerimientoPersonal toEscapedModel();

	@Override
	public com.rec.hitss.layer.model.requerimientoPersonal toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}