/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.hitss.layer.service.base;

import com.hitss.layer.model.ActividadPlan;
import com.hitss.layer.service.ActividadPlanLocalService;
import com.hitss.layer.service.persistence.ActividadCronogramaPersistence;
import com.hitss.layer.service.persistence.ActividadPlanPersistence;
import com.hitss.layer.service.persistence.ContratoPersistence;
import com.hitss.layer.service.persistence.CronogramaPersistence;
import com.hitss.layer.service.persistence.DetalleRepuestaEvaluacionPersistence;
import com.hitss.layer.service.persistence.DetalleRepuestaReclutamientoPersistence;
import com.hitss.layer.service.persistence.EstudioPersistence;
import com.hitss.layer.service.persistence.EtiquetaRelacionadaPersistence;
import com.hitss.layer.service.persistence.EvaluacionPersistence;
import com.hitss.layer.service.persistence.EvaluacionPreguntaPersistence;
import com.hitss.layer.service.persistence.ExperienciaPersistence;
import com.hitss.layer.service.persistence.FasePostulacionPersistence;
import com.hitss.layer.service.persistence.FichaIngresoPersistence;
import com.hitss.layer.service.persistence.FuncionPersistence;
import com.hitss.layer.service.persistence.InformeRetroalimentacionPersistence;
import com.hitss.layer.service.persistence.LogOperacionesPersistence;
import com.hitss.layer.service.persistence.ObservacionesPersistence;
import com.hitss.layer.service.persistence.ParametroFinder;
import com.hitss.layer.service.persistence.ParametroPersistence;
import com.hitss.layer.service.persistence.PlanAccionPersistence;
import com.hitss.layer.service.persistence.PostulacionPersistence;
import com.hitss.layer.service.persistence.PreguntaPersistence;
import com.hitss.layer.service.persistence.PrioridadGrupoUsuariosPersistence;
import com.hitss.layer.service.persistence.ReferenciaPersistence;
import com.hitss.layer.service.persistence.RespuestaPersistence;
import com.hitss.layer.service.persistence.SolicitudEvaluacionDesempennoPersistence;
import com.hitss.layer.service.persistence.SolicitudRequerimientoPersistence;
import com.hitss.layer.service.persistence.SolicitudRequerimientoRequisitoPersistence;
import com.hitss.layer.service.persistence.UsuarioEvaluacionPersistence;
import com.hitss.layer.service.persistence.UsuarioPersistence;
import com.hitss.layer.service.persistence.UsuarioRequisitoPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.persistence.UserPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the actividad plan local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.hitss.layer.service.impl.ActividadPlanLocalServiceImpl}.
 * </p>
 *
 * @author Danielle Delgado
 * @see com.hitss.layer.service.impl.ActividadPlanLocalServiceImpl
 * @see com.hitss.layer.service.ActividadPlanLocalServiceUtil
 * @generated
 */
public abstract class ActividadPlanLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements ActividadPlanLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.hitss.layer.service.ActividadPlanLocalServiceUtil} to access the actividad plan local service.
	 */

	/**
	 * Adds the actividad plan to the database. Also notifies the appropriate model listeners.
	 *
	 * @param actividadPlan the actividad plan
	 * @return the actividad plan that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ActividadPlan addActividadPlan(ActividadPlan actividadPlan)
		throws SystemException {
		actividadPlan.setNew(true);

		return actividadPlanPersistence.update(actividadPlan);
	}

	/**
	 * Creates a new actividad plan with the primary key. Does not add the actividad plan to the database.
	 *
	 * @param actividadPlanId the primary key for the new actividad plan
	 * @return the new actividad plan
	 */
	@Override
	public ActividadPlan createActividadPlan(long actividadPlanId) {
		return actividadPlanPersistence.create(actividadPlanId);
	}

	/**
	 * Deletes the actividad plan with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param actividadPlanId the primary key of the actividad plan
	 * @return the actividad plan that was removed
	 * @throws PortalException if a actividad plan with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ActividadPlan deleteActividadPlan(long actividadPlanId)
		throws PortalException, SystemException {
		return actividadPlanPersistence.remove(actividadPlanId);
	}

	/**
	 * Deletes the actividad plan from the database. Also notifies the appropriate model listeners.
	 *
	 * @param actividadPlan the actividad plan
	 * @return the actividad plan that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ActividadPlan deleteActividadPlan(ActividadPlan actividadPlan)
		throws SystemException {
		return actividadPlanPersistence.remove(actividadPlan);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(ActividadPlan.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return actividadPlanPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.hitss.layer.model.impl.ActividadPlanModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return actividadPlanPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.hitss.layer.model.impl.ActividadPlanModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return actividadPlanPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return actividadPlanPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) throws SystemException {
		return actividadPlanPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public ActividadPlan fetchActividadPlan(long actividadPlanId)
		throws SystemException {
		return actividadPlanPersistence.fetchByPrimaryKey(actividadPlanId);
	}

	/**
	 * Returns the actividad plan with the primary key.
	 *
	 * @param actividadPlanId the primary key of the actividad plan
	 * @return the actividad plan
	 * @throws PortalException if a actividad plan with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public ActividadPlan getActividadPlan(long actividadPlanId)
		throws PortalException, SystemException {
		return actividadPlanPersistence.findByPrimaryKey(actividadPlanId);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return actividadPlanPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the actividad plans.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.hitss.layer.model.impl.ActividadPlanModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of actividad plans
	 * @param end the upper bound of the range of actividad plans (not inclusive)
	 * @return the range of actividad plans
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public List<ActividadPlan> getActividadPlans(int start, int end)
		throws SystemException {
		return actividadPlanPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of actividad plans.
	 *
	 * @return the number of actividad plans
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public int getActividadPlansCount() throws SystemException {
		return actividadPlanPersistence.countAll();
	}

	/**
	 * Updates the actividad plan in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param actividadPlan the actividad plan
	 * @return the actividad plan that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ActividadPlan updateActividadPlan(ActividadPlan actividadPlan)
		throws SystemException {
		return actividadPlanPersistence.update(actividadPlan);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public void addUsuarioActividadPlan(long userId, long actividadPlanId)
		throws SystemException {
		usuarioPersistence.addActividadPlan(userId, actividadPlanId);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public void addUsuarioActividadPlan(long userId, ActividadPlan actividadPlan)
		throws SystemException {
		usuarioPersistence.addActividadPlan(userId, actividadPlan);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public void addUsuarioActividadPlans(long userId, long[] actividadPlanIds)
		throws SystemException {
		usuarioPersistence.addActividadPlans(userId, actividadPlanIds);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public void addUsuarioActividadPlans(long userId,
		List<ActividadPlan> ActividadPlans) throws SystemException {
		usuarioPersistence.addActividadPlans(userId, ActividadPlans);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public void clearUsuarioActividadPlans(long userId)
		throws SystemException {
		usuarioPersistence.clearActividadPlans(userId);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public void deleteUsuarioActividadPlan(long userId, long actividadPlanId)
		throws SystemException {
		usuarioPersistence.removeActividadPlan(userId, actividadPlanId);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public void deleteUsuarioActividadPlan(long userId,
		ActividadPlan actividadPlan) throws SystemException {
		usuarioPersistence.removeActividadPlan(userId, actividadPlan);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public void deleteUsuarioActividadPlans(long userId, long[] actividadPlanIds)
		throws SystemException {
		usuarioPersistence.removeActividadPlans(userId, actividadPlanIds);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public void deleteUsuarioActividadPlans(long userId,
		List<ActividadPlan> ActividadPlans) throws SystemException {
		usuarioPersistence.removeActividadPlans(userId, ActividadPlans);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public List<ActividadPlan> getUsuarioActividadPlans(long userId)
		throws SystemException {
		return usuarioPersistence.getActividadPlans(userId);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public List<ActividadPlan> getUsuarioActividadPlans(long userId, int start,
		int end) throws SystemException {
		return usuarioPersistence.getActividadPlans(userId, start, end);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public List<ActividadPlan> getUsuarioActividadPlans(long userId, int start,
		int end, OrderByComparator orderByComparator) throws SystemException {
		return usuarioPersistence.getActividadPlans(userId, start, end,
			orderByComparator);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public int getUsuarioActividadPlansCount(long userId)
		throws SystemException {
		return usuarioPersistence.getActividadPlansSize(userId);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public boolean hasUsuarioActividadPlan(long userId, long actividadPlanId)
		throws SystemException {
		return usuarioPersistence.containsActividadPlan(userId, actividadPlanId);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public boolean hasUsuarioActividadPlans(long userId)
		throws SystemException {
		return usuarioPersistence.containsActividadPlans(userId);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public void setUsuarioActividadPlans(long userId, long[] actividadPlanIds)
		throws SystemException {
		usuarioPersistence.setActividadPlans(userId, actividadPlanIds);
	}

	/**
	 * Returns the actividad cronograma local service.
	 *
	 * @return the actividad cronograma local service
	 */
	public com.hitss.layer.service.ActividadCronogramaLocalService getActividadCronogramaLocalService() {
		return actividadCronogramaLocalService;
	}

	/**
	 * Sets the actividad cronograma local service.
	 *
	 * @param actividadCronogramaLocalService the actividad cronograma local service
	 */
	public void setActividadCronogramaLocalService(
		com.hitss.layer.service.ActividadCronogramaLocalService actividadCronogramaLocalService) {
		this.actividadCronogramaLocalService = actividadCronogramaLocalService;
	}

	/**
	 * Returns the actividad cronograma remote service.
	 *
	 * @return the actividad cronograma remote service
	 */
	public com.hitss.layer.service.ActividadCronogramaService getActividadCronogramaService() {
		return actividadCronogramaService;
	}

	/**
	 * Sets the actividad cronograma remote service.
	 *
	 * @param actividadCronogramaService the actividad cronograma remote service
	 */
	public void setActividadCronogramaService(
		com.hitss.layer.service.ActividadCronogramaService actividadCronogramaService) {
		this.actividadCronogramaService = actividadCronogramaService;
	}

	/**
	 * Returns the actividad cronograma persistence.
	 *
	 * @return the actividad cronograma persistence
	 */
	public ActividadCronogramaPersistence getActividadCronogramaPersistence() {
		return actividadCronogramaPersistence;
	}

	/**
	 * Sets the actividad cronograma persistence.
	 *
	 * @param actividadCronogramaPersistence the actividad cronograma persistence
	 */
	public void setActividadCronogramaPersistence(
		ActividadCronogramaPersistence actividadCronogramaPersistence) {
		this.actividadCronogramaPersistence = actividadCronogramaPersistence;
	}

	/**
	 * Returns the actividad plan local service.
	 *
	 * @return the actividad plan local service
	 */
	public com.hitss.layer.service.ActividadPlanLocalService getActividadPlanLocalService() {
		return actividadPlanLocalService;
	}

	/**
	 * Sets the actividad plan local service.
	 *
	 * @param actividadPlanLocalService the actividad plan local service
	 */
	public void setActividadPlanLocalService(
		com.hitss.layer.service.ActividadPlanLocalService actividadPlanLocalService) {
		this.actividadPlanLocalService = actividadPlanLocalService;
	}

	/**
	 * Returns the actividad plan remote service.
	 *
	 * @return the actividad plan remote service
	 */
	public com.hitss.layer.service.ActividadPlanService getActividadPlanService() {
		return actividadPlanService;
	}

	/**
	 * Sets the actividad plan remote service.
	 *
	 * @param actividadPlanService the actividad plan remote service
	 */
	public void setActividadPlanService(
		com.hitss.layer.service.ActividadPlanService actividadPlanService) {
		this.actividadPlanService = actividadPlanService;
	}

	/**
	 * Returns the actividad plan persistence.
	 *
	 * @return the actividad plan persistence
	 */
	public ActividadPlanPersistence getActividadPlanPersistence() {
		return actividadPlanPersistence;
	}

	/**
	 * Sets the actividad plan persistence.
	 *
	 * @param actividadPlanPersistence the actividad plan persistence
	 */
	public void setActividadPlanPersistence(
		ActividadPlanPersistence actividadPlanPersistence) {
		this.actividadPlanPersistence = actividadPlanPersistence;
	}

	/**
	 * Returns the contrato local service.
	 *
	 * @return the contrato local service
	 */
	public com.hitss.layer.service.ContratoLocalService getContratoLocalService() {
		return contratoLocalService;
	}

	/**
	 * Sets the contrato local service.
	 *
	 * @param contratoLocalService the contrato local service
	 */
	public void setContratoLocalService(
		com.hitss.layer.service.ContratoLocalService contratoLocalService) {
		this.contratoLocalService = contratoLocalService;
	}

	/**
	 * Returns the contrato remote service.
	 *
	 * @return the contrato remote service
	 */
	public com.hitss.layer.service.ContratoService getContratoService() {
		return contratoService;
	}

	/**
	 * Sets the contrato remote service.
	 *
	 * @param contratoService the contrato remote service
	 */
	public void setContratoService(
		com.hitss.layer.service.ContratoService contratoService) {
		this.contratoService = contratoService;
	}

	/**
	 * Returns the contrato persistence.
	 *
	 * @return the contrato persistence
	 */
	public ContratoPersistence getContratoPersistence() {
		return contratoPersistence;
	}

	/**
	 * Sets the contrato persistence.
	 *
	 * @param contratoPersistence the contrato persistence
	 */
	public void setContratoPersistence(ContratoPersistence contratoPersistence) {
		this.contratoPersistence = contratoPersistence;
	}

	/**
	 * Returns the cronograma local service.
	 *
	 * @return the cronograma local service
	 */
	public com.hitss.layer.service.CronogramaLocalService getCronogramaLocalService() {
		return cronogramaLocalService;
	}

	/**
	 * Sets the cronograma local service.
	 *
	 * @param cronogramaLocalService the cronograma local service
	 */
	public void setCronogramaLocalService(
		com.hitss.layer.service.CronogramaLocalService cronogramaLocalService) {
		this.cronogramaLocalService = cronogramaLocalService;
	}

	/**
	 * Returns the cronograma remote service.
	 *
	 * @return the cronograma remote service
	 */
	public com.hitss.layer.service.CronogramaService getCronogramaService() {
		return cronogramaService;
	}

	/**
	 * Sets the cronograma remote service.
	 *
	 * @param cronogramaService the cronograma remote service
	 */
	public void setCronogramaService(
		com.hitss.layer.service.CronogramaService cronogramaService) {
		this.cronogramaService = cronogramaService;
	}

	/**
	 * Returns the cronograma persistence.
	 *
	 * @return the cronograma persistence
	 */
	public CronogramaPersistence getCronogramaPersistence() {
		return cronogramaPersistence;
	}

	/**
	 * Sets the cronograma persistence.
	 *
	 * @param cronogramaPersistence the cronograma persistence
	 */
	public void setCronogramaPersistence(
		CronogramaPersistence cronogramaPersistence) {
		this.cronogramaPersistence = cronogramaPersistence;
	}

	/**
	 * Returns the detalle repuesta evaluacion local service.
	 *
	 * @return the detalle repuesta evaluacion local service
	 */
	public com.hitss.layer.service.DetalleRepuestaEvaluacionLocalService getDetalleRepuestaEvaluacionLocalService() {
		return detalleRepuestaEvaluacionLocalService;
	}

	/**
	 * Sets the detalle repuesta evaluacion local service.
	 *
	 * @param detalleRepuestaEvaluacionLocalService the detalle repuesta evaluacion local service
	 */
	public void setDetalleRepuestaEvaluacionLocalService(
		com.hitss.layer.service.DetalleRepuestaEvaluacionLocalService detalleRepuestaEvaluacionLocalService) {
		this.detalleRepuestaEvaluacionLocalService = detalleRepuestaEvaluacionLocalService;
	}

	/**
	 * Returns the detalle repuesta evaluacion remote service.
	 *
	 * @return the detalle repuesta evaluacion remote service
	 */
	public com.hitss.layer.service.DetalleRepuestaEvaluacionService getDetalleRepuestaEvaluacionService() {
		return detalleRepuestaEvaluacionService;
	}

	/**
	 * Sets the detalle repuesta evaluacion remote service.
	 *
	 * @param detalleRepuestaEvaluacionService the detalle repuesta evaluacion remote service
	 */
	public void setDetalleRepuestaEvaluacionService(
		com.hitss.layer.service.DetalleRepuestaEvaluacionService detalleRepuestaEvaluacionService) {
		this.detalleRepuestaEvaluacionService = detalleRepuestaEvaluacionService;
	}

	/**
	 * Returns the detalle repuesta evaluacion persistence.
	 *
	 * @return the detalle repuesta evaluacion persistence
	 */
	public DetalleRepuestaEvaluacionPersistence getDetalleRepuestaEvaluacionPersistence() {
		return detalleRepuestaEvaluacionPersistence;
	}

	/**
	 * Sets the detalle repuesta evaluacion persistence.
	 *
	 * @param detalleRepuestaEvaluacionPersistence the detalle repuesta evaluacion persistence
	 */
	public void setDetalleRepuestaEvaluacionPersistence(
		DetalleRepuestaEvaluacionPersistence detalleRepuestaEvaluacionPersistence) {
		this.detalleRepuestaEvaluacionPersistence = detalleRepuestaEvaluacionPersistence;
	}

	/**
	 * Returns the detalle repuesta reclutamiento local service.
	 *
	 * @return the detalle repuesta reclutamiento local service
	 */
	public com.hitss.layer.service.DetalleRepuestaReclutamientoLocalService getDetalleRepuestaReclutamientoLocalService() {
		return detalleRepuestaReclutamientoLocalService;
	}

	/**
	 * Sets the detalle repuesta reclutamiento local service.
	 *
	 * @param detalleRepuestaReclutamientoLocalService the detalle repuesta reclutamiento local service
	 */
	public void setDetalleRepuestaReclutamientoLocalService(
		com.hitss.layer.service.DetalleRepuestaReclutamientoLocalService detalleRepuestaReclutamientoLocalService) {
		this.detalleRepuestaReclutamientoLocalService = detalleRepuestaReclutamientoLocalService;
	}

	/**
	 * Returns the detalle repuesta reclutamiento remote service.
	 *
	 * @return the detalle repuesta reclutamiento remote service
	 */
	public com.hitss.layer.service.DetalleRepuestaReclutamientoService getDetalleRepuestaReclutamientoService() {
		return detalleRepuestaReclutamientoService;
	}

	/**
	 * Sets the detalle repuesta reclutamiento remote service.
	 *
	 * @param detalleRepuestaReclutamientoService the detalle repuesta reclutamiento remote service
	 */
	public void setDetalleRepuestaReclutamientoService(
		com.hitss.layer.service.DetalleRepuestaReclutamientoService detalleRepuestaReclutamientoService) {
		this.detalleRepuestaReclutamientoService = detalleRepuestaReclutamientoService;
	}

	/**
	 * Returns the detalle repuesta reclutamiento persistence.
	 *
	 * @return the detalle repuesta reclutamiento persistence
	 */
	public DetalleRepuestaReclutamientoPersistence getDetalleRepuestaReclutamientoPersistence() {
		return detalleRepuestaReclutamientoPersistence;
	}

	/**
	 * Sets the detalle repuesta reclutamiento persistence.
	 *
	 * @param detalleRepuestaReclutamientoPersistence the detalle repuesta reclutamiento persistence
	 */
	public void setDetalleRepuestaReclutamientoPersistence(
		DetalleRepuestaReclutamientoPersistence detalleRepuestaReclutamientoPersistence) {
		this.detalleRepuestaReclutamientoPersistence = detalleRepuestaReclutamientoPersistence;
	}

	/**
	 * Returns the estudio local service.
	 *
	 * @return the estudio local service
	 */
	public com.hitss.layer.service.EstudioLocalService getEstudioLocalService() {
		return estudioLocalService;
	}

	/**
	 * Sets the estudio local service.
	 *
	 * @param estudioLocalService the estudio local service
	 */
	public void setEstudioLocalService(
		com.hitss.layer.service.EstudioLocalService estudioLocalService) {
		this.estudioLocalService = estudioLocalService;
	}

	/**
	 * Returns the estudio remote service.
	 *
	 * @return the estudio remote service
	 */
	public com.hitss.layer.service.EstudioService getEstudioService() {
		return estudioService;
	}

	/**
	 * Sets the estudio remote service.
	 *
	 * @param estudioService the estudio remote service
	 */
	public void setEstudioService(
		com.hitss.layer.service.EstudioService estudioService) {
		this.estudioService = estudioService;
	}

	/**
	 * Returns the estudio persistence.
	 *
	 * @return the estudio persistence
	 */
	public EstudioPersistence getEstudioPersistence() {
		return estudioPersistence;
	}

	/**
	 * Sets the estudio persistence.
	 *
	 * @param estudioPersistence the estudio persistence
	 */
	public void setEstudioPersistence(EstudioPersistence estudioPersistence) {
		this.estudioPersistence = estudioPersistence;
	}

	/**
	 * Returns the etiqueta relacionada local service.
	 *
	 * @return the etiqueta relacionada local service
	 */
	public com.hitss.layer.service.EtiquetaRelacionadaLocalService getEtiquetaRelacionadaLocalService() {
		return etiquetaRelacionadaLocalService;
	}

	/**
	 * Sets the etiqueta relacionada local service.
	 *
	 * @param etiquetaRelacionadaLocalService the etiqueta relacionada local service
	 */
	public void setEtiquetaRelacionadaLocalService(
		com.hitss.layer.service.EtiquetaRelacionadaLocalService etiquetaRelacionadaLocalService) {
		this.etiquetaRelacionadaLocalService = etiquetaRelacionadaLocalService;
	}

	/**
	 * Returns the etiqueta relacionada remote service.
	 *
	 * @return the etiqueta relacionada remote service
	 */
	public com.hitss.layer.service.EtiquetaRelacionadaService getEtiquetaRelacionadaService() {
		return etiquetaRelacionadaService;
	}

	/**
	 * Sets the etiqueta relacionada remote service.
	 *
	 * @param etiquetaRelacionadaService the etiqueta relacionada remote service
	 */
	public void setEtiquetaRelacionadaService(
		com.hitss.layer.service.EtiquetaRelacionadaService etiquetaRelacionadaService) {
		this.etiquetaRelacionadaService = etiquetaRelacionadaService;
	}

	/**
	 * Returns the etiqueta relacionada persistence.
	 *
	 * @return the etiqueta relacionada persistence
	 */
	public EtiquetaRelacionadaPersistence getEtiquetaRelacionadaPersistence() {
		return etiquetaRelacionadaPersistence;
	}

	/**
	 * Sets the etiqueta relacionada persistence.
	 *
	 * @param etiquetaRelacionadaPersistence the etiqueta relacionada persistence
	 */
	public void setEtiquetaRelacionadaPersistence(
		EtiquetaRelacionadaPersistence etiquetaRelacionadaPersistence) {
		this.etiquetaRelacionadaPersistence = etiquetaRelacionadaPersistence;
	}

	/**
	 * Returns the evaluacion local service.
	 *
	 * @return the evaluacion local service
	 */
	public com.hitss.layer.service.EvaluacionLocalService getEvaluacionLocalService() {
		return evaluacionLocalService;
	}

	/**
	 * Sets the evaluacion local service.
	 *
	 * @param evaluacionLocalService the evaluacion local service
	 */
	public void setEvaluacionLocalService(
		com.hitss.layer.service.EvaluacionLocalService evaluacionLocalService) {
		this.evaluacionLocalService = evaluacionLocalService;
	}

	/**
	 * Returns the evaluacion remote service.
	 *
	 * @return the evaluacion remote service
	 */
	public com.hitss.layer.service.EvaluacionService getEvaluacionService() {
		return evaluacionService;
	}

	/**
	 * Sets the evaluacion remote service.
	 *
	 * @param evaluacionService the evaluacion remote service
	 */
	public void setEvaluacionService(
		com.hitss.layer.service.EvaluacionService evaluacionService) {
		this.evaluacionService = evaluacionService;
	}

	/**
	 * Returns the evaluacion persistence.
	 *
	 * @return the evaluacion persistence
	 */
	public EvaluacionPersistence getEvaluacionPersistence() {
		return evaluacionPersistence;
	}

	/**
	 * Sets the evaluacion persistence.
	 *
	 * @param evaluacionPersistence the evaluacion persistence
	 */
	public void setEvaluacionPersistence(
		EvaluacionPersistence evaluacionPersistence) {
		this.evaluacionPersistence = evaluacionPersistence;
	}

	/**
	 * Returns the evaluacion pregunta local service.
	 *
	 * @return the evaluacion pregunta local service
	 */
	public com.hitss.layer.service.EvaluacionPreguntaLocalService getEvaluacionPreguntaLocalService() {
		return evaluacionPreguntaLocalService;
	}

	/**
	 * Sets the evaluacion pregunta local service.
	 *
	 * @param evaluacionPreguntaLocalService the evaluacion pregunta local service
	 */
	public void setEvaluacionPreguntaLocalService(
		com.hitss.layer.service.EvaluacionPreguntaLocalService evaluacionPreguntaLocalService) {
		this.evaluacionPreguntaLocalService = evaluacionPreguntaLocalService;
	}

	/**
	 * Returns the evaluacion pregunta remote service.
	 *
	 * @return the evaluacion pregunta remote service
	 */
	public com.hitss.layer.service.EvaluacionPreguntaService getEvaluacionPreguntaService() {
		return evaluacionPreguntaService;
	}

	/**
	 * Sets the evaluacion pregunta remote service.
	 *
	 * @param evaluacionPreguntaService the evaluacion pregunta remote service
	 */
	public void setEvaluacionPreguntaService(
		com.hitss.layer.service.EvaluacionPreguntaService evaluacionPreguntaService) {
		this.evaluacionPreguntaService = evaluacionPreguntaService;
	}

	/**
	 * Returns the evaluacion pregunta persistence.
	 *
	 * @return the evaluacion pregunta persistence
	 */
	public EvaluacionPreguntaPersistence getEvaluacionPreguntaPersistence() {
		return evaluacionPreguntaPersistence;
	}

	/**
	 * Sets the evaluacion pregunta persistence.
	 *
	 * @param evaluacionPreguntaPersistence the evaluacion pregunta persistence
	 */
	public void setEvaluacionPreguntaPersistence(
		EvaluacionPreguntaPersistence evaluacionPreguntaPersistence) {
		this.evaluacionPreguntaPersistence = evaluacionPreguntaPersistence;
	}

	/**
	 * Returns the experiencia local service.
	 *
	 * @return the experiencia local service
	 */
	public com.hitss.layer.service.ExperienciaLocalService getExperienciaLocalService() {
		return experienciaLocalService;
	}

	/**
	 * Sets the experiencia local service.
	 *
	 * @param experienciaLocalService the experiencia local service
	 */
	public void setExperienciaLocalService(
		com.hitss.layer.service.ExperienciaLocalService experienciaLocalService) {
		this.experienciaLocalService = experienciaLocalService;
	}

	/**
	 * Returns the experiencia remote service.
	 *
	 * @return the experiencia remote service
	 */
	public com.hitss.layer.service.ExperienciaService getExperienciaService() {
		return experienciaService;
	}

	/**
	 * Sets the experiencia remote service.
	 *
	 * @param experienciaService the experiencia remote service
	 */
	public void setExperienciaService(
		com.hitss.layer.service.ExperienciaService experienciaService) {
		this.experienciaService = experienciaService;
	}

	/**
	 * Returns the experiencia persistence.
	 *
	 * @return the experiencia persistence
	 */
	public ExperienciaPersistence getExperienciaPersistence() {
		return experienciaPersistence;
	}

	/**
	 * Sets the experiencia persistence.
	 *
	 * @param experienciaPersistence the experiencia persistence
	 */
	public void setExperienciaPersistence(
		ExperienciaPersistence experienciaPersistence) {
		this.experienciaPersistence = experienciaPersistence;
	}

	/**
	 * Returns the fase postulacion local service.
	 *
	 * @return the fase postulacion local service
	 */
	public com.hitss.layer.service.FasePostulacionLocalService getFasePostulacionLocalService() {
		return fasePostulacionLocalService;
	}

	/**
	 * Sets the fase postulacion local service.
	 *
	 * @param fasePostulacionLocalService the fase postulacion local service
	 */
	public void setFasePostulacionLocalService(
		com.hitss.layer.service.FasePostulacionLocalService fasePostulacionLocalService) {
		this.fasePostulacionLocalService = fasePostulacionLocalService;
	}

	/**
	 * Returns the fase postulacion remote service.
	 *
	 * @return the fase postulacion remote service
	 */
	public com.hitss.layer.service.FasePostulacionService getFasePostulacionService() {
		return fasePostulacionService;
	}

	/**
	 * Sets the fase postulacion remote service.
	 *
	 * @param fasePostulacionService the fase postulacion remote service
	 */
	public void setFasePostulacionService(
		com.hitss.layer.service.FasePostulacionService fasePostulacionService) {
		this.fasePostulacionService = fasePostulacionService;
	}

	/**
	 * Returns the fase postulacion persistence.
	 *
	 * @return the fase postulacion persistence
	 */
	public FasePostulacionPersistence getFasePostulacionPersistence() {
		return fasePostulacionPersistence;
	}

	/**
	 * Sets the fase postulacion persistence.
	 *
	 * @param fasePostulacionPersistence the fase postulacion persistence
	 */
	public void setFasePostulacionPersistence(
		FasePostulacionPersistence fasePostulacionPersistence) {
		this.fasePostulacionPersistence = fasePostulacionPersistence;
	}

	/**
	 * Returns the ficha ingreso local service.
	 *
	 * @return the ficha ingreso local service
	 */
	public com.hitss.layer.service.FichaIngresoLocalService getFichaIngresoLocalService() {
		return fichaIngresoLocalService;
	}

	/**
	 * Sets the ficha ingreso local service.
	 *
	 * @param fichaIngresoLocalService the ficha ingreso local service
	 */
	public void setFichaIngresoLocalService(
		com.hitss.layer.service.FichaIngresoLocalService fichaIngresoLocalService) {
		this.fichaIngresoLocalService = fichaIngresoLocalService;
	}

	/**
	 * Returns the ficha ingreso remote service.
	 *
	 * @return the ficha ingreso remote service
	 */
	public com.hitss.layer.service.FichaIngresoService getFichaIngresoService() {
		return fichaIngresoService;
	}

	/**
	 * Sets the ficha ingreso remote service.
	 *
	 * @param fichaIngresoService the ficha ingreso remote service
	 */
	public void setFichaIngresoService(
		com.hitss.layer.service.FichaIngresoService fichaIngresoService) {
		this.fichaIngresoService = fichaIngresoService;
	}

	/**
	 * Returns the ficha ingreso persistence.
	 *
	 * @return the ficha ingreso persistence
	 */
	public FichaIngresoPersistence getFichaIngresoPersistence() {
		return fichaIngresoPersistence;
	}

	/**
	 * Sets the ficha ingreso persistence.
	 *
	 * @param fichaIngresoPersistence the ficha ingreso persistence
	 */
	public void setFichaIngresoPersistence(
		FichaIngresoPersistence fichaIngresoPersistence) {
		this.fichaIngresoPersistence = fichaIngresoPersistence;
	}

	/**
	 * Returns the funcion local service.
	 *
	 * @return the funcion local service
	 */
	public com.hitss.layer.service.FuncionLocalService getFuncionLocalService() {
		return funcionLocalService;
	}

	/**
	 * Sets the funcion local service.
	 *
	 * @param funcionLocalService the funcion local service
	 */
	public void setFuncionLocalService(
		com.hitss.layer.service.FuncionLocalService funcionLocalService) {
		this.funcionLocalService = funcionLocalService;
	}

	/**
	 * Returns the funcion remote service.
	 *
	 * @return the funcion remote service
	 */
	public com.hitss.layer.service.FuncionService getFuncionService() {
		return funcionService;
	}

	/**
	 * Sets the funcion remote service.
	 *
	 * @param funcionService the funcion remote service
	 */
	public void setFuncionService(
		com.hitss.layer.service.FuncionService funcionService) {
		this.funcionService = funcionService;
	}

	/**
	 * Returns the funcion persistence.
	 *
	 * @return the funcion persistence
	 */
	public FuncionPersistence getFuncionPersistence() {
		return funcionPersistence;
	}

	/**
	 * Sets the funcion persistence.
	 *
	 * @param funcionPersistence the funcion persistence
	 */
	public void setFuncionPersistence(FuncionPersistence funcionPersistence) {
		this.funcionPersistence = funcionPersistence;
	}

	/**
	 * Returns the informe retroalimentacion local service.
	 *
	 * @return the informe retroalimentacion local service
	 */
	public com.hitss.layer.service.InformeRetroalimentacionLocalService getInformeRetroalimentacionLocalService() {
		return informeRetroalimentacionLocalService;
	}

	/**
	 * Sets the informe retroalimentacion local service.
	 *
	 * @param informeRetroalimentacionLocalService the informe retroalimentacion local service
	 */
	public void setInformeRetroalimentacionLocalService(
		com.hitss.layer.service.InformeRetroalimentacionLocalService informeRetroalimentacionLocalService) {
		this.informeRetroalimentacionLocalService = informeRetroalimentacionLocalService;
	}

	/**
	 * Returns the informe retroalimentacion remote service.
	 *
	 * @return the informe retroalimentacion remote service
	 */
	public com.hitss.layer.service.InformeRetroalimentacionService getInformeRetroalimentacionService() {
		return informeRetroalimentacionService;
	}

	/**
	 * Sets the informe retroalimentacion remote service.
	 *
	 * @param informeRetroalimentacionService the informe retroalimentacion remote service
	 */
	public void setInformeRetroalimentacionService(
		com.hitss.layer.service.InformeRetroalimentacionService informeRetroalimentacionService) {
		this.informeRetroalimentacionService = informeRetroalimentacionService;
	}

	/**
	 * Returns the informe retroalimentacion persistence.
	 *
	 * @return the informe retroalimentacion persistence
	 */
	public InformeRetroalimentacionPersistence getInformeRetroalimentacionPersistence() {
		return informeRetroalimentacionPersistence;
	}

	/**
	 * Sets the informe retroalimentacion persistence.
	 *
	 * @param informeRetroalimentacionPersistence the informe retroalimentacion persistence
	 */
	public void setInformeRetroalimentacionPersistence(
		InformeRetroalimentacionPersistence informeRetroalimentacionPersistence) {
		this.informeRetroalimentacionPersistence = informeRetroalimentacionPersistence;
	}

	/**
	 * Returns the log operaciones local service.
	 *
	 * @return the log operaciones local service
	 */
	public com.hitss.layer.service.LogOperacionesLocalService getLogOperacionesLocalService() {
		return logOperacionesLocalService;
	}

	/**
	 * Sets the log operaciones local service.
	 *
	 * @param logOperacionesLocalService the log operaciones local service
	 */
	public void setLogOperacionesLocalService(
		com.hitss.layer.service.LogOperacionesLocalService logOperacionesLocalService) {
		this.logOperacionesLocalService = logOperacionesLocalService;
	}

	/**
	 * Returns the log operaciones remote service.
	 *
	 * @return the log operaciones remote service
	 */
	public com.hitss.layer.service.LogOperacionesService getLogOperacionesService() {
		return logOperacionesService;
	}

	/**
	 * Sets the log operaciones remote service.
	 *
	 * @param logOperacionesService the log operaciones remote service
	 */
	public void setLogOperacionesService(
		com.hitss.layer.service.LogOperacionesService logOperacionesService) {
		this.logOperacionesService = logOperacionesService;
	}

	/**
	 * Returns the log operaciones persistence.
	 *
	 * @return the log operaciones persistence
	 */
	public LogOperacionesPersistence getLogOperacionesPersistence() {
		return logOperacionesPersistence;
	}

	/**
	 * Sets the log operaciones persistence.
	 *
	 * @param logOperacionesPersistence the log operaciones persistence
	 */
	public void setLogOperacionesPersistence(
		LogOperacionesPersistence logOperacionesPersistence) {
		this.logOperacionesPersistence = logOperacionesPersistence;
	}

	/**
	 * Returns the observaciones local service.
	 *
	 * @return the observaciones local service
	 */
	public com.hitss.layer.service.ObservacionesLocalService getObservacionesLocalService() {
		return observacionesLocalService;
	}

	/**
	 * Sets the observaciones local service.
	 *
	 * @param observacionesLocalService the observaciones local service
	 */
	public void setObservacionesLocalService(
		com.hitss.layer.service.ObservacionesLocalService observacionesLocalService) {
		this.observacionesLocalService = observacionesLocalService;
	}

	/**
	 * Returns the observaciones remote service.
	 *
	 * @return the observaciones remote service
	 */
	public com.hitss.layer.service.ObservacionesService getObservacionesService() {
		return observacionesService;
	}

	/**
	 * Sets the observaciones remote service.
	 *
	 * @param observacionesService the observaciones remote service
	 */
	public void setObservacionesService(
		com.hitss.layer.service.ObservacionesService observacionesService) {
		this.observacionesService = observacionesService;
	}

	/**
	 * Returns the observaciones persistence.
	 *
	 * @return the observaciones persistence
	 */
	public ObservacionesPersistence getObservacionesPersistence() {
		return observacionesPersistence;
	}

	/**
	 * Sets the observaciones persistence.
	 *
	 * @param observacionesPersistence the observaciones persistence
	 */
	public void setObservacionesPersistence(
		ObservacionesPersistence observacionesPersistence) {
		this.observacionesPersistence = observacionesPersistence;
	}

	/**
	 * Returns the parametro local service.
	 *
	 * @return the parametro local service
	 */
	public com.hitss.layer.service.ParametroLocalService getParametroLocalService() {
		return parametroLocalService;
	}

	/**
	 * Sets the parametro local service.
	 *
	 * @param parametroLocalService the parametro local service
	 */
	public void setParametroLocalService(
		com.hitss.layer.service.ParametroLocalService parametroLocalService) {
		this.parametroLocalService = parametroLocalService;
	}

	/**
	 * Returns the parametro remote service.
	 *
	 * @return the parametro remote service
	 */
	public com.hitss.layer.service.ParametroService getParametroService() {
		return parametroService;
	}

	/**
	 * Sets the parametro remote service.
	 *
	 * @param parametroService the parametro remote service
	 */
	public void setParametroService(
		com.hitss.layer.service.ParametroService parametroService) {
		this.parametroService = parametroService;
	}

	/**
	 * Returns the parametro persistence.
	 *
	 * @return the parametro persistence
	 */
	public ParametroPersistence getParametroPersistence() {
		return parametroPersistence;
	}

	/**
	 * Sets the parametro persistence.
	 *
	 * @param parametroPersistence the parametro persistence
	 */
	public void setParametroPersistence(
		ParametroPersistence parametroPersistence) {
		this.parametroPersistence = parametroPersistence;
	}

	/**
	 * Returns the parametro finder.
	 *
	 * @return the parametro finder
	 */
	public ParametroFinder getParametroFinder() {
		return parametroFinder;
	}

	/**
	 * Sets the parametro finder.
	 *
	 * @param parametroFinder the parametro finder
	 */
	public void setParametroFinder(ParametroFinder parametroFinder) {
		this.parametroFinder = parametroFinder;
	}

	/**
	 * Returns the plan accion local service.
	 *
	 * @return the plan accion local service
	 */
	public com.hitss.layer.service.PlanAccionLocalService getPlanAccionLocalService() {
		return planAccionLocalService;
	}

	/**
	 * Sets the plan accion local service.
	 *
	 * @param planAccionLocalService the plan accion local service
	 */
	public void setPlanAccionLocalService(
		com.hitss.layer.service.PlanAccionLocalService planAccionLocalService) {
		this.planAccionLocalService = planAccionLocalService;
	}

	/**
	 * Returns the plan accion remote service.
	 *
	 * @return the plan accion remote service
	 */
	public com.hitss.layer.service.PlanAccionService getPlanAccionService() {
		return planAccionService;
	}

	/**
	 * Sets the plan accion remote service.
	 *
	 * @param planAccionService the plan accion remote service
	 */
	public void setPlanAccionService(
		com.hitss.layer.service.PlanAccionService planAccionService) {
		this.planAccionService = planAccionService;
	}

	/**
	 * Returns the plan accion persistence.
	 *
	 * @return the plan accion persistence
	 */
	public PlanAccionPersistence getPlanAccionPersistence() {
		return planAccionPersistence;
	}

	/**
	 * Sets the plan accion persistence.
	 *
	 * @param planAccionPersistence the plan accion persistence
	 */
	public void setPlanAccionPersistence(
		PlanAccionPersistence planAccionPersistence) {
		this.planAccionPersistence = planAccionPersistence;
	}

	/**
	 * Returns the postulacion local service.
	 *
	 * @return the postulacion local service
	 */
	public com.hitss.layer.service.PostulacionLocalService getPostulacionLocalService() {
		return postulacionLocalService;
	}

	/**
	 * Sets the postulacion local service.
	 *
	 * @param postulacionLocalService the postulacion local service
	 */
	public void setPostulacionLocalService(
		com.hitss.layer.service.PostulacionLocalService postulacionLocalService) {
		this.postulacionLocalService = postulacionLocalService;
	}

	/**
	 * Returns the postulacion remote service.
	 *
	 * @return the postulacion remote service
	 */
	public com.hitss.layer.service.PostulacionService getPostulacionService() {
		return postulacionService;
	}

	/**
	 * Sets the postulacion remote service.
	 *
	 * @param postulacionService the postulacion remote service
	 */
	public void setPostulacionService(
		com.hitss.layer.service.PostulacionService postulacionService) {
		this.postulacionService = postulacionService;
	}

	/**
	 * Returns the postulacion persistence.
	 *
	 * @return the postulacion persistence
	 */
	public PostulacionPersistence getPostulacionPersistence() {
		return postulacionPersistence;
	}

	/**
	 * Sets the postulacion persistence.
	 *
	 * @param postulacionPersistence the postulacion persistence
	 */
	public void setPostulacionPersistence(
		PostulacionPersistence postulacionPersistence) {
		this.postulacionPersistence = postulacionPersistence;
	}

	/**
	 * Returns the pregunta local service.
	 *
	 * @return the pregunta local service
	 */
	public com.hitss.layer.service.PreguntaLocalService getPreguntaLocalService() {
		return preguntaLocalService;
	}

	/**
	 * Sets the pregunta local service.
	 *
	 * @param preguntaLocalService the pregunta local service
	 */
	public void setPreguntaLocalService(
		com.hitss.layer.service.PreguntaLocalService preguntaLocalService) {
		this.preguntaLocalService = preguntaLocalService;
	}

	/**
	 * Returns the pregunta remote service.
	 *
	 * @return the pregunta remote service
	 */
	public com.hitss.layer.service.PreguntaService getPreguntaService() {
		return preguntaService;
	}

	/**
	 * Sets the pregunta remote service.
	 *
	 * @param preguntaService the pregunta remote service
	 */
	public void setPreguntaService(
		com.hitss.layer.service.PreguntaService preguntaService) {
		this.preguntaService = preguntaService;
	}

	/**
	 * Returns the pregunta persistence.
	 *
	 * @return the pregunta persistence
	 */
	public PreguntaPersistence getPreguntaPersistence() {
		return preguntaPersistence;
	}

	/**
	 * Sets the pregunta persistence.
	 *
	 * @param preguntaPersistence the pregunta persistence
	 */
	public void setPreguntaPersistence(PreguntaPersistence preguntaPersistence) {
		this.preguntaPersistence = preguntaPersistence;
	}

	/**
	 * Returns the prioridad grupo usuarios local service.
	 *
	 * @return the prioridad grupo usuarios local service
	 */
	public com.hitss.layer.service.PrioridadGrupoUsuariosLocalService getPrioridadGrupoUsuariosLocalService() {
		return prioridadGrupoUsuariosLocalService;
	}

	/**
	 * Sets the prioridad grupo usuarios local service.
	 *
	 * @param prioridadGrupoUsuariosLocalService the prioridad grupo usuarios local service
	 */
	public void setPrioridadGrupoUsuariosLocalService(
		com.hitss.layer.service.PrioridadGrupoUsuariosLocalService prioridadGrupoUsuariosLocalService) {
		this.prioridadGrupoUsuariosLocalService = prioridadGrupoUsuariosLocalService;
	}

	/**
	 * Returns the prioridad grupo usuarios remote service.
	 *
	 * @return the prioridad grupo usuarios remote service
	 */
	public com.hitss.layer.service.PrioridadGrupoUsuariosService getPrioridadGrupoUsuariosService() {
		return prioridadGrupoUsuariosService;
	}

	/**
	 * Sets the prioridad grupo usuarios remote service.
	 *
	 * @param prioridadGrupoUsuariosService the prioridad grupo usuarios remote service
	 */
	public void setPrioridadGrupoUsuariosService(
		com.hitss.layer.service.PrioridadGrupoUsuariosService prioridadGrupoUsuariosService) {
		this.prioridadGrupoUsuariosService = prioridadGrupoUsuariosService;
	}

	/**
	 * Returns the prioridad grupo usuarios persistence.
	 *
	 * @return the prioridad grupo usuarios persistence
	 */
	public PrioridadGrupoUsuariosPersistence getPrioridadGrupoUsuariosPersistence() {
		return prioridadGrupoUsuariosPersistence;
	}

	/**
	 * Sets the prioridad grupo usuarios persistence.
	 *
	 * @param prioridadGrupoUsuariosPersistence the prioridad grupo usuarios persistence
	 */
	public void setPrioridadGrupoUsuariosPersistence(
		PrioridadGrupoUsuariosPersistence prioridadGrupoUsuariosPersistence) {
		this.prioridadGrupoUsuariosPersistence = prioridadGrupoUsuariosPersistence;
	}

	/**
	 * Returns the referencia local service.
	 *
	 * @return the referencia local service
	 */
	public com.hitss.layer.service.ReferenciaLocalService getReferenciaLocalService() {
		return referenciaLocalService;
	}

	/**
	 * Sets the referencia local service.
	 *
	 * @param referenciaLocalService the referencia local service
	 */
	public void setReferenciaLocalService(
		com.hitss.layer.service.ReferenciaLocalService referenciaLocalService) {
		this.referenciaLocalService = referenciaLocalService;
	}

	/**
	 * Returns the referencia remote service.
	 *
	 * @return the referencia remote service
	 */
	public com.hitss.layer.service.ReferenciaService getReferenciaService() {
		return referenciaService;
	}

	/**
	 * Sets the referencia remote service.
	 *
	 * @param referenciaService the referencia remote service
	 */
	public void setReferenciaService(
		com.hitss.layer.service.ReferenciaService referenciaService) {
		this.referenciaService = referenciaService;
	}

	/**
	 * Returns the referencia persistence.
	 *
	 * @return the referencia persistence
	 */
	public ReferenciaPersistence getReferenciaPersistence() {
		return referenciaPersistence;
	}

	/**
	 * Sets the referencia persistence.
	 *
	 * @param referenciaPersistence the referencia persistence
	 */
	public void setReferenciaPersistence(
		ReferenciaPersistence referenciaPersistence) {
		this.referenciaPersistence = referenciaPersistence;
	}

	/**
	 * Returns the respuesta local service.
	 *
	 * @return the respuesta local service
	 */
	public com.hitss.layer.service.RespuestaLocalService getRespuestaLocalService() {
		return respuestaLocalService;
	}

	/**
	 * Sets the respuesta local service.
	 *
	 * @param respuestaLocalService the respuesta local service
	 */
	public void setRespuestaLocalService(
		com.hitss.layer.service.RespuestaLocalService respuestaLocalService) {
		this.respuestaLocalService = respuestaLocalService;
	}

	/**
	 * Returns the respuesta remote service.
	 *
	 * @return the respuesta remote service
	 */
	public com.hitss.layer.service.RespuestaService getRespuestaService() {
		return respuestaService;
	}

	/**
	 * Sets the respuesta remote service.
	 *
	 * @param respuestaService the respuesta remote service
	 */
	public void setRespuestaService(
		com.hitss.layer.service.RespuestaService respuestaService) {
		this.respuestaService = respuestaService;
	}

	/**
	 * Returns the respuesta persistence.
	 *
	 * @return the respuesta persistence
	 */
	public RespuestaPersistence getRespuestaPersistence() {
		return respuestaPersistence;
	}

	/**
	 * Sets the respuesta persistence.
	 *
	 * @param respuestaPersistence the respuesta persistence
	 */
	public void setRespuestaPersistence(
		RespuestaPersistence respuestaPersistence) {
		this.respuestaPersistence = respuestaPersistence;
	}

	/**
	 * Returns the solicitud evaluacion desempenno local service.
	 *
	 * @return the solicitud evaluacion desempenno local service
	 */
	public com.hitss.layer.service.SolicitudEvaluacionDesempennoLocalService getSolicitudEvaluacionDesempennoLocalService() {
		return solicitudEvaluacionDesempennoLocalService;
	}

	/**
	 * Sets the solicitud evaluacion desempenno local service.
	 *
	 * @param solicitudEvaluacionDesempennoLocalService the solicitud evaluacion desempenno local service
	 */
	public void setSolicitudEvaluacionDesempennoLocalService(
		com.hitss.layer.service.SolicitudEvaluacionDesempennoLocalService solicitudEvaluacionDesempennoLocalService) {
		this.solicitudEvaluacionDesempennoLocalService = solicitudEvaluacionDesempennoLocalService;
	}

	/**
	 * Returns the solicitud evaluacion desempenno remote service.
	 *
	 * @return the solicitud evaluacion desempenno remote service
	 */
	public com.hitss.layer.service.SolicitudEvaluacionDesempennoService getSolicitudEvaluacionDesempennoService() {
		return solicitudEvaluacionDesempennoService;
	}

	/**
	 * Sets the solicitud evaluacion desempenno remote service.
	 *
	 * @param solicitudEvaluacionDesempennoService the solicitud evaluacion desempenno remote service
	 */
	public void setSolicitudEvaluacionDesempennoService(
		com.hitss.layer.service.SolicitudEvaluacionDesempennoService solicitudEvaluacionDesempennoService) {
		this.solicitudEvaluacionDesempennoService = solicitudEvaluacionDesempennoService;
	}

	/**
	 * Returns the solicitud evaluacion desempenno persistence.
	 *
	 * @return the solicitud evaluacion desempenno persistence
	 */
	public SolicitudEvaluacionDesempennoPersistence getSolicitudEvaluacionDesempennoPersistence() {
		return solicitudEvaluacionDesempennoPersistence;
	}

	/**
	 * Sets the solicitud evaluacion desempenno persistence.
	 *
	 * @param solicitudEvaluacionDesempennoPersistence the solicitud evaluacion desempenno persistence
	 */
	public void setSolicitudEvaluacionDesempennoPersistence(
		SolicitudEvaluacionDesempennoPersistence solicitudEvaluacionDesempennoPersistence) {
		this.solicitudEvaluacionDesempennoPersistence = solicitudEvaluacionDesempennoPersistence;
	}

	/**
	 * Returns the solicitud requerimiento local service.
	 *
	 * @return the solicitud requerimiento local service
	 */
	public com.hitss.layer.service.SolicitudRequerimientoLocalService getSolicitudRequerimientoLocalService() {
		return solicitudRequerimientoLocalService;
	}

	/**
	 * Sets the solicitud requerimiento local service.
	 *
	 * @param solicitudRequerimientoLocalService the solicitud requerimiento local service
	 */
	public void setSolicitudRequerimientoLocalService(
		com.hitss.layer.service.SolicitudRequerimientoLocalService solicitudRequerimientoLocalService) {
		this.solicitudRequerimientoLocalService = solicitudRequerimientoLocalService;
	}

	/**
	 * Returns the solicitud requerimiento remote service.
	 *
	 * @return the solicitud requerimiento remote service
	 */
	public com.hitss.layer.service.SolicitudRequerimientoService getSolicitudRequerimientoService() {
		return solicitudRequerimientoService;
	}

	/**
	 * Sets the solicitud requerimiento remote service.
	 *
	 * @param solicitudRequerimientoService the solicitud requerimiento remote service
	 */
	public void setSolicitudRequerimientoService(
		com.hitss.layer.service.SolicitudRequerimientoService solicitudRequerimientoService) {
		this.solicitudRequerimientoService = solicitudRequerimientoService;
	}

	/**
	 * Returns the solicitud requerimiento persistence.
	 *
	 * @return the solicitud requerimiento persistence
	 */
	public SolicitudRequerimientoPersistence getSolicitudRequerimientoPersistence() {
		return solicitudRequerimientoPersistence;
	}

	/**
	 * Sets the solicitud requerimiento persistence.
	 *
	 * @param solicitudRequerimientoPersistence the solicitud requerimiento persistence
	 */
	public void setSolicitudRequerimientoPersistence(
		SolicitudRequerimientoPersistence solicitudRequerimientoPersistence) {
		this.solicitudRequerimientoPersistence = solicitudRequerimientoPersistence;
	}

	/**
	 * Returns the solicitud requerimiento requisito local service.
	 *
	 * @return the solicitud requerimiento requisito local service
	 */
	public com.hitss.layer.service.SolicitudRequerimientoRequisitoLocalService getSolicitudRequerimientoRequisitoLocalService() {
		return solicitudRequerimientoRequisitoLocalService;
	}

	/**
	 * Sets the solicitud requerimiento requisito local service.
	 *
	 * @param solicitudRequerimientoRequisitoLocalService the solicitud requerimiento requisito local service
	 */
	public void setSolicitudRequerimientoRequisitoLocalService(
		com.hitss.layer.service.SolicitudRequerimientoRequisitoLocalService solicitudRequerimientoRequisitoLocalService) {
		this.solicitudRequerimientoRequisitoLocalService = solicitudRequerimientoRequisitoLocalService;
	}

	/**
	 * Returns the solicitud requerimiento requisito remote service.
	 *
	 * @return the solicitud requerimiento requisito remote service
	 */
	public com.hitss.layer.service.SolicitudRequerimientoRequisitoService getSolicitudRequerimientoRequisitoService() {
		return solicitudRequerimientoRequisitoService;
	}

	/**
	 * Sets the solicitud requerimiento requisito remote service.
	 *
	 * @param solicitudRequerimientoRequisitoService the solicitud requerimiento requisito remote service
	 */
	public void setSolicitudRequerimientoRequisitoService(
		com.hitss.layer.service.SolicitudRequerimientoRequisitoService solicitudRequerimientoRequisitoService) {
		this.solicitudRequerimientoRequisitoService = solicitudRequerimientoRequisitoService;
	}

	/**
	 * Returns the solicitud requerimiento requisito persistence.
	 *
	 * @return the solicitud requerimiento requisito persistence
	 */
	public SolicitudRequerimientoRequisitoPersistence getSolicitudRequerimientoRequisitoPersistence() {
		return solicitudRequerimientoRequisitoPersistence;
	}

	/**
	 * Sets the solicitud requerimiento requisito persistence.
	 *
	 * @param solicitudRequerimientoRequisitoPersistence the solicitud requerimiento requisito persistence
	 */
	public void setSolicitudRequerimientoRequisitoPersistence(
		SolicitudRequerimientoRequisitoPersistence solicitudRequerimientoRequisitoPersistence) {
		this.solicitudRequerimientoRequisitoPersistence = solicitudRequerimientoRequisitoPersistence;
	}

	/**
	 * Returns the usuario local service.
	 *
	 * @return the usuario local service
	 */
	public com.hitss.layer.service.UsuarioLocalService getUsuarioLocalService() {
		return usuarioLocalService;
	}

	/**
	 * Sets the usuario local service.
	 *
	 * @param usuarioLocalService the usuario local service
	 */
	public void setUsuarioLocalService(
		com.hitss.layer.service.UsuarioLocalService usuarioLocalService) {
		this.usuarioLocalService = usuarioLocalService;
	}

	/**
	 * Returns the usuario remote service.
	 *
	 * @return the usuario remote service
	 */
	public com.hitss.layer.service.UsuarioService getUsuarioService() {
		return usuarioService;
	}

	/**
	 * Sets the usuario remote service.
	 *
	 * @param usuarioService the usuario remote service
	 */
	public void setUsuarioService(
		com.hitss.layer.service.UsuarioService usuarioService) {
		this.usuarioService = usuarioService;
	}

	/**
	 * Returns the usuario persistence.
	 *
	 * @return the usuario persistence
	 */
	public UsuarioPersistence getUsuarioPersistence() {
		return usuarioPersistence;
	}

	/**
	 * Sets the usuario persistence.
	 *
	 * @param usuarioPersistence the usuario persistence
	 */
	public void setUsuarioPersistence(UsuarioPersistence usuarioPersistence) {
		this.usuarioPersistence = usuarioPersistence;
	}

	/**
	 * Returns the usuario evaluacion local service.
	 *
	 * @return the usuario evaluacion local service
	 */
	public com.hitss.layer.service.UsuarioEvaluacionLocalService getUsuarioEvaluacionLocalService() {
		return usuarioEvaluacionLocalService;
	}

	/**
	 * Sets the usuario evaluacion local service.
	 *
	 * @param usuarioEvaluacionLocalService the usuario evaluacion local service
	 */
	public void setUsuarioEvaluacionLocalService(
		com.hitss.layer.service.UsuarioEvaluacionLocalService usuarioEvaluacionLocalService) {
		this.usuarioEvaluacionLocalService = usuarioEvaluacionLocalService;
	}

	/**
	 * Returns the usuario evaluacion remote service.
	 *
	 * @return the usuario evaluacion remote service
	 */
	public com.hitss.layer.service.UsuarioEvaluacionService getUsuarioEvaluacionService() {
		return usuarioEvaluacionService;
	}

	/**
	 * Sets the usuario evaluacion remote service.
	 *
	 * @param usuarioEvaluacionService the usuario evaluacion remote service
	 */
	public void setUsuarioEvaluacionService(
		com.hitss.layer.service.UsuarioEvaluacionService usuarioEvaluacionService) {
		this.usuarioEvaluacionService = usuarioEvaluacionService;
	}

	/**
	 * Returns the usuario evaluacion persistence.
	 *
	 * @return the usuario evaluacion persistence
	 */
	public UsuarioEvaluacionPersistence getUsuarioEvaluacionPersistence() {
		return usuarioEvaluacionPersistence;
	}

	/**
	 * Sets the usuario evaluacion persistence.
	 *
	 * @param usuarioEvaluacionPersistence the usuario evaluacion persistence
	 */
	public void setUsuarioEvaluacionPersistence(
		UsuarioEvaluacionPersistence usuarioEvaluacionPersistence) {
		this.usuarioEvaluacionPersistence = usuarioEvaluacionPersistence;
	}

	/**
	 * Returns the usuario requisito local service.
	 *
	 * @return the usuario requisito local service
	 */
	public com.hitss.layer.service.UsuarioRequisitoLocalService getUsuarioRequisitoLocalService() {
		return usuarioRequisitoLocalService;
	}

	/**
	 * Sets the usuario requisito local service.
	 *
	 * @param usuarioRequisitoLocalService the usuario requisito local service
	 */
	public void setUsuarioRequisitoLocalService(
		com.hitss.layer.service.UsuarioRequisitoLocalService usuarioRequisitoLocalService) {
		this.usuarioRequisitoLocalService = usuarioRequisitoLocalService;
	}

	/**
	 * Returns the usuario requisito remote service.
	 *
	 * @return the usuario requisito remote service
	 */
	public com.hitss.layer.service.UsuarioRequisitoService getUsuarioRequisitoService() {
		return usuarioRequisitoService;
	}

	/**
	 * Sets the usuario requisito remote service.
	 *
	 * @param usuarioRequisitoService the usuario requisito remote service
	 */
	public void setUsuarioRequisitoService(
		com.hitss.layer.service.UsuarioRequisitoService usuarioRequisitoService) {
		this.usuarioRequisitoService = usuarioRequisitoService;
	}

	/**
	 * Returns the usuario requisito persistence.
	 *
	 * @return the usuario requisito persistence
	 */
	public UsuarioRequisitoPersistence getUsuarioRequisitoPersistence() {
		return usuarioRequisitoPersistence;
	}

	/**
	 * Sets the usuario requisito persistence.
	 *
	 * @param usuarioRequisitoPersistence the usuario requisito persistence
	 */
	public void setUsuarioRequisitoPersistence(
		UsuarioRequisitoPersistence usuarioRequisitoPersistence) {
		this.usuarioRequisitoPersistence = usuarioRequisitoPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();

		PersistedModelLocalServiceRegistryUtil.register("com.hitss.layer.model.ActividadPlan",
			actividadPlanLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.hitss.layer.model.ActividadPlan");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return ActividadPlan.class;
	}

	protected String getModelClassName() {
		return ActividadPlan.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = actividadPlanPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.hitss.layer.service.ActividadCronogramaLocalService.class)
	protected com.hitss.layer.service.ActividadCronogramaLocalService actividadCronogramaLocalService;
	@BeanReference(type = com.hitss.layer.service.ActividadCronogramaService.class)
	protected com.hitss.layer.service.ActividadCronogramaService actividadCronogramaService;
	@BeanReference(type = ActividadCronogramaPersistence.class)
	protected ActividadCronogramaPersistence actividadCronogramaPersistence;
	@BeanReference(type = com.hitss.layer.service.ActividadPlanLocalService.class)
	protected com.hitss.layer.service.ActividadPlanLocalService actividadPlanLocalService;
	@BeanReference(type = com.hitss.layer.service.ActividadPlanService.class)
	protected com.hitss.layer.service.ActividadPlanService actividadPlanService;
	@BeanReference(type = ActividadPlanPersistence.class)
	protected ActividadPlanPersistence actividadPlanPersistence;
	@BeanReference(type = com.hitss.layer.service.ContratoLocalService.class)
	protected com.hitss.layer.service.ContratoLocalService contratoLocalService;
	@BeanReference(type = com.hitss.layer.service.ContratoService.class)
	protected com.hitss.layer.service.ContratoService contratoService;
	@BeanReference(type = ContratoPersistence.class)
	protected ContratoPersistence contratoPersistence;
	@BeanReference(type = com.hitss.layer.service.CronogramaLocalService.class)
	protected com.hitss.layer.service.CronogramaLocalService cronogramaLocalService;
	@BeanReference(type = com.hitss.layer.service.CronogramaService.class)
	protected com.hitss.layer.service.CronogramaService cronogramaService;
	@BeanReference(type = CronogramaPersistence.class)
	protected CronogramaPersistence cronogramaPersistence;
	@BeanReference(type = com.hitss.layer.service.DetalleRepuestaEvaluacionLocalService.class)
	protected com.hitss.layer.service.DetalleRepuestaEvaluacionLocalService detalleRepuestaEvaluacionLocalService;
	@BeanReference(type = com.hitss.layer.service.DetalleRepuestaEvaluacionService.class)
	protected com.hitss.layer.service.DetalleRepuestaEvaluacionService detalleRepuestaEvaluacionService;
	@BeanReference(type = DetalleRepuestaEvaluacionPersistence.class)
	protected DetalleRepuestaEvaluacionPersistence detalleRepuestaEvaluacionPersistence;
	@BeanReference(type = com.hitss.layer.service.DetalleRepuestaReclutamientoLocalService.class)
	protected com.hitss.layer.service.DetalleRepuestaReclutamientoLocalService detalleRepuestaReclutamientoLocalService;
	@BeanReference(type = com.hitss.layer.service.DetalleRepuestaReclutamientoService.class)
	protected com.hitss.layer.service.DetalleRepuestaReclutamientoService detalleRepuestaReclutamientoService;
	@BeanReference(type = DetalleRepuestaReclutamientoPersistence.class)
	protected DetalleRepuestaReclutamientoPersistence detalleRepuestaReclutamientoPersistence;
	@BeanReference(type = com.hitss.layer.service.EstudioLocalService.class)
	protected com.hitss.layer.service.EstudioLocalService estudioLocalService;
	@BeanReference(type = com.hitss.layer.service.EstudioService.class)
	protected com.hitss.layer.service.EstudioService estudioService;
	@BeanReference(type = EstudioPersistence.class)
	protected EstudioPersistence estudioPersistence;
	@BeanReference(type = com.hitss.layer.service.EtiquetaRelacionadaLocalService.class)
	protected com.hitss.layer.service.EtiquetaRelacionadaLocalService etiquetaRelacionadaLocalService;
	@BeanReference(type = com.hitss.layer.service.EtiquetaRelacionadaService.class)
	protected com.hitss.layer.service.EtiquetaRelacionadaService etiquetaRelacionadaService;
	@BeanReference(type = EtiquetaRelacionadaPersistence.class)
	protected EtiquetaRelacionadaPersistence etiquetaRelacionadaPersistence;
	@BeanReference(type = com.hitss.layer.service.EvaluacionLocalService.class)
	protected com.hitss.layer.service.EvaluacionLocalService evaluacionLocalService;
	@BeanReference(type = com.hitss.layer.service.EvaluacionService.class)
	protected com.hitss.layer.service.EvaluacionService evaluacionService;
	@BeanReference(type = EvaluacionPersistence.class)
	protected EvaluacionPersistence evaluacionPersistence;
	@BeanReference(type = com.hitss.layer.service.EvaluacionPreguntaLocalService.class)
	protected com.hitss.layer.service.EvaluacionPreguntaLocalService evaluacionPreguntaLocalService;
	@BeanReference(type = com.hitss.layer.service.EvaluacionPreguntaService.class)
	protected com.hitss.layer.service.EvaluacionPreguntaService evaluacionPreguntaService;
	@BeanReference(type = EvaluacionPreguntaPersistence.class)
	protected EvaluacionPreguntaPersistence evaluacionPreguntaPersistence;
	@BeanReference(type = com.hitss.layer.service.ExperienciaLocalService.class)
	protected com.hitss.layer.service.ExperienciaLocalService experienciaLocalService;
	@BeanReference(type = com.hitss.layer.service.ExperienciaService.class)
	protected com.hitss.layer.service.ExperienciaService experienciaService;
	@BeanReference(type = ExperienciaPersistence.class)
	protected ExperienciaPersistence experienciaPersistence;
	@BeanReference(type = com.hitss.layer.service.FasePostulacionLocalService.class)
	protected com.hitss.layer.service.FasePostulacionLocalService fasePostulacionLocalService;
	@BeanReference(type = com.hitss.layer.service.FasePostulacionService.class)
	protected com.hitss.layer.service.FasePostulacionService fasePostulacionService;
	@BeanReference(type = FasePostulacionPersistence.class)
	protected FasePostulacionPersistence fasePostulacionPersistence;
	@BeanReference(type = com.hitss.layer.service.FichaIngresoLocalService.class)
	protected com.hitss.layer.service.FichaIngresoLocalService fichaIngresoLocalService;
	@BeanReference(type = com.hitss.layer.service.FichaIngresoService.class)
	protected com.hitss.layer.service.FichaIngresoService fichaIngresoService;
	@BeanReference(type = FichaIngresoPersistence.class)
	protected FichaIngresoPersistence fichaIngresoPersistence;
	@BeanReference(type = com.hitss.layer.service.FuncionLocalService.class)
	protected com.hitss.layer.service.FuncionLocalService funcionLocalService;
	@BeanReference(type = com.hitss.layer.service.FuncionService.class)
	protected com.hitss.layer.service.FuncionService funcionService;
	@BeanReference(type = FuncionPersistence.class)
	protected FuncionPersistence funcionPersistence;
	@BeanReference(type = com.hitss.layer.service.InformeRetroalimentacionLocalService.class)
	protected com.hitss.layer.service.InformeRetroalimentacionLocalService informeRetroalimentacionLocalService;
	@BeanReference(type = com.hitss.layer.service.InformeRetroalimentacionService.class)
	protected com.hitss.layer.service.InformeRetroalimentacionService informeRetroalimentacionService;
	@BeanReference(type = InformeRetroalimentacionPersistence.class)
	protected InformeRetroalimentacionPersistence informeRetroalimentacionPersistence;
	@BeanReference(type = com.hitss.layer.service.LogOperacionesLocalService.class)
	protected com.hitss.layer.service.LogOperacionesLocalService logOperacionesLocalService;
	@BeanReference(type = com.hitss.layer.service.LogOperacionesService.class)
	protected com.hitss.layer.service.LogOperacionesService logOperacionesService;
	@BeanReference(type = LogOperacionesPersistence.class)
	protected LogOperacionesPersistence logOperacionesPersistence;
	@BeanReference(type = com.hitss.layer.service.ObservacionesLocalService.class)
	protected com.hitss.layer.service.ObservacionesLocalService observacionesLocalService;
	@BeanReference(type = com.hitss.layer.service.ObservacionesService.class)
	protected com.hitss.layer.service.ObservacionesService observacionesService;
	@BeanReference(type = ObservacionesPersistence.class)
	protected ObservacionesPersistence observacionesPersistence;
	@BeanReference(type = com.hitss.layer.service.ParametroLocalService.class)
	protected com.hitss.layer.service.ParametroLocalService parametroLocalService;
	@BeanReference(type = com.hitss.layer.service.ParametroService.class)
	protected com.hitss.layer.service.ParametroService parametroService;
	@BeanReference(type = ParametroPersistence.class)
	protected ParametroPersistence parametroPersistence;
	@BeanReference(type = ParametroFinder.class)
	protected ParametroFinder parametroFinder;
	@BeanReference(type = com.hitss.layer.service.PlanAccionLocalService.class)
	protected com.hitss.layer.service.PlanAccionLocalService planAccionLocalService;
	@BeanReference(type = com.hitss.layer.service.PlanAccionService.class)
	protected com.hitss.layer.service.PlanAccionService planAccionService;
	@BeanReference(type = PlanAccionPersistence.class)
	protected PlanAccionPersistence planAccionPersistence;
	@BeanReference(type = com.hitss.layer.service.PostulacionLocalService.class)
	protected com.hitss.layer.service.PostulacionLocalService postulacionLocalService;
	@BeanReference(type = com.hitss.layer.service.PostulacionService.class)
	protected com.hitss.layer.service.PostulacionService postulacionService;
	@BeanReference(type = PostulacionPersistence.class)
	protected PostulacionPersistence postulacionPersistence;
	@BeanReference(type = com.hitss.layer.service.PreguntaLocalService.class)
	protected com.hitss.layer.service.PreguntaLocalService preguntaLocalService;
	@BeanReference(type = com.hitss.layer.service.PreguntaService.class)
	protected com.hitss.layer.service.PreguntaService preguntaService;
	@BeanReference(type = PreguntaPersistence.class)
	protected PreguntaPersistence preguntaPersistence;
	@BeanReference(type = com.hitss.layer.service.PrioridadGrupoUsuariosLocalService.class)
	protected com.hitss.layer.service.PrioridadGrupoUsuariosLocalService prioridadGrupoUsuariosLocalService;
	@BeanReference(type = com.hitss.layer.service.PrioridadGrupoUsuariosService.class)
	protected com.hitss.layer.service.PrioridadGrupoUsuariosService prioridadGrupoUsuariosService;
	@BeanReference(type = PrioridadGrupoUsuariosPersistence.class)
	protected PrioridadGrupoUsuariosPersistence prioridadGrupoUsuariosPersistence;
	@BeanReference(type = com.hitss.layer.service.ReferenciaLocalService.class)
	protected com.hitss.layer.service.ReferenciaLocalService referenciaLocalService;
	@BeanReference(type = com.hitss.layer.service.ReferenciaService.class)
	protected com.hitss.layer.service.ReferenciaService referenciaService;
	@BeanReference(type = ReferenciaPersistence.class)
	protected ReferenciaPersistence referenciaPersistence;
	@BeanReference(type = com.hitss.layer.service.RespuestaLocalService.class)
	protected com.hitss.layer.service.RespuestaLocalService respuestaLocalService;
	@BeanReference(type = com.hitss.layer.service.RespuestaService.class)
	protected com.hitss.layer.service.RespuestaService respuestaService;
	@BeanReference(type = RespuestaPersistence.class)
	protected RespuestaPersistence respuestaPersistence;
	@BeanReference(type = com.hitss.layer.service.SolicitudEvaluacionDesempennoLocalService.class)
	protected com.hitss.layer.service.SolicitudEvaluacionDesempennoLocalService solicitudEvaluacionDesempennoLocalService;
	@BeanReference(type = com.hitss.layer.service.SolicitudEvaluacionDesempennoService.class)
	protected com.hitss.layer.service.SolicitudEvaluacionDesempennoService solicitudEvaluacionDesempennoService;
	@BeanReference(type = SolicitudEvaluacionDesempennoPersistence.class)
	protected SolicitudEvaluacionDesempennoPersistence solicitudEvaluacionDesempennoPersistence;
	@BeanReference(type = com.hitss.layer.service.SolicitudRequerimientoLocalService.class)
	protected com.hitss.layer.service.SolicitudRequerimientoLocalService solicitudRequerimientoLocalService;
	@BeanReference(type = com.hitss.layer.service.SolicitudRequerimientoService.class)
	protected com.hitss.layer.service.SolicitudRequerimientoService solicitudRequerimientoService;
	@BeanReference(type = SolicitudRequerimientoPersistence.class)
	protected SolicitudRequerimientoPersistence solicitudRequerimientoPersistence;
	@BeanReference(type = com.hitss.layer.service.SolicitudRequerimientoRequisitoLocalService.class)
	protected com.hitss.layer.service.SolicitudRequerimientoRequisitoLocalService solicitudRequerimientoRequisitoLocalService;
	@BeanReference(type = com.hitss.layer.service.SolicitudRequerimientoRequisitoService.class)
	protected com.hitss.layer.service.SolicitudRequerimientoRequisitoService solicitudRequerimientoRequisitoService;
	@BeanReference(type = SolicitudRequerimientoRequisitoPersistence.class)
	protected SolicitudRequerimientoRequisitoPersistence solicitudRequerimientoRequisitoPersistence;
	@BeanReference(type = com.hitss.layer.service.UsuarioLocalService.class)
	protected com.hitss.layer.service.UsuarioLocalService usuarioLocalService;
	@BeanReference(type = com.hitss.layer.service.UsuarioService.class)
	protected com.hitss.layer.service.UsuarioService usuarioService;
	@BeanReference(type = UsuarioPersistence.class)
	protected UsuarioPersistence usuarioPersistence;
	@BeanReference(type = com.hitss.layer.service.UsuarioEvaluacionLocalService.class)
	protected com.hitss.layer.service.UsuarioEvaluacionLocalService usuarioEvaluacionLocalService;
	@BeanReference(type = com.hitss.layer.service.UsuarioEvaluacionService.class)
	protected com.hitss.layer.service.UsuarioEvaluacionService usuarioEvaluacionService;
	@BeanReference(type = UsuarioEvaluacionPersistence.class)
	protected UsuarioEvaluacionPersistence usuarioEvaluacionPersistence;
	@BeanReference(type = com.hitss.layer.service.UsuarioRequisitoLocalService.class)
	protected com.hitss.layer.service.UsuarioRequisitoLocalService usuarioRequisitoLocalService;
	@BeanReference(type = com.hitss.layer.service.UsuarioRequisitoService.class)
	protected com.hitss.layer.service.UsuarioRequisitoService usuarioRequisitoService;
	@BeanReference(type = UsuarioRequisitoPersistence.class)
	protected UsuarioRequisitoPersistence usuarioRequisitoPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private ActividadPlanLocalServiceClpInvoker _clpInvoker = new ActividadPlanLocalServiceClpInvoker();
}