/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rec.hitss.layer.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.rec.hitss.layer.model.EtiquetaRelacionada;
import com.rec.hitss.layer.model.EtiquetaRelacionadaModel;
import com.rec.hitss.layer.model.EtiquetaRelacionadaSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the EtiquetaRelacionada service. Represents a row in the &quot;EtiquetaRelacionada&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.rec.hitss.layer.model.EtiquetaRelacionadaModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EtiquetaRelacionadaImpl}.
 * </p>
 *
 * @author Crossfire
 * @see EtiquetaRelacionadaImpl
 * @see com.rec.hitss.layer.model.EtiquetaRelacionada
 * @see com.rec.hitss.layer.model.EtiquetaRelacionadaModel
 * @generated
 */
@JSON(strict = true)
public class EtiquetaRelacionadaModelImpl extends BaseModelImpl<EtiquetaRelacionada>
	implements EtiquetaRelacionadaModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a etiqueta relacionada model instance should use the {@link com.rec.hitss.layer.model.EtiquetaRelacionada} interface instead.
	 */
	public static final String TABLE_NAME = "EtiquetaRelacionada";
	public static final Object[][] TABLE_COLUMNS = {
			{ "etiquetaRelacionadaId", Types.BIGINT },
			{ "registroId", Types.BIGINT },
			{ "etiqueta", Types.BIGINT },
			{ "tabla", Types.BIGINT },
			{ "tagId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table EtiquetaRelacionada (etiquetaRelacionadaId LONG not null primary key,registroId LONG,etiqueta LONG,tabla LONG,tagId LONG,groupId LONG,companyId LONG)";
	public static final String TABLE_SQL_DROP = "drop table EtiquetaRelacionada";
	public static final String ORDER_BY_JPQL = " ORDER BY etiquetaRelacionada.etiquetaRelacionadaId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY EtiquetaRelacionada.etiquetaRelacionadaId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rec.hitss.layer.model.EtiquetaRelacionada"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rec.hitss.layer.model.EtiquetaRelacionada"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static EtiquetaRelacionada toModel(EtiquetaRelacionadaSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		EtiquetaRelacionada model = new EtiquetaRelacionadaImpl();

		model.setEtiquetaRelacionadaId(soapModel.getEtiquetaRelacionadaId());
		model.setRegistroId(soapModel.getRegistroId());
		model.setEtiqueta(soapModel.getEtiqueta());
		model.setTabla(soapModel.getTabla());
		model.setTagId(soapModel.getTagId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<EtiquetaRelacionada> toModels(
		EtiquetaRelacionadaSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<EtiquetaRelacionada> models = new ArrayList<EtiquetaRelacionada>(soapModels.length);

		for (EtiquetaRelacionadaSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.rec.hitss.layer.model.EtiquetaRelacionada"));

	public EtiquetaRelacionadaModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _etiquetaRelacionadaId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEtiquetaRelacionadaId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _etiquetaRelacionadaId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EtiquetaRelacionada.class;
	}

	@Override
	public String getModelClassName() {
		return EtiquetaRelacionada.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("etiquetaRelacionadaId", getEtiquetaRelacionadaId());
		attributes.put("registroId", getRegistroId());
		attributes.put("etiqueta", getEtiqueta());
		attributes.put("tabla", getTabla());
		attributes.put("tagId", getTagId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long etiquetaRelacionadaId = (Long)attributes.get(
				"etiquetaRelacionadaId");

		if (etiquetaRelacionadaId != null) {
			setEtiquetaRelacionadaId(etiquetaRelacionadaId);
		}

		Long registroId = (Long)attributes.get("registroId");

		if (registroId != null) {
			setRegistroId(registroId);
		}

		Long etiqueta = (Long)attributes.get("etiqueta");

		if (etiqueta != null) {
			setEtiqueta(etiqueta);
		}

		Long tabla = (Long)attributes.get("tabla");

		if (tabla != null) {
			setTabla(tabla);
		}

		Long tagId = (Long)attributes.get("tagId");

		if (tagId != null) {
			setTagId(tagId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}
	}

	@JSON
	@Override
	public long getEtiquetaRelacionadaId() {
		return _etiquetaRelacionadaId;
	}

	@Override
	public void setEtiquetaRelacionadaId(long etiquetaRelacionadaId) {
		_etiquetaRelacionadaId = etiquetaRelacionadaId;
	}

	@JSON
	@Override
	public long getRegistroId() {
		return _registroId;
	}

	@Override
	public void setRegistroId(long registroId) {
		_registroId = registroId;
	}

	@JSON
	@Override
	public long getEtiqueta() {
		return _etiqueta;
	}

	@Override
	public void setEtiqueta(long etiqueta) {
		_etiqueta = etiqueta;
	}

	@JSON
	@Override
	public long getTabla() {
		return _tabla;
	}

	@Override
	public void setTabla(long tabla) {
		_tabla = tabla;
	}

	@JSON
	@Override
	public long getTagId() {
		return _tagId;
	}

	@Override
	public void setTagId(long tagId) {
		_tagId = tagId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			EtiquetaRelacionada.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EtiquetaRelacionada toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (EtiquetaRelacionada)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EtiquetaRelacionadaImpl etiquetaRelacionadaImpl = new EtiquetaRelacionadaImpl();

		etiquetaRelacionadaImpl.setEtiquetaRelacionadaId(getEtiquetaRelacionadaId());
		etiquetaRelacionadaImpl.setRegistroId(getRegistroId());
		etiquetaRelacionadaImpl.setEtiqueta(getEtiqueta());
		etiquetaRelacionadaImpl.setTabla(getTabla());
		etiquetaRelacionadaImpl.setTagId(getTagId());
		etiquetaRelacionadaImpl.setGroupId(getGroupId());
		etiquetaRelacionadaImpl.setCompanyId(getCompanyId());

		etiquetaRelacionadaImpl.resetOriginalValues();

		return etiquetaRelacionadaImpl;
	}

	@Override
	public int compareTo(EtiquetaRelacionada etiquetaRelacionada) {
		long primaryKey = etiquetaRelacionada.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof EtiquetaRelacionada)) {
			return false;
		}

		EtiquetaRelacionada etiquetaRelacionada = (EtiquetaRelacionada)obj;

		long primaryKey = etiquetaRelacionada.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<EtiquetaRelacionada> toCacheModel() {
		EtiquetaRelacionadaCacheModel etiquetaRelacionadaCacheModel = new EtiquetaRelacionadaCacheModel();

		etiquetaRelacionadaCacheModel.etiquetaRelacionadaId = getEtiquetaRelacionadaId();

		etiquetaRelacionadaCacheModel.registroId = getRegistroId();

		etiquetaRelacionadaCacheModel.etiqueta = getEtiqueta();

		etiquetaRelacionadaCacheModel.tabla = getTabla();

		etiquetaRelacionadaCacheModel.tagId = getTagId();

		etiquetaRelacionadaCacheModel.groupId = getGroupId();

		etiquetaRelacionadaCacheModel.companyId = getCompanyId();

		return etiquetaRelacionadaCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{etiquetaRelacionadaId=");
		sb.append(getEtiquetaRelacionadaId());
		sb.append(", registroId=");
		sb.append(getRegistroId());
		sb.append(", etiqueta=");
		sb.append(getEtiqueta());
		sb.append(", tabla=");
		sb.append(getTabla());
		sb.append(", tagId=");
		sb.append(getTagId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append("com.rec.hitss.layer.model.EtiquetaRelacionada");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>etiquetaRelacionadaId</column-name><column-value><![CDATA[");
		sb.append(getEtiquetaRelacionadaId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>registroId</column-name><column-value><![CDATA[");
		sb.append(getRegistroId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>etiqueta</column-name><column-value><![CDATA[");
		sb.append(getEtiqueta());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tabla</column-name><column-value><![CDATA[");
		sb.append(getTabla());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tagId</column-name><column-value><![CDATA[");
		sb.append(getTagId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = EtiquetaRelacionada.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			EtiquetaRelacionada.class
		};
	private long _etiquetaRelacionadaId;
	private long _registroId;
	private long _etiqueta;
	private long _tabla;
	private long _tagId;
	private long _groupId;
	private long _companyId;
	private EtiquetaRelacionada _escapedModel;
}