/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rec.hitss.layer.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.rec.hitss.layer.model.Respuesta;
import com.rec.hitss.layer.service.RespuestaLocalServiceUtil;

/**
 * The extended model base implementation for the Respuesta service. Represents a row in the &quot;Respuesta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RespuestaImpl}.
 * </p>
 *
 * @author Crossfire
 * @see RespuestaImpl
 * @see com.rec.hitss.layer.model.Respuesta
 * @generated
 */
public abstract class RespuestaBaseImpl extends RespuestaModelImpl
	implements Respuesta {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a respuesta model instance should use the {@link Respuesta} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			RespuestaLocalServiceUtil.addRespuesta(this);
		}
		else {
			RespuestaLocalServiceUtil.updateRespuesta(this);
		}
	}
}