/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.hitss.layer.model.impl;

import com.hitss.layer.model.ActividadPlanAccionUsuario;
import com.hitss.layer.model.ActividadPlanAccionUsuarioModel;
import com.hitss.layer.model.ActividadPlanAccionUsuarioSoap;
import com.hitss.layer.service.persistence.ActividadPlanAccionUsuarioPK;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the ActividadPlanAccionUsuario service. Represents a row in the &quot;ActividadPlanAccionUsuario&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.hitss.layer.model.ActividadPlanAccionUsuarioModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ActividadPlanAccionUsuarioImpl}.
 * </p>
 *
 * @author Danielle Delgado
 * @see ActividadPlanAccionUsuarioImpl
 * @see com.hitss.layer.model.ActividadPlanAccionUsuario
 * @see com.hitss.layer.model.ActividadPlanAccionUsuarioModel
 * @generated
 */
@JSON(strict = true)
public class ActividadPlanAccionUsuarioModelImpl extends BaseModelImpl<ActividadPlanAccionUsuario>
	implements ActividadPlanAccionUsuarioModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a actividad plan accion usuario model instance should use the {@link com.hitss.layer.model.ActividadPlanAccionUsuario} interface instead.
	 */
	public static final String TABLE_NAME = "ActividadPlanAccionUsuario";
	public static final Object[][] TABLE_COLUMNS = {
			{ "actividadPlanAccionUsuariocoId", Types.BIGINT },
			{ "actividadPlanId", Types.BIGINT },
			{ "usuarioId", Types.BIGINT },
			{ "cumplio", Types.BIGINT },
			{ "actividad", Types.VARCHAR },
			{ "puntuacion", Types.INTEGER },
			{ "activo", Types.BOOLEAN },
			{ "usuariocrea", Types.BIGINT },
			{ "fechacrea", Types.TIMESTAMP },
			{ "usuariomodifica", Types.BIGINT },
			{ "fechamodifica", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table ActividadPlanAccionUsuario (actividadPlanAccionUsuariocoId LONG not null,actividadPlanId LONG not null,usuarioId LONG,cumplio LONG,actividad VARCHAR(75) null,puntuacion INTEGER,activo BOOLEAN,usuariocrea LONG,fechacrea DATE null,usuariomodifica LONG,fechamodifica DATE null,primary key (actividadPlanAccionUsuariocoId, actividadPlanId))";
	public static final String TABLE_SQL_DROP = "drop table ActividadPlanAccionUsuario";
	public static final String ORDER_BY_JPQL = " ORDER BY actividadPlanAccionUsuario.fechamodifica ASC";
	public static final String ORDER_BY_SQL = " ORDER BY ActividadPlanAccionUsuario.fechamodifica ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.hitss.layer.model.ActividadPlanAccionUsuario"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.hitss.layer.model.ActividadPlanAccionUsuario"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ActividadPlanAccionUsuario toModel(
		ActividadPlanAccionUsuarioSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ActividadPlanAccionUsuario model = new ActividadPlanAccionUsuarioImpl();

		model.setActividadPlanAccionUsuariocoId(soapModel.getActividadPlanAccionUsuariocoId());
		model.setActividadPlanId(soapModel.getActividadPlanId());
		model.setUsuarioId(soapModel.getUsuarioId());
		model.setCumplio(soapModel.getCumplio());
		model.setActividad(soapModel.getActividad());
		model.setPuntuacion(soapModel.getPuntuacion());
		model.setActivo(soapModel.getActivo());
		model.setUsuariocrea(soapModel.getUsuariocrea());
		model.setFechacrea(soapModel.getFechacrea());
		model.setUsuariomodifica(soapModel.getUsuariomodifica());
		model.setFechamodifica(soapModel.getFechamodifica());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ActividadPlanAccionUsuario> toModels(
		ActividadPlanAccionUsuarioSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ActividadPlanAccionUsuario> models = new ArrayList<ActividadPlanAccionUsuario>(soapModels.length);

		for (ActividadPlanAccionUsuarioSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.hitss.layer.model.ActividadPlanAccionUsuario"));

	public ActividadPlanAccionUsuarioModelImpl() {
	}

	@Override
	public ActividadPlanAccionUsuarioPK getPrimaryKey() {
		return new ActividadPlanAccionUsuarioPK(_actividadPlanAccionUsuariocoId,
			_actividadPlanId);
	}

	@Override
	public void setPrimaryKey(ActividadPlanAccionUsuarioPK primaryKey) {
		setActividadPlanAccionUsuariocoId(primaryKey.actividadPlanAccionUsuariocoId);
		setActividadPlanId(primaryKey.actividadPlanId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new ActividadPlanAccionUsuarioPK(_actividadPlanAccionUsuariocoId,
			_actividadPlanId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((ActividadPlanAccionUsuarioPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return ActividadPlanAccionUsuario.class;
	}

	@Override
	public String getModelClassName() {
		return ActividadPlanAccionUsuario.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("actividadPlanAccionUsuariocoId",
			getActividadPlanAccionUsuariocoId());
		attributes.put("actividadPlanId", getActividadPlanId());
		attributes.put("usuarioId", getUsuarioId());
		attributes.put("cumplio", getCumplio());
		attributes.put("actividad", getActividad());
		attributes.put("puntuacion", getPuntuacion());
		attributes.put("activo", getActivo());
		attributes.put("usuariocrea", getUsuariocrea());
		attributes.put("fechacrea", getFechacrea());
		attributes.put("usuariomodifica", getUsuariomodifica());
		attributes.put("fechamodifica", getFechamodifica());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long actividadPlanAccionUsuariocoId = (Long)attributes.get(
				"actividadPlanAccionUsuariocoId");

		if (actividadPlanAccionUsuariocoId != null) {
			setActividadPlanAccionUsuariocoId(actividadPlanAccionUsuariocoId);
		}

		Long actividadPlanId = (Long)attributes.get("actividadPlanId");

		if (actividadPlanId != null) {
			setActividadPlanId(actividadPlanId);
		}

		Long usuarioId = (Long)attributes.get("usuarioId");

		if (usuarioId != null) {
			setUsuarioId(usuarioId);
		}

		Long cumplio = (Long)attributes.get("cumplio");

		if (cumplio != null) {
			setCumplio(cumplio);
		}

		String actividad = (String)attributes.get("actividad");

		if (actividad != null) {
			setActividad(actividad);
		}

		Integer puntuacion = (Integer)attributes.get("puntuacion");

		if (puntuacion != null) {
			setPuntuacion(puntuacion);
		}

		Boolean activo = (Boolean)attributes.get("activo");

		if (activo != null) {
			setActivo(activo);
		}

		Long usuariocrea = (Long)attributes.get("usuariocrea");

		if (usuariocrea != null) {
			setUsuariocrea(usuariocrea);
		}

		Date fechacrea = (Date)attributes.get("fechacrea");

		if (fechacrea != null) {
			setFechacrea(fechacrea);
		}

		Long usuariomodifica = (Long)attributes.get("usuariomodifica");

		if (usuariomodifica != null) {
			setUsuariomodifica(usuariomodifica);
		}

		Date fechamodifica = (Date)attributes.get("fechamodifica");

		if (fechamodifica != null) {
			setFechamodifica(fechamodifica);
		}
	}

	@JSON
	@Override
	public long getActividadPlanAccionUsuariocoId() {
		return _actividadPlanAccionUsuariocoId;
	}

	@Override
	public void setActividadPlanAccionUsuariocoId(
		long actividadPlanAccionUsuariocoId) {
		_actividadPlanAccionUsuariocoId = actividadPlanAccionUsuariocoId;
	}

	@JSON
	@Override
	public long getActividadPlanId() {
		return _actividadPlanId;
	}

	@Override
	public void setActividadPlanId(long actividadPlanId) {
		_actividadPlanId = actividadPlanId;
	}

	@JSON
	@Override
	public long getUsuarioId() {
		return _usuarioId;
	}

	@Override
	public void setUsuarioId(long usuarioId) {
		_usuarioId = usuarioId;
	}

	@JSON
	@Override
	public long getCumplio() {
		return _cumplio;
	}

	@Override
	public void setCumplio(long cumplio) {
		_cumplio = cumplio;
	}

	@JSON
	@Override
	public String getActividad() {
		if (_actividad == null) {
			return StringPool.BLANK;
		}
		else {
			return _actividad;
		}
	}

	@Override
	public void setActividad(String actividad) {
		_actividad = actividad;
	}

	@JSON
	@Override
	public int getPuntuacion() {
		return _puntuacion;
	}

	@Override
	public void setPuntuacion(int puntuacion) {
		_puntuacion = puntuacion;
	}

	@JSON
	@Override
	public boolean getActivo() {
		return _activo;
	}

	@Override
	public boolean isActivo() {
		return _activo;
	}

	@Override
	public void setActivo(boolean activo) {
		_activo = activo;
	}

	@JSON
	@Override
	public long getUsuariocrea() {
		return _usuariocrea;
	}

	@Override
	public void setUsuariocrea(long usuariocrea) {
		_usuariocrea = usuariocrea;
	}

	@JSON
	@Override
	public Date getFechacrea() {
		return _fechacrea;
	}

	@Override
	public void setFechacrea(Date fechacrea) {
		_fechacrea = fechacrea;
	}

	@JSON
	@Override
	public long getUsuariomodifica() {
		return _usuariomodifica;
	}

	@Override
	public void setUsuariomodifica(long usuariomodifica) {
		_usuariomodifica = usuariomodifica;
	}

	@JSON
	@Override
	public Date getFechamodifica() {
		return _fechamodifica;
	}

	@Override
	public void setFechamodifica(Date fechamodifica) {
		_fechamodifica = fechamodifica;
	}

	@Override
	public ActividadPlanAccionUsuario toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ActividadPlanAccionUsuario)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ActividadPlanAccionUsuarioImpl actividadPlanAccionUsuarioImpl = new ActividadPlanAccionUsuarioImpl();

		actividadPlanAccionUsuarioImpl.setActividadPlanAccionUsuariocoId(getActividadPlanAccionUsuariocoId());
		actividadPlanAccionUsuarioImpl.setActividadPlanId(getActividadPlanId());
		actividadPlanAccionUsuarioImpl.setUsuarioId(getUsuarioId());
		actividadPlanAccionUsuarioImpl.setCumplio(getCumplio());
		actividadPlanAccionUsuarioImpl.setActividad(getActividad());
		actividadPlanAccionUsuarioImpl.setPuntuacion(getPuntuacion());
		actividadPlanAccionUsuarioImpl.setActivo(getActivo());
		actividadPlanAccionUsuarioImpl.setUsuariocrea(getUsuariocrea());
		actividadPlanAccionUsuarioImpl.setFechacrea(getFechacrea());
		actividadPlanAccionUsuarioImpl.setUsuariomodifica(getUsuariomodifica());
		actividadPlanAccionUsuarioImpl.setFechamodifica(getFechamodifica());

		actividadPlanAccionUsuarioImpl.resetOriginalValues();

		return actividadPlanAccionUsuarioImpl;
	}

	@Override
	public int compareTo(ActividadPlanAccionUsuario actividadPlanAccionUsuario) {
		int value = 0;

		value = DateUtil.compareTo(getFechamodifica(),
				actividadPlanAccionUsuario.getFechamodifica());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ActividadPlanAccionUsuario)) {
			return false;
		}

		ActividadPlanAccionUsuario actividadPlanAccionUsuario = (ActividadPlanAccionUsuario)obj;

		ActividadPlanAccionUsuarioPK primaryKey = actividadPlanAccionUsuario.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<ActividadPlanAccionUsuario> toCacheModel() {
		ActividadPlanAccionUsuarioCacheModel actividadPlanAccionUsuarioCacheModel =
			new ActividadPlanAccionUsuarioCacheModel();

		actividadPlanAccionUsuarioCacheModel.actividadPlanAccionUsuariocoId = getActividadPlanAccionUsuariocoId();

		actividadPlanAccionUsuarioCacheModel.actividadPlanId = getActividadPlanId();

		actividadPlanAccionUsuarioCacheModel.usuarioId = getUsuarioId();

		actividadPlanAccionUsuarioCacheModel.cumplio = getCumplio();

		actividadPlanAccionUsuarioCacheModel.actividad = getActividad();

		String actividad = actividadPlanAccionUsuarioCacheModel.actividad;

		if ((actividad != null) && (actividad.length() == 0)) {
			actividadPlanAccionUsuarioCacheModel.actividad = null;
		}

		actividadPlanAccionUsuarioCacheModel.puntuacion = getPuntuacion();

		actividadPlanAccionUsuarioCacheModel.activo = getActivo();

		actividadPlanAccionUsuarioCacheModel.usuariocrea = getUsuariocrea();

		Date fechacrea = getFechacrea();

		if (fechacrea != null) {
			actividadPlanAccionUsuarioCacheModel.fechacrea = fechacrea.getTime();
		}
		else {
			actividadPlanAccionUsuarioCacheModel.fechacrea = Long.MIN_VALUE;
		}

		actividadPlanAccionUsuarioCacheModel.usuariomodifica = getUsuariomodifica();

		Date fechamodifica = getFechamodifica();

		if (fechamodifica != null) {
			actividadPlanAccionUsuarioCacheModel.fechamodifica = fechamodifica.getTime();
		}
		else {
			actividadPlanAccionUsuarioCacheModel.fechamodifica = Long.MIN_VALUE;
		}

		return actividadPlanAccionUsuarioCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{actividadPlanAccionUsuariocoId=");
		sb.append(getActividadPlanAccionUsuariocoId());
		sb.append(", actividadPlanId=");
		sb.append(getActividadPlanId());
		sb.append(", usuarioId=");
		sb.append(getUsuarioId());
		sb.append(", cumplio=");
		sb.append(getCumplio());
		sb.append(", actividad=");
		sb.append(getActividad());
		sb.append(", puntuacion=");
		sb.append(getPuntuacion());
		sb.append(", activo=");
		sb.append(getActivo());
		sb.append(", usuariocrea=");
		sb.append(getUsuariocrea());
		sb.append(", fechacrea=");
		sb.append(getFechacrea());
		sb.append(", usuariomodifica=");
		sb.append(getUsuariomodifica());
		sb.append(", fechamodifica=");
		sb.append(getFechamodifica());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("com.hitss.layer.model.ActividadPlanAccionUsuario");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>actividadPlanAccionUsuariocoId</column-name><column-value><![CDATA[");
		sb.append(getActividadPlanAccionUsuariocoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>actividadPlanId</column-name><column-value><![CDATA[");
		sb.append(getActividadPlanId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>usuarioId</column-name><column-value><![CDATA[");
		sb.append(getUsuarioId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cumplio</column-name><column-value><![CDATA[");
		sb.append(getCumplio());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>actividad</column-name><column-value><![CDATA[");
		sb.append(getActividad());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>puntuacion</column-name><column-value><![CDATA[");
		sb.append(getPuntuacion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>activo</column-name><column-value><![CDATA[");
		sb.append(getActivo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>usuariocrea</column-name><column-value><![CDATA[");
		sb.append(getUsuariocrea());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fechacrea</column-name><column-value><![CDATA[");
		sb.append(getFechacrea());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>usuariomodifica</column-name><column-value><![CDATA[");
		sb.append(getUsuariomodifica());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fechamodifica</column-name><column-value><![CDATA[");
		sb.append(getFechamodifica());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ActividadPlanAccionUsuario.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ActividadPlanAccionUsuario.class
		};
	private long _actividadPlanAccionUsuariocoId;
	private long _actividadPlanId;
	private long _usuarioId;
	private long _cumplio;
	private String _actividad;
	private int _puntuacion;
	private boolean _activo;
	private long _usuariocrea;
	private Date _fechacrea;
	private long _usuariomodifica;
	private Date _fechamodifica;
	private ActividadPlanAccionUsuario _escapedModel;
}