/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.hitss.layer.model.impl;

import com.hitss.layer.model.DetalleRepuestaReclutamiento;
import com.hitss.layer.model.DetalleRepuestaReclutamientoModel;
import com.hitss.layer.model.DetalleRepuestaReclutamientoSoap;
import com.hitss.layer.service.persistence.DetalleRepuestaReclutamientoPK;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the DetalleRepuestaReclutamiento service. Represents a row in the &quot;DetalleRepuestaReclutamiento&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.hitss.layer.model.DetalleRepuestaReclutamientoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DetalleRepuestaReclutamientoImpl}.
 * </p>
 *
 * @author Danielle Delgado
 * @see DetalleRepuestaReclutamientoImpl
 * @see com.hitss.layer.model.DetalleRepuestaReclutamiento
 * @see com.hitss.layer.model.DetalleRepuestaReclutamientoModel
 * @generated
 */
@JSON(strict = true)
public class DetalleRepuestaReclutamientoModelImpl extends BaseModelImpl<DetalleRepuestaReclutamiento>
	implements DetalleRepuestaReclutamientoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a detalle repuesta reclutamiento model instance should use the {@link com.hitss.layer.model.DetalleRepuestaReclutamiento} interface instead.
	 */
	public static final String TABLE_NAME = "DetalleRepuestaReclutamiento";
	public static final Object[][] TABLE_COLUMNS = {
			{ "detalleRepsuestaId", Types.BIGINT },
			{ "evaluacionId", Types.BIGINT },
			{ "fasePostulacionId", Types.BIGINT },
			{ "descripcion", Types.VARCHAR },
			{ "preguntaId", Types.BIGINT },
			{ "respuestaSeleccionada", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table DetalleRepuestaReclutamiento (detalleRepsuestaId LONG not null,evaluacionId LONG not null,fasePostulacionId LONG not null,descripcion VARCHAR(75) null,preguntaId LONG not null,respuestaSeleccionada INTEGER,primary key (detalleRepsuestaId, evaluacionId, fasePostulacionId, preguntaId))";
	public static final String TABLE_SQL_DROP = "drop table DetalleRepuestaReclutamiento";
	public static final String ORDER_BY_JPQL = " ORDER BY detalleRepuestaReclutamiento.id.detalleRepsuestaId ASC, detalleRepuestaReclutamiento.id.evaluacionId ASC, detalleRepuestaReclutamiento.id.fasePostulacionId ASC, detalleRepuestaReclutamiento.id.preguntaId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY DetalleRepuestaReclutamiento.detalleRepsuestaId ASC, DetalleRepuestaReclutamiento.evaluacionId ASC, DetalleRepuestaReclutamiento.fasePostulacionId ASC, DetalleRepuestaReclutamiento.preguntaId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.hitss.layer.model.DetalleRepuestaReclutamiento"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.hitss.layer.model.DetalleRepuestaReclutamiento"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static DetalleRepuestaReclutamiento toModel(
		DetalleRepuestaReclutamientoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		DetalleRepuestaReclutamiento model = new DetalleRepuestaReclutamientoImpl();

		model.setDetalleRepsuestaId(soapModel.getDetalleRepsuestaId());
		model.setEvaluacionId(soapModel.getEvaluacionId());
		model.setFasePostulacionId(soapModel.getFasePostulacionId());
		model.setDescripcion(soapModel.getDescripcion());
		model.setPreguntaId(soapModel.getPreguntaId());
		model.setRespuestaSeleccionada(soapModel.getRespuestaSeleccionada());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<DetalleRepuestaReclutamiento> toModels(
		DetalleRepuestaReclutamientoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<DetalleRepuestaReclutamiento> models = new ArrayList<DetalleRepuestaReclutamiento>(soapModels.length);

		for (DetalleRepuestaReclutamientoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.hitss.layer.model.DetalleRepuestaReclutamiento"));

	public DetalleRepuestaReclutamientoModelImpl() {
	}

	@Override
	public DetalleRepuestaReclutamientoPK getPrimaryKey() {
		return new DetalleRepuestaReclutamientoPK(_detalleRepsuestaId,
			_evaluacionId, _fasePostulacionId, _preguntaId);
	}

	@Override
	public void setPrimaryKey(DetalleRepuestaReclutamientoPK primaryKey) {
		setDetalleRepsuestaId(primaryKey.detalleRepsuestaId);
		setEvaluacionId(primaryKey.evaluacionId);
		setFasePostulacionId(primaryKey.fasePostulacionId);
		setPreguntaId(primaryKey.preguntaId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new DetalleRepuestaReclutamientoPK(_detalleRepsuestaId,
			_evaluacionId, _fasePostulacionId, _preguntaId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((DetalleRepuestaReclutamientoPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return DetalleRepuestaReclutamiento.class;
	}

	@Override
	public String getModelClassName() {
		return DetalleRepuestaReclutamiento.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("detalleRepsuestaId", getDetalleRepsuestaId());
		attributes.put("evaluacionId", getEvaluacionId());
		attributes.put("fasePostulacionId", getFasePostulacionId());
		attributes.put("descripcion", getDescripcion());
		attributes.put("preguntaId", getPreguntaId());
		attributes.put("respuestaSeleccionada", getRespuestaSeleccionada());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long detalleRepsuestaId = (Long)attributes.get("detalleRepsuestaId");

		if (detalleRepsuestaId != null) {
			setDetalleRepsuestaId(detalleRepsuestaId);
		}

		Long evaluacionId = (Long)attributes.get("evaluacionId");

		if (evaluacionId != null) {
			setEvaluacionId(evaluacionId);
		}

		Long fasePostulacionId = (Long)attributes.get("fasePostulacionId");

		if (fasePostulacionId != null) {
			setFasePostulacionId(fasePostulacionId);
		}

		String descripcion = (String)attributes.get("descripcion");

		if (descripcion != null) {
			setDescripcion(descripcion);
		}

		Long preguntaId = (Long)attributes.get("preguntaId");

		if (preguntaId != null) {
			setPreguntaId(preguntaId);
		}

		Integer respuestaSeleccionada = (Integer)attributes.get(
				"respuestaSeleccionada");

		if (respuestaSeleccionada != null) {
			setRespuestaSeleccionada(respuestaSeleccionada);
		}
	}

	@JSON
	@Override
	public long getDetalleRepsuestaId() {
		return _detalleRepsuestaId;
	}

	@Override
	public void setDetalleRepsuestaId(long detalleRepsuestaId) {
		_detalleRepsuestaId = detalleRepsuestaId;
	}

	@JSON
	@Override
	public long getEvaluacionId() {
		return _evaluacionId;
	}

	@Override
	public void setEvaluacionId(long evaluacionId) {
		_evaluacionId = evaluacionId;
	}

	@JSON
	@Override
	public long getFasePostulacionId() {
		return _fasePostulacionId;
	}

	@Override
	public void setFasePostulacionId(long fasePostulacionId) {
		_fasePostulacionId = fasePostulacionId;
	}

	@JSON
	@Override
	public String getDescripcion() {
		if (_descripcion == null) {
			return StringPool.BLANK;
		}
		else {
			return _descripcion;
		}
	}

	@Override
	public void setDescripcion(String descripcion) {
		_descripcion = descripcion;
	}

	@JSON
	@Override
	public long getPreguntaId() {
		return _preguntaId;
	}

	@Override
	public void setPreguntaId(long preguntaId) {
		_preguntaId = preguntaId;
	}

	@JSON
	@Override
	public int getRespuestaSeleccionada() {
		return _respuestaSeleccionada;
	}

	@Override
	public void setRespuestaSeleccionada(int respuestaSeleccionada) {
		_respuestaSeleccionada = respuestaSeleccionada;
	}

	@Override
	public DetalleRepuestaReclutamiento toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (DetalleRepuestaReclutamiento)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DetalleRepuestaReclutamientoImpl detalleRepuestaReclutamientoImpl = new DetalleRepuestaReclutamientoImpl();

		detalleRepuestaReclutamientoImpl.setDetalleRepsuestaId(getDetalleRepsuestaId());
		detalleRepuestaReclutamientoImpl.setEvaluacionId(getEvaluacionId());
		detalleRepuestaReclutamientoImpl.setFasePostulacionId(getFasePostulacionId());
		detalleRepuestaReclutamientoImpl.setDescripcion(getDescripcion());
		detalleRepuestaReclutamientoImpl.setPreguntaId(getPreguntaId());
		detalleRepuestaReclutamientoImpl.setRespuestaSeleccionada(getRespuestaSeleccionada());

		detalleRepuestaReclutamientoImpl.resetOriginalValues();

		return detalleRepuestaReclutamientoImpl;
	}

	@Override
	public int compareTo(
		DetalleRepuestaReclutamiento detalleRepuestaReclutamiento) {
		DetalleRepuestaReclutamientoPK primaryKey = detalleRepuestaReclutamiento.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof DetalleRepuestaReclutamiento)) {
			return false;
		}

		DetalleRepuestaReclutamiento detalleRepuestaReclutamiento = (DetalleRepuestaReclutamiento)obj;

		DetalleRepuestaReclutamientoPK primaryKey = detalleRepuestaReclutamiento.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<DetalleRepuestaReclutamiento> toCacheModel() {
		DetalleRepuestaReclutamientoCacheModel detalleRepuestaReclutamientoCacheModel =
			new DetalleRepuestaReclutamientoCacheModel();

		detalleRepuestaReclutamientoCacheModel.detalleRepsuestaId = getDetalleRepsuestaId();

		detalleRepuestaReclutamientoCacheModel.evaluacionId = getEvaluacionId();

		detalleRepuestaReclutamientoCacheModel.fasePostulacionId = getFasePostulacionId();

		detalleRepuestaReclutamientoCacheModel.descripcion = getDescripcion();

		String descripcion = detalleRepuestaReclutamientoCacheModel.descripcion;

		if ((descripcion != null) && (descripcion.length() == 0)) {
			detalleRepuestaReclutamientoCacheModel.descripcion = null;
		}

		detalleRepuestaReclutamientoCacheModel.preguntaId = getPreguntaId();

		detalleRepuestaReclutamientoCacheModel.respuestaSeleccionada = getRespuestaSeleccionada();

		return detalleRepuestaReclutamientoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{detalleRepsuestaId=");
		sb.append(getDetalleRepsuestaId());
		sb.append(", evaluacionId=");
		sb.append(getEvaluacionId());
		sb.append(", fasePostulacionId=");
		sb.append(getFasePostulacionId());
		sb.append(", descripcion=");
		sb.append(getDescripcion());
		sb.append(", preguntaId=");
		sb.append(getPreguntaId());
		sb.append(", respuestaSeleccionada=");
		sb.append(getRespuestaSeleccionada());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append("com.hitss.layer.model.DetalleRepuestaReclutamiento");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>detalleRepsuestaId</column-name><column-value><![CDATA[");
		sb.append(getDetalleRepsuestaId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>evaluacionId</column-name><column-value><![CDATA[");
		sb.append(getEvaluacionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fasePostulacionId</column-name><column-value><![CDATA[");
		sb.append(getFasePostulacionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>descripcion</column-name><column-value><![CDATA[");
		sb.append(getDescripcion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>preguntaId</column-name><column-value><![CDATA[");
		sb.append(getPreguntaId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>respuestaSeleccionada</column-name><column-value><![CDATA[");
		sb.append(getRespuestaSeleccionada());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = DetalleRepuestaReclutamiento.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			DetalleRepuestaReclutamiento.class
		};
	private long _detalleRepsuestaId;
	private long _evaluacionId;
	private long _fasePostulacionId;
	private String _descripcion;
	private long _preguntaId;
	private int _respuestaSeleccionada;
	private DetalleRepuestaReclutamiento _escapedModel;
}