/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.hitss.layer.model.impl;

import com.hitss.layer.model.DetalleRepuestaEvaluacion;
import com.hitss.layer.model.DetalleRepuestaEvaluacionModel;
import com.hitss.layer.model.DetalleRepuestaEvaluacionSoap;
import com.hitss.layer.service.persistence.DetalleRepuestaEvaluacionPK;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the DetalleRepuestaEvaluacion service. Represents a row in the &quot;DetalleRepuestaEvaluacion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.hitss.layer.model.DetalleRepuestaEvaluacionModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DetalleRepuestaEvaluacionImpl}.
 * </p>
 *
 * @author Danielle Delgado
 * @see DetalleRepuestaEvaluacionImpl
 * @see com.hitss.layer.model.DetalleRepuestaEvaluacion
 * @see com.hitss.layer.model.DetalleRepuestaEvaluacionModel
 * @generated
 */
@JSON(strict = true)
public class DetalleRepuestaEvaluacionModelImpl extends BaseModelImpl<DetalleRepuestaEvaluacion>
	implements DetalleRepuestaEvaluacionModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a detalle repuesta evaluacion model instance should use the {@link com.hitss.layer.model.DetalleRepuestaEvaluacion} interface instead.
	 */
	public static final String TABLE_NAME = "DetalleRepuestaEvaluacion";
	public static final Object[][] TABLE_COLUMNS = {
			{ "detalleRepuestaEvaluacionId", Types.BIGINT },
			{ "evaluacionId", Types.BIGINT },
			{ "usuarioId", Types.BIGINT },
			{ "descripcion", Types.VARCHAR },
			{ "preguntaId", Types.BIGINT },
			{ "respuestaSeleccionada", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table DetalleRepuestaEvaluacion (detalleRepuestaEvaluacionId LONG not null,evaluacionId LONG not null,usuarioId LONG not null,descripcion VARCHAR(75) null,preguntaId LONG,respuestaSeleccionada LONG,primary key (detalleRepuestaEvaluacionId, evaluacionId, usuarioId))";
	public static final String TABLE_SQL_DROP = "drop table DetalleRepuestaEvaluacion";
	public static final String ORDER_BY_JPQL = " ORDER BY detalleRepuestaEvaluacion.id.detalleRepuestaEvaluacionId ASC, detalleRepuestaEvaluacion.id.evaluacionId ASC, detalleRepuestaEvaluacion.id.usuarioId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY DetalleRepuestaEvaluacion.detalleRepuestaEvaluacionId ASC, DetalleRepuestaEvaluacion.evaluacionId ASC, DetalleRepuestaEvaluacion.usuarioId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.hitss.layer.model.DetalleRepuestaEvaluacion"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.hitss.layer.model.DetalleRepuestaEvaluacion"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static DetalleRepuestaEvaluacion toModel(
		DetalleRepuestaEvaluacionSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		DetalleRepuestaEvaluacion model = new DetalleRepuestaEvaluacionImpl();

		model.setDetalleRepuestaEvaluacionId(soapModel.getDetalleRepuestaEvaluacionId());
		model.setEvaluacionId(soapModel.getEvaluacionId());
		model.setUsuarioId(soapModel.getUsuarioId());
		model.setDescripcion(soapModel.getDescripcion());
		model.setPreguntaId(soapModel.getPreguntaId());
		model.setRespuestaSeleccionada(soapModel.getRespuestaSeleccionada());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<DetalleRepuestaEvaluacion> toModels(
		DetalleRepuestaEvaluacionSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<DetalleRepuestaEvaluacion> models = new ArrayList<DetalleRepuestaEvaluacion>(soapModels.length);

		for (DetalleRepuestaEvaluacionSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.hitss.layer.model.DetalleRepuestaEvaluacion"));

	public DetalleRepuestaEvaluacionModelImpl() {
	}

	@Override
	public DetalleRepuestaEvaluacionPK getPrimaryKey() {
		return new DetalleRepuestaEvaluacionPK(_detalleRepuestaEvaluacionId,
			_evaluacionId, _usuarioId);
	}

	@Override
	public void setPrimaryKey(DetalleRepuestaEvaluacionPK primaryKey) {
		setDetalleRepuestaEvaluacionId(primaryKey.detalleRepuestaEvaluacionId);
		setEvaluacionId(primaryKey.evaluacionId);
		setUsuarioId(primaryKey.usuarioId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new DetalleRepuestaEvaluacionPK(_detalleRepuestaEvaluacionId,
			_evaluacionId, _usuarioId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((DetalleRepuestaEvaluacionPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return DetalleRepuestaEvaluacion.class;
	}

	@Override
	public String getModelClassName() {
		return DetalleRepuestaEvaluacion.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("detalleRepuestaEvaluacionId",
			getDetalleRepuestaEvaluacionId());
		attributes.put("evaluacionId", getEvaluacionId());
		attributes.put("usuarioId", getUsuarioId());
		attributes.put("descripcion", getDescripcion());
		attributes.put("preguntaId", getPreguntaId());
		attributes.put("respuestaSeleccionada", getRespuestaSeleccionada());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long detalleRepuestaEvaluacionId = (Long)attributes.get(
				"detalleRepuestaEvaluacionId");

		if (detalleRepuestaEvaluacionId != null) {
			setDetalleRepuestaEvaluacionId(detalleRepuestaEvaluacionId);
		}

		Long evaluacionId = (Long)attributes.get("evaluacionId");

		if (evaluacionId != null) {
			setEvaluacionId(evaluacionId);
		}

		Long usuarioId = (Long)attributes.get("usuarioId");

		if (usuarioId != null) {
			setUsuarioId(usuarioId);
		}

		String descripcion = (String)attributes.get("descripcion");

		if (descripcion != null) {
			setDescripcion(descripcion);
		}

		Long preguntaId = (Long)attributes.get("preguntaId");

		if (preguntaId != null) {
			setPreguntaId(preguntaId);
		}

		Long respuestaSeleccionada = (Long)attributes.get(
				"respuestaSeleccionada");

		if (respuestaSeleccionada != null) {
			setRespuestaSeleccionada(respuestaSeleccionada);
		}
	}

	@JSON
	@Override
	public long getDetalleRepuestaEvaluacionId() {
		return _detalleRepuestaEvaluacionId;
	}

	@Override
	public void setDetalleRepuestaEvaluacionId(long detalleRepuestaEvaluacionId) {
		_detalleRepuestaEvaluacionId = detalleRepuestaEvaluacionId;
	}

	@JSON
	@Override
	public long getEvaluacionId() {
		return _evaluacionId;
	}

	@Override
	public void setEvaluacionId(long evaluacionId) {
		_evaluacionId = evaluacionId;
	}

	@JSON
	@Override
	public long getUsuarioId() {
		return _usuarioId;
	}

	@Override
	public void setUsuarioId(long usuarioId) {
		_usuarioId = usuarioId;
	}

	@JSON
	@Override
	public String getDescripcion() {
		if (_descripcion == null) {
			return StringPool.BLANK;
		}
		else {
			return _descripcion;
		}
	}

	@Override
	public void setDescripcion(String descripcion) {
		_descripcion = descripcion;
	}

	@JSON
	@Override
	public long getPreguntaId() {
		return _preguntaId;
	}

	@Override
	public void setPreguntaId(long preguntaId) {
		_preguntaId = preguntaId;
	}

	@JSON
	@Override
	public long getRespuestaSeleccionada() {
		return _respuestaSeleccionada;
	}

	@Override
	public void setRespuestaSeleccionada(long respuestaSeleccionada) {
		_respuestaSeleccionada = respuestaSeleccionada;
	}

	@Override
	public DetalleRepuestaEvaluacion toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (DetalleRepuestaEvaluacion)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DetalleRepuestaEvaluacionImpl detalleRepuestaEvaluacionImpl = new DetalleRepuestaEvaluacionImpl();

		detalleRepuestaEvaluacionImpl.setDetalleRepuestaEvaluacionId(getDetalleRepuestaEvaluacionId());
		detalleRepuestaEvaluacionImpl.setEvaluacionId(getEvaluacionId());
		detalleRepuestaEvaluacionImpl.setUsuarioId(getUsuarioId());
		detalleRepuestaEvaluacionImpl.setDescripcion(getDescripcion());
		detalleRepuestaEvaluacionImpl.setPreguntaId(getPreguntaId());
		detalleRepuestaEvaluacionImpl.setRespuestaSeleccionada(getRespuestaSeleccionada());

		detalleRepuestaEvaluacionImpl.resetOriginalValues();

		return detalleRepuestaEvaluacionImpl;
	}

	@Override
	public int compareTo(DetalleRepuestaEvaluacion detalleRepuestaEvaluacion) {
		DetalleRepuestaEvaluacionPK primaryKey = detalleRepuestaEvaluacion.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof DetalleRepuestaEvaluacion)) {
			return false;
		}

		DetalleRepuestaEvaluacion detalleRepuestaEvaluacion = (DetalleRepuestaEvaluacion)obj;

		DetalleRepuestaEvaluacionPK primaryKey = detalleRepuestaEvaluacion.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<DetalleRepuestaEvaluacion> toCacheModel() {
		DetalleRepuestaEvaluacionCacheModel detalleRepuestaEvaluacionCacheModel = new DetalleRepuestaEvaluacionCacheModel();

		detalleRepuestaEvaluacionCacheModel.detalleRepuestaEvaluacionId = getDetalleRepuestaEvaluacionId();

		detalleRepuestaEvaluacionCacheModel.evaluacionId = getEvaluacionId();

		detalleRepuestaEvaluacionCacheModel.usuarioId = getUsuarioId();

		detalleRepuestaEvaluacionCacheModel.descripcion = getDescripcion();

		String descripcion = detalleRepuestaEvaluacionCacheModel.descripcion;

		if ((descripcion != null) && (descripcion.length() == 0)) {
			detalleRepuestaEvaluacionCacheModel.descripcion = null;
		}

		detalleRepuestaEvaluacionCacheModel.preguntaId = getPreguntaId();

		detalleRepuestaEvaluacionCacheModel.respuestaSeleccionada = getRespuestaSeleccionada();

		return detalleRepuestaEvaluacionCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{detalleRepuestaEvaluacionId=");
		sb.append(getDetalleRepuestaEvaluacionId());
		sb.append(", evaluacionId=");
		sb.append(getEvaluacionId());
		sb.append(", usuarioId=");
		sb.append(getUsuarioId());
		sb.append(", descripcion=");
		sb.append(getDescripcion());
		sb.append(", preguntaId=");
		sb.append(getPreguntaId());
		sb.append(", respuestaSeleccionada=");
		sb.append(getRespuestaSeleccionada());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append("com.hitss.layer.model.DetalleRepuestaEvaluacion");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>detalleRepuestaEvaluacionId</column-name><column-value><![CDATA[");
		sb.append(getDetalleRepuestaEvaluacionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>evaluacionId</column-name><column-value><![CDATA[");
		sb.append(getEvaluacionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>usuarioId</column-name><column-value><![CDATA[");
		sb.append(getUsuarioId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>descripcion</column-name><column-value><![CDATA[");
		sb.append(getDescripcion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>preguntaId</column-name><column-value><![CDATA[");
		sb.append(getPreguntaId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>respuestaSeleccionada</column-name><column-value><![CDATA[");
		sb.append(getRespuestaSeleccionada());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = DetalleRepuestaEvaluacion.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			DetalleRepuestaEvaluacion.class
		};
	private long _detalleRepuestaEvaluacionId;
	private long _evaluacionId;
	private long _usuarioId;
	private String _descripcion;
	private long _preguntaId;
	private long _respuestaSeleccionada;
	private DetalleRepuestaEvaluacion _escapedModel;
}