/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.hitss.layer.model.impl;

import com.hitss.layer.model.FasePostulacionPuestoEvaluacion;
import com.hitss.layer.model.FasePostulacionPuestoEvaluacionModel;
import com.hitss.layer.model.FasePostulacionPuestoEvaluacionSoap;
import com.hitss.layer.service.persistence.FasePostulacionPuestoEvaluacionPK;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the FasePostulacionPuestoEvaluacion service. Represents a row in the &quot;FasePostulacionPuestoEvaluacion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.hitss.layer.model.FasePostulacionPuestoEvaluacionModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FasePostulacionPuestoEvaluacionImpl}.
 * </p>
 *
 * @author Danielle Delgado
 * @see FasePostulacionPuestoEvaluacionImpl
 * @see com.hitss.layer.model.FasePostulacionPuestoEvaluacion
 * @see com.hitss.layer.model.FasePostulacionPuestoEvaluacionModel
 * @generated
 */
@JSON(strict = true)
public class FasePostulacionPuestoEvaluacionModelImpl extends BaseModelImpl<FasePostulacionPuestoEvaluacion>
	implements FasePostulacionPuestoEvaluacionModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a fase postulacion puesto evaluacion model instance should use the {@link com.hitss.layer.model.FasePostulacionPuestoEvaluacion} interface instead.
	 */
	public static final String TABLE_NAME = "FasePostulacionPuestoEvaluacion";
	public static final Object[][] TABLE_COLUMNS = {
			{ "fasePostulacionId", Types.BIGINT },
			{ "solicitudFuncionId", Types.BIGINT },
			{ "evaluacionId", Types.BIGINT },
			{ "resultado", Types.DOUBLE }
		};
	public static final String TABLE_SQL_CREATE = "create table FasePostulacionPuestoEvaluacion (fasePostulacionId LONG not null,solicitudFuncionId LONG not null,evaluacionId LONG not null,resultado DOUBLE,primary key (fasePostulacionId, solicitudFuncionId, evaluacionId))";
	public static final String TABLE_SQL_DROP = "drop table FasePostulacionPuestoEvaluacion";
	public static final String ORDER_BY_JPQL = " ORDER BY fasePostulacionPuestoEvaluacion.id.fasePostulacionId ASC, fasePostulacionPuestoEvaluacion.id.solicitudFuncionId ASC, fasePostulacionPuestoEvaluacion.id.evaluacionId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY FasePostulacionPuestoEvaluacion.fasePostulacionId ASC, FasePostulacionPuestoEvaluacion.solicitudFuncionId ASC, FasePostulacionPuestoEvaluacion.evaluacionId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.hitss.layer.model.FasePostulacionPuestoEvaluacion"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.hitss.layer.model.FasePostulacionPuestoEvaluacion"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.hitss.layer.model.FasePostulacionPuestoEvaluacion"),
			true);
	public static long EVALUACIONID_COLUMN_BITMASK = 1L;
	public static long FASEPOSTULACIONID_COLUMN_BITMASK = 2L;
	public static long SOLICITUDFUNCIONID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static FasePostulacionPuestoEvaluacion toModel(
		FasePostulacionPuestoEvaluacionSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		FasePostulacionPuestoEvaluacion model = new FasePostulacionPuestoEvaluacionImpl();

		model.setFasePostulacionId(soapModel.getFasePostulacionId());
		model.setSolicitudFuncionId(soapModel.getSolicitudFuncionId());
		model.setEvaluacionId(soapModel.getEvaluacionId());
		model.setResultado(soapModel.getResultado());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<FasePostulacionPuestoEvaluacion> toModels(
		FasePostulacionPuestoEvaluacionSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<FasePostulacionPuestoEvaluacion> models = new ArrayList<FasePostulacionPuestoEvaluacion>(soapModels.length);

		for (FasePostulacionPuestoEvaluacionSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.hitss.layer.model.FasePostulacionPuestoEvaluacion"));

	public FasePostulacionPuestoEvaluacionModelImpl() {
	}

	@Override
	public FasePostulacionPuestoEvaluacionPK getPrimaryKey() {
		return new FasePostulacionPuestoEvaluacionPK(_fasePostulacionId,
			_solicitudFuncionId, _evaluacionId);
	}

	@Override
	public void setPrimaryKey(FasePostulacionPuestoEvaluacionPK primaryKey) {
		setFasePostulacionId(primaryKey.fasePostulacionId);
		setSolicitudFuncionId(primaryKey.solicitudFuncionId);
		setEvaluacionId(primaryKey.evaluacionId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new FasePostulacionPuestoEvaluacionPK(_fasePostulacionId,
			_solicitudFuncionId, _evaluacionId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((FasePostulacionPuestoEvaluacionPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return FasePostulacionPuestoEvaluacion.class;
	}

	@Override
	public String getModelClassName() {
		return FasePostulacionPuestoEvaluacion.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("fasePostulacionId", getFasePostulacionId());
		attributes.put("solicitudFuncionId", getSolicitudFuncionId());
		attributes.put("evaluacionId", getEvaluacionId());
		attributes.put("resultado", getResultado());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long fasePostulacionId = (Long)attributes.get("fasePostulacionId");

		if (fasePostulacionId != null) {
			setFasePostulacionId(fasePostulacionId);
		}

		Long solicitudFuncionId = (Long)attributes.get("solicitudFuncionId");

		if (solicitudFuncionId != null) {
			setSolicitudFuncionId(solicitudFuncionId);
		}

		Long evaluacionId = (Long)attributes.get("evaluacionId");

		if (evaluacionId != null) {
			setEvaluacionId(evaluacionId);
		}

		Double resultado = (Double)attributes.get("resultado");

		if (resultado != null) {
			setResultado(resultado);
		}
	}

	@JSON
	@Override
	public long getFasePostulacionId() {
		return _fasePostulacionId;
	}

	@Override
	public void setFasePostulacionId(long fasePostulacionId) {
		_columnBitmask |= FASEPOSTULACIONID_COLUMN_BITMASK;

		if (!_setOriginalFasePostulacionId) {
			_setOriginalFasePostulacionId = true;

			_originalFasePostulacionId = _fasePostulacionId;
		}

		_fasePostulacionId = fasePostulacionId;
	}

	public long getOriginalFasePostulacionId() {
		return _originalFasePostulacionId;
	}

	@JSON
	@Override
	public long getSolicitudFuncionId() {
		return _solicitudFuncionId;
	}

	@Override
	public void setSolicitudFuncionId(long solicitudFuncionId) {
		_columnBitmask |= SOLICITUDFUNCIONID_COLUMN_BITMASK;

		if (!_setOriginalSolicitudFuncionId) {
			_setOriginalSolicitudFuncionId = true;

			_originalSolicitudFuncionId = _solicitudFuncionId;
		}

		_solicitudFuncionId = solicitudFuncionId;
	}

	public long getOriginalSolicitudFuncionId() {
		return _originalSolicitudFuncionId;
	}

	@JSON
	@Override
	public long getEvaluacionId() {
		return _evaluacionId;
	}

	@Override
	public void setEvaluacionId(long evaluacionId) {
		_columnBitmask |= EVALUACIONID_COLUMN_BITMASK;

		if (!_setOriginalEvaluacionId) {
			_setOriginalEvaluacionId = true;

			_originalEvaluacionId = _evaluacionId;
		}

		_evaluacionId = evaluacionId;
	}

	public long getOriginalEvaluacionId() {
		return _originalEvaluacionId;
	}

	@JSON
	@Override
	public double getResultado() {
		return _resultado;
	}

	@Override
	public void setResultado(double resultado) {
		_resultado = resultado;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public FasePostulacionPuestoEvaluacion toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (FasePostulacionPuestoEvaluacion)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FasePostulacionPuestoEvaluacionImpl fasePostulacionPuestoEvaluacionImpl = new FasePostulacionPuestoEvaluacionImpl();

		fasePostulacionPuestoEvaluacionImpl.setFasePostulacionId(getFasePostulacionId());
		fasePostulacionPuestoEvaluacionImpl.setSolicitudFuncionId(getSolicitudFuncionId());
		fasePostulacionPuestoEvaluacionImpl.setEvaluacionId(getEvaluacionId());
		fasePostulacionPuestoEvaluacionImpl.setResultado(getResultado());

		fasePostulacionPuestoEvaluacionImpl.resetOriginalValues();

		return fasePostulacionPuestoEvaluacionImpl;
	}

	@Override
	public int compareTo(
		FasePostulacionPuestoEvaluacion fasePostulacionPuestoEvaluacion) {
		FasePostulacionPuestoEvaluacionPK primaryKey = fasePostulacionPuestoEvaluacion.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof FasePostulacionPuestoEvaluacion)) {
			return false;
		}

		FasePostulacionPuestoEvaluacion fasePostulacionPuestoEvaluacion = (FasePostulacionPuestoEvaluacion)obj;

		FasePostulacionPuestoEvaluacionPK primaryKey = fasePostulacionPuestoEvaluacion.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
		FasePostulacionPuestoEvaluacionModelImpl fasePostulacionPuestoEvaluacionModelImpl =
			this;

		fasePostulacionPuestoEvaluacionModelImpl._originalFasePostulacionId = fasePostulacionPuestoEvaluacionModelImpl._fasePostulacionId;

		fasePostulacionPuestoEvaluacionModelImpl._setOriginalFasePostulacionId = false;

		fasePostulacionPuestoEvaluacionModelImpl._originalSolicitudFuncionId = fasePostulacionPuestoEvaluacionModelImpl._solicitudFuncionId;

		fasePostulacionPuestoEvaluacionModelImpl._setOriginalSolicitudFuncionId = false;

		fasePostulacionPuestoEvaluacionModelImpl._originalEvaluacionId = fasePostulacionPuestoEvaluacionModelImpl._evaluacionId;

		fasePostulacionPuestoEvaluacionModelImpl._setOriginalEvaluacionId = false;

		fasePostulacionPuestoEvaluacionModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<FasePostulacionPuestoEvaluacion> toCacheModel() {
		FasePostulacionPuestoEvaluacionCacheModel fasePostulacionPuestoEvaluacionCacheModel =
			new FasePostulacionPuestoEvaluacionCacheModel();

		fasePostulacionPuestoEvaluacionCacheModel.fasePostulacionId = getFasePostulacionId();

		fasePostulacionPuestoEvaluacionCacheModel.solicitudFuncionId = getSolicitudFuncionId();

		fasePostulacionPuestoEvaluacionCacheModel.evaluacionId = getEvaluacionId();

		fasePostulacionPuestoEvaluacionCacheModel.resultado = getResultado();

		return fasePostulacionPuestoEvaluacionCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{fasePostulacionId=");
		sb.append(getFasePostulacionId());
		sb.append(", solicitudFuncionId=");
		sb.append(getSolicitudFuncionId());
		sb.append(", evaluacionId=");
		sb.append(getEvaluacionId());
		sb.append(", resultado=");
		sb.append(getResultado());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.hitss.layer.model.FasePostulacionPuestoEvaluacion");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>fasePostulacionId</column-name><column-value><![CDATA[");
		sb.append(getFasePostulacionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>solicitudFuncionId</column-name><column-value><![CDATA[");
		sb.append(getSolicitudFuncionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>evaluacionId</column-name><column-value><![CDATA[");
		sb.append(getEvaluacionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>resultado</column-name><column-value><![CDATA[");
		sb.append(getResultado());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = FasePostulacionPuestoEvaluacion.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			FasePostulacionPuestoEvaluacion.class
		};
	private long _fasePostulacionId;
	private long _originalFasePostulacionId;
	private boolean _setOriginalFasePostulacionId;
	private long _solicitudFuncionId;
	private long _originalSolicitudFuncionId;
	private boolean _setOriginalSolicitudFuncionId;
	private long _evaluacionId;
	private long _originalEvaluacionId;
	private boolean _setOriginalEvaluacionId;
	private double _resultado;
	private long _columnBitmask;
	private FasePostulacionPuestoEvaluacion _escapedModel;
}