/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.hitss.layer.model.impl;

import com.hitss.layer.model.FichaIngreso;
import com.hitss.layer.model.FichaIngresoModel;
import com.hitss.layer.model.FichaIngresoSoap;
import com.hitss.layer.service.persistence.FichaIngresoPK;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.util.PortalUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the FichaIngreso service. Represents a row in the &quot;FichaIngreso&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.hitss.layer.model.FichaIngresoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FichaIngresoImpl}.
 * </p>
 *
 * @author Danielle Delgado
 * @see FichaIngresoImpl
 * @see com.hitss.layer.model.FichaIngreso
 * @see com.hitss.layer.model.FichaIngresoModel
 * @generated
 */
@JSON(strict = true)
public class FichaIngresoModelImpl extends BaseModelImpl<FichaIngreso>
	implements FichaIngresoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ficha ingreso model instance should use the {@link com.hitss.layer.model.FichaIngreso} interface instead.
	 */
	public static final String TABLE_NAME = "FichaIngreso";
	public static final Object[][] TABLE_COLUMNS = {
			{ "fichaingresoId", Types.BIGINT },
			{ "solicitudRequerimientoId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "requieroEquipoTecnico", Types.BOOLEAN },
			{ "reemplazo", Types.BOOLEAN },
			{ "aprobacionFichaIngresoCapitalHumano", Types.BOOLEAN },
			{ "aprobacionFichaIngresoOperaciones", Types.BOOLEAN },
			{ "activo", Types.BOOLEAN },
			{ "usuariocrea", Types.BIGINT },
			{ "fechacrea", Types.TIMESTAMP },
			{ "usuariomodifica", Types.BIGINT },
			{ "fechamodifica", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table FichaIngreso (fichaingresoId LONG not null,solicitudRequerimientoId LONG not null,userId LONG,requieroEquipoTecnico BOOLEAN,reemplazo BOOLEAN,aprobacionFichaIngresoCapitalHumano BOOLEAN,aprobacionFichaIngresoOperaciones BOOLEAN,activo BOOLEAN,usuariocrea LONG,fechacrea DATE null,usuariomodifica LONG,fechamodifica DATE null,primary key (fichaingresoId, solicitudRequerimientoId))";
	public static final String TABLE_SQL_DROP = "drop table FichaIngreso";
	public static final String ORDER_BY_JPQL = " ORDER BY fichaIngreso.fechamodifica ASC";
	public static final String ORDER_BY_SQL = " ORDER BY FichaIngreso.fechamodifica ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.hitss.layer.model.FichaIngreso"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.hitss.layer.model.FichaIngreso"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static FichaIngreso toModel(FichaIngresoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		FichaIngreso model = new FichaIngresoImpl();

		model.setFichaingresoId(soapModel.getFichaingresoId());
		model.setSolicitudRequerimientoId(soapModel.getSolicitudRequerimientoId());
		model.setUserId(soapModel.getUserId());
		model.setRequieroEquipoTecnico(soapModel.getRequieroEquipoTecnico());
		model.setReemplazo(soapModel.getReemplazo());
		model.setAprobacionFichaIngresoCapitalHumano(soapModel.getAprobacionFichaIngresoCapitalHumano());
		model.setAprobacionFichaIngresoOperaciones(soapModel.getAprobacionFichaIngresoOperaciones());
		model.setActivo(soapModel.getActivo());
		model.setUsuariocrea(soapModel.getUsuariocrea());
		model.setFechacrea(soapModel.getFechacrea());
		model.setUsuariomodifica(soapModel.getUsuariomodifica());
		model.setFechamodifica(soapModel.getFechamodifica());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<FichaIngreso> toModels(FichaIngresoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<FichaIngreso> models = new ArrayList<FichaIngreso>(soapModels.length);

		for (FichaIngresoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.hitss.layer.model.FichaIngreso"));

	public FichaIngresoModelImpl() {
	}

	@Override
	public FichaIngresoPK getPrimaryKey() {
		return new FichaIngresoPK(_fichaingresoId, _solicitudRequerimientoId);
	}

	@Override
	public void setPrimaryKey(FichaIngresoPK primaryKey) {
		setFichaingresoId(primaryKey.fichaingresoId);
		setSolicitudRequerimientoId(primaryKey.solicitudRequerimientoId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new FichaIngresoPK(_fichaingresoId, _solicitudRequerimientoId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((FichaIngresoPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return FichaIngreso.class;
	}

	@Override
	public String getModelClassName() {
		return FichaIngreso.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("fichaingresoId", getFichaingresoId());
		attributes.put("solicitudRequerimientoId", getSolicitudRequerimientoId());
		attributes.put("userId", getUserId());
		attributes.put("requieroEquipoTecnico", getRequieroEquipoTecnico());
		attributes.put("reemplazo", getReemplazo());
		attributes.put("aprobacionFichaIngresoCapitalHumano",
			getAprobacionFichaIngresoCapitalHumano());
		attributes.put("aprobacionFichaIngresoOperaciones",
			getAprobacionFichaIngresoOperaciones());
		attributes.put("activo", getActivo());
		attributes.put("usuariocrea", getUsuariocrea());
		attributes.put("fechacrea", getFechacrea());
		attributes.put("usuariomodifica", getUsuariomodifica());
		attributes.put("fechamodifica", getFechamodifica());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long fichaingresoId = (Long)attributes.get("fichaingresoId");

		if (fichaingresoId != null) {
			setFichaingresoId(fichaingresoId);
		}

		Long solicitudRequerimientoId = (Long)attributes.get(
				"solicitudRequerimientoId");

		if (solicitudRequerimientoId != null) {
			setSolicitudRequerimientoId(solicitudRequerimientoId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Boolean requieroEquipoTecnico = (Boolean)attributes.get(
				"requieroEquipoTecnico");

		if (requieroEquipoTecnico != null) {
			setRequieroEquipoTecnico(requieroEquipoTecnico);
		}

		Boolean reemplazo = (Boolean)attributes.get("reemplazo");

		if (reemplazo != null) {
			setReemplazo(reemplazo);
		}

		Boolean aprobacionFichaIngresoCapitalHumano = (Boolean)attributes.get(
				"aprobacionFichaIngresoCapitalHumano");

		if (aprobacionFichaIngresoCapitalHumano != null) {
			setAprobacionFichaIngresoCapitalHumano(aprobacionFichaIngresoCapitalHumano);
		}

		Boolean aprobacionFichaIngresoOperaciones = (Boolean)attributes.get(
				"aprobacionFichaIngresoOperaciones");

		if (aprobacionFichaIngresoOperaciones != null) {
			setAprobacionFichaIngresoOperaciones(aprobacionFichaIngresoOperaciones);
		}

		Boolean activo = (Boolean)attributes.get("activo");

		if (activo != null) {
			setActivo(activo);
		}

		Long usuariocrea = (Long)attributes.get("usuariocrea");

		if (usuariocrea != null) {
			setUsuariocrea(usuariocrea);
		}

		Date fechacrea = (Date)attributes.get("fechacrea");

		if (fechacrea != null) {
			setFechacrea(fechacrea);
		}

		Long usuariomodifica = (Long)attributes.get("usuariomodifica");

		if (usuariomodifica != null) {
			setUsuariomodifica(usuariomodifica);
		}

		Date fechamodifica = (Date)attributes.get("fechamodifica");

		if (fechamodifica != null) {
			setFechamodifica(fechamodifica);
		}
	}

	@JSON
	@Override
	public long getFichaingresoId() {
		return _fichaingresoId;
	}

	@Override
	public void setFichaingresoId(long fichaingresoId) {
		_fichaingresoId = fichaingresoId;
	}

	@JSON
	@Override
	public long getSolicitudRequerimientoId() {
		return _solicitudRequerimientoId;
	}

	@Override
	public void setSolicitudRequerimientoId(long solicitudRequerimientoId) {
		_solicitudRequerimientoId = solicitudRequerimientoId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public boolean getRequieroEquipoTecnico() {
		return _requieroEquipoTecnico;
	}

	@Override
	public boolean isRequieroEquipoTecnico() {
		return _requieroEquipoTecnico;
	}

	@Override
	public void setRequieroEquipoTecnico(boolean requieroEquipoTecnico) {
		_requieroEquipoTecnico = requieroEquipoTecnico;
	}

	@JSON
	@Override
	public boolean getReemplazo() {
		return _reemplazo;
	}

	@Override
	public boolean isReemplazo() {
		return _reemplazo;
	}

	@Override
	public void setReemplazo(boolean reemplazo) {
		_reemplazo = reemplazo;
	}

	@JSON
	@Override
	public boolean getAprobacionFichaIngresoCapitalHumano() {
		return _aprobacionFichaIngresoCapitalHumano;
	}

	@Override
	public boolean isAprobacionFichaIngresoCapitalHumano() {
		return _aprobacionFichaIngresoCapitalHumano;
	}

	@Override
	public void setAprobacionFichaIngresoCapitalHumano(
		boolean aprobacionFichaIngresoCapitalHumano) {
		_aprobacionFichaIngresoCapitalHumano = aprobacionFichaIngresoCapitalHumano;
	}

	@JSON
	@Override
	public boolean getAprobacionFichaIngresoOperaciones() {
		return _aprobacionFichaIngresoOperaciones;
	}

	@Override
	public boolean isAprobacionFichaIngresoOperaciones() {
		return _aprobacionFichaIngresoOperaciones;
	}

	@Override
	public void setAprobacionFichaIngresoOperaciones(
		boolean aprobacionFichaIngresoOperaciones) {
		_aprobacionFichaIngresoOperaciones = aprobacionFichaIngresoOperaciones;
	}

	@JSON
	@Override
	public boolean getActivo() {
		return _activo;
	}

	@Override
	public boolean isActivo() {
		return _activo;
	}

	@Override
	public void setActivo(boolean activo) {
		_activo = activo;
	}

	@JSON
	@Override
	public long getUsuariocrea() {
		return _usuariocrea;
	}

	@Override
	public void setUsuariocrea(long usuariocrea) {
		_usuariocrea = usuariocrea;
	}

	@JSON
	@Override
	public Date getFechacrea() {
		return _fechacrea;
	}

	@Override
	public void setFechacrea(Date fechacrea) {
		_fechacrea = fechacrea;
	}

	@JSON
	@Override
	public long getUsuariomodifica() {
		return _usuariomodifica;
	}

	@Override
	public void setUsuariomodifica(long usuariomodifica) {
		_usuariomodifica = usuariomodifica;
	}

	@JSON
	@Override
	public Date getFechamodifica() {
		return _fechamodifica;
	}

	@Override
	public void setFechamodifica(Date fechamodifica) {
		_fechamodifica = fechamodifica;
	}

	@Override
	public FichaIngreso toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (FichaIngreso)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FichaIngresoImpl fichaIngresoImpl = new FichaIngresoImpl();

		fichaIngresoImpl.setFichaingresoId(getFichaingresoId());
		fichaIngresoImpl.setSolicitudRequerimientoId(getSolicitudRequerimientoId());
		fichaIngresoImpl.setUserId(getUserId());
		fichaIngresoImpl.setRequieroEquipoTecnico(getRequieroEquipoTecnico());
		fichaIngresoImpl.setReemplazo(getReemplazo());
		fichaIngresoImpl.setAprobacionFichaIngresoCapitalHumano(getAprobacionFichaIngresoCapitalHumano());
		fichaIngresoImpl.setAprobacionFichaIngresoOperaciones(getAprobacionFichaIngresoOperaciones());
		fichaIngresoImpl.setActivo(getActivo());
		fichaIngresoImpl.setUsuariocrea(getUsuariocrea());
		fichaIngresoImpl.setFechacrea(getFechacrea());
		fichaIngresoImpl.setUsuariomodifica(getUsuariomodifica());
		fichaIngresoImpl.setFechamodifica(getFechamodifica());

		fichaIngresoImpl.resetOriginalValues();

		return fichaIngresoImpl;
	}

	@Override
	public int compareTo(FichaIngreso fichaIngreso) {
		int value = 0;

		value = DateUtil.compareTo(getFechamodifica(),
				fichaIngreso.getFechamodifica());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof FichaIngreso)) {
			return false;
		}

		FichaIngreso fichaIngreso = (FichaIngreso)obj;

		FichaIngresoPK primaryKey = fichaIngreso.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<FichaIngreso> toCacheModel() {
		FichaIngresoCacheModel fichaIngresoCacheModel = new FichaIngresoCacheModel();

		fichaIngresoCacheModel.fichaingresoId = getFichaingresoId();

		fichaIngresoCacheModel.solicitudRequerimientoId = getSolicitudRequerimientoId();

		fichaIngresoCacheModel.userId = getUserId();

		fichaIngresoCacheModel.requieroEquipoTecnico = getRequieroEquipoTecnico();

		fichaIngresoCacheModel.reemplazo = getReemplazo();

		fichaIngresoCacheModel.aprobacionFichaIngresoCapitalHumano = getAprobacionFichaIngresoCapitalHumano();

		fichaIngresoCacheModel.aprobacionFichaIngresoOperaciones = getAprobacionFichaIngresoOperaciones();

		fichaIngresoCacheModel.activo = getActivo();

		fichaIngresoCacheModel.usuariocrea = getUsuariocrea();

		Date fechacrea = getFechacrea();

		if (fechacrea != null) {
			fichaIngresoCacheModel.fechacrea = fechacrea.getTime();
		}
		else {
			fichaIngresoCacheModel.fechacrea = Long.MIN_VALUE;
		}

		fichaIngresoCacheModel.usuariomodifica = getUsuariomodifica();

		Date fechamodifica = getFechamodifica();

		if (fechamodifica != null) {
			fichaIngresoCacheModel.fechamodifica = fechamodifica.getTime();
		}
		else {
			fichaIngresoCacheModel.fechamodifica = Long.MIN_VALUE;
		}

		return fichaIngresoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(25);

		sb.append("{fichaingresoId=");
		sb.append(getFichaingresoId());
		sb.append(", solicitudRequerimientoId=");
		sb.append(getSolicitudRequerimientoId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", requieroEquipoTecnico=");
		sb.append(getRequieroEquipoTecnico());
		sb.append(", reemplazo=");
		sb.append(getReemplazo());
		sb.append(", aprobacionFichaIngresoCapitalHumano=");
		sb.append(getAprobacionFichaIngresoCapitalHumano());
		sb.append(", aprobacionFichaIngresoOperaciones=");
		sb.append(getAprobacionFichaIngresoOperaciones());
		sb.append(", activo=");
		sb.append(getActivo());
		sb.append(", usuariocrea=");
		sb.append(getUsuariocrea());
		sb.append(", fechacrea=");
		sb.append(getFechacrea());
		sb.append(", usuariomodifica=");
		sb.append(getUsuariomodifica());
		sb.append(", fechamodifica=");
		sb.append(getFechamodifica());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(40);

		sb.append("<model><model-name>");
		sb.append("com.hitss.layer.model.FichaIngreso");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>fichaingresoId</column-name><column-value><![CDATA[");
		sb.append(getFichaingresoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>solicitudRequerimientoId</column-name><column-value><![CDATA[");
		sb.append(getSolicitudRequerimientoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>requieroEquipoTecnico</column-name><column-value><![CDATA[");
		sb.append(getRequieroEquipoTecnico());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>reemplazo</column-name><column-value><![CDATA[");
		sb.append(getReemplazo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>aprobacionFichaIngresoCapitalHumano</column-name><column-value><![CDATA[");
		sb.append(getAprobacionFichaIngresoCapitalHumano());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>aprobacionFichaIngresoOperaciones</column-name><column-value><![CDATA[");
		sb.append(getAprobacionFichaIngresoOperaciones());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>activo</column-name><column-value><![CDATA[");
		sb.append(getActivo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>usuariocrea</column-name><column-value><![CDATA[");
		sb.append(getUsuariocrea());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fechacrea</column-name><column-value><![CDATA[");
		sb.append(getFechacrea());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>usuariomodifica</column-name><column-value><![CDATA[");
		sb.append(getUsuariomodifica());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fechamodifica</column-name><column-value><![CDATA[");
		sb.append(getFechamodifica());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = FichaIngreso.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			FichaIngreso.class
		};
	private long _fichaingresoId;
	private long _solicitudRequerimientoId;
	private long _userId;
	private String _userUuid;
	private boolean _requieroEquipoTecnico;
	private boolean _reemplazo;
	private boolean _aprobacionFichaIngresoCapitalHumano;
	private boolean _aprobacionFichaIngresoOperaciones;
	private boolean _activo;
	private long _usuariocrea;
	private Date _fechacrea;
	private long _usuariomodifica;
	private Date _fechamodifica;
	private FichaIngreso _escapedModel;
}