/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.hitss.layer.model.impl;

import com.hitss.layer.model.Funcion;
import com.hitss.layer.service.FuncionLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Funcion service. Represents a row in the &quot;Funcion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FuncionImpl}.
 * </p>
 *
 * @author Danielle Delgado
 * @see FuncionImpl
 * @see com.hitss.layer.model.Funcion
 * @generated
 */
public abstract class FuncionBaseImpl extends FuncionModelImpl
	implements Funcion {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a funcion model instance should use the {@link Funcion} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			FuncionLocalServiceUtil.addFuncion(this);
		}
		else {
			FuncionLocalServiceUtil.updateFuncion(this);
		}
	}
}