/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.hitss.layer.model.impl;

import com.hitss.layer.model.PuestoEvaluacion;
import com.hitss.layer.model.PuestoEvaluacionModel;
import com.hitss.layer.model.PuestoEvaluacionSoap;
import com.hitss.layer.service.persistence.PuestoEvaluacionPK;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the PuestoEvaluacion service. Represents a row in the &quot;PuestoEvaluacion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.hitss.layer.model.PuestoEvaluacionModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PuestoEvaluacionImpl}.
 * </p>
 *
 * @author Danielle Delgado
 * @see PuestoEvaluacionImpl
 * @see com.hitss.layer.model.PuestoEvaluacion
 * @see com.hitss.layer.model.PuestoEvaluacionModel
 * @generated
 */
@JSON(strict = true)
public class PuestoEvaluacionModelImpl extends BaseModelImpl<PuestoEvaluacion>
	implements PuestoEvaluacionModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a puesto evaluacion model instance should use the {@link com.hitss.layer.model.PuestoEvaluacion} interface instead.
	 */
	public static final String TABLE_NAME = "PuestoEvaluacion";
	public static final Object[][] TABLE_COLUMNS = {
			{ "solicitudFuncionId", Types.BIGINT },
			{ "evaluacionId", Types.BIGINT },
			{ "rangoSuperior", Types.DOUBLE },
			{ "rangoInferior", Types.DOUBLE }
		};
	public static final String TABLE_SQL_CREATE = "create table PuestoEvaluacion (solicitudFuncionId LONG not null,evaluacionId LONG not null,rangoSuperior DOUBLE,rangoInferior DOUBLE,primary key (solicitudFuncionId, evaluacionId))";
	public static final String TABLE_SQL_DROP = "drop table PuestoEvaluacion";
	public static final String ORDER_BY_JPQL = " ORDER BY puestoEvaluacion.id.solicitudFuncionId ASC, puestoEvaluacion.id.evaluacionId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY PuestoEvaluacion.solicitudFuncionId ASC, PuestoEvaluacion.evaluacionId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.hitss.layer.model.PuestoEvaluacion"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.hitss.layer.model.PuestoEvaluacion"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.hitss.layer.model.PuestoEvaluacion"),
			true);
	public static long SOLICITUDFUNCIONID_COLUMN_BITMASK = 1L;
	public static long EVALUACIONID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static PuestoEvaluacion toModel(PuestoEvaluacionSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		PuestoEvaluacion model = new PuestoEvaluacionImpl();

		model.setSolicitudFuncionId(soapModel.getSolicitudFuncionId());
		model.setEvaluacionId(soapModel.getEvaluacionId());
		model.setRangoSuperior(soapModel.getRangoSuperior());
		model.setRangoInferior(soapModel.getRangoInferior());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<PuestoEvaluacion> toModels(
		PuestoEvaluacionSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<PuestoEvaluacion> models = new ArrayList<PuestoEvaluacion>(soapModels.length);

		for (PuestoEvaluacionSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.hitss.layer.model.PuestoEvaluacion"));

	public PuestoEvaluacionModelImpl() {
	}

	@Override
	public PuestoEvaluacionPK getPrimaryKey() {
		return new PuestoEvaluacionPK(_solicitudFuncionId, _evaluacionId);
	}

	@Override
	public void setPrimaryKey(PuestoEvaluacionPK primaryKey) {
		setSolicitudFuncionId(primaryKey.solicitudFuncionId);
		setEvaluacionId(primaryKey.evaluacionId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new PuestoEvaluacionPK(_solicitudFuncionId, _evaluacionId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((PuestoEvaluacionPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return PuestoEvaluacion.class;
	}

	@Override
	public String getModelClassName() {
		return PuestoEvaluacion.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("solicitudFuncionId", getSolicitudFuncionId());
		attributes.put("evaluacionId", getEvaluacionId());
		attributes.put("rangoSuperior", getRangoSuperior());
		attributes.put("rangoInferior", getRangoInferior());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long solicitudFuncionId = (Long)attributes.get("solicitudFuncionId");

		if (solicitudFuncionId != null) {
			setSolicitudFuncionId(solicitudFuncionId);
		}

		Long evaluacionId = (Long)attributes.get("evaluacionId");

		if (evaluacionId != null) {
			setEvaluacionId(evaluacionId);
		}

		Double rangoSuperior = (Double)attributes.get("rangoSuperior");

		if (rangoSuperior != null) {
			setRangoSuperior(rangoSuperior);
		}

		Double rangoInferior = (Double)attributes.get("rangoInferior");

		if (rangoInferior != null) {
			setRangoInferior(rangoInferior);
		}
	}

	@JSON
	@Override
	public long getSolicitudFuncionId() {
		return _solicitudFuncionId;
	}

	@Override
	public void setSolicitudFuncionId(long solicitudFuncionId) {
		_columnBitmask |= SOLICITUDFUNCIONID_COLUMN_BITMASK;

		if (!_setOriginalSolicitudFuncionId) {
			_setOriginalSolicitudFuncionId = true;

			_originalSolicitudFuncionId = _solicitudFuncionId;
		}

		_solicitudFuncionId = solicitudFuncionId;
	}

	public long getOriginalSolicitudFuncionId() {
		return _originalSolicitudFuncionId;
	}

	@JSON
	@Override
	public long getEvaluacionId() {
		return _evaluacionId;
	}

	@Override
	public void setEvaluacionId(long evaluacionId) {
		_evaluacionId = evaluacionId;
	}

	@JSON
	@Override
	public double getRangoSuperior() {
		return _rangoSuperior;
	}

	@Override
	public void setRangoSuperior(double rangoSuperior) {
		_rangoSuperior = rangoSuperior;
	}

	@JSON
	@Override
	public double getRangoInferior() {
		return _rangoInferior;
	}

	@Override
	public void setRangoInferior(double rangoInferior) {
		_rangoInferior = rangoInferior;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public PuestoEvaluacion toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (PuestoEvaluacion)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PuestoEvaluacionImpl puestoEvaluacionImpl = new PuestoEvaluacionImpl();

		puestoEvaluacionImpl.setSolicitudFuncionId(getSolicitudFuncionId());
		puestoEvaluacionImpl.setEvaluacionId(getEvaluacionId());
		puestoEvaluacionImpl.setRangoSuperior(getRangoSuperior());
		puestoEvaluacionImpl.setRangoInferior(getRangoInferior());

		puestoEvaluacionImpl.resetOriginalValues();

		return puestoEvaluacionImpl;
	}

	@Override
	public int compareTo(PuestoEvaluacion puestoEvaluacion) {
		PuestoEvaluacionPK primaryKey = puestoEvaluacion.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof PuestoEvaluacion)) {
			return false;
		}

		PuestoEvaluacion puestoEvaluacion = (PuestoEvaluacion)obj;

		PuestoEvaluacionPK primaryKey = puestoEvaluacion.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
		PuestoEvaluacionModelImpl puestoEvaluacionModelImpl = this;

		puestoEvaluacionModelImpl._originalSolicitudFuncionId = puestoEvaluacionModelImpl._solicitudFuncionId;

		puestoEvaluacionModelImpl._setOriginalSolicitudFuncionId = false;

		puestoEvaluacionModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<PuestoEvaluacion> toCacheModel() {
		PuestoEvaluacionCacheModel puestoEvaluacionCacheModel = new PuestoEvaluacionCacheModel();

		puestoEvaluacionCacheModel.solicitudFuncionId = getSolicitudFuncionId();

		puestoEvaluacionCacheModel.evaluacionId = getEvaluacionId();

		puestoEvaluacionCacheModel.rangoSuperior = getRangoSuperior();

		puestoEvaluacionCacheModel.rangoInferior = getRangoInferior();

		return puestoEvaluacionCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{solicitudFuncionId=");
		sb.append(getSolicitudFuncionId());
		sb.append(", evaluacionId=");
		sb.append(getEvaluacionId());
		sb.append(", rangoSuperior=");
		sb.append(getRangoSuperior());
		sb.append(", rangoInferior=");
		sb.append(getRangoInferior());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.hitss.layer.model.PuestoEvaluacion");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>solicitudFuncionId</column-name><column-value><![CDATA[");
		sb.append(getSolicitudFuncionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>evaluacionId</column-name><column-value><![CDATA[");
		sb.append(getEvaluacionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>rangoSuperior</column-name><column-value><![CDATA[");
		sb.append(getRangoSuperior());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>rangoInferior</column-name><column-value><![CDATA[");
		sb.append(getRangoInferior());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = PuestoEvaluacion.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			PuestoEvaluacion.class
		};
	private long _solicitudFuncionId;
	private long _originalSolicitudFuncionId;
	private boolean _setOriginalSolicitudFuncionId;
	private long _evaluacionId;
	private double _rangoSuperior;
	private double _rangoInferior;
	private long _columnBitmask;
	private PuestoEvaluacion _escapedModel;
}