/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.hitss.layer.model.impl;

import com.hitss.layer.model.SolicitudEvaluacionDesempenno;
import com.hitss.layer.model.SolicitudEvaluacionDesempennoModel;
import com.hitss.layer.model.SolicitudEvaluacionDesempennoSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the SolicitudEvaluacionDesempenno service. Represents a row in the &quot;SolicitudEvaluacionDesempenno&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.hitss.layer.model.SolicitudEvaluacionDesempennoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SolicitudEvaluacionDesempennoImpl}.
 * </p>
 *
 * @author Danielle Delgado
 * @see SolicitudEvaluacionDesempennoImpl
 * @see com.hitss.layer.model.SolicitudEvaluacionDesempenno
 * @see com.hitss.layer.model.SolicitudEvaluacionDesempennoModel
 * @generated
 */
@JSON(strict = true)
public class SolicitudEvaluacionDesempennoModelImpl extends BaseModelImpl<SolicitudEvaluacionDesempenno>
	implements SolicitudEvaluacionDesempennoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a solicitud evaluacion desempenno model instance should use the {@link com.hitss.layer.model.SolicitudEvaluacionDesempenno} interface instead.
	 */
	public static final String TABLE_NAME = "SolicitudEvaluacionDesempenno";
	public static final Object[][] TABLE_COLUMNS = {
			{ "solicitudEvaluacionDesempennoId", Types.BIGINT },
			{ "descripcion", Types.VARCHAR },
			{ "fechaInicio", Types.TIMESTAMP },
			{ "estado", Types.BIGINT },
			{ "activo", Types.BOOLEAN },
			{ "usuariocrea", Types.BIGINT },
			{ "fechacrea", Types.TIMESTAMP },
			{ "usuariomodifica", Types.BIGINT },
			{ "fechamodifica", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table SolicitudEvaluacionDesempenno (solicitudEvaluacionDesempennoId LONG not null primary key,descripcion VARCHAR(75) null,fechaInicio DATE null,estado LONG,activo BOOLEAN,usuariocrea LONG,fechacrea DATE null,usuariomodifica LONG,fechamodifica DATE null)";
	public static final String TABLE_SQL_DROP = "drop table SolicitudEvaluacionDesempenno";
	public static final String ORDER_BY_JPQL = " ORDER BY solicitudEvaluacionDesempenno.fechamodifica ASC";
	public static final String ORDER_BY_SQL = " ORDER BY SolicitudEvaluacionDesempenno.fechamodifica ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.hitss.layer.model.SolicitudEvaluacionDesempenno"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.hitss.layer.model.SolicitudEvaluacionDesempenno"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static SolicitudEvaluacionDesempenno toModel(
		SolicitudEvaluacionDesempennoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		SolicitudEvaluacionDesempenno model = new SolicitudEvaluacionDesempennoImpl();

		model.setSolicitudEvaluacionDesempennoId(soapModel.getSolicitudEvaluacionDesempennoId());
		model.setDescripcion(soapModel.getDescripcion());
		model.setFechaInicio(soapModel.getFechaInicio());
		model.setEstado(soapModel.getEstado());
		model.setActivo(soapModel.getActivo());
		model.setUsuariocrea(soapModel.getUsuariocrea());
		model.setFechacrea(soapModel.getFechacrea());
		model.setUsuariomodifica(soapModel.getUsuariomodifica());
		model.setFechamodifica(soapModel.getFechamodifica());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<SolicitudEvaluacionDesempenno> toModels(
		SolicitudEvaluacionDesempennoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<SolicitudEvaluacionDesempenno> models = new ArrayList<SolicitudEvaluacionDesempenno>(soapModels.length);

		for (SolicitudEvaluacionDesempennoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.hitss.layer.model.SolicitudEvaluacionDesempenno"));

	public SolicitudEvaluacionDesempennoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _solicitudEvaluacionDesempennoId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSolicitudEvaluacionDesempennoId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _solicitudEvaluacionDesempennoId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SolicitudEvaluacionDesempenno.class;
	}

	@Override
	public String getModelClassName() {
		return SolicitudEvaluacionDesempenno.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("solicitudEvaluacionDesempennoId",
			getSolicitudEvaluacionDesempennoId());
		attributes.put("descripcion", getDescripcion());
		attributes.put("fechaInicio", getFechaInicio());
		attributes.put("estado", getEstado());
		attributes.put("activo", getActivo());
		attributes.put("usuariocrea", getUsuariocrea());
		attributes.put("fechacrea", getFechacrea());
		attributes.put("usuariomodifica", getUsuariomodifica());
		attributes.put("fechamodifica", getFechamodifica());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long solicitudEvaluacionDesempennoId = (Long)attributes.get(
				"solicitudEvaluacionDesempennoId");

		if (solicitudEvaluacionDesempennoId != null) {
			setSolicitudEvaluacionDesempennoId(solicitudEvaluacionDesempennoId);
		}

		String descripcion = (String)attributes.get("descripcion");

		if (descripcion != null) {
			setDescripcion(descripcion);
		}

		Date fechaInicio = (Date)attributes.get("fechaInicio");

		if (fechaInicio != null) {
			setFechaInicio(fechaInicio);
		}

		Long estado = (Long)attributes.get("estado");

		if (estado != null) {
			setEstado(estado);
		}

		Boolean activo = (Boolean)attributes.get("activo");

		if (activo != null) {
			setActivo(activo);
		}

		Long usuariocrea = (Long)attributes.get("usuariocrea");

		if (usuariocrea != null) {
			setUsuariocrea(usuariocrea);
		}

		Date fechacrea = (Date)attributes.get("fechacrea");

		if (fechacrea != null) {
			setFechacrea(fechacrea);
		}

		Long usuariomodifica = (Long)attributes.get("usuariomodifica");

		if (usuariomodifica != null) {
			setUsuariomodifica(usuariomodifica);
		}

		Date fechamodifica = (Date)attributes.get("fechamodifica");

		if (fechamodifica != null) {
			setFechamodifica(fechamodifica);
		}
	}

	@JSON
	@Override
	public long getSolicitudEvaluacionDesempennoId() {
		return _solicitudEvaluacionDesempennoId;
	}

	@Override
	public void setSolicitudEvaluacionDesempennoId(
		long solicitudEvaluacionDesempennoId) {
		_solicitudEvaluacionDesempennoId = solicitudEvaluacionDesempennoId;
	}

	@JSON
	@Override
	public String getDescripcion() {
		if (_descripcion == null) {
			return StringPool.BLANK;
		}
		else {
			return _descripcion;
		}
	}

	@Override
	public void setDescripcion(String descripcion) {
		_descripcion = descripcion;
	}

	@JSON
	@Override
	public Date getFechaInicio() {
		return _fechaInicio;
	}

	@Override
	public void setFechaInicio(Date fechaInicio) {
		_fechaInicio = fechaInicio;
	}

	@JSON
	@Override
	public long getEstado() {
		return _estado;
	}

	@Override
	public void setEstado(long estado) {
		_estado = estado;
	}

	@JSON
	@Override
	public boolean getActivo() {
		return _activo;
	}

	@Override
	public boolean isActivo() {
		return _activo;
	}

	@Override
	public void setActivo(boolean activo) {
		_activo = activo;
	}

	@JSON
	@Override
	public long getUsuariocrea() {
		return _usuariocrea;
	}

	@Override
	public void setUsuariocrea(long usuariocrea) {
		_usuariocrea = usuariocrea;
	}

	@JSON
	@Override
	public Date getFechacrea() {
		return _fechacrea;
	}

	@Override
	public void setFechacrea(Date fechacrea) {
		_fechacrea = fechacrea;
	}

	@JSON
	@Override
	public long getUsuariomodifica() {
		return _usuariomodifica;
	}

	@Override
	public void setUsuariomodifica(long usuariomodifica) {
		_usuariomodifica = usuariomodifica;
	}

	@JSON
	@Override
	public Date getFechamodifica() {
		return _fechamodifica;
	}

	@Override
	public void setFechamodifica(Date fechamodifica) {
		_fechamodifica = fechamodifica;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			SolicitudEvaluacionDesempenno.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SolicitudEvaluacionDesempenno toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (SolicitudEvaluacionDesempenno)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SolicitudEvaluacionDesempennoImpl solicitudEvaluacionDesempennoImpl = new SolicitudEvaluacionDesempennoImpl();

		solicitudEvaluacionDesempennoImpl.setSolicitudEvaluacionDesempennoId(getSolicitudEvaluacionDesempennoId());
		solicitudEvaluacionDesempennoImpl.setDescripcion(getDescripcion());
		solicitudEvaluacionDesempennoImpl.setFechaInicio(getFechaInicio());
		solicitudEvaluacionDesempennoImpl.setEstado(getEstado());
		solicitudEvaluacionDesempennoImpl.setActivo(getActivo());
		solicitudEvaluacionDesempennoImpl.setUsuariocrea(getUsuariocrea());
		solicitudEvaluacionDesempennoImpl.setFechacrea(getFechacrea());
		solicitudEvaluacionDesempennoImpl.setUsuariomodifica(getUsuariomodifica());
		solicitudEvaluacionDesempennoImpl.setFechamodifica(getFechamodifica());

		solicitudEvaluacionDesempennoImpl.resetOriginalValues();

		return solicitudEvaluacionDesempennoImpl;
	}

	@Override
	public int compareTo(
		SolicitudEvaluacionDesempenno solicitudEvaluacionDesempenno) {
		int value = 0;

		value = DateUtil.compareTo(getFechamodifica(),
				solicitudEvaluacionDesempenno.getFechamodifica());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof SolicitudEvaluacionDesempenno)) {
			return false;
		}

		SolicitudEvaluacionDesempenno solicitudEvaluacionDesempenno = (SolicitudEvaluacionDesempenno)obj;

		long primaryKey = solicitudEvaluacionDesempenno.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<SolicitudEvaluacionDesempenno> toCacheModel() {
		SolicitudEvaluacionDesempennoCacheModel solicitudEvaluacionDesempennoCacheModel =
			new SolicitudEvaluacionDesempennoCacheModel();

		solicitudEvaluacionDesempennoCacheModel.solicitudEvaluacionDesempennoId = getSolicitudEvaluacionDesempennoId();

		solicitudEvaluacionDesempennoCacheModel.descripcion = getDescripcion();

		String descripcion = solicitudEvaluacionDesempennoCacheModel.descripcion;

		if ((descripcion != null) && (descripcion.length() == 0)) {
			solicitudEvaluacionDesempennoCacheModel.descripcion = null;
		}

		Date fechaInicio = getFechaInicio();

		if (fechaInicio != null) {
			solicitudEvaluacionDesempennoCacheModel.fechaInicio = fechaInicio.getTime();
		}
		else {
			solicitudEvaluacionDesempennoCacheModel.fechaInicio = Long.MIN_VALUE;
		}

		solicitudEvaluacionDesempennoCacheModel.estado = getEstado();

		solicitudEvaluacionDesempennoCacheModel.activo = getActivo();

		solicitudEvaluacionDesempennoCacheModel.usuariocrea = getUsuariocrea();

		Date fechacrea = getFechacrea();

		if (fechacrea != null) {
			solicitudEvaluacionDesempennoCacheModel.fechacrea = fechacrea.getTime();
		}
		else {
			solicitudEvaluacionDesempennoCacheModel.fechacrea = Long.MIN_VALUE;
		}

		solicitudEvaluacionDesempennoCacheModel.usuariomodifica = getUsuariomodifica();

		Date fechamodifica = getFechamodifica();

		if (fechamodifica != null) {
			solicitudEvaluacionDesempennoCacheModel.fechamodifica = fechamodifica.getTime();
		}
		else {
			solicitudEvaluacionDesempennoCacheModel.fechamodifica = Long.MIN_VALUE;
		}

		return solicitudEvaluacionDesempennoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{solicitudEvaluacionDesempennoId=");
		sb.append(getSolicitudEvaluacionDesempennoId());
		sb.append(", descripcion=");
		sb.append(getDescripcion());
		sb.append(", fechaInicio=");
		sb.append(getFechaInicio());
		sb.append(", estado=");
		sb.append(getEstado());
		sb.append(", activo=");
		sb.append(getActivo());
		sb.append(", usuariocrea=");
		sb.append(getUsuariocrea());
		sb.append(", fechacrea=");
		sb.append(getFechacrea());
		sb.append(", usuariomodifica=");
		sb.append(getUsuariomodifica());
		sb.append(", fechamodifica=");
		sb.append(getFechamodifica());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.hitss.layer.model.SolicitudEvaluacionDesempenno");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>solicitudEvaluacionDesempennoId</column-name><column-value><![CDATA[");
		sb.append(getSolicitudEvaluacionDesempennoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>descripcion</column-name><column-value><![CDATA[");
		sb.append(getDescripcion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fechaInicio</column-name><column-value><![CDATA[");
		sb.append(getFechaInicio());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>estado</column-name><column-value><![CDATA[");
		sb.append(getEstado());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>activo</column-name><column-value><![CDATA[");
		sb.append(getActivo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>usuariocrea</column-name><column-value><![CDATA[");
		sb.append(getUsuariocrea());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fechacrea</column-name><column-value><![CDATA[");
		sb.append(getFechacrea());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>usuariomodifica</column-name><column-value><![CDATA[");
		sb.append(getUsuariomodifica());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fechamodifica</column-name><column-value><![CDATA[");
		sb.append(getFechamodifica());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = SolicitudEvaluacionDesempenno.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			SolicitudEvaluacionDesempenno.class
		};
	private long _solicitudEvaluacionDesempennoId;
	private String _descripcion;
	private Date _fechaInicio;
	private long _estado;
	private boolean _activo;
	private long _usuariocrea;
	private Date _fechacrea;
	private long _usuariomodifica;
	private Date _fechamodifica;
	private SolicitudEvaluacionDesempenno _escapedModel;
}