/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.hitss.layer.model.impl;

import com.hitss.layer.model.SolicitudRequerimientoFuncion;
import com.hitss.layer.model.SolicitudRequerimientoFuncionModel;
import com.hitss.layer.model.SolicitudRequerimientoFuncionSoap;
import com.hitss.layer.service.persistence.SolicitudRequerimientoFuncionPK;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the SolicitudRequerimientoFuncion service. Represents a row in the &quot;SolicitudRequerimientoFuncion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.hitss.layer.model.SolicitudRequerimientoFuncionModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SolicitudRequerimientoFuncionImpl}.
 * </p>
 *
 * @author Danielle Delgado
 * @see SolicitudRequerimientoFuncionImpl
 * @see com.hitss.layer.model.SolicitudRequerimientoFuncion
 * @see com.hitss.layer.model.SolicitudRequerimientoFuncionModel
 * @generated
 */
@JSON(strict = true)
public class SolicitudRequerimientoFuncionModelImpl extends BaseModelImpl<SolicitudRequerimientoFuncion>
	implements SolicitudRequerimientoFuncionModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a solicitud requerimiento funcion model instance should use the {@link com.hitss.layer.model.SolicitudRequerimientoFuncion} interface instead.
	 */
	public static final String TABLE_NAME = "SolicitudRequerimientoFuncion";
	public static final Object[][] TABLE_COLUMNS = {
			{ "solicitudFuncionId", Types.BIGINT },
			{ "funcionId", Types.BIGINT },
			{ "exigible", Types.BOOLEAN },
			{ "activo", Types.BOOLEAN },
			{ "usuariocrea", Types.BIGINT },
			{ "fechacrea", Types.TIMESTAMP },
			{ "usuariomodifica", Types.BIGINT },
			{ "fechamodifica", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table SolicitudRequerimientoFuncion (solicitudFuncionId LONG not null,funcionId LONG not null,exigible BOOLEAN,activo BOOLEAN,usuariocrea LONG,fechacrea DATE null,usuariomodifica LONG,fechamodifica DATE null,primary key (solicitudFuncionId, funcionId))";
	public static final String TABLE_SQL_DROP = "drop table SolicitudRequerimientoFuncion";
	public static final String ORDER_BY_JPQL = " ORDER BY solicitudRequerimientoFuncion.fechamodifica ASC";
	public static final String ORDER_BY_SQL = " ORDER BY SolicitudRequerimientoFuncion.fechamodifica ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.hitss.layer.model.SolicitudRequerimientoFuncion"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.hitss.layer.model.SolicitudRequerimientoFuncion"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.hitss.layer.model.SolicitudRequerimientoFuncion"),
			true);
	public static long FUNCIONID_COLUMN_BITMASK = 1L;
	public static long SOLICITUDFUNCIONID_COLUMN_BITMASK = 2L;
	public static long FECHAMODIFICA_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static SolicitudRequerimientoFuncion toModel(
		SolicitudRequerimientoFuncionSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		SolicitudRequerimientoFuncion model = new SolicitudRequerimientoFuncionImpl();

		model.setSolicitudFuncionId(soapModel.getSolicitudFuncionId());
		model.setFuncionId(soapModel.getFuncionId());
		model.setExigible(soapModel.getExigible());
		model.setActivo(soapModel.getActivo());
		model.setUsuariocrea(soapModel.getUsuariocrea());
		model.setFechacrea(soapModel.getFechacrea());
		model.setUsuariomodifica(soapModel.getUsuariomodifica());
		model.setFechamodifica(soapModel.getFechamodifica());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<SolicitudRequerimientoFuncion> toModels(
		SolicitudRequerimientoFuncionSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<SolicitudRequerimientoFuncion> models = new ArrayList<SolicitudRequerimientoFuncion>(soapModels.length);

		for (SolicitudRequerimientoFuncionSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.hitss.layer.model.SolicitudRequerimientoFuncion"));

	public SolicitudRequerimientoFuncionModelImpl() {
	}

	@Override
	public SolicitudRequerimientoFuncionPK getPrimaryKey() {
		return new SolicitudRequerimientoFuncionPK(_solicitudFuncionId,
			_funcionId);
	}

	@Override
	public void setPrimaryKey(SolicitudRequerimientoFuncionPK primaryKey) {
		setSolicitudFuncionId(primaryKey.solicitudFuncionId);
		setFuncionId(primaryKey.funcionId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new SolicitudRequerimientoFuncionPK(_solicitudFuncionId,
			_funcionId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((SolicitudRequerimientoFuncionPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return SolicitudRequerimientoFuncion.class;
	}

	@Override
	public String getModelClassName() {
		return SolicitudRequerimientoFuncion.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("solicitudFuncionId", getSolicitudFuncionId());
		attributes.put("funcionId", getFuncionId());
		attributes.put("exigible", getExigible());
		attributes.put("activo", getActivo());
		attributes.put("usuariocrea", getUsuariocrea());
		attributes.put("fechacrea", getFechacrea());
		attributes.put("usuariomodifica", getUsuariomodifica());
		attributes.put("fechamodifica", getFechamodifica());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long solicitudFuncionId = (Long)attributes.get("solicitudFuncionId");

		if (solicitudFuncionId != null) {
			setSolicitudFuncionId(solicitudFuncionId);
		}

		Long funcionId = (Long)attributes.get("funcionId");

		if (funcionId != null) {
			setFuncionId(funcionId);
		}

		Boolean exigible = (Boolean)attributes.get("exigible");

		if (exigible != null) {
			setExigible(exigible);
		}

		Boolean activo = (Boolean)attributes.get("activo");

		if (activo != null) {
			setActivo(activo);
		}

		Long usuariocrea = (Long)attributes.get("usuariocrea");

		if (usuariocrea != null) {
			setUsuariocrea(usuariocrea);
		}

		Date fechacrea = (Date)attributes.get("fechacrea");

		if (fechacrea != null) {
			setFechacrea(fechacrea);
		}

		Long usuariomodifica = (Long)attributes.get("usuariomodifica");

		if (usuariomodifica != null) {
			setUsuariomodifica(usuariomodifica);
		}

		Date fechamodifica = (Date)attributes.get("fechamodifica");

		if (fechamodifica != null) {
			setFechamodifica(fechamodifica);
		}
	}

	@JSON
	@Override
	public long getSolicitudFuncionId() {
		return _solicitudFuncionId;
	}

	@Override
	public void setSolicitudFuncionId(long solicitudFuncionId) {
		_columnBitmask |= SOLICITUDFUNCIONID_COLUMN_BITMASK;

		if (!_setOriginalSolicitudFuncionId) {
			_setOriginalSolicitudFuncionId = true;

			_originalSolicitudFuncionId = _solicitudFuncionId;
		}

		_solicitudFuncionId = solicitudFuncionId;
	}

	public long getOriginalSolicitudFuncionId() {
		return _originalSolicitudFuncionId;
	}

	@JSON
	@Override
	public long getFuncionId() {
		return _funcionId;
	}

	@Override
	public void setFuncionId(long funcionId) {
		_columnBitmask |= FUNCIONID_COLUMN_BITMASK;

		if (!_setOriginalFuncionId) {
			_setOriginalFuncionId = true;

			_originalFuncionId = _funcionId;
		}

		_funcionId = funcionId;
	}

	public long getOriginalFuncionId() {
		return _originalFuncionId;
	}

	@JSON
	@Override
	public boolean getExigible() {
		return _exigible;
	}

	@Override
	public boolean isExigible() {
		return _exigible;
	}

	@Override
	public void setExigible(boolean exigible) {
		_exigible = exigible;
	}

	@JSON
	@Override
	public boolean getActivo() {
		return _activo;
	}

	@Override
	public boolean isActivo() {
		return _activo;
	}

	@Override
	public void setActivo(boolean activo) {
		_activo = activo;
	}

	@JSON
	@Override
	public long getUsuariocrea() {
		return _usuariocrea;
	}

	@Override
	public void setUsuariocrea(long usuariocrea) {
		_usuariocrea = usuariocrea;
	}

	@JSON
	@Override
	public Date getFechacrea() {
		return _fechacrea;
	}

	@Override
	public void setFechacrea(Date fechacrea) {
		_fechacrea = fechacrea;
	}

	@JSON
	@Override
	public long getUsuariomodifica() {
		return _usuariomodifica;
	}

	@Override
	public void setUsuariomodifica(long usuariomodifica) {
		_usuariomodifica = usuariomodifica;
	}

	@JSON
	@Override
	public Date getFechamodifica() {
		return _fechamodifica;
	}

	@Override
	public void setFechamodifica(Date fechamodifica) {
		_columnBitmask = -1L;

		_fechamodifica = fechamodifica;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public SolicitudRequerimientoFuncion toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (SolicitudRequerimientoFuncion)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SolicitudRequerimientoFuncionImpl solicitudRequerimientoFuncionImpl = new SolicitudRequerimientoFuncionImpl();

		solicitudRequerimientoFuncionImpl.setSolicitudFuncionId(getSolicitudFuncionId());
		solicitudRequerimientoFuncionImpl.setFuncionId(getFuncionId());
		solicitudRequerimientoFuncionImpl.setExigible(getExigible());
		solicitudRequerimientoFuncionImpl.setActivo(getActivo());
		solicitudRequerimientoFuncionImpl.setUsuariocrea(getUsuariocrea());
		solicitudRequerimientoFuncionImpl.setFechacrea(getFechacrea());
		solicitudRequerimientoFuncionImpl.setUsuariomodifica(getUsuariomodifica());
		solicitudRequerimientoFuncionImpl.setFechamodifica(getFechamodifica());

		solicitudRequerimientoFuncionImpl.resetOriginalValues();

		return solicitudRequerimientoFuncionImpl;
	}

	@Override
	public int compareTo(
		SolicitudRequerimientoFuncion solicitudRequerimientoFuncion) {
		int value = 0;

		value = DateUtil.compareTo(getFechamodifica(),
				solicitudRequerimientoFuncion.getFechamodifica());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof SolicitudRequerimientoFuncion)) {
			return false;
		}

		SolicitudRequerimientoFuncion solicitudRequerimientoFuncion = (SolicitudRequerimientoFuncion)obj;

		SolicitudRequerimientoFuncionPK primaryKey = solicitudRequerimientoFuncion.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
		SolicitudRequerimientoFuncionModelImpl solicitudRequerimientoFuncionModelImpl =
			this;

		solicitudRequerimientoFuncionModelImpl._originalSolicitudFuncionId = solicitudRequerimientoFuncionModelImpl._solicitudFuncionId;

		solicitudRequerimientoFuncionModelImpl._setOriginalSolicitudFuncionId = false;

		solicitudRequerimientoFuncionModelImpl._originalFuncionId = solicitudRequerimientoFuncionModelImpl._funcionId;

		solicitudRequerimientoFuncionModelImpl._setOriginalFuncionId = false;

		solicitudRequerimientoFuncionModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<SolicitudRequerimientoFuncion> toCacheModel() {
		SolicitudRequerimientoFuncionCacheModel solicitudRequerimientoFuncionCacheModel =
			new SolicitudRequerimientoFuncionCacheModel();

		solicitudRequerimientoFuncionCacheModel.solicitudFuncionId = getSolicitudFuncionId();

		solicitudRequerimientoFuncionCacheModel.funcionId = getFuncionId();

		solicitudRequerimientoFuncionCacheModel.exigible = getExigible();

		solicitudRequerimientoFuncionCacheModel.activo = getActivo();

		solicitudRequerimientoFuncionCacheModel.usuariocrea = getUsuariocrea();

		Date fechacrea = getFechacrea();

		if (fechacrea != null) {
			solicitudRequerimientoFuncionCacheModel.fechacrea = fechacrea.getTime();
		}
		else {
			solicitudRequerimientoFuncionCacheModel.fechacrea = Long.MIN_VALUE;
		}

		solicitudRequerimientoFuncionCacheModel.usuariomodifica = getUsuariomodifica();

		Date fechamodifica = getFechamodifica();

		if (fechamodifica != null) {
			solicitudRequerimientoFuncionCacheModel.fechamodifica = fechamodifica.getTime();
		}
		else {
			solicitudRequerimientoFuncionCacheModel.fechamodifica = Long.MIN_VALUE;
		}

		return solicitudRequerimientoFuncionCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{solicitudFuncionId=");
		sb.append(getSolicitudFuncionId());
		sb.append(", funcionId=");
		sb.append(getFuncionId());
		sb.append(", exigible=");
		sb.append(getExigible());
		sb.append(", activo=");
		sb.append(getActivo());
		sb.append(", usuariocrea=");
		sb.append(getUsuariocrea());
		sb.append(", fechacrea=");
		sb.append(getFechacrea());
		sb.append(", usuariomodifica=");
		sb.append(getUsuariomodifica());
		sb.append(", fechamodifica=");
		sb.append(getFechamodifica());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("com.hitss.layer.model.SolicitudRequerimientoFuncion");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>solicitudFuncionId</column-name><column-value><![CDATA[");
		sb.append(getSolicitudFuncionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>funcionId</column-name><column-value><![CDATA[");
		sb.append(getFuncionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>exigible</column-name><column-value><![CDATA[");
		sb.append(getExigible());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>activo</column-name><column-value><![CDATA[");
		sb.append(getActivo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>usuariocrea</column-name><column-value><![CDATA[");
		sb.append(getUsuariocrea());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fechacrea</column-name><column-value><![CDATA[");
		sb.append(getFechacrea());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>usuariomodifica</column-name><column-value><![CDATA[");
		sb.append(getUsuariomodifica());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fechamodifica</column-name><column-value><![CDATA[");
		sb.append(getFechamodifica());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = SolicitudRequerimientoFuncion.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			SolicitudRequerimientoFuncion.class
		};
	private long _solicitudFuncionId;
	private long _originalSolicitudFuncionId;
	private boolean _setOriginalSolicitudFuncionId;
	private long _funcionId;
	private long _originalFuncionId;
	private boolean _setOriginalFuncionId;
	private boolean _exigible;
	private boolean _activo;
	private long _usuariocrea;
	private Date _fechacrea;
	private long _usuariomodifica;
	private Date _fechamodifica;
	private long _columnBitmask;
	private SolicitudRequerimientoFuncion _escapedModel;
}