/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.hitss.layer.model.impl;

import com.hitss.layer.model.SolicitudRequerimientoRequisito;
import com.hitss.layer.model.SolicitudRequerimientoRequisitoModel;
import com.hitss.layer.model.SolicitudRequerimientoRequisitoSoap;
import com.hitss.layer.service.persistence.SolicitudRequerimientoRequisitoPK;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the SolicitudRequerimientoRequisito service. Represents a row in the &quot;SolicitudRequerimientoRequisito&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.hitss.layer.model.SolicitudRequerimientoRequisitoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SolicitudRequerimientoRequisitoImpl}.
 * </p>
 *
 * @author Danielle Delgado
 * @see SolicitudRequerimientoRequisitoImpl
 * @see com.hitss.layer.model.SolicitudRequerimientoRequisito
 * @see com.hitss.layer.model.SolicitudRequerimientoRequisitoModel
 * @generated
 */
@JSON(strict = true)
public class SolicitudRequerimientoRequisitoModelImpl extends BaseModelImpl<SolicitudRequerimientoRequisito>
	implements SolicitudRequerimientoRequisitoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a solicitud requerimiento requisito model instance should use the {@link com.hitss.layer.model.SolicitudRequerimientoRequisito} interface instead.
	 */
	public static final String TABLE_NAME = "SolicitudRequerimientoRequisito";
	public static final Object[][] TABLE_COLUMNS = {
			{ "solicitudRequerimientoId", Types.BIGINT },
			{ "tagId", Types.BIGINT },
			{ "annos", Types.BIGINT },
			{ "exigible", Types.BOOLEAN },
			{ "tipoRequisito", Types.BIGINT },
			{ "herramienta", Types.BIGINT },
			{ "activo", Types.BOOLEAN },
			{ "usuariocrea", Types.BIGINT },
			{ "fechacrea", Types.TIMESTAMP },
			{ "usuariomodifica", Types.BIGINT },
			{ "fechamodifica", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table SolicitudRequerimientoRequisito (solicitudRequerimientoId LONG not null,tagId LONG not null,annos LONG,exigible BOOLEAN,tipoRequisito LONG,herramienta LONG,activo BOOLEAN,usuariocrea LONG,fechacrea DATE null,usuariomodifica LONG,fechamodifica DATE null,primary key (solicitudRequerimientoId, tagId))";
	public static final String TABLE_SQL_DROP = "drop table SolicitudRequerimientoRequisito";
	public static final String ORDER_BY_JPQL = " ORDER BY solicitudRequerimientoRequisito.fechamodifica ASC";
	public static final String ORDER_BY_SQL = " ORDER BY SolicitudRequerimientoRequisito.fechamodifica ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.hitss.layer.model.SolicitudRequerimientoRequisito"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.hitss.layer.model.SolicitudRequerimientoRequisito"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.hitss.layer.model.SolicitudRequerimientoRequisito"),
			true);
	public static long SOLICITUDREQUERIMIENTOID_COLUMN_BITMASK = 1L;
	public static long TAGID_COLUMN_BITMASK = 2L;
	public static long FECHAMODIFICA_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static SolicitudRequerimientoRequisito toModel(
		SolicitudRequerimientoRequisitoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		SolicitudRequerimientoRequisito model = new SolicitudRequerimientoRequisitoImpl();

		model.setSolicitudRequerimientoId(soapModel.getSolicitudRequerimientoId());
		model.setTagId(soapModel.getTagId());
		model.setAnnos(soapModel.getAnnos());
		model.setExigible(soapModel.getExigible());
		model.setTipoRequisito(soapModel.getTipoRequisito());
		model.setHerramienta(soapModel.getHerramienta());
		model.setActivo(soapModel.getActivo());
		model.setUsuariocrea(soapModel.getUsuariocrea());
		model.setFechacrea(soapModel.getFechacrea());
		model.setUsuariomodifica(soapModel.getUsuariomodifica());
		model.setFechamodifica(soapModel.getFechamodifica());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<SolicitudRequerimientoRequisito> toModels(
		SolicitudRequerimientoRequisitoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<SolicitudRequerimientoRequisito> models = new ArrayList<SolicitudRequerimientoRequisito>(soapModels.length);

		for (SolicitudRequerimientoRequisitoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.hitss.layer.model.SolicitudRequerimientoRequisito"));

	public SolicitudRequerimientoRequisitoModelImpl() {
	}

	@Override
	public SolicitudRequerimientoRequisitoPK getPrimaryKey() {
		return new SolicitudRequerimientoRequisitoPK(_solicitudRequerimientoId,
			_tagId);
	}

	@Override
	public void setPrimaryKey(SolicitudRequerimientoRequisitoPK primaryKey) {
		setSolicitudRequerimientoId(primaryKey.solicitudRequerimientoId);
		setTagId(primaryKey.tagId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new SolicitudRequerimientoRequisitoPK(_solicitudRequerimientoId,
			_tagId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((SolicitudRequerimientoRequisitoPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return SolicitudRequerimientoRequisito.class;
	}

	@Override
	public String getModelClassName() {
		return SolicitudRequerimientoRequisito.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("solicitudRequerimientoId", getSolicitudRequerimientoId());
		attributes.put("tagId", getTagId());
		attributes.put("annos", getAnnos());
		attributes.put("exigible", getExigible());
		attributes.put("tipoRequisito", getTipoRequisito());
		attributes.put("herramienta", getHerramienta());
		attributes.put("activo", getActivo());
		attributes.put("usuariocrea", getUsuariocrea());
		attributes.put("fechacrea", getFechacrea());
		attributes.put("usuariomodifica", getUsuariomodifica());
		attributes.put("fechamodifica", getFechamodifica());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long solicitudRequerimientoId = (Long)attributes.get(
				"solicitudRequerimientoId");

		if (solicitudRequerimientoId != null) {
			setSolicitudRequerimientoId(solicitudRequerimientoId);
		}

		Long tagId = (Long)attributes.get("tagId");

		if (tagId != null) {
			setTagId(tagId);
		}

		Long annos = (Long)attributes.get("annos");

		if (annos != null) {
			setAnnos(annos);
		}

		Boolean exigible = (Boolean)attributes.get("exigible");

		if (exigible != null) {
			setExigible(exigible);
		}

		Long tipoRequisito = (Long)attributes.get("tipoRequisito");

		if (tipoRequisito != null) {
			setTipoRequisito(tipoRequisito);
		}

		Long herramienta = (Long)attributes.get("herramienta");

		if (herramienta != null) {
			setHerramienta(herramienta);
		}

		Boolean activo = (Boolean)attributes.get("activo");

		if (activo != null) {
			setActivo(activo);
		}

		Long usuariocrea = (Long)attributes.get("usuariocrea");

		if (usuariocrea != null) {
			setUsuariocrea(usuariocrea);
		}

		Date fechacrea = (Date)attributes.get("fechacrea");

		if (fechacrea != null) {
			setFechacrea(fechacrea);
		}

		Long usuariomodifica = (Long)attributes.get("usuariomodifica");

		if (usuariomodifica != null) {
			setUsuariomodifica(usuariomodifica);
		}

		Date fechamodifica = (Date)attributes.get("fechamodifica");

		if (fechamodifica != null) {
			setFechamodifica(fechamodifica);
		}
	}

	@JSON
	@Override
	public long getSolicitudRequerimientoId() {
		return _solicitudRequerimientoId;
	}

	@Override
	public void setSolicitudRequerimientoId(long solicitudRequerimientoId) {
		_columnBitmask |= SOLICITUDREQUERIMIENTOID_COLUMN_BITMASK;

		if (!_setOriginalSolicitudRequerimientoId) {
			_setOriginalSolicitudRequerimientoId = true;

			_originalSolicitudRequerimientoId = _solicitudRequerimientoId;
		}

		_solicitudRequerimientoId = solicitudRequerimientoId;
	}

	public long getOriginalSolicitudRequerimientoId() {
		return _originalSolicitudRequerimientoId;
	}

	@JSON
	@Override
	public long getTagId() {
		return _tagId;
	}

	@Override
	public void setTagId(long tagId) {
		_columnBitmask |= TAGID_COLUMN_BITMASK;

		if (!_setOriginalTagId) {
			_setOriginalTagId = true;

			_originalTagId = _tagId;
		}

		_tagId = tagId;
	}

	public long getOriginalTagId() {
		return _originalTagId;
	}

	@JSON
	@Override
	public long getAnnos() {
		return _annos;
	}

	@Override
	public void setAnnos(long annos) {
		_annos = annos;
	}

	@JSON
	@Override
	public boolean getExigible() {
		return _exigible;
	}

	@Override
	public boolean isExigible() {
		return _exigible;
	}

	@Override
	public void setExigible(boolean exigible) {
		_exigible = exigible;
	}

	@JSON
	@Override
	public long getTipoRequisito() {
		return _tipoRequisito;
	}

	@Override
	public void setTipoRequisito(long tipoRequisito) {
		_tipoRequisito = tipoRequisito;
	}

	@JSON
	@Override
	public long getHerramienta() {
		return _herramienta;
	}

	@Override
	public void setHerramienta(long herramienta) {
		_herramienta = herramienta;
	}

	@JSON
	@Override
	public boolean getActivo() {
		return _activo;
	}

	@Override
	public boolean isActivo() {
		return _activo;
	}

	@Override
	public void setActivo(boolean activo) {
		_activo = activo;
	}

	@JSON
	@Override
	public long getUsuariocrea() {
		return _usuariocrea;
	}

	@Override
	public void setUsuariocrea(long usuariocrea) {
		_usuariocrea = usuariocrea;
	}

	@JSON
	@Override
	public Date getFechacrea() {
		return _fechacrea;
	}

	@Override
	public void setFechacrea(Date fechacrea) {
		_fechacrea = fechacrea;
	}

	@JSON
	@Override
	public long getUsuariomodifica() {
		return _usuariomodifica;
	}

	@Override
	public void setUsuariomodifica(long usuariomodifica) {
		_usuariomodifica = usuariomodifica;
	}

	@JSON
	@Override
	public Date getFechamodifica() {
		return _fechamodifica;
	}

	@Override
	public void setFechamodifica(Date fechamodifica) {
		_columnBitmask = -1L;

		_fechamodifica = fechamodifica;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public SolicitudRequerimientoRequisito toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (SolicitudRequerimientoRequisito)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SolicitudRequerimientoRequisitoImpl solicitudRequerimientoRequisitoImpl = new SolicitudRequerimientoRequisitoImpl();

		solicitudRequerimientoRequisitoImpl.setSolicitudRequerimientoId(getSolicitudRequerimientoId());
		solicitudRequerimientoRequisitoImpl.setTagId(getTagId());
		solicitudRequerimientoRequisitoImpl.setAnnos(getAnnos());
		solicitudRequerimientoRequisitoImpl.setExigible(getExigible());
		solicitudRequerimientoRequisitoImpl.setTipoRequisito(getTipoRequisito());
		solicitudRequerimientoRequisitoImpl.setHerramienta(getHerramienta());
		solicitudRequerimientoRequisitoImpl.setActivo(getActivo());
		solicitudRequerimientoRequisitoImpl.setUsuariocrea(getUsuariocrea());
		solicitudRequerimientoRequisitoImpl.setFechacrea(getFechacrea());
		solicitudRequerimientoRequisitoImpl.setUsuariomodifica(getUsuariomodifica());
		solicitudRequerimientoRequisitoImpl.setFechamodifica(getFechamodifica());

		solicitudRequerimientoRequisitoImpl.resetOriginalValues();

		return solicitudRequerimientoRequisitoImpl;
	}

	@Override
	public int compareTo(
		SolicitudRequerimientoRequisito solicitudRequerimientoRequisito) {
		int value = 0;

		value = DateUtil.compareTo(getFechamodifica(),
				solicitudRequerimientoRequisito.getFechamodifica());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof SolicitudRequerimientoRequisito)) {
			return false;
		}

		SolicitudRequerimientoRequisito solicitudRequerimientoRequisito = (SolicitudRequerimientoRequisito)obj;

		SolicitudRequerimientoRequisitoPK primaryKey = solicitudRequerimientoRequisito.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
		SolicitudRequerimientoRequisitoModelImpl solicitudRequerimientoRequisitoModelImpl =
			this;

		solicitudRequerimientoRequisitoModelImpl._originalSolicitudRequerimientoId = solicitudRequerimientoRequisitoModelImpl._solicitudRequerimientoId;

		solicitudRequerimientoRequisitoModelImpl._setOriginalSolicitudRequerimientoId = false;

		solicitudRequerimientoRequisitoModelImpl._originalTagId = solicitudRequerimientoRequisitoModelImpl._tagId;

		solicitudRequerimientoRequisitoModelImpl._setOriginalTagId = false;

		solicitudRequerimientoRequisitoModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<SolicitudRequerimientoRequisito> toCacheModel() {
		SolicitudRequerimientoRequisitoCacheModel solicitudRequerimientoRequisitoCacheModel =
			new SolicitudRequerimientoRequisitoCacheModel();

		solicitudRequerimientoRequisitoCacheModel.solicitudRequerimientoId = getSolicitudRequerimientoId();

		solicitudRequerimientoRequisitoCacheModel.tagId = getTagId();

		solicitudRequerimientoRequisitoCacheModel.annos = getAnnos();

		solicitudRequerimientoRequisitoCacheModel.exigible = getExigible();

		solicitudRequerimientoRequisitoCacheModel.tipoRequisito = getTipoRequisito();

		solicitudRequerimientoRequisitoCacheModel.herramienta = getHerramienta();

		solicitudRequerimientoRequisitoCacheModel.activo = getActivo();

		solicitudRequerimientoRequisitoCacheModel.usuariocrea = getUsuariocrea();

		Date fechacrea = getFechacrea();

		if (fechacrea != null) {
			solicitudRequerimientoRequisitoCacheModel.fechacrea = fechacrea.getTime();
		}
		else {
			solicitudRequerimientoRequisitoCacheModel.fechacrea = Long.MIN_VALUE;
		}

		solicitudRequerimientoRequisitoCacheModel.usuariomodifica = getUsuariomodifica();

		Date fechamodifica = getFechamodifica();

		if (fechamodifica != null) {
			solicitudRequerimientoRequisitoCacheModel.fechamodifica = fechamodifica.getTime();
		}
		else {
			solicitudRequerimientoRequisitoCacheModel.fechamodifica = Long.MIN_VALUE;
		}

		return solicitudRequerimientoRequisitoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{solicitudRequerimientoId=");
		sb.append(getSolicitudRequerimientoId());
		sb.append(", tagId=");
		sb.append(getTagId());
		sb.append(", annos=");
		sb.append(getAnnos());
		sb.append(", exigible=");
		sb.append(getExigible());
		sb.append(", tipoRequisito=");
		sb.append(getTipoRequisito());
		sb.append(", herramienta=");
		sb.append(getHerramienta());
		sb.append(", activo=");
		sb.append(getActivo());
		sb.append(", usuariocrea=");
		sb.append(getUsuariocrea());
		sb.append(", fechacrea=");
		sb.append(getFechacrea());
		sb.append(", usuariomodifica=");
		sb.append(getUsuariomodifica());
		sb.append(", fechamodifica=");
		sb.append(getFechamodifica());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("com.hitss.layer.model.SolicitudRequerimientoRequisito");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>solicitudRequerimientoId</column-name><column-value><![CDATA[");
		sb.append(getSolicitudRequerimientoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tagId</column-name><column-value><![CDATA[");
		sb.append(getTagId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>annos</column-name><column-value><![CDATA[");
		sb.append(getAnnos());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>exigible</column-name><column-value><![CDATA[");
		sb.append(getExigible());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tipoRequisito</column-name><column-value><![CDATA[");
		sb.append(getTipoRequisito());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>herramienta</column-name><column-value><![CDATA[");
		sb.append(getHerramienta());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>activo</column-name><column-value><![CDATA[");
		sb.append(getActivo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>usuariocrea</column-name><column-value><![CDATA[");
		sb.append(getUsuariocrea());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fechacrea</column-name><column-value><![CDATA[");
		sb.append(getFechacrea());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>usuariomodifica</column-name><column-value><![CDATA[");
		sb.append(getUsuariomodifica());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fechamodifica</column-name><column-value><![CDATA[");
		sb.append(getFechamodifica());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = SolicitudRequerimientoRequisito.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			SolicitudRequerimientoRequisito.class
		};
	private long _solicitudRequerimientoId;
	private long _originalSolicitudRequerimientoId;
	private boolean _setOriginalSolicitudRequerimientoId;
	private long _tagId;
	private long _originalTagId;
	private boolean _setOriginalTagId;
	private long _annos;
	private boolean _exigible;
	private long _tipoRequisito;
	private long _herramienta;
	private boolean _activo;
	private long _usuariocrea;
	private Date _fechacrea;
	private long _usuariomodifica;
	private Date _fechamodifica;
	private long _columnBitmask;
	private SolicitudRequerimientoRequisito _escapedModel;
}