/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.hitss.layer.model.impl;

import com.hitss.layer.model.UsuarioRequisito;
import com.hitss.layer.model.UsuarioRequisitoModel;
import com.hitss.layer.model.UsuarioRequisitoSoap;
import com.hitss.layer.service.persistence.UsuarioRequisitoPK;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.util.PortalUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the UsuarioRequisito service. Represents a row in the &quot;UsuarioRequisito&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.hitss.layer.model.UsuarioRequisitoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UsuarioRequisitoImpl}.
 * </p>
 *
 * @author Danielle Delgado
 * @see UsuarioRequisitoImpl
 * @see com.hitss.layer.model.UsuarioRequisito
 * @see com.hitss.layer.model.UsuarioRequisitoModel
 * @generated
 */
@JSON(strict = true)
public class UsuarioRequisitoModelImpl extends BaseModelImpl<UsuarioRequisito>
	implements UsuarioRequisitoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a usuario requisito model instance should use the {@link com.hitss.layer.model.UsuarioRequisito} interface instead.
	 */
	public static final String TABLE_NAME = "UsuarioRequisito";
	public static final Object[][] TABLE_COLUMNS = {
			{ "userId", Types.BIGINT },
			{ "tagId", Types.BIGINT },
			{ "annos", Types.BIGINT },
			{ "exigible", Types.BOOLEAN },
			{ "tipoRequisito", Types.BIGINT },
			{ "herramienta", Types.BIGINT },
			{ "cumplerequisito", Types.BOOLEAN },
			{ "activo", Types.BOOLEAN },
			{ "usuariocrea", Types.BIGINT },
			{ "fechacrea", Types.TIMESTAMP },
			{ "usuariomodifica", Types.BIGINT },
			{ "fechamodifica", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table UsuarioRequisito (userId LONG not null,tagId LONG not null,annos LONG,exigible BOOLEAN,tipoRequisito LONG,herramienta LONG,cumplerequisito BOOLEAN,activo BOOLEAN,usuariocrea LONG,fechacrea DATE null,usuariomodifica LONG,fechamodifica DATE null,primary key (userId, tagId))";
	public static final String TABLE_SQL_DROP = "drop table UsuarioRequisito";
	public static final String ORDER_BY_JPQL = " ORDER BY usuarioRequisito.fechamodifica ASC";
	public static final String ORDER_BY_SQL = " ORDER BY UsuarioRequisito.fechamodifica ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.hitss.layer.model.UsuarioRequisito"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.hitss.layer.model.UsuarioRequisito"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.hitss.layer.model.UsuarioRequisito"),
			true);
	public static long USERID_COLUMN_BITMASK = 1L;
	public static long FECHAMODIFICA_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static UsuarioRequisito toModel(UsuarioRequisitoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		UsuarioRequisito model = new UsuarioRequisitoImpl();

		model.setUserId(soapModel.getUserId());
		model.setTagId(soapModel.getTagId());
		model.setAnnos(soapModel.getAnnos());
		model.setExigible(soapModel.getExigible());
		model.setTipoRequisito(soapModel.getTipoRequisito());
		model.setHerramienta(soapModel.getHerramienta());
		model.setCumplerequisito(soapModel.getCumplerequisito());
		model.setActivo(soapModel.getActivo());
		model.setUsuariocrea(soapModel.getUsuariocrea());
		model.setFechacrea(soapModel.getFechacrea());
		model.setUsuariomodifica(soapModel.getUsuariomodifica());
		model.setFechamodifica(soapModel.getFechamodifica());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<UsuarioRequisito> toModels(
		UsuarioRequisitoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<UsuarioRequisito> models = new ArrayList<UsuarioRequisito>(soapModels.length);

		for (UsuarioRequisitoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.hitss.layer.model.UsuarioRequisito"));

	public UsuarioRequisitoModelImpl() {
	}

	@Override
	public UsuarioRequisitoPK getPrimaryKey() {
		return new UsuarioRequisitoPK(_userId, _tagId);
	}

	@Override
	public void setPrimaryKey(UsuarioRequisitoPK primaryKey) {
		setUserId(primaryKey.userId);
		setTagId(primaryKey.tagId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new UsuarioRequisitoPK(_userId, _tagId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((UsuarioRequisitoPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return UsuarioRequisito.class;
	}

	@Override
	public String getModelClassName() {
		return UsuarioRequisito.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("userId", getUserId());
		attributes.put("tagId", getTagId());
		attributes.put("annos", getAnnos());
		attributes.put("exigible", getExigible());
		attributes.put("tipoRequisito", getTipoRequisito());
		attributes.put("herramienta", getHerramienta());
		attributes.put("cumplerequisito", getCumplerequisito());
		attributes.put("activo", getActivo());
		attributes.put("usuariocrea", getUsuariocrea());
		attributes.put("fechacrea", getFechacrea());
		attributes.put("usuariomodifica", getUsuariomodifica());
		attributes.put("fechamodifica", getFechamodifica());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Long tagId = (Long)attributes.get("tagId");

		if (tagId != null) {
			setTagId(tagId);
		}

		Long annos = (Long)attributes.get("annos");

		if (annos != null) {
			setAnnos(annos);
		}

		Boolean exigible = (Boolean)attributes.get("exigible");

		if (exigible != null) {
			setExigible(exigible);
		}

		Long tipoRequisito = (Long)attributes.get("tipoRequisito");

		if (tipoRequisito != null) {
			setTipoRequisito(tipoRequisito);
		}

		Long herramienta = (Long)attributes.get("herramienta");

		if (herramienta != null) {
			setHerramienta(herramienta);
		}

		Boolean cumplerequisito = (Boolean)attributes.get("cumplerequisito");

		if (cumplerequisito != null) {
			setCumplerequisito(cumplerequisito);
		}

		Boolean activo = (Boolean)attributes.get("activo");

		if (activo != null) {
			setActivo(activo);
		}

		Long usuariocrea = (Long)attributes.get("usuariocrea");

		if (usuariocrea != null) {
			setUsuariocrea(usuariocrea);
		}

		Date fechacrea = (Date)attributes.get("fechacrea");

		if (fechacrea != null) {
			setFechacrea(fechacrea);
		}

		Long usuariomodifica = (Long)attributes.get("usuariomodifica");

		if (usuariomodifica != null) {
			setUsuariomodifica(usuariomodifica);
		}

		Date fechamodifica = (Date)attributes.get("fechamodifica");

		if (fechamodifica != null) {
			setFechamodifica(fechamodifica);
		}
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@JSON
	@Override
	public long getTagId() {
		return _tagId;
	}

	@Override
	public void setTagId(long tagId) {
		_tagId = tagId;
	}

	@JSON
	@Override
	public long getAnnos() {
		return _annos;
	}

	@Override
	public void setAnnos(long annos) {
		_annos = annos;
	}

	@JSON
	@Override
	public boolean getExigible() {
		return _exigible;
	}

	@Override
	public boolean isExigible() {
		return _exigible;
	}

	@Override
	public void setExigible(boolean exigible) {
		_exigible = exigible;
	}

	@JSON
	@Override
	public long getTipoRequisito() {
		return _tipoRequisito;
	}

	@Override
	public void setTipoRequisito(long tipoRequisito) {
		_tipoRequisito = tipoRequisito;
	}

	@JSON
	@Override
	public long getHerramienta() {
		return _herramienta;
	}

	@Override
	public void setHerramienta(long herramienta) {
		_herramienta = herramienta;
	}

	@JSON
	@Override
	public boolean getCumplerequisito() {
		return _cumplerequisito;
	}

	@Override
	public boolean isCumplerequisito() {
		return _cumplerequisito;
	}

	@Override
	public void setCumplerequisito(boolean cumplerequisito) {
		_cumplerequisito = cumplerequisito;
	}

	@JSON
	@Override
	public boolean getActivo() {
		return _activo;
	}

	@Override
	public boolean isActivo() {
		return _activo;
	}

	@Override
	public void setActivo(boolean activo) {
		_activo = activo;
	}

	@JSON
	@Override
	public long getUsuariocrea() {
		return _usuariocrea;
	}

	@Override
	public void setUsuariocrea(long usuariocrea) {
		_usuariocrea = usuariocrea;
	}

	@JSON
	@Override
	public Date getFechacrea() {
		return _fechacrea;
	}

	@Override
	public void setFechacrea(Date fechacrea) {
		_fechacrea = fechacrea;
	}

	@JSON
	@Override
	public long getUsuariomodifica() {
		return _usuariomodifica;
	}

	@Override
	public void setUsuariomodifica(long usuariomodifica) {
		_usuariomodifica = usuariomodifica;
	}

	@JSON
	@Override
	public Date getFechamodifica() {
		return _fechamodifica;
	}

	@Override
	public void setFechamodifica(Date fechamodifica) {
		_columnBitmask = -1L;

		_fechamodifica = fechamodifica;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public UsuarioRequisito toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (UsuarioRequisito)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		UsuarioRequisitoImpl usuarioRequisitoImpl = new UsuarioRequisitoImpl();

		usuarioRequisitoImpl.setUserId(getUserId());
		usuarioRequisitoImpl.setTagId(getTagId());
		usuarioRequisitoImpl.setAnnos(getAnnos());
		usuarioRequisitoImpl.setExigible(getExigible());
		usuarioRequisitoImpl.setTipoRequisito(getTipoRequisito());
		usuarioRequisitoImpl.setHerramienta(getHerramienta());
		usuarioRequisitoImpl.setCumplerequisito(getCumplerequisito());
		usuarioRequisitoImpl.setActivo(getActivo());
		usuarioRequisitoImpl.setUsuariocrea(getUsuariocrea());
		usuarioRequisitoImpl.setFechacrea(getFechacrea());
		usuarioRequisitoImpl.setUsuariomodifica(getUsuariomodifica());
		usuarioRequisitoImpl.setFechamodifica(getFechamodifica());

		usuarioRequisitoImpl.resetOriginalValues();

		return usuarioRequisitoImpl;
	}

	@Override
	public int compareTo(UsuarioRequisito usuarioRequisito) {
		int value = 0;

		value = DateUtil.compareTo(getFechamodifica(),
				usuarioRequisito.getFechamodifica());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof UsuarioRequisito)) {
			return false;
		}

		UsuarioRequisito usuarioRequisito = (UsuarioRequisito)obj;

		UsuarioRequisitoPK primaryKey = usuarioRequisito.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
		UsuarioRequisitoModelImpl usuarioRequisitoModelImpl = this;

		usuarioRequisitoModelImpl._originalUserId = usuarioRequisitoModelImpl._userId;

		usuarioRequisitoModelImpl._setOriginalUserId = false;

		usuarioRequisitoModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<UsuarioRequisito> toCacheModel() {
		UsuarioRequisitoCacheModel usuarioRequisitoCacheModel = new UsuarioRequisitoCacheModel();

		usuarioRequisitoCacheModel.userId = getUserId();

		usuarioRequisitoCacheModel.tagId = getTagId();

		usuarioRequisitoCacheModel.annos = getAnnos();

		usuarioRequisitoCacheModel.exigible = getExigible();

		usuarioRequisitoCacheModel.tipoRequisito = getTipoRequisito();

		usuarioRequisitoCacheModel.herramienta = getHerramienta();

		usuarioRequisitoCacheModel.cumplerequisito = getCumplerequisito();

		usuarioRequisitoCacheModel.activo = getActivo();

		usuarioRequisitoCacheModel.usuariocrea = getUsuariocrea();

		Date fechacrea = getFechacrea();

		if (fechacrea != null) {
			usuarioRequisitoCacheModel.fechacrea = fechacrea.getTime();
		}
		else {
			usuarioRequisitoCacheModel.fechacrea = Long.MIN_VALUE;
		}

		usuarioRequisitoCacheModel.usuariomodifica = getUsuariomodifica();

		Date fechamodifica = getFechamodifica();

		if (fechamodifica != null) {
			usuarioRequisitoCacheModel.fechamodifica = fechamodifica.getTime();
		}
		else {
			usuarioRequisitoCacheModel.fechamodifica = Long.MIN_VALUE;
		}

		return usuarioRequisitoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(25);

		sb.append("{userId=");
		sb.append(getUserId());
		sb.append(", tagId=");
		sb.append(getTagId());
		sb.append(", annos=");
		sb.append(getAnnos());
		sb.append(", exigible=");
		sb.append(getExigible());
		sb.append(", tipoRequisito=");
		sb.append(getTipoRequisito());
		sb.append(", herramienta=");
		sb.append(getHerramienta());
		sb.append(", cumplerequisito=");
		sb.append(getCumplerequisito());
		sb.append(", activo=");
		sb.append(getActivo());
		sb.append(", usuariocrea=");
		sb.append(getUsuariocrea());
		sb.append(", fechacrea=");
		sb.append(getFechacrea());
		sb.append(", usuariomodifica=");
		sb.append(getUsuariomodifica());
		sb.append(", fechamodifica=");
		sb.append(getFechamodifica());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(40);

		sb.append("<model><model-name>");
		sb.append("com.hitss.layer.model.UsuarioRequisito");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tagId</column-name><column-value><![CDATA[");
		sb.append(getTagId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>annos</column-name><column-value><![CDATA[");
		sb.append(getAnnos());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>exigible</column-name><column-value><![CDATA[");
		sb.append(getExigible());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tipoRequisito</column-name><column-value><![CDATA[");
		sb.append(getTipoRequisito());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>herramienta</column-name><column-value><![CDATA[");
		sb.append(getHerramienta());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cumplerequisito</column-name><column-value><![CDATA[");
		sb.append(getCumplerequisito());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>activo</column-name><column-value><![CDATA[");
		sb.append(getActivo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>usuariocrea</column-name><column-value><![CDATA[");
		sb.append(getUsuariocrea());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fechacrea</column-name><column-value><![CDATA[");
		sb.append(getFechacrea());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>usuariomodifica</column-name><column-value><![CDATA[");
		sb.append(getUsuariomodifica());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fechamodifica</column-name><column-value><![CDATA[");
		sb.append(getFechamodifica());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = UsuarioRequisito.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			UsuarioRequisito.class
		};
	private long _userId;
	private String _userUuid;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private long _tagId;
	private long _annos;
	private boolean _exigible;
	private long _tipoRequisito;
	private long _herramienta;
	private boolean _cumplerequisito;
	private boolean _activo;
	private long _usuariocrea;
	private Date _fechacrea;
	private long _usuariomodifica;
	private Date _fechamodifica;
	private long _columnBitmask;
	private UsuarioRequisito _escapedModel;
}