/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rec.hitss.layer.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.rec.hitss.layer.model.Actividades;
import com.rec.hitss.layer.model.ActividadesModel;
import com.rec.hitss.layer.model.ActividadesSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Actividades service. Represents a row in the &quot;Actividades&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.rec.hitss.layer.model.ActividadesModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ActividadesImpl}.
 * </p>
 *
 * @author Crossfire
 * @see ActividadesImpl
 * @see com.rec.hitss.layer.model.Actividades
 * @see com.rec.hitss.layer.model.ActividadesModel
 * @generated
 */
@JSON(strict = true)
public class ActividadesModelImpl extends BaseModelImpl<Actividades>
	implements ActividadesModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a actividades model instance should use the {@link com.rec.hitss.layer.model.Actividades} interface instead.
	 */
	public static final String TABLE_NAME = "Actividades";
	public static final Object[][] TABLE_COLUMNS = {
			{ "actividadesId", Types.BIGINT },
			{ "cronogramaEvaluacionPersonalId", Types.BIGINT },
			{ "fechacreamodifica", Types.TIMESTAMP },
			{ "fechaInicioEvaluacion", Types.TIMESTAMP },
			{ "fechaFinEvaluacion", Types.TIMESTAMP },
			{ "descripcion", Types.VARCHAR },
			{ "activo", Types.BOOLEAN },
			{ "usuariocrea", Types.BIGINT },
			{ "fechacrea", Types.TIMESTAMP },
			{ "usuariomodifica", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table Actividades (actividadesId LONG not null primary key,cronogramaEvaluacionPersonalId LONG,fechacreamodifica DATE null,fechaInicioEvaluacion DATE null,fechaFinEvaluacion DATE null,descripcion VARCHAR(75) null,activo BOOLEAN,usuariocrea LONG,fechacrea DATE null,usuariomodifica LONG)";
	public static final String TABLE_SQL_DROP = "drop table Actividades";
	public static final String ORDER_BY_JPQL = " ORDER BY actividades.fechacrea ASC";
	public static final String ORDER_BY_SQL = " ORDER BY Actividades.fechacrea ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rec.hitss.layer.model.Actividades"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rec.hitss.layer.model.Actividades"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Actividades toModel(ActividadesSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Actividades model = new ActividadesImpl();

		model.setActividadesId(soapModel.getActividadesId());
		model.setCronogramaEvaluacionPersonalId(soapModel.getCronogramaEvaluacionPersonalId());
		model.setFechacreamodifica(soapModel.getFechacreamodifica());
		model.setFechaInicioEvaluacion(soapModel.getFechaInicioEvaluacion());
		model.setFechaFinEvaluacion(soapModel.getFechaFinEvaluacion());
		model.setDescripcion(soapModel.getDescripcion());
		model.setActivo(soapModel.getActivo());
		model.setUsuariocrea(soapModel.getUsuariocrea());
		model.setFechacrea(soapModel.getFechacrea());
		model.setUsuariomodifica(soapModel.getUsuariomodifica());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Actividades> toModels(ActividadesSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Actividades> models = new ArrayList<Actividades>(soapModels.length);

		for (ActividadesSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.rec.hitss.layer.model.Actividades"));

	public ActividadesModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _actividadesId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setActividadesId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _actividadesId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Actividades.class;
	}

	@Override
	public String getModelClassName() {
		return Actividades.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("actividadesId", getActividadesId());
		attributes.put("cronogramaEvaluacionPersonalId",
			getCronogramaEvaluacionPersonalId());
		attributes.put("fechacreamodifica", getFechacreamodifica());
		attributes.put("fechaInicioEvaluacion", getFechaInicioEvaluacion());
		attributes.put("fechaFinEvaluacion", getFechaFinEvaluacion());
		attributes.put("descripcion", getDescripcion());
		attributes.put("activo", getActivo());
		attributes.put("usuariocrea", getUsuariocrea());
		attributes.put("fechacrea", getFechacrea());
		attributes.put("usuariomodifica", getUsuariomodifica());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long actividadesId = (Long)attributes.get("actividadesId");

		if (actividadesId != null) {
			setActividadesId(actividadesId);
		}

		Long cronogramaEvaluacionPersonalId = (Long)attributes.get(
				"cronogramaEvaluacionPersonalId");

		if (cronogramaEvaluacionPersonalId != null) {
			setCronogramaEvaluacionPersonalId(cronogramaEvaluacionPersonalId);
		}

		Date fechacreamodifica = (Date)attributes.get("fechacreamodifica");

		if (fechacreamodifica != null) {
			setFechacreamodifica(fechacreamodifica);
		}

		Date fechaInicioEvaluacion = (Date)attributes.get(
				"fechaInicioEvaluacion");

		if (fechaInicioEvaluacion != null) {
			setFechaInicioEvaluacion(fechaInicioEvaluacion);
		}

		Date fechaFinEvaluacion = (Date)attributes.get("fechaFinEvaluacion");

		if (fechaFinEvaluacion != null) {
			setFechaFinEvaluacion(fechaFinEvaluacion);
		}

		String descripcion = (String)attributes.get("descripcion");

		if (descripcion != null) {
			setDescripcion(descripcion);
		}

		Boolean activo = (Boolean)attributes.get("activo");

		if (activo != null) {
			setActivo(activo);
		}

		Long usuariocrea = (Long)attributes.get("usuariocrea");

		if (usuariocrea != null) {
			setUsuariocrea(usuariocrea);
		}

		Date fechacrea = (Date)attributes.get("fechacrea");

		if (fechacrea != null) {
			setFechacrea(fechacrea);
		}

		Long usuariomodifica = (Long)attributes.get("usuariomodifica");

		if (usuariomodifica != null) {
			setUsuariomodifica(usuariomodifica);
		}
	}

	@JSON
	@Override
	public long getActividadesId() {
		return _actividadesId;
	}

	@Override
	public void setActividadesId(long actividadesId) {
		_actividadesId = actividadesId;
	}

	@JSON
	@Override
	public long getCronogramaEvaluacionPersonalId() {
		return _cronogramaEvaluacionPersonalId;
	}

	@Override
	public void setCronogramaEvaluacionPersonalId(
		long cronogramaEvaluacionPersonalId) {
		_cronogramaEvaluacionPersonalId = cronogramaEvaluacionPersonalId;
	}

	@JSON
	@Override
	public Date getFechacreamodifica() {
		return _fechacreamodifica;
	}

	@Override
	public void setFechacreamodifica(Date fechacreamodifica) {
		_fechacreamodifica = fechacreamodifica;
	}

	@JSON
	@Override
	public Date getFechaInicioEvaluacion() {
		return _fechaInicioEvaluacion;
	}

	@Override
	public void setFechaInicioEvaluacion(Date fechaInicioEvaluacion) {
		_fechaInicioEvaluacion = fechaInicioEvaluacion;
	}

	@JSON
	@Override
	public Date getFechaFinEvaluacion() {
		return _fechaFinEvaluacion;
	}

	@Override
	public void setFechaFinEvaluacion(Date fechaFinEvaluacion) {
		_fechaFinEvaluacion = fechaFinEvaluacion;
	}

	@JSON
	@Override
	public String getDescripcion() {
		if (_descripcion == null) {
			return StringPool.BLANK;
		}
		else {
			return _descripcion;
		}
	}

	@Override
	public void setDescripcion(String descripcion) {
		_descripcion = descripcion;
	}

	@JSON
	@Override
	public boolean getActivo() {
		return _activo;
	}

	@Override
	public boolean isActivo() {
		return _activo;
	}

	@Override
	public void setActivo(boolean activo) {
		_activo = activo;
	}

	@JSON
	@Override
	public long getUsuariocrea() {
		return _usuariocrea;
	}

	@Override
	public void setUsuariocrea(long usuariocrea) {
		_usuariocrea = usuariocrea;
	}

	@JSON
	@Override
	public Date getFechacrea() {
		return _fechacrea;
	}

	@Override
	public void setFechacrea(Date fechacrea) {
		_fechacrea = fechacrea;
	}

	@JSON
	@Override
	public long getUsuariomodifica() {
		return _usuariomodifica;
	}

	@Override
	public void setUsuariomodifica(long usuariomodifica) {
		_usuariomodifica = usuariomodifica;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Actividades.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Actividades toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Actividades)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ActividadesImpl actividadesImpl = new ActividadesImpl();

		actividadesImpl.setActividadesId(getActividadesId());
		actividadesImpl.setCronogramaEvaluacionPersonalId(getCronogramaEvaluacionPersonalId());
		actividadesImpl.setFechacreamodifica(getFechacreamodifica());
		actividadesImpl.setFechaInicioEvaluacion(getFechaInicioEvaluacion());
		actividadesImpl.setFechaFinEvaluacion(getFechaFinEvaluacion());
		actividadesImpl.setDescripcion(getDescripcion());
		actividadesImpl.setActivo(getActivo());
		actividadesImpl.setUsuariocrea(getUsuariocrea());
		actividadesImpl.setFechacrea(getFechacrea());
		actividadesImpl.setUsuariomodifica(getUsuariomodifica());

		actividadesImpl.resetOriginalValues();

		return actividadesImpl;
	}

	@Override
	public int compareTo(Actividades actividades) {
		int value = 0;

		value = DateUtil.compareTo(getFechacrea(), actividades.getFechacrea());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Actividades)) {
			return false;
		}

		Actividades actividades = (Actividades)obj;

		long primaryKey = actividades.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Actividades> toCacheModel() {
		ActividadesCacheModel actividadesCacheModel = new ActividadesCacheModel();

		actividadesCacheModel.actividadesId = getActividadesId();

		actividadesCacheModel.cronogramaEvaluacionPersonalId = getCronogramaEvaluacionPersonalId();

		Date fechacreamodifica = getFechacreamodifica();

		if (fechacreamodifica != null) {
			actividadesCacheModel.fechacreamodifica = fechacreamodifica.getTime();
		}
		else {
			actividadesCacheModel.fechacreamodifica = Long.MIN_VALUE;
		}

		Date fechaInicioEvaluacion = getFechaInicioEvaluacion();

		if (fechaInicioEvaluacion != null) {
			actividadesCacheModel.fechaInicioEvaluacion = fechaInicioEvaluacion.getTime();
		}
		else {
			actividadesCacheModel.fechaInicioEvaluacion = Long.MIN_VALUE;
		}

		Date fechaFinEvaluacion = getFechaFinEvaluacion();

		if (fechaFinEvaluacion != null) {
			actividadesCacheModel.fechaFinEvaluacion = fechaFinEvaluacion.getTime();
		}
		else {
			actividadesCacheModel.fechaFinEvaluacion = Long.MIN_VALUE;
		}

		actividadesCacheModel.descripcion = getDescripcion();

		String descripcion = actividadesCacheModel.descripcion;

		if ((descripcion != null) && (descripcion.length() == 0)) {
			actividadesCacheModel.descripcion = null;
		}

		actividadesCacheModel.activo = getActivo();

		actividadesCacheModel.usuariocrea = getUsuariocrea();

		Date fechacrea = getFechacrea();

		if (fechacrea != null) {
			actividadesCacheModel.fechacrea = fechacrea.getTime();
		}
		else {
			actividadesCacheModel.fechacrea = Long.MIN_VALUE;
		}

		actividadesCacheModel.usuariomodifica = getUsuariomodifica();

		return actividadesCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{actividadesId=");
		sb.append(getActividadesId());
		sb.append(", cronogramaEvaluacionPersonalId=");
		sb.append(getCronogramaEvaluacionPersonalId());
		sb.append(", fechacreamodifica=");
		sb.append(getFechacreamodifica());
		sb.append(", fechaInicioEvaluacion=");
		sb.append(getFechaInicioEvaluacion());
		sb.append(", fechaFinEvaluacion=");
		sb.append(getFechaFinEvaluacion());
		sb.append(", descripcion=");
		sb.append(getDescripcion());
		sb.append(", activo=");
		sb.append(getActivo());
		sb.append(", usuariocrea=");
		sb.append(getUsuariocrea());
		sb.append(", fechacrea=");
		sb.append(getFechacrea());
		sb.append(", usuariomodifica=");
		sb.append(getUsuariomodifica());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("com.rec.hitss.layer.model.Actividades");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>actividadesId</column-name><column-value><![CDATA[");
		sb.append(getActividadesId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cronogramaEvaluacionPersonalId</column-name><column-value><![CDATA[");
		sb.append(getCronogramaEvaluacionPersonalId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fechacreamodifica</column-name><column-value><![CDATA[");
		sb.append(getFechacreamodifica());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fechaInicioEvaluacion</column-name><column-value><![CDATA[");
		sb.append(getFechaInicioEvaluacion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fechaFinEvaluacion</column-name><column-value><![CDATA[");
		sb.append(getFechaFinEvaluacion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>descripcion</column-name><column-value><![CDATA[");
		sb.append(getDescripcion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>activo</column-name><column-value><![CDATA[");
		sb.append(getActivo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>usuariocrea</column-name><column-value><![CDATA[");
		sb.append(getUsuariocrea());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fechacrea</column-name><column-value><![CDATA[");
		sb.append(getFechacrea());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>usuariomodifica</column-name><column-value><![CDATA[");
		sb.append(getUsuariomodifica());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Actividades.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			Actividades.class
		};
	private long _actividadesId;
	private long _cronogramaEvaluacionPersonalId;
	private Date _fechacreamodifica;
	private Date _fechaInicioEvaluacion;
	private Date _fechaFinEvaluacion;
	private String _descripcion;
	private boolean _activo;
	private long _usuariocrea;
	private Date _fechacrea;
	private long _usuariomodifica;
	private Actividades _escapedModel;
}