/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rec.hitss.layer.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.rec.hitss.layer.model.CronogramaEvaluacionPersonal;
import com.rec.hitss.layer.model.CronogramaEvaluacionPersonalModel;
import com.rec.hitss.layer.model.CronogramaEvaluacionPersonalSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the CronogramaEvaluacionPersonal service. Represents a row in the &quot;CronogramaEvaluacionPersonal&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.rec.hitss.layer.model.CronogramaEvaluacionPersonalModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CronogramaEvaluacionPersonalImpl}.
 * </p>
 *
 * @author Crossfire
 * @see CronogramaEvaluacionPersonalImpl
 * @see com.rec.hitss.layer.model.CronogramaEvaluacionPersonal
 * @see com.rec.hitss.layer.model.CronogramaEvaluacionPersonalModel
 * @generated
 */
@JSON(strict = true)
public class CronogramaEvaluacionPersonalModelImpl extends BaseModelImpl<CronogramaEvaluacionPersonal>
	implements CronogramaEvaluacionPersonalModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cronograma evaluacion personal model instance should use the {@link com.rec.hitss.layer.model.CronogramaEvaluacionPersonal} interface instead.
	 */
	public static final String TABLE_NAME = "CronogramaEvaluacionPersonal";
	public static final Object[][] TABLE_COLUMNS = {
			{ "cronogramaEvaluacionPersonalId", Types.BIGINT },
			{ "solicitudEvaluacionDesempenoId", Types.BIGINT },
			{ "descripcion", Types.VARCHAR },
			{ "estado", Types.VARCHAR },
			{ "observacion", Types.VARCHAR },
			{ "activo", Types.BOOLEAN },
			{ "usuariocrea", Types.BIGINT },
			{ "fechacrea", Types.TIMESTAMP },
			{ "usuariomodifica", Types.BIGINT },
			{ "fechacreamodifica", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table CronogramaEvaluacionPersonal (cronogramaEvaluacionPersonalId LONG not null primary key,solicitudEvaluacionDesempenoId LONG,descripcion VARCHAR(75) null,estado VARCHAR(75) null,observacion VARCHAR(75) null,activo BOOLEAN,usuariocrea LONG,fechacrea DATE null,usuariomodifica LONG,fechacreamodifica DATE null)";
	public static final String TABLE_SQL_DROP = "drop table CronogramaEvaluacionPersonal";
	public static final String ORDER_BY_JPQL = " ORDER BY cronogramaEvaluacionPersonal.fechacrea ASC";
	public static final String ORDER_BY_SQL = " ORDER BY CronogramaEvaluacionPersonal.fechacrea ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rec.hitss.layer.model.CronogramaEvaluacionPersonal"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rec.hitss.layer.model.CronogramaEvaluacionPersonal"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static CronogramaEvaluacionPersonal toModel(
		CronogramaEvaluacionPersonalSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		CronogramaEvaluacionPersonal model = new CronogramaEvaluacionPersonalImpl();

		model.setCronogramaEvaluacionPersonalId(soapModel.getCronogramaEvaluacionPersonalId());
		model.setSolicitudEvaluacionDesempenoId(soapModel.getSolicitudEvaluacionDesempenoId());
		model.setDescripcion(soapModel.getDescripcion());
		model.setEstado(soapModel.getEstado());
		model.setObservacion(soapModel.getObservacion());
		model.setActivo(soapModel.getActivo());
		model.setUsuariocrea(soapModel.getUsuariocrea());
		model.setFechacrea(soapModel.getFechacrea());
		model.setUsuariomodifica(soapModel.getUsuariomodifica());
		model.setFechacreamodifica(soapModel.getFechacreamodifica());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<CronogramaEvaluacionPersonal> toModels(
		CronogramaEvaluacionPersonalSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<CronogramaEvaluacionPersonal> models = new ArrayList<CronogramaEvaluacionPersonal>(soapModels.length);

		for (CronogramaEvaluacionPersonalSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.rec.hitss.layer.model.CronogramaEvaluacionPersonal"));

	public CronogramaEvaluacionPersonalModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _cronogramaEvaluacionPersonalId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCronogramaEvaluacionPersonalId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _cronogramaEvaluacionPersonalId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CronogramaEvaluacionPersonal.class;
	}

	@Override
	public String getModelClassName() {
		return CronogramaEvaluacionPersonal.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("cronogramaEvaluacionPersonalId",
			getCronogramaEvaluacionPersonalId());
		attributes.put("solicitudEvaluacionDesempenoId",
			getSolicitudEvaluacionDesempenoId());
		attributes.put("descripcion", getDescripcion());
		attributes.put("estado", getEstado());
		attributes.put("observacion", getObservacion());
		attributes.put("activo", getActivo());
		attributes.put("usuariocrea", getUsuariocrea());
		attributes.put("fechacrea", getFechacrea());
		attributes.put("usuariomodifica", getUsuariomodifica());
		attributes.put("fechacreamodifica", getFechacreamodifica());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long cronogramaEvaluacionPersonalId = (Long)attributes.get(
				"cronogramaEvaluacionPersonalId");

		if (cronogramaEvaluacionPersonalId != null) {
			setCronogramaEvaluacionPersonalId(cronogramaEvaluacionPersonalId);
		}

		Long solicitudEvaluacionDesempenoId = (Long)attributes.get(
				"solicitudEvaluacionDesempenoId");

		if (solicitudEvaluacionDesempenoId != null) {
			setSolicitudEvaluacionDesempenoId(solicitudEvaluacionDesempenoId);
		}

		String descripcion = (String)attributes.get("descripcion");

		if (descripcion != null) {
			setDescripcion(descripcion);
		}

		String estado = (String)attributes.get("estado");

		if (estado != null) {
			setEstado(estado);
		}

		String observacion = (String)attributes.get("observacion");

		if (observacion != null) {
			setObservacion(observacion);
		}

		Boolean activo = (Boolean)attributes.get("activo");

		if (activo != null) {
			setActivo(activo);
		}

		Long usuariocrea = (Long)attributes.get("usuariocrea");

		if (usuariocrea != null) {
			setUsuariocrea(usuariocrea);
		}

		Date fechacrea = (Date)attributes.get("fechacrea");

		if (fechacrea != null) {
			setFechacrea(fechacrea);
		}

		Long usuariomodifica = (Long)attributes.get("usuariomodifica");

		if (usuariomodifica != null) {
			setUsuariomodifica(usuariomodifica);
		}

		Date fechacreamodifica = (Date)attributes.get("fechacreamodifica");

		if (fechacreamodifica != null) {
			setFechacreamodifica(fechacreamodifica);
		}
	}

	@JSON
	@Override
	public long getCronogramaEvaluacionPersonalId() {
		return _cronogramaEvaluacionPersonalId;
	}

	@Override
	public void setCronogramaEvaluacionPersonalId(
		long cronogramaEvaluacionPersonalId) {
		_cronogramaEvaluacionPersonalId = cronogramaEvaluacionPersonalId;
	}

	@JSON
	@Override
	public long getSolicitudEvaluacionDesempenoId() {
		return _solicitudEvaluacionDesempenoId;
	}

	@Override
	public void setSolicitudEvaluacionDesempenoId(
		long solicitudEvaluacionDesempenoId) {
		_solicitudEvaluacionDesempenoId = solicitudEvaluacionDesempenoId;
	}

	@JSON
	@Override
	public String getDescripcion() {
		if (_descripcion == null) {
			return StringPool.BLANK;
		}
		else {
			return _descripcion;
		}
	}

	@Override
	public void setDescripcion(String descripcion) {
		_descripcion = descripcion;
	}

	@JSON
	@Override
	public String getEstado() {
		if (_estado == null) {
			return StringPool.BLANK;
		}
		else {
			return _estado;
		}
	}

	@Override
	public void setEstado(String estado) {
		_estado = estado;
	}

	@JSON
	@Override
	public String getObservacion() {
		if (_observacion == null) {
			return StringPool.BLANK;
		}
		else {
			return _observacion;
		}
	}

	@Override
	public void setObservacion(String observacion) {
		_observacion = observacion;
	}

	@JSON
	@Override
	public boolean getActivo() {
		return _activo;
	}

	@Override
	public boolean isActivo() {
		return _activo;
	}

	@Override
	public void setActivo(boolean activo) {
		_activo = activo;
	}

	@JSON
	@Override
	public long getUsuariocrea() {
		return _usuariocrea;
	}

	@Override
	public void setUsuariocrea(long usuariocrea) {
		_usuariocrea = usuariocrea;
	}

	@JSON
	@Override
	public Date getFechacrea() {
		return _fechacrea;
	}

	@Override
	public void setFechacrea(Date fechacrea) {
		_fechacrea = fechacrea;
	}

	@JSON
	@Override
	public long getUsuariomodifica() {
		return _usuariomodifica;
	}

	@Override
	public void setUsuariomodifica(long usuariomodifica) {
		_usuariomodifica = usuariomodifica;
	}

	@JSON
	@Override
	public Date getFechacreamodifica() {
		return _fechacreamodifica;
	}

	@Override
	public void setFechacreamodifica(Date fechacreamodifica) {
		_fechacreamodifica = fechacreamodifica;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			CronogramaEvaluacionPersonal.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CronogramaEvaluacionPersonal toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (CronogramaEvaluacionPersonal)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CronogramaEvaluacionPersonalImpl cronogramaEvaluacionPersonalImpl = new CronogramaEvaluacionPersonalImpl();

		cronogramaEvaluacionPersonalImpl.setCronogramaEvaluacionPersonalId(getCronogramaEvaluacionPersonalId());
		cronogramaEvaluacionPersonalImpl.setSolicitudEvaluacionDesempenoId(getSolicitudEvaluacionDesempenoId());
		cronogramaEvaluacionPersonalImpl.setDescripcion(getDescripcion());
		cronogramaEvaluacionPersonalImpl.setEstado(getEstado());
		cronogramaEvaluacionPersonalImpl.setObservacion(getObservacion());
		cronogramaEvaluacionPersonalImpl.setActivo(getActivo());
		cronogramaEvaluacionPersonalImpl.setUsuariocrea(getUsuariocrea());
		cronogramaEvaluacionPersonalImpl.setFechacrea(getFechacrea());
		cronogramaEvaluacionPersonalImpl.setUsuariomodifica(getUsuariomodifica());
		cronogramaEvaluacionPersonalImpl.setFechacreamodifica(getFechacreamodifica());

		cronogramaEvaluacionPersonalImpl.resetOriginalValues();

		return cronogramaEvaluacionPersonalImpl;
	}

	@Override
	public int compareTo(
		CronogramaEvaluacionPersonal cronogramaEvaluacionPersonal) {
		int value = 0;

		value = DateUtil.compareTo(getFechacrea(),
				cronogramaEvaluacionPersonal.getFechacrea());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CronogramaEvaluacionPersonal)) {
			return false;
		}

		CronogramaEvaluacionPersonal cronogramaEvaluacionPersonal = (CronogramaEvaluacionPersonal)obj;

		long primaryKey = cronogramaEvaluacionPersonal.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<CronogramaEvaluacionPersonal> toCacheModel() {
		CronogramaEvaluacionPersonalCacheModel cronogramaEvaluacionPersonalCacheModel =
			new CronogramaEvaluacionPersonalCacheModel();

		cronogramaEvaluacionPersonalCacheModel.cronogramaEvaluacionPersonalId = getCronogramaEvaluacionPersonalId();

		cronogramaEvaluacionPersonalCacheModel.solicitudEvaluacionDesempenoId = getSolicitudEvaluacionDesempenoId();

		cronogramaEvaluacionPersonalCacheModel.descripcion = getDescripcion();

		String descripcion = cronogramaEvaluacionPersonalCacheModel.descripcion;

		if ((descripcion != null) && (descripcion.length() == 0)) {
			cronogramaEvaluacionPersonalCacheModel.descripcion = null;
		}

		cronogramaEvaluacionPersonalCacheModel.estado = getEstado();

		String estado = cronogramaEvaluacionPersonalCacheModel.estado;

		if ((estado != null) && (estado.length() == 0)) {
			cronogramaEvaluacionPersonalCacheModel.estado = null;
		}

		cronogramaEvaluacionPersonalCacheModel.observacion = getObservacion();

		String observacion = cronogramaEvaluacionPersonalCacheModel.observacion;

		if ((observacion != null) && (observacion.length() == 0)) {
			cronogramaEvaluacionPersonalCacheModel.observacion = null;
		}

		cronogramaEvaluacionPersonalCacheModel.activo = getActivo();

		cronogramaEvaluacionPersonalCacheModel.usuariocrea = getUsuariocrea();

		Date fechacrea = getFechacrea();

		if (fechacrea != null) {
			cronogramaEvaluacionPersonalCacheModel.fechacrea = fechacrea.getTime();
		}
		else {
			cronogramaEvaluacionPersonalCacheModel.fechacrea = Long.MIN_VALUE;
		}

		cronogramaEvaluacionPersonalCacheModel.usuariomodifica = getUsuariomodifica();

		Date fechacreamodifica = getFechacreamodifica();

		if (fechacreamodifica != null) {
			cronogramaEvaluacionPersonalCacheModel.fechacreamodifica = fechacreamodifica.getTime();
		}
		else {
			cronogramaEvaluacionPersonalCacheModel.fechacreamodifica = Long.MIN_VALUE;
		}

		return cronogramaEvaluacionPersonalCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{cronogramaEvaluacionPersonalId=");
		sb.append(getCronogramaEvaluacionPersonalId());
		sb.append(", solicitudEvaluacionDesempenoId=");
		sb.append(getSolicitudEvaluacionDesempenoId());
		sb.append(", descripcion=");
		sb.append(getDescripcion());
		sb.append(", estado=");
		sb.append(getEstado());
		sb.append(", observacion=");
		sb.append(getObservacion());
		sb.append(", activo=");
		sb.append(getActivo());
		sb.append(", usuariocrea=");
		sb.append(getUsuariocrea());
		sb.append(", fechacrea=");
		sb.append(getFechacrea());
		sb.append(", usuariomodifica=");
		sb.append(getUsuariomodifica());
		sb.append(", fechacreamodifica=");
		sb.append(getFechacreamodifica());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("com.rec.hitss.layer.model.CronogramaEvaluacionPersonal");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>cronogramaEvaluacionPersonalId</column-name><column-value><![CDATA[");
		sb.append(getCronogramaEvaluacionPersonalId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>solicitudEvaluacionDesempenoId</column-name><column-value><![CDATA[");
		sb.append(getSolicitudEvaluacionDesempenoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>descripcion</column-name><column-value><![CDATA[");
		sb.append(getDescripcion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>estado</column-name><column-value><![CDATA[");
		sb.append(getEstado());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>observacion</column-name><column-value><![CDATA[");
		sb.append(getObservacion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>activo</column-name><column-value><![CDATA[");
		sb.append(getActivo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>usuariocrea</column-name><column-value><![CDATA[");
		sb.append(getUsuariocrea());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fechacrea</column-name><column-value><![CDATA[");
		sb.append(getFechacrea());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>usuariomodifica</column-name><column-value><![CDATA[");
		sb.append(getUsuariomodifica());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fechacreamodifica</column-name><column-value><![CDATA[");
		sb.append(getFechacreamodifica());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = CronogramaEvaluacionPersonal.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			CronogramaEvaluacionPersonal.class
		};
	private long _cronogramaEvaluacionPersonalId;
	private long _solicitudEvaluacionDesempenoId;
	private String _descripcion;
	private String _estado;
	private String _observacion;
	private boolean _activo;
	private long _usuariocrea;
	private Date _fechacrea;
	private long _usuariomodifica;
	private Date _fechacreamodifica;
	private CronogramaEvaluacionPersonal _escapedModel;
}