/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rec.hitss.layer.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.rec.hitss.layer.model.Evaluacion;
import com.rec.hitss.layer.model.EvaluacionModel;
import com.rec.hitss.layer.model.EvaluacionSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Evaluacion service. Represents a row in the &quot;Evaluacion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.rec.hitss.layer.model.EvaluacionModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EvaluacionImpl}.
 * </p>
 *
 * @author Crossfire
 * @see EvaluacionImpl
 * @see com.rec.hitss.layer.model.Evaluacion
 * @see com.rec.hitss.layer.model.EvaluacionModel
 * @generated
 */
@JSON(strict = true)
public class EvaluacionModelImpl extends BaseModelImpl<Evaluacion>
	implements EvaluacionModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a evaluacion model instance should use the {@link com.rec.hitss.layer.model.Evaluacion} interface instead.
	 */
	public static final String TABLE_NAME = "Evaluacion";
	public static final Object[][] TABLE_COLUMNS = {
			{ "evaluacionId", Types.BIGINT },
			{ "tiempoMinuto", Types.BIGINT },
			{ "enfoque", Types.BIGINT },
			{ "puestoEvaluacion", Types.BIGINT },
			{ "tiempoPuesto", Types.BIGINT },
			{ "TipoEvaluacion", Types.BIGINT },
			{ "activo", Types.BOOLEAN },
			{ "usuariocrea", Types.BIGINT },
			{ "fechacrea", Types.TIMESTAMP },
			{ "usuariomodifica", Types.BIGINT },
			{ "fechacreamodifica", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table Evaluacion (evaluacionId LONG not null primary key,tiempoMinuto LONG,enfoque LONG,puestoEvaluacion LONG,tiempoPuesto LONG,TipoEvaluacion LONG,activo BOOLEAN,usuariocrea LONG,fechacrea DATE null,usuariomodifica LONG,fechacreamodifica DATE null)";
	public static final String TABLE_SQL_DROP = "drop table Evaluacion";
	public static final String ORDER_BY_JPQL = " ORDER BY evaluacion.fechacrea ASC";
	public static final String ORDER_BY_SQL = " ORDER BY Evaluacion.fechacrea ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rec.hitss.layer.model.Evaluacion"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rec.hitss.layer.model.Evaluacion"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Evaluacion toModel(EvaluacionSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Evaluacion model = new EvaluacionImpl();

		model.setEvaluacionId(soapModel.getEvaluacionId());
		model.setTiempoMinuto(soapModel.getTiempoMinuto());
		model.setEnfoque(soapModel.getEnfoque());
		model.setPuestoEvaluacion(soapModel.getPuestoEvaluacion());
		model.setTiempoPuesto(soapModel.getTiempoPuesto());
		model.setTipoEvaluacion(soapModel.getTipoEvaluacion());
		model.setActivo(soapModel.getActivo());
		model.setUsuariocrea(soapModel.getUsuariocrea());
		model.setFechacrea(soapModel.getFechacrea());
		model.setUsuariomodifica(soapModel.getUsuariomodifica());
		model.setFechacreamodifica(soapModel.getFechacreamodifica());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Evaluacion> toModels(EvaluacionSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Evaluacion> models = new ArrayList<Evaluacion>(soapModels.length);

		for (EvaluacionSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.rec.hitss.layer.model.Evaluacion"));

	public EvaluacionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _evaluacionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEvaluacionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _evaluacionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Evaluacion.class;
	}

	@Override
	public String getModelClassName() {
		return Evaluacion.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("evaluacionId", getEvaluacionId());
		attributes.put("tiempoMinuto", getTiempoMinuto());
		attributes.put("enfoque", getEnfoque());
		attributes.put("puestoEvaluacion", getPuestoEvaluacion());
		attributes.put("tiempoPuesto", getTiempoPuesto());
		attributes.put("TipoEvaluacion", getTipoEvaluacion());
		attributes.put("activo", getActivo());
		attributes.put("usuariocrea", getUsuariocrea());
		attributes.put("fechacrea", getFechacrea());
		attributes.put("usuariomodifica", getUsuariomodifica());
		attributes.put("fechacreamodifica", getFechacreamodifica());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long evaluacionId = (Long)attributes.get("evaluacionId");

		if (evaluacionId != null) {
			setEvaluacionId(evaluacionId);
		}

		Long tiempoMinuto = (Long)attributes.get("tiempoMinuto");

		if (tiempoMinuto != null) {
			setTiempoMinuto(tiempoMinuto);
		}

		Long enfoque = (Long)attributes.get("enfoque");

		if (enfoque != null) {
			setEnfoque(enfoque);
		}

		Long puestoEvaluacion = (Long)attributes.get("puestoEvaluacion");

		if (puestoEvaluacion != null) {
			setPuestoEvaluacion(puestoEvaluacion);
		}

		Long tiempoPuesto = (Long)attributes.get("tiempoPuesto");

		if (tiempoPuesto != null) {
			setTiempoPuesto(tiempoPuesto);
		}

		Long TipoEvaluacion = (Long)attributes.get("TipoEvaluacion");

		if (TipoEvaluacion != null) {
			setTipoEvaluacion(TipoEvaluacion);
		}

		Boolean activo = (Boolean)attributes.get("activo");

		if (activo != null) {
			setActivo(activo);
		}

		Long usuariocrea = (Long)attributes.get("usuariocrea");

		if (usuariocrea != null) {
			setUsuariocrea(usuariocrea);
		}

		Date fechacrea = (Date)attributes.get("fechacrea");

		if (fechacrea != null) {
			setFechacrea(fechacrea);
		}

		Long usuariomodifica = (Long)attributes.get("usuariomodifica");

		if (usuariomodifica != null) {
			setUsuariomodifica(usuariomodifica);
		}

		Date fechacreamodifica = (Date)attributes.get("fechacreamodifica");

		if (fechacreamodifica != null) {
			setFechacreamodifica(fechacreamodifica);
		}
	}

	@JSON
	@Override
	public long getEvaluacionId() {
		return _evaluacionId;
	}

	@Override
	public void setEvaluacionId(long evaluacionId) {
		_evaluacionId = evaluacionId;
	}

	@JSON
	@Override
	public long getTiempoMinuto() {
		return _tiempoMinuto;
	}

	@Override
	public void setTiempoMinuto(long tiempoMinuto) {
		_tiempoMinuto = tiempoMinuto;
	}

	@JSON
	@Override
	public long getEnfoque() {
		return _enfoque;
	}

	@Override
	public void setEnfoque(long enfoque) {
		_enfoque = enfoque;
	}

	@JSON
	@Override
	public long getPuestoEvaluacion() {
		return _puestoEvaluacion;
	}

	@Override
	public void setPuestoEvaluacion(long puestoEvaluacion) {
		_puestoEvaluacion = puestoEvaluacion;
	}

	@JSON
	@Override
	public long getTiempoPuesto() {
		return _tiempoPuesto;
	}

	@Override
	public void setTiempoPuesto(long tiempoPuesto) {
		_tiempoPuesto = tiempoPuesto;
	}

	@JSON
	@Override
	public long getTipoEvaluacion() {
		return _TipoEvaluacion;
	}

	@Override
	public void setTipoEvaluacion(long TipoEvaluacion) {
		_TipoEvaluacion = TipoEvaluacion;
	}

	@JSON
	@Override
	public boolean getActivo() {
		return _activo;
	}

	@Override
	public boolean isActivo() {
		return _activo;
	}

	@Override
	public void setActivo(boolean activo) {
		_activo = activo;
	}

	@JSON
	@Override
	public long getUsuariocrea() {
		return _usuariocrea;
	}

	@Override
	public void setUsuariocrea(long usuariocrea) {
		_usuariocrea = usuariocrea;
	}

	@JSON
	@Override
	public Date getFechacrea() {
		return _fechacrea;
	}

	@Override
	public void setFechacrea(Date fechacrea) {
		_fechacrea = fechacrea;
	}

	@JSON
	@Override
	public long getUsuariomodifica() {
		return _usuariomodifica;
	}

	@Override
	public void setUsuariomodifica(long usuariomodifica) {
		_usuariomodifica = usuariomodifica;
	}

	@JSON
	@Override
	public Date getFechacreamodifica() {
		return _fechacreamodifica;
	}

	@Override
	public void setFechacreamodifica(Date fechacreamodifica) {
		_fechacreamodifica = fechacreamodifica;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Evaluacion.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Evaluacion toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Evaluacion)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EvaluacionImpl evaluacionImpl = new EvaluacionImpl();

		evaluacionImpl.setEvaluacionId(getEvaluacionId());
		evaluacionImpl.setTiempoMinuto(getTiempoMinuto());
		evaluacionImpl.setEnfoque(getEnfoque());
		evaluacionImpl.setPuestoEvaluacion(getPuestoEvaluacion());
		evaluacionImpl.setTiempoPuesto(getTiempoPuesto());
		evaluacionImpl.setTipoEvaluacion(getTipoEvaluacion());
		evaluacionImpl.setActivo(getActivo());
		evaluacionImpl.setUsuariocrea(getUsuariocrea());
		evaluacionImpl.setFechacrea(getFechacrea());
		evaluacionImpl.setUsuariomodifica(getUsuariomodifica());
		evaluacionImpl.setFechacreamodifica(getFechacreamodifica());

		evaluacionImpl.resetOriginalValues();

		return evaluacionImpl;
	}

	@Override
	public int compareTo(Evaluacion evaluacion) {
		int value = 0;

		value = DateUtil.compareTo(getFechacrea(), evaluacion.getFechacrea());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Evaluacion)) {
			return false;
		}

		Evaluacion evaluacion = (Evaluacion)obj;

		long primaryKey = evaluacion.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Evaluacion> toCacheModel() {
		EvaluacionCacheModel evaluacionCacheModel = new EvaluacionCacheModel();

		evaluacionCacheModel.evaluacionId = getEvaluacionId();

		evaluacionCacheModel.tiempoMinuto = getTiempoMinuto();

		evaluacionCacheModel.enfoque = getEnfoque();

		evaluacionCacheModel.puestoEvaluacion = getPuestoEvaluacion();

		evaluacionCacheModel.tiempoPuesto = getTiempoPuesto();

		evaluacionCacheModel.TipoEvaluacion = getTipoEvaluacion();

		evaluacionCacheModel.activo = getActivo();

		evaluacionCacheModel.usuariocrea = getUsuariocrea();

		Date fechacrea = getFechacrea();

		if (fechacrea != null) {
			evaluacionCacheModel.fechacrea = fechacrea.getTime();
		}
		else {
			evaluacionCacheModel.fechacrea = Long.MIN_VALUE;
		}

		evaluacionCacheModel.usuariomodifica = getUsuariomodifica();

		Date fechacreamodifica = getFechacreamodifica();

		if (fechacreamodifica != null) {
			evaluacionCacheModel.fechacreamodifica = fechacreamodifica.getTime();
		}
		else {
			evaluacionCacheModel.fechacreamodifica = Long.MIN_VALUE;
		}

		return evaluacionCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{evaluacionId=");
		sb.append(getEvaluacionId());
		sb.append(", tiempoMinuto=");
		sb.append(getTiempoMinuto());
		sb.append(", enfoque=");
		sb.append(getEnfoque());
		sb.append(", puestoEvaluacion=");
		sb.append(getPuestoEvaluacion());
		sb.append(", tiempoPuesto=");
		sb.append(getTiempoPuesto());
		sb.append(", TipoEvaluacion=");
		sb.append(getTipoEvaluacion());
		sb.append(", activo=");
		sb.append(getActivo());
		sb.append(", usuariocrea=");
		sb.append(getUsuariocrea());
		sb.append(", fechacrea=");
		sb.append(getFechacrea());
		sb.append(", usuariomodifica=");
		sb.append(getUsuariomodifica());
		sb.append(", fechacreamodifica=");
		sb.append(getFechacreamodifica());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("com.rec.hitss.layer.model.Evaluacion");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>evaluacionId</column-name><column-value><![CDATA[");
		sb.append(getEvaluacionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tiempoMinuto</column-name><column-value><![CDATA[");
		sb.append(getTiempoMinuto());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>enfoque</column-name><column-value><![CDATA[");
		sb.append(getEnfoque());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>puestoEvaluacion</column-name><column-value><![CDATA[");
		sb.append(getPuestoEvaluacion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tiempoPuesto</column-name><column-value><![CDATA[");
		sb.append(getTiempoPuesto());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>TipoEvaluacion</column-name><column-value><![CDATA[");
		sb.append(getTipoEvaluacion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>activo</column-name><column-value><![CDATA[");
		sb.append(getActivo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>usuariocrea</column-name><column-value><![CDATA[");
		sb.append(getUsuariocrea());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fechacrea</column-name><column-value><![CDATA[");
		sb.append(getFechacrea());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>usuariomodifica</column-name><column-value><![CDATA[");
		sb.append(getUsuariomodifica());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fechacreamodifica</column-name><column-value><![CDATA[");
		sb.append(getFechacreamodifica());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Evaluacion.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			Evaluacion.class
		};
	private long _evaluacionId;
	private long _tiempoMinuto;
	private long _enfoque;
	private long _puestoEvaluacion;
	private long _tiempoPuesto;
	private long _TipoEvaluacion;
	private boolean _activo;
	private long _usuariocrea;
	private Date _fechacrea;
	private long _usuariomodifica;
	private Date _fechacreamodifica;
	private Evaluacion _escapedModel;
}