/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rec.hitss.layer.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.rec.hitss.layer.model.InformeRetroalimentacion;
import com.rec.hitss.layer.model.InformeRetroalimentacionModel;
import com.rec.hitss.layer.model.InformeRetroalimentacionSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the InformeRetroalimentacion service. Represents a row in the &quot;InformeRetroalimentacion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.rec.hitss.layer.model.InformeRetroalimentacionModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link InformeRetroalimentacionImpl}.
 * </p>
 *
 * @author Crossfire
 * @see InformeRetroalimentacionImpl
 * @see com.rec.hitss.layer.model.InformeRetroalimentacion
 * @see com.rec.hitss.layer.model.InformeRetroalimentacionModel
 * @generated
 */
@JSON(strict = true)
public class InformeRetroalimentacionModelImpl extends BaseModelImpl<InformeRetroalimentacion>
	implements InformeRetroalimentacionModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a informe retroalimentacion model instance should use the {@link com.rec.hitss.layer.model.InformeRetroalimentacion} interface instead.
	 */
	public static final String TABLE_NAME = "InformeRetroalimentacion";
	public static final Object[][] TABLE_COLUMNS = {
			{ "informeRetroalimentacionId", Types.BIGINT },
			{ "planAccionId", Types.BIGINT },
			{ "responsable", Types.VARCHAR },
			{ "fechaEmision", Types.VARCHAR },
			{ "titulo", Types.VARCHAR },
			{ "integrante", Types.VARCHAR },
			{ "descripcion", Types.VARCHAR },
			{ "activo", Types.BOOLEAN },
			{ "usuariocrea", Types.BIGINT },
			{ "fechacrea", Types.TIMESTAMP },
			{ "usuariomodifica", Types.BIGINT },
			{ "fechacreamodifica", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table InformeRetroalimentacion (informeRetroalimentacionId LONG not null primary key,planAccionId LONG,responsable VARCHAR(75) null,fechaEmision VARCHAR(75) null,titulo VARCHAR(75) null,integrante VARCHAR(75) null,descripcion VARCHAR(75) null,activo BOOLEAN,usuariocrea LONG,fechacrea DATE null,usuariomodifica LONG,fechacreamodifica DATE null)";
	public static final String TABLE_SQL_DROP = "drop table InformeRetroalimentacion";
	public static final String ORDER_BY_JPQL = " ORDER BY informeRetroalimentacion.fechacrea ASC";
	public static final String ORDER_BY_SQL = " ORDER BY InformeRetroalimentacion.fechacrea ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rec.hitss.layer.model.InformeRetroalimentacion"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rec.hitss.layer.model.InformeRetroalimentacion"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static InformeRetroalimentacion toModel(
		InformeRetroalimentacionSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		InformeRetroalimentacion model = new InformeRetroalimentacionImpl();

		model.setInformeRetroalimentacionId(soapModel.getInformeRetroalimentacionId());
		model.setPlanAccionId(soapModel.getPlanAccionId());
		model.setResponsable(soapModel.getResponsable());
		model.setFechaEmision(soapModel.getFechaEmision());
		model.setTitulo(soapModel.getTitulo());
		model.setIntegrante(soapModel.getIntegrante());
		model.setDescripcion(soapModel.getDescripcion());
		model.setActivo(soapModel.getActivo());
		model.setUsuariocrea(soapModel.getUsuariocrea());
		model.setFechacrea(soapModel.getFechacrea());
		model.setUsuariomodifica(soapModel.getUsuariomodifica());
		model.setFechacreamodifica(soapModel.getFechacreamodifica());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<InformeRetroalimentacion> toModels(
		InformeRetroalimentacionSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<InformeRetroalimentacion> models = new ArrayList<InformeRetroalimentacion>(soapModels.length);

		for (InformeRetroalimentacionSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.rec.hitss.layer.model.InformeRetroalimentacion"));

	public InformeRetroalimentacionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _informeRetroalimentacionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setInformeRetroalimentacionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _informeRetroalimentacionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return InformeRetroalimentacion.class;
	}

	@Override
	public String getModelClassName() {
		return InformeRetroalimentacion.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("informeRetroalimentacionId",
			getInformeRetroalimentacionId());
		attributes.put("planAccionId", getPlanAccionId());
		attributes.put("responsable", getResponsable());
		attributes.put("fechaEmision", getFechaEmision());
		attributes.put("titulo", getTitulo());
		attributes.put("integrante", getIntegrante());
		attributes.put("descripcion", getDescripcion());
		attributes.put("activo", getActivo());
		attributes.put("usuariocrea", getUsuariocrea());
		attributes.put("fechacrea", getFechacrea());
		attributes.put("usuariomodifica", getUsuariomodifica());
		attributes.put("fechacreamodifica", getFechacreamodifica());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long informeRetroalimentacionId = (Long)attributes.get(
				"informeRetroalimentacionId");

		if (informeRetroalimentacionId != null) {
			setInformeRetroalimentacionId(informeRetroalimentacionId);
		}

		Long planAccionId = (Long)attributes.get("planAccionId");

		if (planAccionId != null) {
			setPlanAccionId(planAccionId);
		}

		String responsable = (String)attributes.get("responsable");

		if (responsable != null) {
			setResponsable(responsable);
		}

		String fechaEmision = (String)attributes.get("fechaEmision");

		if (fechaEmision != null) {
			setFechaEmision(fechaEmision);
		}

		String titulo = (String)attributes.get("titulo");

		if (titulo != null) {
			setTitulo(titulo);
		}

		String integrante = (String)attributes.get("integrante");

		if (integrante != null) {
			setIntegrante(integrante);
		}

		String descripcion = (String)attributes.get("descripcion");

		if (descripcion != null) {
			setDescripcion(descripcion);
		}

		Boolean activo = (Boolean)attributes.get("activo");

		if (activo != null) {
			setActivo(activo);
		}

		Long usuariocrea = (Long)attributes.get("usuariocrea");

		if (usuariocrea != null) {
			setUsuariocrea(usuariocrea);
		}

		Date fechacrea = (Date)attributes.get("fechacrea");

		if (fechacrea != null) {
			setFechacrea(fechacrea);
		}

		Long usuariomodifica = (Long)attributes.get("usuariomodifica");

		if (usuariomodifica != null) {
			setUsuariomodifica(usuariomodifica);
		}

		Date fechacreamodifica = (Date)attributes.get("fechacreamodifica");

		if (fechacreamodifica != null) {
			setFechacreamodifica(fechacreamodifica);
		}
	}

	@JSON
	@Override
	public long getInformeRetroalimentacionId() {
		return _informeRetroalimentacionId;
	}

	@Override
	public void setInformeRetroalimentacionId(long informeRetroalimentacionId) {
		_informeRetroalimentacionId = informeRetroalimentacionId;
	}

	@JSON
	@Override
	public long getPlanAccionId() {
		return _planAccionId;
	}

	@Override
	public void setPlanAccionId(long planAccionId) {
		_planAccionId = planAccionId;
	}

	@JSON
	@Override
	public String getResponsable() {
		if (_responsable == null) {
			return StringPool.BLANK;
		}
		else {
			return _responsable;
		}
	}

	@Override
	public void setResponsable(String responsable) {
		_responsable = responsable;
	}

	@JSON
	@Override
	public String getFechaEmision() {
		if (_fechaEmision == null) {
			return StringPool.BLANK;
		}
		else {
			return _fechaEmision;
		}
	}

	@Override
	public void setFechaEmision(String fechaEmision) {
		_fechaEmision = fechaEmision;
	}

	@JSON
	@Override
	public String getTitulo() {
		if (_titulo == null) {
			return StringPool.BLANK;
		}
		else {
			return _titulo;
		}
	}

	@Override
	public void setTitulo(String titulo) {
		_titulo = titulo;
	}

	@JSON
	@Override
	public String getIntegrante() {
		if (_integrante == null) {
			return StringPool.BLANK;
		}
		else {
			return _integrante;
		}
	}

	@Override
	public void setIntegrante(String integrante) {
		_integrante = integrante;
	}

	@JSON
	@Override
	public String getDescripcion() {
		if (_descripcion == null) {
			return StringPool.BLANK;
		}
		else {
			return _descripcion;
		}
	}

	@Override
	public void setDescripcion(String descripcion) {
		_descripcion = descripcion;
	}

	@JSON
	@Override
	public boolean getActivo() {
		return _activo;
	}

	@Override
	public boolean isActivo() {
		return _activo;
	}

	@Override
	public void setActivo(boolean activo) {
		_activo = activo;
	}

	@JSON
	@Override
	public long getUsuariocrea() {
		return _usuariocrea;
	}

	@Override
	public void setUsuariocrea(long usuariocrea) {
		_usuariocrea = usuariocrea;
	}

	@JSON
	@Override
	public Date getFechacrea() {
		return _fechacrea;
	}

	@Override
	public void setFechacrea(Date fechacrea) {
		_fechacrea = fechacrea;
	}

	@JSON
	@Override
	public long getUsuariomodifica() {
		return _usuariomodifica;
	}

	@Override
	public void setUsuariomodifica(long usuariomodifica) {
		_usuariomodifica = usuariomodifica;
	}

	@JSON
	@Override
	public Date getFechacreamodifica() {
		return _fechacreamodifica;
	}

	@Override
	public void setFechacreamodifica(Date fechacreamodifica) {
		_fechacreamodifica = fechacreamodifica;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			InformeRetroalimentacion.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public InformeRetroalimentacion toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (InformeRetroalimentacion)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		InformeRetroalimentacionImpl informeRetroalimentacionImpl = new InformeRetroalimentacionImpl();

		informeRetroalimentacionImpl.setInformeRetroalimentacionId(getInformeRetroalimentacionId());
		informeRetroalimentacionImpl.setPlanAccionId(getPlanAccionId());
		informeRetroalimentacionImpl.setResponsable(getResponsable());
		informeRetroalimentacionImpl.setFechaEmision(getFechaEmision());
		informeRetroalimentacionImpl.setTitulo(getTitulo());
		informeRetroalimentacionImpl.setIntegrante(getIntegrante());
		informeRetroalimentacionImpl.setDescripcion(getDescripcion());
		informeRetroalimentacionImpl.setActivo(getActivo());
		informeRetroalimentacionImpl.setUsuariocrea(getUsuariocrea());
		informeRetroalimentacionImpl.setFechacrea(getFechacrea());
		informeRetroalimentacionImpl.setUsuariomodifica(getUsuariomodifica());
		informeRetroalimentacionImpl.setFechacreamodifica(getFechacreamodifica());

		informeRetroalimentacionImpl.resetOriginalValues();

		return informeRetroalimentacionImpl;
	}

	@Override
	public int compareTo(InformeRetroalimentacion informeRetroalimentacion) {
		int value = 0;

		value = DateUtil.compareTo(getFechacrea(),
				informeRetroalimentacion.getFechacrea());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof InformeRetroalimentacion)) {
			return false;
		}

		InformeRetroalimentacion informeRetroalimentacion = (InformeRetroalimentacion)obj;

		long primaryKey = informeRetroalimentacion.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<InformeRetroalimentacion> toCacheModel() {
		InformeRetroalimentacionCacheModel informeRetroalimentacionCacheModel = new InformeRetroalimentacionCacheModel();

		informeRetroalimentacionCacheModel.informeRetroalimentacionId = getInformeRetroalimentacionId();

		informeRetroalimentacionCacheModel.planAccionId = getPlanAccionId();

		informeRetroalimentacionCacheModel.responsable = getResponsable();

		String responsable = informeRetroalimentacionCacheModel.responsable;

		if ((responsable != null) && (responsable.length() == 0)) {
			informeRetroalimentacionCacheModel.responsable = null;
		}

		informeRetroalimentacionCacheModel.fechaEmision = getFechaEmision();

		String fechaEmision = informeRetroalimentacionCacheModel.fechaEmision;

		if ((fechaEmision != null) && (fechaEmision.length() == 0)) {
			informeRetroalimentacionCacheModel.fechaEmision = null;
		}

		informeRetroalimentacionCacheModel.titulo = getTitulo();

		String titulo = informeRetroalimentacionCacheModel.titulo;

		if ((titulo != null) && (titulo.length() == 0)) {
			informeRetroalimentacionCacheModel.titulo = null;
		}

		informeRetroalimentacionCacheModel.integrante = getIntegrante();

		String integrante = informeRetroalimentacionCacheModel.integrante;

		if ((integrante != null) && (integrante.length() == 0)) {
			informeRetroalimentacionCacheModel.integrante = null;
		}

		informeRetroalimentacionCacheModel.descripcion = getDescripcion();

		String descripcion = informeRetroalimentacionCacheModel.descripcion;

		if ((descripcion != null) && (descripcion.length() == 0)) {
			informeRetroalimentacionCacheModel.descripcion = null;
		}

		informeRetroalimentacionCacheModel.activo = getActivo();

		informeRetroalimentacionCacheModel.usuariocrea = getUsuariocrea();

		Date fechacrea = getFechacrea();

		if (fechacrea != null) {
			informeRetroalimentacionCacheModel.fechacrea = fechacrea.getTime();
		}
		else {
			informeRetroalimentacionCacheModel.fechacrea = Long.MIN_VALUE;
		}

		informeRetroalimentacionCacheModel.usuariomodifica = getUsuariomodifica();

		Date fechacreamodifica = getFechacreamodifica();

		if (fechacreamodifica != null) {
			informeRetroalimentacionCacheModel.fechacreamodifica = fechacreamodifica.getTime();
		}
		else {
			informeRetroalimentacionCacheModel.fechacreamodifica = Long.MIN_VALUE;
		}

		return informeRetroalimentacionCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(25);

		sb.append("{informeRetroalimentacionId=");
		sb.append(getInformeRetroalimentacionId());
		sb.append(", planAccionId=");
		sb.append(getPlanAccionId());
		sb.append(", responsable=");
		sb.append(getResponsable());
		sb.append(", fechaEmision=");
		sb.append(getFechaEmision());
		sb.append(", titulo=");
		sb.append(getTitulo());
		sb.append(", integrante=");
		sb.append(getIntegrante());
		sb.append(", descripcion=");
		sb.append(getDescripcion());
		sb.append(", activo=");
		sb.append(getActivo());
		sb.append(", usuariocrea=");
		sb.append(getUsuariocrea());
		sb.append(", fechacrea=");
		sb.append(getFechacrea());
		sb.append(", usuariomodifica=");
		sb.append(getUsuariomodifica());
		sb.append(", fechacreamodifica=");
		sb.append(getFechacreamodifica());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(40);

		sb.append("<model><model-name>");
		sb.append("com.rec.hitss.layer.model.InformeRetroalimentacion");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>informeRetroalimentacionId</column-name><column-value><![CDATA[");
		sb.append(getInformeRetroalimentacionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>planAccionId</column-name><column-value><![CDATA[");
		sb.append(getPlanAccionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>responsable</column-name><column-value><![CDATA[");
		sb.append(getResponsable());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fechaEmision</column-name><column-value><![CDATA[");
		sb.append(getFechaEmision());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>titulo</column-name><column-value><![CDATA[");
		sb.append(getTitulo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>integrante</column-name><column-value><![CDATA[");
		sb.append(getIntegrante());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>descripcion</column-name><column-value><![CDATA[");
		sb.append(getDescripcion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>activo</column-name><column-value><![CDATA[");
		sb.append(getActivo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>usuariocrea</column-name><column-value><![CDATA[");
		sb.append(getUsuariocrea());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fechacrea</column-name><column-value><![CDATA[");
		sb.append(getFechacrea());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>usuariomodifica</column-name><column-value><![CDATA[");
		sb.append(getUsuariomodifica());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fechacreamodifica</column-name><column-value><![CDATA[");
		sb.append(getFechacreamodifica());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = InformeRetroalimentacion.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			InformeRetroalimentacion.class
		};
	private long _informeRetroalimentacionId;
	private long _planAccionId;
	private String _responsable;
	private String _fechaEmision;
	private String _titulo;
	private String _integrante;
	private String _descripcion;
	private boolean _activo;
	private long _usuariocrea;
	private Date _fechacrea;
	private long _usuariomodifica;
	private Date _fechacreamodifica;
	private InformeRetroalimentacion _escapedModel;
}