/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rec.hitss.layer.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.rec.hitss.layer.model.PrioridadEquipos;
import com.rec.hitss.layer.model.PrioridadEquiposModel;
import com.rec.hitss.layer.model.PrioridadEquiposSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the PrioridadEquipos service. Represents a row in the &quot;PrioridadEquipos&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.rec.hitss.layer.model.PrioridadEquiposModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PrioridadEquiposImpl}.
 * </p>
 *
 * @author Crossfire
 * @see PrioridadEquiposImpl
 * @see com.rec.hitss.layer.model.PrioridadEquipos
 * @see com.rec.hitss.layer.model.PrioridadEquiposModel
 * @generated
 */
@JSON(strict = true)
public class PrioridadEquiposModelImpl extends BaseModelImpl<PrioridadEquipos>
	implements PrioridadEquiposModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a prioridad equipos model instance should use the {@link com.rec.hitss.layer.model.PrioridadEquipos} interface instead.
	 */
	public static final String TABLE_NAME = "PrioridadEquipos";
	public static final Object[][] TABLE_COLUMNS = {
			{ "prioridadEquiposId", Types.BIGINT },
			{ "solicitudEvaluacionDesempenoId", Types.BIGINT },
			{ "responsable", Types.BIGINT },
			{ "activo", Types.BOOLEAN },
			{ "usuariocrea", Types.BIGINT },
			{ "fechacrea", Types.TIMESTAMP },
			{ "usuariomodifica", Types.BIGINT },
			{ "fechacreamodifica", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table PrioridadEquipos (prioridadEquiposId LONG not null primary key,solicitudEvaluacionDesempenoId LONG,responsable LONG,activo BOOLEAN,usuariocrea LONG,fechacrea DATE null,usuariomodifica LONG,fechacreamodifica DATE null)";
	public static final String TABLE_SQL_DROP = "drop table PrioridadEquipos";
	public static final String ORDER_BY_JPQL = " ORDER BY prioridadEquipos.fechacrea ASC";
	public static final String ORDER_BY_SQL = " ORDER BY PrioridadEquipos.fechacrea ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rec.hitss.layer.model.PrioridadEquipos"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rec.hitss.layer.model.PrioridadEquipos"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static PrioridadEquipos toModel(PrioridadEquiposSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		PrioridadEquipos model = new PrioridadEquiposImpl();

		model.setPrioridadEquiposId(soapModel.getPrioridadEquiposId());
		model.setSolicitudEvaluacionDesempenoId(soapModel.getSolicitudEvaluacionDesempenoId());
		model.setResponsable(soapModel.getResponsable());
		model.setActivo(soapModel.getActivo());
		model.setUsuariocrea(soapModel.getUsuariocrea());
		model.setFechacrea(soapModel.getFechacrea());
		model.setUsuariomodifica(soapModel.getUsuariomodifica());
		model.setFechacreamodifica(soapModel.getFechacreamodifica());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<PrioridadEquipos> toModels(
		PrioridadEquiposSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<PrioridadEquipos> models = new ArrayList<PrioridadEquipos>(soapModels.length);

		for (PrioridadEquiposSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.rec.hitss.layer.model.PrioridadEquipos"));

	public PrioridadEquiposModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _prioridadEquiposId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPrioridadEquiposId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _prioridadEquiposId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PrioridadEquipos.class;
	}

	@Override
	public String getModelClassName() {
		return PrioridadEquipos.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("prioridadEquiposId", getPrioridadEquiposId());
		attributes.put("solicitudEvaluacionDesempenoId",
			getSolicitudEvaluacionDesempenoId());
		attributes.put("responsable", getResponsable());
		attributes.put("activo", getActivo());
		attributes.put("usuariocrea", getUsuariocrea());
		attributes.put("fechacrea", getFechacrea());
		attributes.put("usuariomodifica", getUsuariomodifica());
		attributes.put("fechacreamodifica", getFechacreamodifica());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long prioridadEquiposId = (Long)attributes.get("prioridadEquiposId");

		if (prioridadEquiposId != null) {
			setPrioridadEquiposId(prioridadEquiposId);
		}

		Long solicitudEvaluacionDesempenoId = (Long)attributes.get(
				"solicitudEvaluacionDesempenoId");

		if (solicitudEvaluacionDesempenoId != null) {
			setSolicitudEvaluacionDesempenoId(solicitudEvaluacionDesempenoId);
		}

		Long responsable = (Long)attributes.get("responsable");

		if (responsable != null) {
			setResponsable(responsable);
		}

		Boolean activo = (Boolean)attributes.get("activo");

		if (activo != null) {
			setActivo(activo);
		}

		Long usuariocrea = (Long)attributes.get("usuariocrea");

		if (usuariocrea != null) {
			setUsuariocrea(usuariocrea);
		}

		Date fechacrea = (Date)attributes.get("fechacrea");

		if (fechacrea != null) {
			setFechacrea(fechacrea);
		}

		Long usuariomodifica = (Long)attributes.get("usuariomodifica");

		if (usuariomodifica != null) {
			setUsuariomodifica(usuariomodifica);
		}

		Date fechacreamodifica = (Date)attributes.get("fechacreamodifica");

		if (fechacreamodifica != null) {
			setFechacreamodifica(fechacreamodifica);
		}
	}

	@JSON
	@Override
	public long getPrioridadEquiposId() {
		return _prioridadEquiposId;
	}

	@Override
	public void setPrioridadEquiposId(long prioridadEquiposId) {
		_prioridadEquiposId = prioridadEquiposId;
	}

	@JSON
	@Override
	public long getSolicitudEvaluacionDesempenoId() {
		return _solicitudEvaluacionDesempenoId;
	}

	@Override
	public void setSolicitudEvaluacionDesempenoId(
		long solicitudEvaluacionDesempenoId) {
		_solicitudEvaluacionDesempenoId = solicitudEvaluacionDesempenoId;
	}

	@JSON
	@Override
	public long getResponsable() {
		return _responsable;
	}

	@Override
	public void setResponsable(long responsable) {
		_responsable = responsable;
	}

	@JSON
	@Override
	public boolean getActivo() {
		return _activo;
	}

	@Override
	public boolean isActivo() {
		return _activo;
	}

	@Override
	public void setActivo(boolean activo) {
		_activo = activo;
	}

	@JSON
	@Override
	public long getUsuariocrea() {
		return _usuariocrea;
	}

	@Override
	public void setUsuariocrea(long usuariocrea) {
		_usuariocrea = usuariocrea;
	}

	@JSON
	@Override
	public Date getFechacrea() {
		return _fechacrea;
	}

	@Override
	public void setFechacrea(Date fechacrea) {
		_fechacrea = fechacrea;
	}

	@JSON
	@Override
	public long getUsuariomodifica() {
		return _usuariomodifica;
	}

	@Override
	public void setUsuariomodifica(long usuariomodifica) {
		_usuariomodifica = usuariomodifica;
	}

	@JSON
	@Override
	public Date getFechacreamodifica() {
		return _fechacreamodifica;
	}

	@Override
	public void setFechacreamodifica(Date fechacreamodifica) {
		_fechacreamodifica = fechacreamodifica;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			PrioridadEquipos.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PrioridadEquipos toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (PrioridadEquipos)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PrioridadEquiposImpl prioridadEquiposImpl = new PrioridadEquiposImpl();

		prioridadEquiposImpl.setPrioridadEquiposId(getPrioridadEquiposId());
		prioridadEquiposImpl.setSolicitudEvaluacionDesempenoId(getSolicitudEvaluacionDesempenoId());
		prioridadEquiposImpl.setResponsable(getResponsable());
		prioridadEquiposImpl.setActivo(getActivo());
		prioridadEquiposImpl.setUsuariocrea(getUsuariocrea());
		prioridadEquiposImpl.setFechacrea(getFechacrea());
		prioridadEquiposImpl.setUsuariomodifica(getUsuariomodifica());
		prioridadEquiposImpl.setFechacreamodifica(getFechacreamodifica());

		prioridadEquiposImpl.resetOriginalValues();

		return prioridadEquiposImpl;
	}

	@Override
	public int compareTo(PrioridadEquipos prioridadEquipos) {
		int value = 0;

		value = DateUtil.compareTo(getFechacrea(),
				prioridadEquipos.getFechacrea());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof PrioridadEquipos)) {
			return false;
		}

		PrioridadEquipos prioridadEquipos = (PrioridadEquipos)obj;

		long primaryKey = prioridadEquipos.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<PrioridadEquipos> toCacheModel() {
		PrioridadEquiposCacheModel prioridadEquiposCacheModel = new PrioridadEquiposCacheModel();

		prioridadEquiposCacheModel.prioridadEquiposId = getPrioridadEquiposId();

		prioridadEquiposCacheModel.solicitudEvaluacionDesempenoId = getSolicitudEvaluacionDesempenoId();

		prioridadEquiposCacheModel.responsable = getResponsable();

		prioridadEquiposCacheModel.activo = getActivo();

		prioridadEquiposCacheModel.usuariocrea = getUsuariocrea();

		Date fechacrea = getFechacrea();

		if (fechacrea != null) {
			prioridadEquiposCacheModel.fechacrea = fechacrea.getTime();
		}
		else {
			prioridadEquiposCacheModel.fechacrea = Long.MIN_VALUE;
		}

		prioridadEquiposCacheModel.usuariomodifica = getUsuariomodifica();

		Date fechacreamodifica = getFechacreamodifica();

		if (fechacreamodifica != null) {
			prioridadEquiposCacheModel.fechacreamodifica = fechacreamodifica.getTime();
		}
		else {
			prioridadEquiposCacheModel.fechacreamodifica = Long.MIN_VALUE;
		}

		return prioridadEquiposCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{prioridadEquiposId=");
		sb.append(getPrioridadEquiposId());
		sb.append(", solicitudEvaluacionDesempenoId=");
		sb.append(getSolicitudEvaluacionDesempenoId());
		sb.append(", responsable=");
		sb.append(getResponsable());
		sb.append(", activo=");
		sb.append(getActivo());
		sb.append(", usuariocrea=");
		sb.append(getUsuariocrea());
		sb.append(", fechacrea=");
		sb.append(getFechacrea());
		sb.append(", usuariomodifica=");
		sb.append(getUsuariomodifica());
		sb.append(", fechacreamodifica=");
		sb.append(getFechacreamodifica());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("com.rec.hitss.layer.model.PrioridadEquipos");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>prioridadEquiposId</column-name><column-value><![CDATA[");
		sb.append(getPrioridadEquiposId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>solicitudEvaluacionDesempenoId</column-name><column-value><![CDATA[");
		sb.append(getSolicitudEvaluacionDesempenoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>responsable</column-name><column-value><![CDATA[");
		sb.append(getResponsable());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>activo</column-name><column-value><![CDATA[");
		sb.append(getActivo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>usuariocrea</column-name><column-value><![CDATA[");
		sb.append(getUsuariocrea());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fechacrea</column-name><column-value><![CDATA[");
		sb.append(getFechacrea());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>usuariomodifica</column-name><column-value><![CDATA[");
		sb.append(getUsuariomodifica());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fechacreamodifica</column-name><column-value><![CDATA[");
		sb.append(getFechacreamodifica());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = PrioridadEquipos.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			PrioridadEquipos.class
		};
	private long _prioridadEquiposId;
	private long _solicitudEvaluacionDesempenoId;
	private long _responsable;
	private boolean _activo;
	private long _usuariocrea;
	private Date _fechacrea;
	private long _usuariomodifica;
	private Date _fechacreamodifica;
	private PrioridadEquipos _escapedModel;
}