/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rec.hitss.layer.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.rec.hitss.layer.model.ResultadoEvaluacion;
import com.rec.hitss.layer.model.ResultadoEvaluacionModel;
import com.rec.hitss.layer.model.ResultadoEvaluacionSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the ResultadoEvaluacion service. Represents a row in the &quot;ResultadoEvaluacion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.rec.hitss.layer.model.ResultadoEvaluacionModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ResultadoEvaluacionImpl}.
 * </p>
 *
 * @author Crossfire
 * @see ResultadoEvaluacionImpl
 * @see com.rec.hitss.layer.model.ResultadoEvaluacion
 * @see com.rec.hitss.layer.model.ResultadoEvaluacionModel
 * @generated
 */
@JSON(strict = true)
public class ResultadoEvaluacionModelImpl extends BaseModelImpl<ResultadoEvaluacion>
	implements ResultadoEvaluacionModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a resultado evaluacion model instance should use the {@link com.rec.hitss.layer.model.ResultadoEvaluacion} interface instead.
	 */
	public static final String TABLE_NAME = "ResultadoEvaluacion";
	public static final Object[][] TABLE_COLUMNS = {
			{ "resultadoEvaluacionId", Types.BIGINT },
			{ "respuestaSelccionada", Types.BIGINT },
			{ "habilidadCumplida", Types.BOOLEAN },
			{ "evaluacionId", Types.BIGINT },
			{ "usuarioHitssId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table ResultadoEvaluacion (resultadoEvaluacionId LONG not null primary key,respuestaSelccionada LONG,habilidadCumplida BOOLEAN,evaluacionId LONG,usuarioHitssId LONG)";
	public static final String TABLE_SQL_DROP = "drop table ResultadoEvaluacion";
	public static final String ORDER_BY_JPQL = " ORDER BY resultadoEvaluacion.resultadoEvaluacionId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY ResultadoEvaluacion.resultadoEvaluacionId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rec.hitss.layer.model.ResultadoEvaluacion"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rec.hitss.layer.model.ResultadoEvaluacion"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ResultadoEvaluacion toModel(ResultadoEvaluacionSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ResultadoEvaluacion model = new ResultadoEvaluacionImpl();

		model.setResultadoEvaluacionId(soapModel.getResultadoEvaluacionId());
		model.setRespuestaSelccionada(soapModel.getRespuestaSelccionada());
		model.setHabilidadCumplida(soapModel.getHabilidadCumplida());
		model.setEvaluacionId(soapModel.getEvaluacionId());
		model.setUsuarioHitssId(soapModel.getUsuarioHitssId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ResultadoEvaluacion> toModels(
		ResultadoEvaluacionSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ResultadoEvaluacion> models = new ArrayList<ResultadoEvaluacion>(soapModels.length);

		for (ResultadoEvaluacionSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.rec.hitss.layer.model.ResultadoEvaluacion"));

	public ResultadoEvaluacionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _resultadoEvaluacionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setResultadoEvaluacionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _resultadoEvaluacionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ResultadoEvaluacion.class;
	}

	@Override
	public String getModelClassName() {
		return ResultadoEvaluacion.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("resultadoEvaluacionId", getResultadoEvaluacionId());
		attributes.put("respuestaSelccionada", getRespuestaSelccionada());
		attributes.put("habilidadCumplida", getHabilidadCumplida());
		attributes.put("evaluacionId", getEvaluacionId());
		attributes.put("usuarioHitssId", getUsuarioHitssId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long resultadoEvaluacionId = (Long)attributes.get(
				"resultadoEvaluacionId");

		if (resultadoEvaluacionId != null) {
			setResultadoEvaluacionId(resultadoEvaluacionId);
		}

		Long respuestaSelccionada = (Long)attributes.get("respuestaSelccionada");

		if (respuestaSelccionada != null) {
			setRespuestaSelccionada(respuestaSelccionada);
		}

		Boolean habilidadCumplida = (Boolean)attributes.get("habilidadCumplida");

		if (habilidadCumplida != null) {
			setHabilidadCumplida(habilidadCumplida);
		}

		Long evaluacionId = (Long)attributes.get("evaluacionId");

		if (evaluacionId != null) {
			setEvaluacionId(evaluacionId);
		}

		Long usuarioHitssId = (Long)attributes.get("usuarioHitssId");

		if (usuarioHitssId != null) {
			setUsuarioHitssId(usuarioHitssId);
		}
	}

	@JSON
	@Override
	public long getResultadoEvaluacionId() {
		return _resultadoEvaluacionId;
	}

	@Override
	public void setResultadoEvaluacionId(long resultadoEvaluacionId) {
		_resultadoEvaluacionId = resultadoEvaluacionId;
	}

	@JSON
	@Override
	public long getRespuestaSelccionada() {
		return _respuestaSelccionada;
	}

	@Override
	public void setRespuestaSelccionada(long respuestaSelccionada) {
		_respuestaSelccionada = respuestaSelccionada;
	}

	@JSON
	@Override
	public boolean getHabilidadCumplida() {
		return _habilidadCumplida;
	}

	@Override
	public boolean isHabilidadCumplida() {
		return _habilidadCumplida;
	}

	@Override
	public void setHabilidadCumplida(boolean habilidadCumplida) {
		_habilidadCumplida = habilidadCumplida;
	}

	@JSON
	@Override
	public long getEvaluacionId() {
		return _evaluacionId;
	}

	@Override
	public void setEvaluacionId(long evaluacionId) {
		_evaluacionId = evaluacionId;
	}

	@JSON
	@Override
	public long getUsuarioHitssId() {
		return _usuarioHitssId;
	}

	@Override
	public void setUsuarioHitssId(long usuarioHitssId) {
		_usuarioHitssId = usuarioHitssId;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			ResultadoEvaluacion.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ResultadoEvaluacion toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ResultadoEvaluacion)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ResultadoEvaluacionImpl resultadoEvaluacionImpl = new ResultadoEvaluacionImpl();

		resultadoEvaluacionImpl.setResultadoEvaluacionId(getResultadoEvaluacionId());
		resultadoEvaluacionImpl.setRespuestaSelccionada(getRespuestaSelccionada());
		resultadoEvaluacionImpl.setHabilidadCumplida(getHabilidadCumplida());
		resultadoEvaluacionImpl.setEvaluacionId(getEvaluacionId());
		resultadoEvaluacionImpl.setUsuarioHitssId(getUsuarioHitssId());

		resultadoEvaluacionImpl.resetOriginalValues();

		return resultadoEvaluacionImpl;
	}

	@Override
	public int compareTo(ResultadoEvaluacion resultadoEvaluacion) {
		long primaryKey = resultadoEvaluacion.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ResultadoEvaluacion)) {
			return false;
		}

		ResultadoEvaluacion resultadoEvaluacion = (ResultadoEvaluacion)obj;

		long primaryKey = resultadoEvaluacion.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<ResultadoEvaluacion> toCacheModel() {
		ResultadoEvaluacionCacheModel resultadoEvaluacionCacheModel = new ResultadoEvaluacionCacheModel();

		resultadoEvaluacionCacheModel.resultadoEvaluacionId = getResultadoEvaluacionId();

		resultadoEvaluacionCacheModel.respuestaSelccionada = getRespuestaSelccionada();

		resultadoEvaluacionCacheModel.habilidadCumplida = getHabilidadCumplida();

		resultadoEvaluacionCacheModel.evaluacionId = getEvaluacionId();

		resultadoEvaluacionCacheModel.usuarioHitssId = getUsuarioHitssId();

		return resultadoEvaluacionCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{resultadoEvaluacionId=");
		sb.append(getResultadoEvaluacionId());
		sb.append(", respuestaSelccionada=");
		sb.append(getRespuestaSelccionada());
		sb.append(", habilidadCumplida=");
		sb.append(getHabilidadCumplida());
		sb.append(", evaluacionId=");
		sb.append(getEvaluacionId());
		sb.append(", usuarioHitssId=");
		sb.append(getUsuarioHitssId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("com.rec.hitss.layer.model.ResultadoEvaluacion");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>resultadoEvaluacionId</column-name><column-value><![CDATA[");
		sb.append(getResultadoEvaluacionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>respuestaSelccionada</column-name><column-value><![CDATA[");
		sb.append(getRespuestaSelccionada());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>habilidadCumplida</column-name><column-value><![CDATA[");
		sb.append(getHabilidadCumplida());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>evaluacionId</column-name><column-value><![CDATA[");
		sb.append(getEvaluacionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>usuarioHitssId</column-name><column-value><![CDATA[");
		sb.append(getUsuarioHitssId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ResultadoEvaluacion.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ResultadoEvaluacion.class
		};
	private long _resultadoEvaluacionId;
	private long _respuestaSelccionada;
	private boolean _habilidadCumplida;
	private long _evaluacionId;
	private long _usuarioHitssId;
	private ResultadoEvaluacion _escapedModel;
}