/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rec.hitss.layer.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.rec.hitss.layer.model.SolicitudEvaluacionDesempeno;
import com.rec.hitss.layer.model.SolicitudEvaluacionDesempenoModel;
import com.rec.hitss.layer.model.SolicitudEvaluacionDesempenoSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the SolicitudEvaluacionDesempeno service. Represents a row in the &quot;SolicitudEvaluacionDesempeno&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.rec.hitss.layer.model.SolicitudEvaluacionDesempenoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SolicitudEvaluacionDesempenoImpl}.
 * </p>
 *
 * @author Crossfire
 * @see SolicitudEvaluacionDesempenoImpl
 * @see com.rec.hitss.layer.model.SolicitudEvaluacionDesempeno
 * @see com.rec.hitss.layer.model.SolicitudEvaluacionDesempenoModel
 * @generated
 */
@JSON(strict = true)
public class SolicitudEvaluacionDesempenoModelImpl extends BaseModelImpl<SolicitudEvaluacionDesempeno>
	implements SolicitudEvaluacionDesempenoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a solicitud evaluacion desempeno model instance should use the {@link com.rec.hitss.layer.model.SolicitudEvaluacionDesempeno} interface instead.
	 */
	public static final String TABLE_NAME = "SolicitudEvaluacionDesempeno";
	public static final Object[][] TABLE_COLUMNS = {
			{ "solicitudEvaluacionDesempenoId", Types.BIGINT },
			{ "descripcion", Types.VARCHAR },
			{ "fechaIncioEvaluacion", Types.TIMESTAMP },
			{ "estado", Types.VARCHAR },
			{ "motivo", Types.VARCHAR },
			{ "observacion", Types.VARCHAR },
			{ "activo", Types.BOOLEAN },
			{ "usuariocrea", Types.BIGINT },
			{ "fechacrea", Types.TIMESTAMP },
			{ "usuariomodifica", Types.BIGINT },
			{ "fechacreamodifica", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table SolicitudEvaluacionDesempeno (solicitudEvaluacionDesempenoId LONG not null primary key,descripcion VARCHAR(75) null,fechaIncioEvaluacion DATE null,estado VARCHAR(75) null,motivo VARCHAR(75) null,observacion VARCHAR(75) null,activo BOOLEAN,usuariocrea LONG,fechacrea DATE null,usuariomodifica LONG,fechacreamodifica DATE null)";
	public static final String TABLE_SQL_DROP = "drop table SolicitudEvaluacionDesempeno";
	public static final String ORDER_BY_JPQL = " ORDER BY solicitudEvaluacionDesempeno.fechacrea ASC";
	public static final String ORDER_BY_SQL = " ORDER BY SolicitudEvaluacionDesempeno.fechacrea ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rec.hitss.layer.model.SolicitudEvaluacionDesempeno"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rec.hitss.layer.model.SolicitudEvaluacionDesempeno"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static SolicitudEvaluacionDesempeno toModel(
		SolicitudEvaluacionDesempenoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		SolicitudEvaluacionDesempeno model = new SolicitudEvaluacionDesempenoImpl();

		model.setSolicitudEvaluacionDesempenoId(soapModel.getSolicitudEvaluacionDesempenoId());
		model.setDescripcion(soapModel.getDescripcion());
		model.setFechaIncioEvaluacion(soapModel.getFechaIncioEvaluacion());
		model.setEstado(soapModel.getEstado());
		model.setMotivo(soapModel.getMotivo());
		model.setObservacion(soapModel.getObservacion());
		model.setActivo(soapModel.getActivo());
		model.setUsuariocrea(soapModel.getUsuariocrea());
		model.setFechacrea(soapModel.getFechacrea());
		model.setUsuariomodifica(soapModel.getUsuariomodifica());
		model.setFechacreamodifica(soapModel.getFechacreamodifica());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<SolicitudEvaluacionDesempeno> toModels(
		SolicitudEvaluacionDesempenoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<SolicitudEvaluacionDesempeno> models = new ArrayList<SolicitudEvaluacionDesempeno>(soapModels.length);

		for (SolicitudEvaluacionDesempenoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.rec.hitss.layer.model.SolicitudEvaluacionDesempeno"));

	public SolicitudEvaluacionDesempenoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _solicitudEvaluacionDesempenoId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSolicitudEvaluacionDesempenoId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _solicitudEvaluacionDesempenoId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SolicitudEvaluacionDesempeno.class;
	}

	@Override
	public String getModelClassName() {
		return SolicitudEvaluacionDesempeno.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("solicitudEvaluacionDesempenoId",
			getSolicitudEvaluacionDesempenoId());
		attributes.put("descripcion", getDescripcion());
		attributes.put("fechaIncioEvaluacion", getFechaIncioEvaluacion());
		attributes.put("estado", getEstado());
		attributes.put("motivo", getMotivo());
		attributes.put("observacion", getObservacion());
		attributes.put("activo", getActivo());
		attributes.put("usuariocrea", getUsuariocrea());
		attributes.put("fechacrea", getFechacrea());
		attributes.put("usuariomodifica", getUsuariomodifica());
		attributes.put("fechacreamodifica", getFechacreamodifica());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long solicitudEvaluacionDesempenoId = (Long)attributes.get(
				"solicitudEvaluacionDesempenoId");

		if (solicitudEvaluacionDesempenoId != null) {
			setSolicitudEvaluacionDesempenoId(solicitudEvaluacionDesempenoId);
		}

		String descripcion = (String)attributes.get("descripcion");

		if (descripcion != null) {
			setDescripcion(descripcion);
		}

		Date fechaIncioEvaluacion = (Date)attributes.get("fechaIncioEvaluacion");

		if (fechaIncioEvaluacion != null) {
			setFechaIncioEvaluacion(fechaIncioEvaluacion);
		}

		String estado = (String)attributes.get("estado");

		if (estado != null) {
			setEstado(estado);
		}

		String motivo = (String)attributes.get("motivo");

		if (motivo != null) {
			setMotivo(motivo);
		}

		String observacion = (String)attributes.get("observacion");

		if (observacion != null) {
			setObservacion(observacion);
		}

		Boolean activo = (Boolean)attributes.get("activo");

		if (activo != null) {
			setActivo(activo);
		}

		Long usuariocrea = (Long)attributes.get("usuariocrea");

		if (usuariocrea != null) {
			setUsuariocrea(usuariocrea);
		}

		Date fechacrea = (Date)attributes.get("fechacrea");

		if (fechacrea != null) {
			setFechacrea(fechacrea);
		}

		Long usuariomodifica = (Long)attributes.get("usuariomodifica");

		if (usuariomodifica != null) {
			setUsuariomodifica(usuariomodifica);
		}

		Date fechacreamodifica = (Date)attributes.get("fechacreamodifica");

		if (fechacreamodifica != null) {
			setFechacreamodifica(fechacreamodifica);
		}
	}

	@JSON
	@Override
	public long getSolicitudEvaluacionDesempenoId() {
		return _solicitudEvaluacionDesempenoId;
	}

	@Override
	public void setSolicitudEvaluacionDesempenoId(
		long solicitudEvaluacionDesempenoId) {
		_solicitudEvaluacionDesempenoId = solicitudEvaluacionDesempenoId;
	}

	@JSON
	@Override
	public String getDescripcion() {
		if (_descripcion == null) {
			return StringPool.BLANK;
		}
		else {
			return _descripcion;
		}
	}

	@Override
	public void setDescripcion(String descripcion) {
		_descripcion = descripcion;
	}

	@JSON
	@Override
	public Date getFechaIncioEvaluacion() {
		return _fechaIncioEvaluacion;
	}

	@Override
	public void setFechaIncioEvaluacion(Date fechaIncioEvaluacion) {
		_fechaIncioEvaluacion = fechaIncioEvaluacion;
	}

	@JSON
	@Override
	public String getEstado() {
		if (_estado == null) {
			return StringPool.BLANK;
		}
		else {
			return _estado;
		}
	}

	@Override
	public void setEstado(String estado) {
		_estado = estado;
	}

	@JSON
	@Override
	public String getMotivo() {
		if (_motivo == null) {
			return StringPool.BLANK;
		}
		else {
			return _motivo;
		}
	}

	@Override
	public void setMotivo(String motivo) {
		_motivo = motivo;
	}

	@JSON
	@Override
	public String getObservacion() {
		if (_observacion == null) {
			return StringPool.BLANK;
		}
		else {
			return _observacion;
		}
	}

	@Override
	public void setObservacion(String observacion) {
		_observacion = observacion;
	}

	@JSON
	@Override
	public boolean getActivo() {
		return _activo;
	}

	@Override
	public boolean isActivo() {
		return _activo;
	}

	@Override
	public void setActivo(boolean activo) {
		_activo = activo;
	}

	@JSON
	@Override
	public long getUsuariocrea() {
		return _usuariocrea;
	}

	@Override
	public void setUsuariocrea(long usuariocrea) {
		_usuariocrea = usuariocrea;
	}

	@JSON
	@Override
	public Date getFechacrea() {
		return _fechacrea;
	}

	@Override
	public void setFechacrea(Date fechacrea) {
		_fechacrea = fechacrea;
	}

	@JSON
	@Override
	public long getUsuariomodifica() {
		return _usuariomodifica;
	}

	@Override
	public void setUsuariomodifica(long usuariomodifica) {
		_usuariomodifica = usuariomodifica;
	}

	@JSON
	@Override
	public Date getFechacreamodifica() {
		return _fechacreamodifica;
	}

	@Override
	public void setFechacreamodifica(Date fechacreamodifica) {
		_fechacreamodifica = fechacreamodifica;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			SolicitudEvaluacionDesempeno.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SolicitudEvaluacionDesempeno toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (SolicitudEvaluacionDesempeno)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SolicitudEvaluacionDesempenoImpl solicitudEvaluacionDesempenoImpl = new SolicitudEvaluacionDesempenoImpl();

		solicitudEvaluacionDesempenoImpl.setSolicitudEvaluacionDesempenoId(getSolicitudEvaluacionDesempenoId());
		solicitudEvaluacionDesempenoImpl.setDescripcion(getDescripcion());
		solicitudEvaluacionDesempenoImpl.setFechaIncioEvaluacion(getFechaIncioEvaluacion());
		solicitudEvaluacionDesempenoImpl.setEstado(getEstado());
		solicitudEvaluacionDesempenoImpl.setMotivo(getMotivo());
		solicitudEvaluacionDesempenoImpl.setObservacion(getObservacion());
		solicitudEvaluacionDesempenoImpl.setActivo(getActivo());
		solicitudEvaluacionDesempenoImpl.setUsuariocrea(getUsuariocrea());
		solicitudEvaluacionDesempenoImpl.setFechacrea(getFechacrea());
		solicitudEvaluacionDesempenoImpl.setUsuariomodifica(getUsuariomodifica());
		solicitudEvaluacionDesempenoImpl.setFechacreamodifica(getFechacreamodifica());

		solicitudEvaluacionDesempenoImpl.resetOriginalValues();

		return solicitudEvaluacionDesempenoImpl;
	}

	@Override
	public int compareTo(
		SolicitudEvaluacionDesempeno solicitudEvaluacionDesempeno) {
		int value = 0;

		value = DateUtil.compareTo(getFechacrea(),
				solicitudEvaluacionDesempeno.getFechacrea());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof SolicitudEvaluacionDesempeno)) {
			return false;
		}

		SolicitudEvaluacionDesempeno solicitudEvaluacionDesempeno = (SolicitudEvaluacionDesempeno)obj;

		long primaryKey = solicitudEvaluacionDesempeno.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<SolicitudEvaluacionDesempeno> toCacheModel() {
		SolicitudEvaluacionDesempenoCacheModel solicitudEvaluacionDesempenoCacheModel =
			new SolicitudEvaluacionDesempenoCacheModel();

		solicitudEvaluacionDesempenoCacheModel.solicitudEvaluacionDesempenoId = getSolicitudEvaluacionDesempenoId();

		solicitudEvaluacionDesempenoCacheModel.descripcion = getDescripcion();

		String descripcion = solicitudEvaluacionDesempenoCacheModel.descripcion;

		if ((descripcion != null) && (descripcion.length() == 0)) {
			solicitudEvaluacionDesempenoCacheModel.descripcion = null;
		}

		Date fechaIncioEvaluacion = getFechaIncioEvaluacion();

		if (fechaIncioEvaluacion != null) {
			solicitudEvaluacionDesempenoCacheModel.fechaIncioEvaluacion = fechaIncioEvaluacion.getTime();
		}
		else {
			solicitudEvaluacionDesempenoCacheModel.fechaIncioEvaluacion = Long.MIN_VALUE;
		}

		solicitudEvaluacionDesempenoCacheModel.estado = getEstado();

		String estado = solicitudEvaluacionDesempenoCacheModel.estado;

		if ((estado != null) && (estado.length() == 0)) {
			solicitudEvaluacionDesempenoCacheModel.estado = null;
		}

		solicitudEvaluacionDesempenoCacheModel.motivo = getMotivo();

		String motivo = solicitudEvaluacionDesempenoCacheModel.motivo;

		if ((motivo != null) && (motivo.length() == 0)) {
			solicitudEvaluacionDesempenoCacheModel.motivo = null;
		}

		solicitudEvaluacionDesempenoCacheModel.observacion = getObservacion();

		String observacion = solicitudEvaluacionDesempenoCacheModel.observacion;

		if ((observacion != null) && (observacion.length() == 0)) {
			solicitudEvaluacionDesempenoCacheModel.observacion = null;
		}

		solicitudEvaluacionDesempenoCacheModel.activo = getActivo();

		solicitudEvaluacionDesempenoCacheModel.usuariocrea = getUsuariocrea();

		Date fechacrea = getFechacrea();

		if (fechacrea != null) {
			solicitudEvaluacionDesempenoCacheModel.fechacrea = fechacrea.getTime();
		}
		else {
			solicitudEvaluacionDesempenoCacheModel.fechacrea = Long.MIN_VALUE;
		}

		solicitudEvaluacionDesempenoCacheModel.usuariomodifica = getUsuariomodifica();

		Date fechacreamodifica = getFechacreamodifica();

		if (fechacreamodifica != null) {
			solicitudEvaluacionDesempenoCacheModel.fechacreamodifica = fechacreamodifica.getTime();
		}
		else {
			solicitudEvaluacionDesempenoCacheModel.fechacreamodifica = Long.MIN_VALUE;
		}

		return solicitudEvaluacionDesempenoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{solicitudEvaluacionDesempenoId=");
		sb.append(getSolicitudEvaluacionDesempenoId());
		sb.append(", descripcion=");
		sb.append(getDescripcion());
		sb.append(", fechaIncioEvaluacion=");
		sb.append(getFechaIncioEvaluacion());
		sb.append(", estado=");
		sb.append(getEstado());
		sb.append(", motivo=");
		sb.append(getMotivo());
		sb.append(", observacion=");
		sb.append(getObservacion());
		sb.append(", activo=");
		sb.append(getActivo());
		sb.append(", usuariocrea=");
		sb.append(getUsuariocrea());
		sb.append(", fechacrea=");
		sb.append(getFechacrea());
		sb.append(", usuariomodifica=");
		sb.append(getUsuariomodifica());
		sb.append(", fechacreamodifica=");
		sb.append(getFechacreamodifica());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("com.rec.hitss.layer.model.SolicitudEvaluacionDesempeno");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>solicitudEvaluacionDesempenoId</column-name><column-value><![CDATA[");
		sb.append(getSolicitudEvaluacionDesempenoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>descripcion</column-name><column-value><![CDATA[");
		sb.append(getDescripcion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fechaIncioEvaluacion</column-name><column-value><![CDATA[");
		sb.append(getFechaIncioEvaluacion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>estado</column-name><column-value><![CDATA[");
		sb.append(getEstado());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>motivo</column-name><column-value><![CDATA[");
		sb.append(getMotivo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>observacion</column-name><column-value><![CDATA[");
		sb.append(getObservacion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>activo</column-name><column-value><![CDATA[");
		sb.append(getActivo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>usuariocrea</column-name><column-value><![CDATA[");
		sb.append(getUsuariocrea());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fechacrea</column-name><column-value><![CDATA[");
		sb.append(getFechacrea());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>usuariomodifica</column-name><column-value><![CDATA[");
		sb.append(getUsuariomodifica());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fechacreamodifica</column-name><column-value><![CDATA[");
		sb.append(getFechacreamodifica());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = SolicitudEvaluacionDesempeno.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			SolicitudEvaluacionDesempeno.class
		};
	private long _solicitudEvaluacionDesempenoId;
	private String _descripcion;
	private Date _fechaIncioEvaluacion;
	private String _estado;
	private String _motivo;
	private String _observacion;
	private boolean _activo;
	private long _usuariocrea;
	private Date _fechacrea;
	private long _usuariomodifica;
	private Date _fechacreamodifica;
	private SolicitudEvaluacionDesempeno _escapedModel;
}