/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rec.hitss.layer.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.rec.hitss.layer.model.UsuarioGrupo;
import com.rec.hitss.layer.model.UsuarioGrupoModel;
import com.rec.hitss.layer.model.UsuarioGrupoSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the UsuarioGrupo service. Represents a row in the &quot;UsuarioGrupo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.rec.hitss.layer.model.UsuarioGrupoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UsuarioGrupoImpl}.
 * </p>
 *
 * @author Crossfire
 * @see UsuarioGrupoImpl
 * @see com.rec.hitss.layer.model.UsuarioGrupo
 * @see com.rec.hitss.layer.model.UsuarioGrupoModel
 * @generated
 */
@JSON(strict = true)
public class UsuarioGrupoModelImpl extends BaseModelImpl<UsuarioGrupo>
	implements UsuarioGrupoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a usuario grupo model instance should use the {@link com.rec.hitss.layer.model.UsuarioGrupo} interface instead.
	 */
	public static final String TABLE_NAME = "UsuarioGrupo";
	public static final Object[][] TABLE_COLUMNS = {
			{ "userGroupId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "prioridadEquiposId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table UsuarioGrupo (userGroupId LONG not null primary key,groupId LONG,companyId LONG,prioridadEquiposId LONG)";
	public static final String TABLE_SQL_DROP = "drop table UsuarioGrupo";
	public static final String ORDER_BY_JPQL = " ORDER BY usuarioGrupo.userGroupId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY UsuarioGrupo.userGroupId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rec.hitss.layer.model.UsuarioGrupo"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rec.hitss.layer.model.UsuarioGrupo"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static UsuarioGrupo toModel(UsuarioGrupoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		UsuarioGrupo model = new UsuarioGrupoImpl();

		model.setUserGroupId(soapModel.getUserGroupId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setPrioridadEquiposId(soapModel.getPrioridadEquiposId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<UsuarioGrupo> toModels(UsuarioGrupoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<UsuarioGrupo> models = new ArrayList<UsuarioGrupo>(soapModels.length);

		for (UsuarioGrupoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.rec.hitss.layer.model.UsuarioGrupo"));

	public UsuarioGrupoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _userGroupId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setUserGroupId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _userGroupId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return UsuarioGrupo.class;
	}

	@Override
	public String getModelClassName() {
		return UsuarioGrupo.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("userGroupId", getUserGroupId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("prioridadEquiposId", getPrioridadEquiposId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long userGroupId = (Long)attributes.get("userGroupId");

		if (userGroupId != null) {
			setUserGroupId(userGroupId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long prioridadEquiposId = (Long)attributes.get("prioridadEquiposId");

		if (prioridadEquiposId != null) {
			setPrioridadEquiposId(prioridadEquiposId);
		}
	}

	@JSON
	@Override
	public long getUserGroupId() {
		return _userGroupId;
	}

	@Override
	public void setUserGroupId(long userGroupId) {
		_userGroupId = userGroupId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getPrioridadEquiposId() {
		return _prioridadEquiposId;
	}

	@Override
	public void setPrioridadEquiposId(long prioridadEquiposId) {
		_prioridadEquiposId = prioridadEquiposId;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			UsuarioGrupo.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public UsuarioGrupo toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (UsuarioGrupo)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		UsuarioGrupoImpl usuarioGrupoImpl = new UsuarioGrupoImpl();

		usuarioGrupoImpl.setUserGroupId(getUserGroupId());
		usuarioGrupoImpl.setGroupId(getGroupId());
		usuarioGrupoImpl.setCompanyId(getCompanyId());
		usuarioGrupoImpl.setPrioridadEquiposId(getPrioridadEquiposId());

		usuarioGrupoImpl.resetOriginalValues();

		return usuarioGrupoImpl;
	}

	@Override
	public int compareTo(UsuarioGrupo usuarioGrupo) {
		long primaryKey = usuarioGrupo.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof UsuarioGrupo)) {
			return false;
		}

		UsuarioGrupo usuarioGrupo = (UsuarioGrupo)obj;

		long primaryKey = usuarioGrupo.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<UsuarioGrupo> toCacheModel() {
		UsuarioGrupoCacheModel usuarioGrupoCacheModel = new UsuarioGrupoCacheModel();

		usuarioGrupoCacheModel.userGroupId = getUserGroupId();

		usuarioGrupoCacheModel.groupId = getGroupId();

		usuarioGrupoCacheModel.companyId = getCompanyId();

		usuarioGrupoCacheModel.prioridadEquiposId = getPrioridadEquiposId();

		return usuarioGrupoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{userGroupId=");
		sb.append(getUserGroupId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", prioridadEquiposId=");
		sb.append(getPrioridadEquiposId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.rec.hitss.layer.model.UsuarioGrupo");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>userGroupId</column-name><column-value><![CDATA[");
		sb.append(getUserGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>prioridadEquiposId</column-name><column-value><![CDATA[");
		sb.append(getPrioridadEquiposId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = UsuarioGrupo.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			UsuarioGrupo.class
		};
	private long _userGroupId;
	private long _groupId;
	private long _companyId;
	private long _prioridadEquiposId;
	private UsuarioGrupo _escapedModel;
}