
package com.hitss.rev.dools.impl

 dialect "java"



import com.hitss.rev.dools.impl.EvaluacionBean
import com.hitss.rev.dools.impl.EvaluacionPuestoBean
import com.hitss.rev.dools.impl.ExperienciaBean
import com.hitss.rev.dools.impl.Postulacion
import com.hitss.rev.dools.impl.PuestoBean
import com.hitss.rev.dools.impl.ReferenciaBean
import com.hitss.rev.dools.impl.RequisitoBean
import com.hitss.rev.dools.impl.SolicitudReclutamiento
import com.hitss.rev.dools.impl.UsuarioBean

rule PrintString when
    $p : Postulacion( )
then
   System.out.println( " ----------------------------- " );
   System.out.println( $p );
   System.out.println( $p.getSolicitudReclutamiento() );
   System.out.println( $p.getSolicitudReclutamiento().getId() );
   System.out.println( $p.getSolicitudReclutamiento().getPuesto() );
   System.out.println( $p.getSolicitudReclutamiento().getPuesto().getNombre() );
   System.out.println( $p.getUsuarioBean() );
   System.out.println( $p.getUsuarioBean().getIdUsuario() );
   System.out.println( $p.getUsuarioBean().getNombre() );
   System.out.println( " ----------------------------- " );
end


rule "Analizar requisitos" when
    
    $p : Postulacion( )
    $s : SolicitudReclutamiento()
    
then


end