
package com.hitss.rev.dools.impl

dialect "java"

import com.hitss.rev.dools.impl.EvaluacionBean
import com.hitss.rev.dools.impl.EvaluacionPuestoBean
import com.hitss.rev.dools.impl.ExperienciaBean
import com.hitss.rev.dools.impl.Postulacion
import com.hitss.rev.dools.impl.PuestoBean
import com.hitss.rev.dools.impl.ReferenciaBean
import com.hitss.rev.dools.impl.RequisitoBean
import com.hitss.rev.dools.impl.SolicitudReclutamiento
import com.hitss.rev.dools.impl.UsuarioBean
import com.hitss.rev.dools.impl.Haming
import com.hitss.rev.dools.impl.Euclistica
import com.hitss.rev.dools.impl.DataHamming
import com.hitss.rev.dools.impl.DistanciaEuclidiana
import java.util.ArrayList
import java.util.List
import com.hitss.rev.dools.impl.LogTraza

rule "Analisis de cercanos" salience 200 when
    $postulacion : Postulacion( $usuario : usuarioBean , $puesto : solicitudReclutamiento.puesto , filtroPostulacion == true && filtroConocimiento == true  && filtroPsicologico == true && filtroTecnico == false && analizadoCercania == false )
  
then
	System.out.println( " ----------------------------- " );
	System.out.println( "Analisis de Cercania i " );
	LogTraza.log( $postulacion.getPostulacionId() , $postulacion.getUsuarioId() , "Analisis de Cercania i ");
	System.out.println("-----------------");
	System.out.println("getIdUsuario--" + $postulacion.getUsuarioBean().getIdUsuario());
	LogTraza.log( $postulacion.getPostulacionId() , $postulacion.getUsuarioId() ,"getIdUsuario--" + $postulacion.getUsuarioBean().getIdUsuario());
	System.out.println("-----------------");
	System.out.println("DistanciaEuclidianaEntrevista--" + $postulacion.getDistanciaEuclidianaEntrevista());
	LogTraza.log( $postulacion.getPostulacionId() , $postulacion.getUsuarioId() ,"DistanciaEuclidianaEntrevista--" + $postulacion.getDistanciaEuclidianaEntrevista());
	System.out.println("DistanciaHammingEntrevista--" + $postulacion.getDistanciaHammingEntrevista());
	LogTraza.log( $postulacion.getPostulacionId() , $postulacion.getUsuarioId() ,"DistanciaHammingEntrevista--" + $postulacion.getDistanciaHammingEntrevista());
	System.out.println("DistanciaEuclidianaPsicologico--" + $postulacion.getDistanciaEuclidianaPsicologico());
	LogTraza.log( $postulacion.getPostulacionId() , $postulacion.getUsuarioId() ,"DistanciaEuclidianaPsicologico--" + $postulacion.getDistanciaEuclidianaPsicologico());
	System.out.println("DistanciaHammingPsicologico--" + $postulacion.getDistanciaHammingPsicologico());
	LogTraza.log( $postulacion.getPostulacionId() , $postulacion.getUsuarioId() ,"DistanciaHammingPsicologico--" + $postulacion.getDistanciaHammingPsicologico());
	System.out.println("DistanciaEuclidianaTecnico--" + $postulacion.getDistanciaEuclidianaTecnico());
	LogTraza.log( $postulacion.getPostulacionId() , $postulacion.getUsuarioId() ,"DistanciaEuclidianaTecnico--" + $postulacion.getDistanciaEuclidianaTecnico());
	System.out.println("DistanciaHammingTecnico--" + $postulacion.getDistanciaHammingTecnico());   
	LogTraza.log( $postulacion.getPostulacionId() , $postulacion.getUsuarioId() ,"DistanciaHammingTecnico--" + $postulacion.getDistanciaHammingTecnico()); 
				   	
   	System.out.println( " porcentajeReqCum:" + $postulacion.getPorcentajeReqCum() );	   
	LogTraza.log( $postulacion.getPostulacionId() , $postulacion.getUsuarioId() , 	 " porcentajeReqCum:" + $postulacion.getPorcentajeReqCum() );		   
   	System.out.println( " porcentajeRequisitosCumplidoPorUsuario:" + $postulacion.getPorcentajeRequisitosCumplidoPorUsuario() ); 
	LogTraza.log( $postulacion.getPostulacionId() , $postulacion.getUsuarioId() ,	" porcentajeRequisitosCumplidoPorUsuario:" + $postulacion.getPorcentajeRequisitosCumplidoPorUsuario() );    			   
   	System.out.println( " porcentajeReqCertiCum:" + $postulacion.getPorcentajeReqCertiCum() );	   		 
	LogTraza.log( $postulacion.getPostulacionId() , $postulacion.getUsuarioId() ,	   " porcentajeReqCertiCum:" + $postulacion.getPorcentajeReqCertiCum() );	
   	System.out.println( " porcentajeCertificadoCumplidoPorUsuario:" + $postulacion.getPorcentajeCertificadoCumplidoPorUsuario() );	 
	LogTraza.log( $postulacion.getPostulacionId() , $postulacion.getUsuarioId() ,	  " porcentajeCertificadoCumplidoPorUsuario:" + $postulacion.getPorcentajeCertificadoCumplidoPorUsuario() );  			   
		
	List<Haming> dis = new ArrayList<Haming>();
	Haming a1 = new Haming();
	a1.setValorDefinido(0.0);	
	a1.setValor($postulacion.getDistanciaEuclidianaEntrevista());
	dis.add(a1);
	Haming a2 = new Haming();
	a2.setValorDefinido(0.0);	
	a2.setValor($postulacion.getDistanciaHammingEntrevista());
	dis.add(a2);
	Haming a3 = new Haming();
	a3.setValorDefinido(0.0);	
	a3.setValor($postulacion.getDistanciaEuclidianaPsicologico());
	dis.add(a3);
	Haming a4 = new Haming();
	a4.setValorDefinido(0.0);	
	a4.setValor($postulacion.getDistanciaHammingPsicologico());
	dis.add(a4);
	Haming a5 = new Haming();
	a5.setValorDefinido(0.0);	
	a5.setValor($postulacion.getDistanciaEuclidianaTecnico());
	dis.add(a5);
	Haming a6 = new Haming();
	a6.setValorDefinido(0.0);	
	a6.setValor($postulacion.getDistanciaHammingTecnico());
	dis.add(a6);
	
	System.out.println( "DataHamming:" + DataHamming.calcularDistancia(dis) );
	LogTraza.log( $postulacion.getPostulacionId() , $postulacion.getUsuarioId() , "DataHamming:" + DataHamming.calcularDistancia(dis) );
	$postulacion.setCercania(DataHamming.calcularDistancia(dis));
	
	if($postulacion.getPorcentajeReqCum() >= 0.5){	
		$postulacion.setRecomendableReqCum(true);	
	}
	if($postulacion.getPorcentajeRequisitosCumplidoPorUsuario() >= 0.5){	
		$postulacion.setRecomendableRequisitosCumplidoPorUsuario(true);	
	}	
	if($postulacion.getPorcentajeReqCertiCum() >= 0.5){	
		$postulacion.setRecomendableReqCertiCum(true);	
	}	
	if($postulacion.getPorcentajeCertificadoCumplidoPorUsuario() >= 0.5){	
		$postulacion.setRecomendableReqCertiCum(true);	
	}
	
	$postulacion.setAnalizadoCercania(true);
	update($postulacion);
	
	System.out.println( "Analisis de Cercania f" );
end


