/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rec.hitss.layer.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.rec.hitss.layer.model.avanceEstadoSolicitudReclutamiento;
import com.rec.hitss.layer.model.avanceEstadoSolicitudReclutamientoModel;
import com.rec.hitss.layer.model.avanceEstadoSolicitudReclutamientoSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the avanceEstadoSolicitudReclutamiento service. Represents a row in the &quot;AVANCE_ESTADO_SOLICITUD_RECLUTAMIENTO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.rec.hitss.layer.model.avanceEstadoSolicitudReclutamientoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link avanceEstadoSolicitudReclutamientoImpl}.
 * </p>
 *
 * @author Crossfire
 * @see avanceEstadoSolicitudReclutamientoImpl
 * @see com.rec.hitss.layer.model.avanceEstadoSolicitudReclutamiento
 * @see com.rec.hitss.layer.model.avanceEstadoSolicitudReclutamientoModel
 * @generated
 */
@JSON(strict = true)
public class avanceEstadoSolicitudReclutamientoModelImpl extends BaseModelImpl<avanceEstadoSolicitudReclutamiento>
	implements avanceEstadoSolicitudReclutamientoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a avance estado solicitud reclutamiento model instance should use the {@link com.rec.hitss.layer.model.avanceEstadoSolicitudReclutamiento} interface instead.
	 */
	public static final String TABLE_NAME = "AVANCE_ESTADO_SOLICITUD_RECLUTAMIENTO";
	public static final Object[][] TABLE_COLUMNS = {
			{ "AESR_ID", Types.BIGINT },
			{ "AESR_ESTADO", Types.VARCHAR },
			{ "AESR_ACTIVO", Types.VARCHAR },
			{ "AESR_USUARIO_CREA", Types.BIGINT },
			{ "AESR_FECHA_CREA", Types.TIMESTAMP },
			{ "AESR_USUARIO_MODIFICA", Types.BIGINT },
			{ "AESR_FECHA_MODIFICA", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table AVANCE_ESTADO_SOLICITUD_RECLUTAMIENTO (AESR_ID LONG not null primary key,AESR_ESTADO VARCHAR(75) null,AESR_ACTIVO VARCHAR(75) null,AESR_USUARIO_CREA LONG,AESR_FECHA_CREA DATE null,AESR_USUARIO_MODIFICA LONG,AESR_FECHA_MODIFICA DATE null)";
	public static final String TABLE_SQL_DROP = "drop table AVANCE_ESTADO_SOLICITUD_RECLUTAMIENTO";
	public static final String ORDER_BY_JPQL = " ORDER BY avanceEstadoSolicitudReclutamiento.AESR_ID ASC";
	public static final String ORDER_BY_SQL = " ORDER BY AVANCE_ESTADO_SOLICITUD_RECLUTAMIENTO.AESR_ID ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rec.hitss.layer.model.avanceEstadoSolicitudReclutamiento"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rec.hitss.layer.model.avanceEstadoSolicitudReclutamiento"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static avanceEstadoSolicitudReclutamiento toModel(
		avanceEstadoSolicitudReclutamientoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		avanceEstadoSolicitudReclutamiento model = new avanceEstadoSolicitudReclutamientoImpl();

		model.setAESR_ID(soapModel.getAESR_ID());
		model.setAESR_ESTADO(soapModel.getAESR_ESTADO());
		model.setAESR_ACTIVO(soapModel.getAESR_ACTIVO());
		model.setAESR_USUARIO_CREA(soapModel.getAESR_USUARIO_CREA());
		model.setAESR_FECHA_CREA(soapModel.getAESR_FECHA_CREA());
		model.setAESR_USUARIO_MODIFICA(soapModel.getAESR_USUARIO_MODIFICA());
		model.setAESR_FECHA_MODIFICA(soapModel.getAESR_FECHA_MODIFICA());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<avanceEstadoSolicitudReclutamiento> toModels(
		avanceEstadoSolicitudReclutamientoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<avanceEstadoSolicitudReclutamiento> models = new ArrayList<avanceEstadoSolicitudReclutamiento>(soapModels.length);

		for (avanceEstadoSolicitudReclutamientoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.rec.hitss.layer.model.avanceEstadoSolicitudReclutamiento"));

	public avanceEstadoSolicitudReclutamientoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _AESR_ID;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAESR_ID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _AESR_ID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return avanceEstadoSolicitudReclutamiento.class;
	}

	@Override
	public String getModelClassName() {
		return avanceEstadoSolicitudReclutamiento.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("AESR_ID", getAESR_ID());
		attributes.put("AESR_ESTADO", getAESR_ESTADO());
		attributes.put("AESR_ACTIVO", getAESR_ACTIVO());
		attributes.put("AESR_USUARIO_CREA", getAESR_USUARIO_CREA());
		attributes.put("AESR_FECHA_CREA", getAESR_FECHA_CREA());
		attributes.put("AESR_USUARIO_MODIFICA", getAESR_USUARIO_MODIFICA());
		attributes.put("AESR_FECHA_MODIFICA", getAESR_FECHA_MODIFICA());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long AESR_ID = (Long)attributes.get("AESR_ID");

		if (AESR_ID != null) {
			setAESR_ID(AESR_ID);
		}

		String AESR_ESTADO = (String)attributes.get("AESR_ESTADO");

		if (AESR_ESTADO != null) {
			setAESR_ESTADO(AESR_ESTADO);
		}

		String AESR_ACTIVO = (String)attributes.get("AESR_ACTIVO");

		if (AESR_ACTIVO != null) {
			setAESR_ACTIVO(AESR_ACTIVO);
		}

		Long AESR_USUARIO_CREA = (Long)attributes.get("AESR_USUARIO_CREA");

		if (AESR_USUARIO_CREA != null) {
			setAESR_USUARIO_CREA(AESR_USUARIO_CREA);
		}

		Date AESR_FECHA_CREA = (Date)attributes.get("AESR_FECHA_CREA");

		if (AESR_FECHA_CREA != null) {
			setAESR_FECHA_CREA(AESR_FECHA_CREA);
		}

		Long AESR_USUARIO_MODIFICA = (Long)attributes.get(
				"AESR_USUARIO_MODIFICA");

		if (AESR_USUARIO_MODIFICA != null) {
			setAESR_USUARIO_MODIFICA(AESR_USUARIO_MODIFICA);
		}

		Date AESR_FECHA_MODIFICA = (Date)attributes.get("AESR_FECHA_MODIFICA");

		if (AESR_FECHA_MODIFICA != null) {
			setAESR_FECHA_MODIFICA(AESR_FECHA_MODIFICA);
		}
	}

	@JSON
	@Override
	public long getAESR_ID() {
		return _AESR_ID;
	}

	@Override
	public void setAESR_ID(long AESR_ID) {
		_AESR_ID = AESR_ID;
	}

	@JSON
	@Override
	public String getAESR_ESTADO() {
		if (_AESR_ESTADO == null) {
			return StringPool.BLANK;
		}
		else {
			return _AESR_ESTADO;
		}
	}

	@Override
	public void setAESR_ESTADO(String AESR_ESTADO) {
		_AESR_ESTADO = AESR_ESTADO;
	}

	@JSON
	@Override
	public String getAESR_ACTIVO() {
		if (_AESR_ACTIVO == null) {
			return StringPool.BLANK;
		}
		else {
			return _AESR_ACTIVO;
		}
	}

	@Override
	public void setAESR_ACTIVO(String AESR_ACTIVO) {
		_AESR_ACTIVO = AESR_ACTIVO;
	}

	@JSON
	@Override
	public long getAESR_USUARIO_CREA() {
		return _AESR_USUARIO_CREA;
	}

	@Override
	public void setAESR_USUARIO_CREA(long AESR_USUARIO_CREA) {
		_AESR_USUARIO_CREA = AESR_USUARIO_CREA;
	}

	@JSON
	@Override
	public Date getAESR_FECHA_CREA() {
		return _AESR_FECHA_CREA;
	}

	@Override
	public void setAESR_FECHA_CREA(Date AESR_FECHA_CREA) {
		_AESR_FECHA_CREA = AESR_FECHA_CREA;
	}

	@JSON
	@Override
	public long getAESR_USUARIO_MODIFICA() {
		return _AESR_USUARIO_MODIFICA;
	}

	@Override
	public void setAESR_USUARIO_MODIFICA(long AESR_USUARIO_MODIFICA) {
		_AESR_USUARIO_MODIFICA = AESR_USUARIO_MODIFICA;
	}

	@JSON
	@Override
	public Date getAESR_FECHA_MODIFICA() {
		return _AESR_FECHA_MODIFICA;
	}

	@Override
	public void setAESR_FECHA_MODIFICA(Date AESR_FECHA_MODIFICA) {
		_AESR_FECHA_MODIFICA = AESR_FECHA_MODIFICA;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			avanceEstadoSolicitudReclutamiento.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public avanceEstadoSolicitudReclutamiento toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (avanceEstadoSolicitudReclutamiento)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		avanceEstadoSolicitudReclutamientoImpl avanceEstadoSolicitudReclutamientoImpl =
			new avanceEstadoSolicitudReclutamientoImpl();

		avanceEstadoSolicitudReclutamientoImpl.setAESR_ID(getAESR_ID());
		avanceEstadoSolicitudReclutamientoImpl.setAESR_ESTADO(getAESR_ESTADO());
		avanceEstadoSolicitudReclutamientoImpl.setAESR_ACTIVO(getAESR_ACTIVO());
		avanceEstadoSolicitudReclutamientoImpl.setAESR_USUARIO_CREA(getAESR_USUARIO_CREA());
		avanceEstadoSolicitudReclutamientoImpl.setAESR_FECHA_CREA(getAESR_FECHA_CREA());
		avanceEstadoSolicitudReclutamientoImpl.setAESR_USUARIO_MODIFICA(getAESR_USUARIO_MODIFICA());
		avanceEstadoSolicitudReclutamientoImpl.setAESR_FECHA_MODIFICA(getAESR_FECHA_MODIFICA());

		avanceEstadoSolicitudReclutamientoImpl.resetOriginalValues();

		return avanceEstadoSolicitudReclutamientoImpl;
	}

	@Override
	public int compareTo(
		avanceEstadoSolicitudReclutamiento avanceEstadoSolicitudReclutamiento) {
		int value = 0;

		if (getAESR_ID() < avanceEstadoSolicitudReclutamiento.getAESR_ID()) {
			value = -1;
		}
		else if (getAESR_ID() > avanceEstadoSolicitudReclutamiento.getAESR_ID()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof avanceEstadoSolicitudReclutamiento)) {
			return false;
		}

		avanceEstadoSolicitudReclutamiento avanceEstadoSolicitudReclutamiento = (avanceEstadoSolicitudReclutamiento)obj;

		long primaryKey = avanceEstadoSolicitudReclutamiento.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<avanceEstadoSolicitudReclutamiento> toCacheModel() {
		avanceEstadoSolicitudReclutamientoCacheModel avanceEstadoSolicitudReclutamientoCacheModel =
			new avanceEstadoSolicitudReclutamientoCacheModel();

		avanceEstadoSolicitudReclutamientoCacheModel.AESR_ID = getAESR_ID();

		avanceEstadoSolicitudReclutamientoCacheModel.AESR_ESTADO = getAESR_ESTADO();

		String AESR_ESTADO = avanceEstadoSolicitudReclutamientoCacheModel.AESR_ESTADO;

		if ((AESR_ESTADO != null) && (AESR_ESTADO.length() == 0)) {
			avanceEstadoSolicitudReclutamientoCacheModel.AESR_ESTADO = null;
		}

		avanceEstadoSolicitudReclutamientoCacheModel.AESR_ACTIVO = getAESR_ACTIVO();

		String AESR_ACTIVO = avanceEstadoSolicitudReclutamientoCacheModel.AESR_ACTIVO;

		if ((AESR_ACTIVO != null) && (AESR_ACTIVO.length() == 0)) {
			avanceEstadoSolicitudReclutamientoCacheModel.AESR_ACTIVO = null;
		}

		avanceEstadoSolicitudReclutamientoCacheModel.AESR_USUARIO_CREA = getAESR_USUARIO_CREA();

		Date AESR_FECHA_CREA = getAESR_FECHA_CREA();

		if (AESR_FECHA_CREA != null) {
			avanceEstadoSolicitudReclutamientoCacheModel.AESR_FECHA_CREA = AESR_FECHA_CREA.getTime();
		}
		else {
			avanceEstadoSolicitudReclutamientoCacheModel.AESR_FECHA_CREA = Long.MIN_VALUE;
		}

		avanceEstadoSolicitudReclutamientoCacheModel.AESR_USUARIO_MODIFICA = getAESR_USUARIO_MODIFICA();

		Date AESR_FECHA_MODIFICA = getAESR_FECHA_MODIFICA();

		if (AESR_FECHA_MODIFICA != null) {
			avanceEstadoSolicitudReclutamientoCacheModel.AESR_FECHA_MODIFICA = AESR_FECHA_MODIFICA.getTime();
		}
		else {
			avanceEstadoSolicitudReclutamientoCacheModel.AESR_FECHA_MODIFICA = Long.MIN_VALUE;
		}

		return avanceEstadoSolicitudReclutamientoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{AESR_ID=");
		sb.append(getAESR_ID());
		sb.append(", AESR_ESTADO=");
		sb.append(getAESR_ESTADO());
		sb.append(", AESR_ACTIVO=");
		sb.append(getAESR_ACTIVO());
		sb.append(", AESR_USUARIO_CREA=");
		sb.append(getAESR_USUARIO_CREA());
		sb.append(", AESR_FECHA_CREA=");
		sb.append(getAESR_FECHA_CREA());
		sb.append(", AESR_USUARIO_MODIFICA=");
		sb.append(getAESR_USUARIO_MODIFICA());
		sb.append(", AESR_FECHA_MODIFICA=");
		sb.append(getAESR_FECHA_MODIFICA());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append(
			"com.rec.hitss.layer.model.avanceEstadoSolicitudReclutamiento");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>AESR_ID</column-name><column-value><![CDATA[");
		sb.append(getAESR_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>AESR_ESTADO</column-name><column-value><![CDATA[");
		sb.append(getAESR_ESTADO());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>AESR_ACTIVO</column-name><column-value><![CDATA[");
		sb.append(getAESR_ACTIVO());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>AESR_USUARIO_CREA</column-name><column-value><![CDATA[");
		sb.append(getAESR_USUARIO_CREA());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>AESR_FECHA_CREA</column-name><column-value><![CDATA[");
		sb.append(getAESR_FECHA_CREA());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>AESR_USUARIO_MODIFICA</column-name><column-value><![CDATA[");
		sb.append(getAESR_USUARIO_MODIFICA());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>AESR_FECHA_MODIFICA</column-name><column-value><![CDATA[");
		sb.append(getAESR_FECHA_MODIFICA());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = avanceEstadoSolicitudReclutamiento.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			avanceEstadoSolicitudReclutamiento.class
		};
	private long _AESR_ID;
	private String _AESR_ESTADO;
	private String _AESR_ACTIVO;
	private long _AESR_USUARIO_CREA;
	private Date _AESR_FECHA_CREA;
	private long _AESR_USUARIO_MODIFICA;
	private Date _AESR_FECHA_MODIFICA;
	private avanceEstadoSolicitudReclutamiento _escapedModel;
}