/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rec.hitss.layer.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.rec.hitss.layer.model.cartillaReclutamiento;
import com.rec.hitss.layer.model.cartillaReclutamientoModel;
import com.rec.hitss.layer.model.cartillaReclutamientoSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the cartillaReclutamiento service. Represents a row in the &quot;cartilla_reclutamiento&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.rec.hitss.layer.model.cartillaReclutamientoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link cartillaReclutamientoImpl}.
 * </p>
 *
 * @author Crossfire
 * @see cartillaReclutamientoImpl
 * @see com.rec.hitss.layer.model.cartillaReclutamiento
 * @see com.rec.hitss.layer.model.cartillaReclutamientoModel
 * @generated
 */
@JSON(strict = true)
public class cartillaReclutamientoModelImpl extends BaseModelImpl<cartillaReclutamiento>
	implements cartillaReclutamientoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cartilla reclutamiento model instance should use the {@link com.rec.hitss.layer.model.cartillaReclutamiento} interface instead.
	 */
	public static final String TABLE_NAME = "cartilla_reclutamiento";
	public static final Object[][] TABLE_COLUMNS = {
			{ "CR_ID", Types.BIGINT },
			{ "CR_ESTADO", Types.VARCHAR },
			{ "CR_ACTIVO", Types.VARCHAR },
			{ "CR_USUARIO_CREA", Types.BIGINT },
			{ "CR_FECHA_CREA", Types.TIMESTAMP },
			{ "CR_USUARIO_MODIFICA", Types.BIGINT },
			{ "CR_FECHA_MODIFICA", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table cartilla_reclutamiento (CR_ID LONG not null primary key,CR_ESTADO VARCHAR(75) null,CR_ACTIVO VARCHAR(75) null,CR_USUARIO_CREA LONG,CR_FECHA_CREA DATE null,CR_USUARIO_MODIFICA LONG,CR_FECHA_MODIFICA DATE null)";
	public static final String TABLE_SQL_DROP = "drop table cartilla_reclutamiento";
	public static final String ORDER_BY_JPQL = " ORDER BY cartillaReclutamiento.CR_ID ASC";
	public static final String ORDER_BY_SQL = " ORDER BY cartilla_reclutamiento.CR_ID ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rec.hitss.layer.model.cartillaReclutamiento"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rec.hitss.layer.model.cartillaReclutamiento"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static cartillaReclutamiento toModel(
		cartillaReclutamientoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		cartillaReclutamiento model = new cartillaReclutamientoImpl();

		model.setCR_ID(soapModel.getCR_ID());
		model.setCR_ESTADO(soapModel.getCR_ESTADO());
		model.setCR_ACTIVO(soapModel.getCR_ACTIVO());
		model.setCR_USUARIO_CREA(soapModel.getCR_USUARIO_CREA());
		model.setCR_FECHA_CREA(soapModel.getCR_FECHA_CREA());
		model.setCR_USUARIO_MODIFICA(soapModel.getCR_USUARIO_MODIFICA());
		model.setCR_FECHA_MODIFICA(soapModel.getCR_FECHA_MODIFICA());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<cartillaReclutamiento> toModels(
		cartillaReclutamientoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<cartillaReclutamiento> models = new ArrayList<cartillaReclutamiento>(soapModels.length);

		for (cartillaReclutamientoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.rec.hitss.layer.model.cartillaReclutamiento"));

	public cartillaReclutamientoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _CR_ID;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCR_ID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _CR_ID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return cartillaReclutamiento.class;
	}

	@Override
	public String getModelClassName() {
		return cartillaReclutamiento.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("CR_ID", getCR_ID());
		attributes.put("CR_ESTADO", getCR_ESTADO());
		attributes.put("CR_ACTIVO", getCR_ACTIVO());
		attributes.put("CR_USUARIO_CREA", getCR_USUARIO_CREA());
		attributes.put("CR_FECHA_CREA", getCR_FECHA_CREA());
		attributes.put("CR_USUARIO_MODIFICA", getCR_USUARIO_MODIFICA());
		attributes.put("CR_FECHA_MODIFICA", getCR_FECHA_MODIFICA());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long CR_ID = (Long)attributes.get("CR_ID");

		if (CR_ID != null) {
			setCR_ID(CR_ID);
		}

		String CR_ESTADO = (String)attributes.get("CR_ESTADO");

		if (CR_ESTADO != null) {
			setCR_ESTADO(CR_ESTADO);
		}

		String CR_ACTIVO = (String)attributes.get("CR_ACTIVO");

		if (CR_ACTIVO != null) {
			setCR_ACTIVO(CR_ACTIVO);
		}

		Long CR_USUARIO_CREA = (Long)attributes.get("CR_USUARIO_CREA");

		if (CR_USUARIO_CREA != null) {
			setCR_USUARIO_CREA(CR_USUARIO_CREA);
		}

		Date CR_FECHA_CREA = (Date)attributes.get("CR_FECHA_CREA");

		if (CR_FECHA_CREA != null) {
			setCR_FECHA_CREA(CR_FECHA_CREA);
		}

		Long CR_USUARIO_MODIFICA = (Long)attributes.get("CR_USUARIO_MODIFICA");

		if (CR_USUARIO_MODIFICA != null) {
			setCR_USUARIO_MODIFICA(CR_USUARIO_MODIFICA);
		}

		Date CR_FECHA_MODIFICA = (Date)attributes.get("CR_FECHA_MODIFICA");

		if (CR_FECHA_MODIFICA != null) {
			setCR_FECHA_MODIFICA(CR_FECHA_MODIFICA);
		}
	}

	@JSON
	@Override
	public long getCR_ID() {
		return _CR_ID;
	}

	@Override
	public void setCR_ID(long CR_ID) {
		_CR_ID = CR_ID;
	}

	@JSON
	@Override
	public String getCR_ESTADO() {
		if (_CR_ESTADO == null) {
			return StringPool.BLANK;
		}
		else {
			return _CR_ESTADO;
		}
	}

	@Override
	public void setCR_ESTADO(String CR_ESTADO) {
		_CR_ESTADO = CR_ESTADO;
	}

	@JSON
	@Override
	public String getCR_ACTIVO() {
		if (_CR_ACTIVO == null) {
			return StringPool.BLANK;
		}
		else {
			return _CR_ACTIVO;
		}
	}

	@Override
	public void setCR_ACTIVO(String CR_ACTIVO) {
		_CR_ACTIVO = CR_ACTIVO;
	}

	@JSON
	@Override
	public long getCR_USUARIO_CREA() {
		return _CR_USUARIO_CREA;
	}

	@Override
	public void setCR_USUARIO_CREA(long CR_USUARIO_CREA) {
		_CR_USUARIO_CREA = CR_USUARIO_CREA;
	}

	@JSON
	@Override
	public Date getCR_FECHA_CREA() {
		return _CR_FECHA_CREA;
	}

	@Override
	public void setCR_FECHA_CREA(Date CR_FECHA_CREA) {
		_CR_FECHA_CREA = CR_FECHA_CREA;
	}

	@JSON
	@Override
	public long getCR_USUARIO_MODIFICA() {
		return _CR_USUARIO_MODIFICA;
	}

	@Override
	public void setCR_USUARIO_MODIFICA(long CR_USUARIO_MODIFICA) {
		_CR_USUARIO_MODIFICA = CR_USUARIO_MODIFICA;
	}

	@JSON
	@Override
	public Date getCR_FECHA_MODIFICA() {
		return _CR_FECHA_MODIFICA;
	}

	@Override
	public void setCR_FECHA_MODIFICA(Date CR_FECHA_MODIFICA) {
		_CR_FECHA_MODIFICA = CR_FECHA_MODIFICA;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			cartillaReclutamiento.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public cartillaReclutamiento toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (cartillaReclutamiento)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		cartillaReclutamientoImpl cartillaReclutamientoImpl = new cartillaReclutamientoImpl();

		cartillaReclutamientoImpl.setCR_ID(getCR_ID());
		cartillaReclutamientoImpl.setCR_ESTADO(getCR_ESTADO());
		cartillaReclutamientoImpl.setCR_ACTIVO(getCR_ACTIVO());
		cartillaReclutamientoImpl.setCR_USUARIO_CREA(getCR_USUARIO_CREA());
		cartillaReclutamientoImpl.setCR_FECHA_CREA(getCR_FECHA_CREA());
		cartillaReclutamientoImpl.setCR_USUARIO_MODIFICA(getCR_USUARIO_MODIFICA());
		cartillaReclutamientoImpl.setCR_FECHA_MODIFICA(getCR_FECHA_MODIFICA());

		cartillaReclutamientoImpl.resetOriginalValues();

		return cartillaReclutamientoImpl;
	}

	@Override
	public int compareTo(cartillaReclutamiento cartillaReclutamiento) {
		int value = 0;

		if (getCR_ID() < cartillaReclutamiento.getCR_ID()) {
			value = -1;
		}
		else if (getCR_ID() > cartillaReclutamiento.getCR_ID()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof cartillaReclutamiento)) {
			return false;
		}

		cartillaReclutamiento cartillaReclutamiento = (cartillaReclutamiento)obj;

		long primaryKey = cartillaReclutamiento.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<cartillaReclutamiento> toCacheModel() {
		cartillaReclutamientoCacheModel cartillaReclutamientoCacheModel = new cartillaReclutamientoCacheModel();

		cartillaReclutamientoCacheModel.CR_ID = getCR_ID();

		cartillaReclutamientoCacheModel.CR_ESTADO = getCR_ESTADO();

		String CR_ESTADO = cartillaReclutamientoCacheModel.CR_ESTADO;

		if ((CR_ESTADO != null) && (CR_ESTADO.length() == 0)) {
			cartillaReclutamientoCacheModel.CR_ESTADO = null;
		}

		cartillaReclutamientoCacheModel.CR_ACTIVO = getCR_ACTIVO();

		String CR_ACTIVO = cartillaReclutamientoCacheModel.CR_ACTIVO;

		if ((CR_ACTIVO != null) && (CR_ACTIVO.length() == 0)) {
			cartillaReclutamientoCacheModel.CR_ACTIVO = null;
		}

		cartillaReclutamientoCacheModel.CR_USUARIO_CREA = getCR_USUARIO_CREA();

		Date CR_FECHA_CREA = getCR_FECHA_CREA();

		if (CR_FECHA_CREA != null) {
			cartillaReclutamientoCacheModel.CR_FECHA_CREA = CR_FECHA_CREA.getTime();
		}
		else {
			cartillaReclutamientoCacheModel.CR_FECHA_CREA = Long.MIN_VALUE;
		}

		cartillaReclutamientoCacheModel.CR_USUARIO_MODIFICA = getCR_USUARIO_MODIFICA();

		Date CR_FECHA_MODIFICA = getCR_FECHA_MODIFICA();

		if (CR_FECHA_MODIFICA != null) {
			cartillaReclutamientoCacheModel.CR_FECHA_MODIFICA = CR_FECHA_MODIFICA.getTime();
		}
		else {
			cartillaReclutamientoCacheModel.CR_FECHA_MODIFICA = Long.MIN_VALUE;
		}

		return cartillaReclutamientoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{CR_ID=");
		sb.append(getCR_ID());
		sb.append(", CR_ESTADO=");
		sb.append(getCR_ESTADO());
		sb.append(", CR_ACTIVO=");
		sb.append(getCR_ACTIVO());
		sb.append(", CR_USUARIO_CREA=");
		sb.append(getCR_USUARIO_CREA());
		sb.append(", CR_FECHA_CREA=");
		sb.append(getCR_FECHA_CREA());
		sb.append(", CR_USUARIO_MODIFICA=");
		sb.append(getCR_USUARIO_MODIFICA());
		sb.append(", CR_FECHA_MODIFICA=");
		sb.append(getCR_FECHA_MODIFICA());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append("com.rec.hitss.layer.model.cartillaReclutamiento");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>CR_ID</column-name><column-value><![CDATA[");
		sb.append(getCR_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CR_ESTADO</column-name><column-value><![CDATA[");
		sb.append(getCR_ESTADO());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CR_ACTIVO</column-name><column-value><![CDATA[");
		sb.append(getCR_ACTIVO());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CR_USUARIO_CREA</column-name><column-value><![CDATA[");
		sb.append(getCR_USUARIO_CREA());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CR_FECHA_CREA</column-name><column-value><![CDATA[");
		sb.append(getCR_FECHA_CREA());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CR_USUARIO_MODIFICA</column-name><column-value><![CDATA[");
		sb.append(getCR_USUARIO_MODIFICA());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CR_FECHA_MODIFICA</column-name><column-value><![CDATA[");
		sb.append(getCR_FECHA_MODIFICA());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = cartillaReclutamiento.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			cartillaReclutamiento.class
		};
	private long _CR_ID;
	private String _CR_ESTADO;
	private String _CR_ACTIVO;
	private long _CR_USUARIO_CREA;
	private Date _CR_FECHA_CREA;
	private long _CR_USUARIO_MODIFICA;
	private Date _CR_FECHA_MODIFICA;
	private cartillaReclutamiento _escapedModel;
}