/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rec.hitss.layer.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.rec.hitss.layer.model.Contrato;
import com.rec.hitss.layer.model.ContratoModel;
import com.rec.hitss.layer.model.ContratoSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Contrato service. Represents a row in the &quot;CONTRATO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.rec.hitss.layer.model.ContratoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ContratoImpl}.
 * </p>
 *
 * @author Crossfire
 * @see ContratoImpl
 * @see com.rec.hitss.layer.model.Contrato
 * @see com.rec.hitss.layer.model.ContratoModel
 * @generated
 */
@JSON(strict = true)
public class ContratoModelImpl extends BaseModelImpl<Contrato>
	implements ContratoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a contrato model instance should use the {@link com.rec.hitss.layer.model.Contrato} interface instead.
	 */
	public static final String TABLE_NAME = "CONTRATO";
	public static final Object[][] TABLE_COLUMNS = {
			{ "CT_ID", Types.BIGINT },
			{ "CT_ESTADO", Types.VARCHAR },
			{ "CT_ACTIVO", Types.VARCHAR },
			{ "CT_USUARIO_CREA", Types.BIGINT },
			{ "CT_FECHA_CREA", Types.TIMESTAMP },
			{ "CT_USUARIO_MODIFICA", Types.BIGINT },
			{ "CT_FECHA_MODIFICA", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table CONTRATO (CT_ID LONG not null primary key,CT_ESTADO VARCHAR(75) null,CT_ACTIVO VARCHAR(75) null,CT_USUARIO_CREA LONG,CT_FECHA_CREA DATE null,CT_USUARIO_MODIFICA LONG,CT_FECHA_MODIFICA DATE null)";
	public static final String TABLE_SQL_DROP = "drop table CONTRATO";
	public static final String ORDER_BY_JPQL = " ORDER BY contrato.CT_ID ASC";
	public static final String ORDER_BY_SQL = " ORDER BY CONTRATO.CT_ID ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rec.hitss.layer.model.Contrato"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rec.hitss.layer.model.Contrato"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Contrato toModel(ContratoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Contrato model = new ContratoImpl();

		model.setCT_ID(soapModel.getCT_ID());
		model.setCT_ESTADO(soapModel.getCT_ESTADO());
		model.setCT_ACTIVO(soapModel.getCT_ACTIVO());
		model.setCT_USUARIO_CREA(soapModel.getCT_USUARIO_CREA());
		model.setCT_FECHA_CREA(soapModel.getCT_FECHA_CREA());
		model.setCT_USUARIO_MODIFICA(soapModel.getCT_USUARIO_MODIFICA());
		model.setCT_FECHA_MODIFICA(soapModel.getCT_FECHA_MODIFICA());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Contrato> toModels(ContratoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Contrato> models = new ArrayList<Contrato>(soapModels.length);

		for (ContratoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.rec.hitss.layer.model.Contrato"));

	public ContratoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _CT_ID;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCT_ID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _CT_ID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Contrato.class;
	}

	@Override
	public String getModelClassName() {
		return Contrato.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("CT_ID", getCT_ID());
		attributes.put("CT_ESTADO", getCT_ESTADO());
		attributes.put("CT_ACTIVO", getCT_ACTIVO());
		attributes.put("CT_USUARIO_CREA", getCT_USUARIO_CREA());
		attributes.put("CT_FECHA_CREA", getCT_FECHA_CREA());
		attributes.put("CT_USUARIO_MODIFICA", getCT_USUARIO_MODIFICA());
		attributes.put("CT_FECHA_MODIFICA", getCT_FECHA_MODIFICA());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long CT_ID = (Long)attributes.get("CT_ID");

		if (CT_ID != null) {
			setCT_ID(CT_ID);
		}

		String CT_ESTADO = (String)attributes.get("CT_ESTADO");

		if (CT_ESTADO != null) {
			setCT_ESTADO(CT_ESTADO);
		}

		String CT_ACTIVO = (String)attributes.get("CT_ACTIVO");

		if (CT_ACTIVO != null) {
			setCT_ACTIVO(CT_ACTIVO);
		}

		Long CT_USUARIO_CREA = (Long)attributes.get("CT_USUARIO_CREA");

		if (CT_USUARIO_CREA != null) {
			setCT_USUARIO_CREA(CT_USUARIO_CREA);
		}

		Date CT_FECHA_CREA = (Date)attributes.get("CT_FECHA_CREA");

		if (CT_FECHA_CREA != null) {
			setCT_FECHA_CREA(CT_FECHA_CREA);
		}

		Long CT_USUARIO_MODIFICA = (Long)attributes.get("CT_USUARIO_MODIFICA");

		if (CT_USUARIO_MODIFICA != null) {
			setCT_USUARIO_MODIFICA(CT_USUARIO_MODIFICA);
		}

		Date CT_FECHA_MODIFICA = (Date)attributes.get("CT_FECHA_MODIFICA");

		if (CT_FECHA_MODIFICA != null) {
			setCT_FECHA_MODIFICA(CT_FECHA_MODIFICA);
		}
	}

	@JSON
	@Override
	public long getCT_ID() {
		return _CT_ID;
	}

	@Override
	public void setCT_ID(long CT_ID) {
		_CT_ID = CT_ID;
	}

	@JSON
	@Override
	public String getCT_ESTADO() {
		if (_CT_ESTADO == null) {
			return StringPool.BLANK;
		}
		else {
			return _CT_ESTADO;
		}
	}

	@Override
	public void setCT_ESTADO(String CT_ESTADO) {
		_CT_ESTADO = CT_ESTADO;
	}

	@JSON
	@Override
	public String getCT_ACTIVO() {
		if (_CT_ACTIVO == null) {
			return StringPool.BLANK;
		}
		else {
			return _CT_ACTIVO;
		}
	}

	@Override
	public void setCT_ACTIVO(String CT_ACTIVO) {
		_CT_ACTIVO = CT_ACTIVO;
	}

	@JSON
	@Override
	public long getCT_USUARIO_CREA() {
		return _CT_USUARIO_CREA;
	}

	@Override
	public void setCT_USUARIO_CREA(long CT_USUARIO_CREA) {
		_CT_USUARIO_CREA = CT_USUARIO_CREA;
	}

	@JSON
	@Override
	public Date getCT_FECHA_CREA() {
		return _CT_FECHA_CREA;
	}

	@Override
	public void setCT_FECHA_CREA(Date CT_FECHA_CREA) {
		_CT_FECHA_CREA = CT_FECHA_CREA;
	}

	@JSON
	@Override
	public long getCT_USUARIO_MODIFICA() {
		return _CT_USUARIO_MODIFICA;
	}

	@Override
	public void setCT_USUARIO_MODIFICA(long CT_USUARIO_MODIFICA) {
		_CT_USUARIO_MODIFICA = CT_USUARIO_MODIFICA;
	}

	@JSON
	@Override
	public Date getCT_FECHA_MODIFICA() {
		return _CT_FECHA_MODIFICA;
	}

	@Override
	public void setCT_FECHA_MODIFICA(Date CT_FECHA_MODIFICA) {
		_CT_FECHA_MODIFICA = CT_FECHA_MODIFICA;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Contrato.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Contrato toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Contrato)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ContratoImpl contratoImpl = new ContratoImpl();

		contratoImpl.setCT_ID(getCT_ID());
		contratoImpl.setCT_ESTADO(getCT_ESTADO());
		contratoImpl.setCT_ACTIVO(getCT_ACTIVO());
		contratoImpl.setCT_USUARIO_CREA(getCT_USUARIO_CREA());
		contratoImpl.setCT_FECHA_CREA(getCT_FECHA_CREA());
		contratoImpl.setCT_USUARIO_MODIFICA(getCT_USUARIO_MODIFICA());
		contratoImpl.setCT_FECHA_MODIFICA(getCT_FECHA_MODIFICA());

		contratoImpl.resetOriginalValues();

		return contratoImpl;
	}

	@Override
	public int compareTo(Contrato contrato) {
		int value = 0;

		if (getCT_ID() < contrato.getCT_ID()) {
			value = -1;
		}
		else if (getCT_ID() > contrato.getCT_ID()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Contrato)) {
			return false;
		}

		Contrato contrato = (Contrato)obj;

		long primaryKey = contrato.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Contrato> toCacheModel() {
		ContratoCacheModel contratoCacheModel = new ContratoCacheModel();

		contratoCacheModel.CT_ID = getCT_ID();

		contratoCacheModel.CT_ESTADO = getCT_ESTADO();

		String CT_ESTADO = contratoCacheModel.CT_ESTADO;

		if ((CT_ESTADO != null) && (CT_ESTADO.length() == 0)) {
			contratoCacheModel.CT_ESTADO = null;
		}

		contratoCacheModel.CT_ACTIVO = getCT_ACTIVO();

		String CT_ACTIVO = contratoCacheModel.CT_ACTIVO;

		if ((CT_ACTIVO != null) && (CT_ACTIVO.length() == 0)) {
			contratoCacheModel.CT_ACTIVO = null;
		}

		contratoCacheModel.CT_USUARIO_CREA = getCT_USUARIO_CREA();

		Date CT_FECHA_CREA = getCT_FECHA_CREA();

		if (CT_FECHA_CREA != null) {
			contratoCacheModel.CT_FECHA_CREA = CT_FECHA_CREA.getTime();
		}
		else {
			contratoCacheModel.CT_FECHA_CREA = Long.MIN_VALUE;
		}

		contratoCacheModel.CT_USUARIO_MODIFICA = getCT_USUARIO_MODIFICA();

		Date CT_FECHA_MODIFICA = getCT_FECHA_MODIFICA();

		if (CT_FECHA_MODIFICA != null) {
			contratoCacheModel.CT_FECHA_MODIFICA = CT_FECHA_MODIFICA.getTime();
		}
		else {
			contratoCacheModel.CT_FECHA_MODIFICA = Long.MIN_VALUE;
		}

		return contratoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{CT_ID=");
		sb.append(getCT_ID());
		sb.append(", CT_ESTADO=");
		sb.append(getCT_ESTADO());
		sb.append(", CT_ACTIVO=");
		sb.append(getCT_ACTIVO());
		sb.append(", CT_USUARIO_CREA=");
		sb.append(getCT_USUARIO_CREA());
		sb.append(", CT_FECHA_CREA=");
		sb.append(getCT_FECHA_CREA());
		sb.append(", CT_USUARIO_MODIFICA=");
		sb.append(getCT_USUARIO_MODIFICA());
		sb.append(", CT_FECHA_MODIFICA=");
		sb.append(getCT_FECHA_MODIFICA());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append("com.rec.hitss.layer.model.Contrato");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>CT_ID</column-name><column-value><![CDATA[");
		sb.append(getCT_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CT_ESTADO</column-name><column-value><![CDATA[");
		sb.append(getCT_ESTADO());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CT_ACTIVO</column-name><column-value><![CDATA[");
		sb.append(getCT_ACTIVO());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CT_USUARIO_CREA</column-name><column-value><![CDATA[");
		sb.append(getCT_USUARIO_CREA());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CT_FECHA_CREA</column-name><column-value><![CDATA[");
		sb.append(getCT_FECHA_CREA());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CT_USUARIO_MODIFICA</column-name><column-value><![CDATA[");
		sb.append(getCT_USUARIO_MODIFICA());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CT_FECHA_MODIFICA</column-name><column-value><![CDATA[");
		sb.append(getCT_FECHA_MODIFICA());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Contrato.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			Contrato.class
		};
	private long _CT_ID;
	private String _CT_ESTADO;
	private String _CT_ACTIVO;
	private long _CT_USUARIO_CREA;
	private Date _CT_FECHA_CREA;
	private long _CT_USUARIO_MODIFICA;
	private Date _CT_FECHA_MODIFICA;
	private Contrato _escapedModel;
}