/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rec.hitss.layer.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.rec.hitss.layer.model.EvaluacionReclutamiento;
import com.rec.hitss.layer.model.EvaluacionReclutamientoModel;
import com.rec.hitss.layer.model.EvaluacionReclutamientoSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the EvaluacionReclutamiento service. Represents a row in the &quot;EVALUACION_RECLUTAMIENTO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.rec.hitss.layer.model.EvaluacionReclutamientoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EvaluacionReclutamientoImpl}.
 * </p>
 *
 * @author Crossfire
 * @see EvaluacionReclutamientoImpl
 * @see com.rec.hitss.layer.model.EvaluacionReclutamiento
 * @see com.rec.hitss.layer.model.EvaluacionReclutamientoModel
 * @generated
 */
@JSON(strict = true)
public class EvaluacionReclutamientoModelImpl extends BaseModelImpl<EvaluacionReclutamiento>
	implements EvaluacionReclutamientoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a evaluacion reclutamiento model instance should use the {@link com.rec.hitss.layer.model.EvaluacionReclutamiento} interface instead.
	 */
	public static final String TABLE_NAME = "EVALUACION_RECLUTAMIENTO";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ER_ID", Types.BIGINT },
			{ "ER_ESTADO", Types.VARCHAR },
			{ "ER_ACTIVO", Types.VARCHAR },
			{ "ER_USUARIO_CREA", Types.BIGINT },
			{ "ER_FECHA_CREA", Types.TIMESTAMP },
			{ "ER_USUARIO_MODIFICA", Types.BIGINT },
			{ "ER_FECHA_MODIFICA", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table EVALUACION_RECLUTAMIENTO (ER_ID LONG not null primary key,ER_ESTADO VARCHAR(75) null,ER_ACTIVO VARCHAR(75) null,ER_USUARIO_CREA LONG,ER_FECHA_CREA DATE null,ER_USUARIO_MODIFICA LONG,ER_FECHA_MODIFICA DATE null)";
	public static final String TABLE_SQL_DROP = "drop table EVALUACION_RECLUTAMIENTO";
	public static final String ORDER_BY_JPQL = " ORDER BY evaluacionReclutamiento.ER_ID ASC";
	public static final String ORDER_BY_SQL = " ORDER BY EVALUACION_RECLUTAMIENTO.ER_ID ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rec.hitss.layer.model.EvaluacionReclutamiento"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rec.hitss.layer.model.EvaluacionReclutamiento"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static EvaluacionReclutamiento toModel(
		EvaluacionReclutamientoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		EvaluacionReclutamiento model = new EvaluacionReclutamientoImpl();

		model.setER_ID(soapModel.getER_ID());
		model.setER_ESTADO(soapModel.getER_ESTADO());
		model.setER_ACTIVO(soapModel.getER_ACTIVO());
		model.setER_USUARIO_CREA(soapModel.getER_USUARIO_CREA());
		model.setER_FECHA_CREA(soapModel.getER_FECHA_CREA());
		model.setER_USUARIO_MODIFICA(soapModel.getER_USUARIO_MODIFICA());
		model.setER_FECHA_MODIFICA(soapModel.getER_FECHA_MODIFICA());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<EvaluacionReclutamiento> toModels(
		EvaluacionReclutamientoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<EvaluacionReclutamiento> models = new ArrayList<EvaluacionReclutamiento>(soapModels.length);

		for (EvaluacionReclutamientoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.rec.hitss.layer.model.EvaluacionReclutamiento"));

	public EvaluacionReclutamientoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _ER_ID;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setER_ID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _ER_ID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EvaluacionReclutamiento.class;
	}

	@Override
	public String getModelClassName() {
		return EvaluacionReclutamiento.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("ER_ID", getER_ID());
		attributes.put("ER_ESTADO", getER_ESTADO());
		attributes.put("ER_ACTIVO", getER_ACTIVO());
		attributes.put("ER_USUARIO_CREA", getER_USUARIO_CREA());
		attributes.put("ER_FECHA_CREA", getER_FECHA_CREA());
		attributes.put("ER_USUARIO_MODIFICA", getER_USUARIO_MODIFICA());
		attributes.put("ER_FECHA_MODIFICA", getER_FECHA_MODIFICA());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long ER_ID = (Long)attributes.get("ER_ID");

		if (ER_ID != null) {
			setER_ID(ER_ID);
		}

		String ER_ESTADO = (String)attributes.get("ER_ESTADO");

		if (ER_ESTADO != null) {
			setER_ESTADO(ER_ESTADO);
		}

		String ER_ACTIVO = (String)attributes.get("ER_ACTIVO");

		if (ER_ACTIVO != null) {
			setER_ACTIVO(ER_ACTIVO);
		}

		Long ER_USUARIO_CREA = (Long)attributes.get("ER_USUARIO_CREA");

		if (ER_USUARIO_CREA != null) {
			setER_USUARIO_CREA(ER_USUARIO_CREA);
		}

		Date ER_FECHA_CREA = (Date)attributes.get("ER_FECHA_CREA");

		if (ER_FECHA_CREA != null) {
			setER_FECHA_CREA(ER_FECHA_CREA);
		}

		Long ER_USUARIO_MODIFICA = (Long)attributes.get("ER_USUARIO_MODIFICA");

		if (ER_USUARIO_MODIFICA != null) {
			setER_USUARIO_MODIFICA(ER_USUARIO_MODIFICA);
		}

		Date ER_FECHA_MODIFICA = (Date)attributes.get("ER_FECHA_MODIFICA");

		if (ER_FECHA_MODIFICA != null) {
			setER_FECHA_MODIFICA(ER_FECHA_MODIFICA);
		}
	}

	@JSON
	@Override
	public long getER_ID() {
		return _ER_ID;
	}

	@Override
	public void setER_ID(long ER_ID) {
		_ER_ID = ER_ID;
	}

	@JSON
	@Override
	public String getER_ESTADO() {
		if (_ER_ESTADO == null) {
			return StringPool.BLANK;
		}
		else {
			return _ER_ESTADO;
		}
	}

	@Override
	public void setER_ESTADO(String ER_ESTADO) {
		_ER_ESTADO = ER_ESTADO;
	}

	@JSON
	@Override
	public String getER_ACTIVO() {
		if (_ER_ACTIVO == null) {
			return StringPool.BLANK;
		}
		else {
			return _ER_ACTIVO;
		}
	}

	@Override
	public void setER_ACTIVO(String ER_ACTIVO) {
		_ER_ACTIVO = ER_ACTIVO;
	}

	@JSON
	@Override
	public long getER_USUARIO_CREA() {
		return _ER_USUARIO_CREA;
	}

	@Override
	public void setER_USUARIO_CREA(long ER_USUARIO_CREA) {
		_ER_USUARIO_CREA = ER_USUARIO_CREA;
	}

	@JSON
	@Override
	public Date getER_FECHA_CREA() {
		return _ER_FECHA_CREA;
	}

	@Override
	public void setER_FECHA_CREA(Date ER_FECHA_CREA) {
		_ER_FECHA_CREA = ER_FECHA_CREA;
	}

	@JSON
	@Override
	public long getER_USUARIO_MODIFICA() {
		return _ER_USUARIO_MODIFICA;
	}

	@Override
	public void setER_USUARIO_MODIFICA(long ER_USUARIO_MODIFICA) {
		_ER_USUARIO_MODIFICA = ER_USUARIO_MODIFICA;
	}

	@JSON
	@Override
	public Date getER_FECHA_MODIFICA() {
		return _ER_FECHA_MODIFICA;
	}

	@Override
	public void setER_FECHA_MODIFICA(Date ER_FECHA_MODIFICA) {
		_ER_FECHA_MODIFICA = ER_FECHA_MODIFICA;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			EvaluacionReclutamiento.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EvaluacionReclutamiento toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (EvaluacionReclutamiento)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EvaluacionReclutamientoImpl evaluacionReclutamientoImpl = new EvaluacionReclutamientoImpl();

		evaluacionReclutamientoImpl.setER_ID(getER_ID());
		evaluacionReclutamientoImpl.setER_ESTADO(getER_ESTADO());
		evaluacionReclutamientoImpl.setER_ACTIVO(getER_ACTIVO());
		evaluacionReclutamientoImpl.setER_USUARIO_CREA(getER_USUARIO_CREA());
		evaluacionReclutamientoImpl.setER_FECHA_CREA(getER_FECHA_CREA());
		evaluacionReclutamientoImpl.setER_USUARIO_MODIFICA(getER_USUARIO_MODIFICA());
		evaluacionReclutamientoImpl.setER_FECHA_MODIFICA(getER_FECHA_MODIFICA());

		evaluacionReclutamientoImpl.resetOriginalValues();

		return evaluacionReclutamientoImpl;
	}

	@Override
	public int compareTo(EvaluacionReclutamiento evaluacionReclutamiento) {
		int value = 0;

		if (getER_ID() < evaluacionReclutamiento.getER_ID()) {
			value = -1;
		}
		else if (getER_ID() > evaluacionReclutamiento.getER_ID()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof EvaluacionReclutamiento)) {
			return false;
		}

		EvaluacionReclutamiento evaluacionReclutamiento = (EvaluacionReclutamiento)obj;

		long primaryKey = evaluacionReclutamiento.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<EvaluacionReclutamiento> toCacheModel() {
		EvaluacionReclutamientoCacheModel evaluacionReclutamientoCacheModel = new EvaluacionReclutamientoCacheModel();

		evaluacionReclutamientoCacheModel.ER_ID = getER_ID();

		evaluacionReclutamientoCacheModel.ER_ESTADO = getER_ESTADO();

		String ER_ESTADO = evaluacionReclutamientoCacheModel.ER_ESTADO;

		if ((ER_ESTADO != null) && (ER_ESTADO.length() == 0)) {
			evaluacionReclutamientoCacheModel.ER_ESTADO = null;
		}

		evaluacionReclutamientoCacheModel.ER_ACTIVO = getER_ACTIVO();

		String ER_ACTIVO = evaluacionReclutamientoCacheModel.ER_ACTIVO;

		if ((ER_ACTIVO != null) && (ER_ACTIVO.length() == 0)) {
			evaluacionReclutamientoCacheModel.ER_ACTIVO = null;
		}

		evaluacionReclutamientoCacheModel.ER_USUARIO_CREA = getER_USUARIO_CREA();

		Date ER_FECHA_CREA = getER_FECHA_CREA();

		if (ER_FECHA_CREA != null) {
			evaluacionReclutamientoCacheModel.ER_FECHA_CREA = ER_FECHA_CREA.getTime();
		}
		else {
			evaluacionReclutamientoCacheModel.ER_FECHA_CREA = Long.MIN_VALUE;
		}

		evaluacionReclutamientoCacheModel.ER_USUARIO_MODIFICA = getER_USUARIO_MODIFICA();

		Date ER_FECHA_MODIFICA = getER_FECHA_MODIFICA();

		if (ER_FECHA_MODIFICA != null) {
			evaluacionReclutamientoCacheModel.ER_FECHA_MODIFICA = ER_FECHA_MODIFICA.getTime();
		}
		else {
			evaluacionReclutamientoCacheModel.ER_FECHA_MODIFICA = Long.MIN_VALUE;
		}

		return evaluacionReclutamientoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{ER_ID=");
		sb.append(getER_ID());
		sb.append(", ER_ESTADO=");
		sb.append(getER_ESTADO());
		sb.append(", ER_ACTIVO=");
		sb.append(getER_ACTIVO());
		sb.append(", ER_USUARIO_CREA=");
		sb.append(getER_USUARIO_CREA());
		sb.append(", ER_FECHA_CREA=");
		sb.append(getER_FECHA_CREA());
		sb.append(", ER_USUARIO_MODIFICA=");
		sb.append(getER_USUARIO_MODIFICA());
		sb.append(", ER_FECHA_MODIFICA=");
		sb.append(getER_FECHA_MODIFICA());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append("com.rec.hitss.layer.model.EvaluacionReclutamiento");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>ER_ID</column-name><column-value><![CDATA[");
		sb.append(getER_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ER_ESTADO</column-name><column-value><![CDATA[");
		sb.append(getER_ESTADO());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ER_ACTIVO</column-name><column-value><![CDATA[");
		sb.append(getER_ACTIVO());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ER_USUARIO_CREA</column-name><column-value><![CDATA[");
		sb.append(getER_USUARIO_CREA());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ER_FECHA_CREA</column-name><column-value><![CDATA[");
		sb.append(getER_FECHA_CREA());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ER_USUARIO_MODIFICA</column-name><column-value><![CDATA[");
		sb.append(getER_USUARIO_MODIFICA());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ER_FECHA_MODIFICA</column-name><column-value><![CDATA[");
		sb.append(getER_FECHA_MODIFICA());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = EvaluacionReclutamiento.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			EvaluacionReclutamiento.class
		};
	private long _ER_ID;
	private String _ER_ESTADO;
	private String _ER_ACTIVO;
	private long _ER_USUARIO_CREA;
	private Date _ER_FECHA_CREA;
	private long _ER_USUARIO_MODIFICA;
	private Date _ER_FECHA_MODIFICA;
	private EvaluacionReclutamiento _escapedModel;
}