/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rec.hitss.layer.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.rec.hitss.layer.model.fichaIngreso;
import com.rec.hitss.layer.model.fichaIngresoModel;
import com.rec.hitss.layer.model.fichaIngresoSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the fichaIngreso service. Represents a row in the &quot;FICHA_INGRESO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.rec.hitss.layer.model.fichaIngresoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link fichaIngresoImpl}.
 * </p>
 *
 * @author Crossfire
 * @see fichaIngresoImpl
 * @see com.rec.hitss.layer.model.fichaIngreso
 * @see com.rec.hitss.layer.model.fichaIngresoModel
 * @generated
 */
@JSON(strict = true)
public class fichaIngresoModelImpl extends BaseModelImpl<fichaIngreso>
	implements fichaIngresoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ficha ingreso model instance should use the {@link com.rec.hitss.layer.model.fichaIngreso} interface instead.
	 */
	public static final String TABLE_NAME = "FICHA_INGRESO";
	public static final Object[][] TABLE_COLUMNS = {
			{ "FI_ID", Types.BIGINT },
			{ "FI_ESTADO", Types.VARCHAR },
			{ "FI_ACTIVO", Types.VARCHAR },
			{ "FI_USUARIO_CREA", Types.BIGINT },
			{ "FI_FECHA_CREA", Types.TIMESTAMP },
			{ "FI_USUARIO_MODIFICA", Types.BIGINT },
			{ "FI_FECHA_MODIFICA", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table FICHA_INGRESO (FI_ID LONG not null primary key,FI_ESTADO VARCHAR(75) null,FI_ACTIVO VARCHAR(75) null,FI_USUARIO_CREA LONG,FI_FECHA_CREA DATE null,FI_USUARIO_MODIFICA LONG,FI_FECHA_MODIFICA DATE null)";
	public static final String TABLE_SQL_DROP = "drop table FICHA_INGRESO";
	public static final String ORDER_BY_JPQL = " ORDER BY fichaIngreso.FI_ID ASC";
	public static final String ORDER_BY_SQL = " ORDER BY FICHA_INGRESO.FI_ID ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rec.hitss.layer.model.fichaIngreso"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rec.hitss.layer.model.fichaIngreso"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static fichaIngreso toModel(fichaIngresoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		fichaIngreso model = new fichaIngresoImpl();

		model.setFI_ID(soapModel.getFI_ID());
		model.setFI_ESTADO(soapModel.getFI_ESTADO());
		model.setFI_ACTIVO(soapModel.getFI_ACTIVO());
		model.setFI_USUARIO_CREA(soapModel.getFI_USUARIO_CREA());
		model.setFI_FECHA_CREA(soapModel.getFI_FECHA_CREA());
		model.setFI_USUARIO_MODIFICA(soapModel.getFI_USUARIO_MODIFICA());
		model.setFI_FECHA_MODIFICA(soapModel.getFI_FECHA_MODIFICA());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<fichaIngreso> toModels(fichaIngresoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<fichaIngreso> models = new ArrayList<fichaIngreso>(soapModels.length);

		for (fichaIngresoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.rec.hitss.layer.model.fichaIngreso"));

	public fichaIngresoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _FI_ID;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFI_ID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _FI_ID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return fichaIngreso.class;
	}

	@Override
	public String getModelClassName() {
		return fichaIngreso.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("FI_ID", getFI_ID());
		attributes.put("FI_ESTADO", getFI_ESTADO());
		attributes.put("FI_ACTIVO", getFI_ACTIVO());
		attributes.put("FI_USUARIO_CREA", getFI_USUARIO_CREA());
		attributes.put("FI_FECHA_CREA", getFI_FECHA_CREA());
		attributes.put("FI_USUARIO_MODIFICA", getFI_USUARIO_MODIFICA());
		attributes.put("FI_FECHA_MODIFICA", getFI_FECHA_MODIFICA());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long FI_ID = (Long)attributes.get("FI_ID");

		if (FI_ID != null) {
			setFI_ID(FI_ID);
		}

		String FI_ESTADO = (String)attributes.get("FI_ESTADO");

		if (FI_ESTADO != null) {
			setFI_ESTADO(FI_ESTADO);
		}

		String FI_ACTIVO = (String)attributes.get("FI_ACTIVO");

		if (FI_ACTIVO != null) {
			setFI_ACTIVO(FI_ACTIVO);
		}

		Long FI_USUARIO_CREA = (Long)attributes.get("FI_USUARIO_CREA");

		if (FI_USUARIO_CREA != null) {
			setFI_USUARIO_CREA(FI_USUARIO_CREA);
		}

		Date FI_FECHA_CREA = (Date)attributes.get("FI_FECHA_CREA");

		if (FI_FECHA_CREA != null) {
			setFI_FECHA_CREA(FI_FECHA_CREA);
		}

		Long FI_USUARIO_MODIFICA = (Long)attributes.get("FI_USUARIO_MODIFICA");

		if (FI_USUARIO_MODIFICA != null) {
			setFI_USUARIO_MODIFICA(FI_USUARIO_MODIFICA);
		}

		Date FI_FECHA_MODIFICA = (Date)attributes.get("FI_FECHA_MODIFICA");

		if (FI_FECHA_MODIFICA != null) {
			setFI_FECHA_MODIFICA(FI_FECHA_MODIFICA);
		}
	}

	@JSON
	@Override
	public long getFI_ID() {
		return _FI_ID;
	}

	@Override
	public void setFI_ID(long FI_ID) {
		_FI_ID = FI_ID;
	}

	@JSON
	@Override
	public String getFI_ESTADO() {
		if (_FI_ESTADO == null) {
			return StringPool.BLANK;
		}
		else {
			return _FI_ESTADO;
		}
	}

	@Override
	public void setFI_ESTADO(String FI_ESTADO) {
		_FI_ESTADO = FI_ESTADO;
	}

	@JSON
	@Override
	public String getFI_ACTIVO() {
		if (_FI_ACTIVO == null) {
			return StringPool.BLANK;
		}
		else {
			return _FI_ACTIVO;
		}
	}

	@Override
	public void setFI_ACTIVO(String FI_ACTIVO) {
		_FI_ACTIVO = FI_ACTIVO;
	}

	@JSON
	@Override
	public long getFI_USUARIO_CREA() {
		return _FI_USUARIO_CREA;
	}

	@Override
	public void setFI_USUARIO_CREA(long FI_USUARIO_CREA) {
		_FI_USUARIO_CREA = FI_USUARIO_CREA;
	}

	@JSON
	@Override
	public Date getFI_FECHA_CREA() {
		return _FI_FECHA_CREA;
	}

	@Override
	public void setFI_FECHA_CREA(Date FI_FECHA_CREA) {
		_FI_FECHA_CREA = FI_FECHA_CREA;
	}

	@JSON
	@Override
	public long getFI_USUARIO_MODIFICA() {
		return _FI_USUARIO_MODIFICA;
	}

	@Override
	public void setFI_USUARIO_MODIFICA(long FI_USUARIO_MODIFICA) {
		_FI_USUARIO_MODIFICA = FI_USUARIO_MODIFICA;
	}

	@JSON
	@Override
	public Date getFI_FECHA_MODIFICA() {
		return _FI_FECHA_MODIFICA;
	}

	@Override
	public void setFI_FECHA_MODIFICA(Date FI_FECHA_MODIFICA) {
		_FI_FECHA_MODIFICA = FI_FECHA_MODIFICA;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			fichaIngreso.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public fichaIngreso toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (fichaIngreso)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		fichaIngresoImpl fichaIngresoImpl = new fichaIngresoImpl();

		fichaIngresoImpl.setFI_ID(getFI_ID());
		fichaIngresoImpl.setFI_ESTADO(getFI_ESTADO());
		fichaIngresoImpl.setFI_ACTIVO(getFI_ACTIVO());
		fichaIngresoImpl.setFI_USUARIO_CREA(getFI_USUARIO_CREA());
		fichaIngresoImpl.setFI_FECHA_CREA(getFI_FECHA_CREA());
		fichaIngresoImpl.setFI_USUARIO_MODIFICA(getFI_USUARIO_MODIFICA());
		fichaIngresoImpl.setFI_FECHA_MODIFICA(getFI_FECHA_MODIFICA());

		fichaIngresoImpl.resetOriginalValues();

		return fichaIngresoImpl;
	}

	@Override
	public int compareTo(fichaIngreso fichaIngreso) {
		int value = 0;

		if (getFI_ID() < fichaIngreso.getFI_ID()) {
			value = -1;
		}
		else if (getFI_ID() > fichaIngreso.getFI_ID()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof fichaIngreso)) {
			return false;
		}

		fichaIngreso fichaIngreso = (fichaIngreso)obj;

		long primaryKey = fichaIngreso.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<fichaIngreso> toCacheModel() {
		fichaIngresoCacheModel fichaIngresoCacheModel = new fichaIngresoCacheModel();

		fichaIngresoCacheModel.FI_ID = getFI_ID();

		fichaIngresoCacheModel.FI_ESTADO = getFI_ESTADO();

		String FI_ESTADO = fichaIngresoCacheModel.FI_ESTADO;

		if ((FI_ESTADO != null) && (FI_ESTADO.length() == 0)) {
			fichaIngresoCacheModel.FI_ESTADO = null;
		}

		fichaIngresoCacheModel.FI_ACTIVO = getFI_ACTIVO();

		String FI_ACTIVO = fichaIngresoCacheModel.FI_ACTIVO;

		if ((FI_ACTIVO != null) && (FI_ACTIVO.length() == 0)) {
			fichaIngresoCacheModel.FI_ACTIVO = null;
		}

		fichaIngresoCacheModel.FI_USUARIO_CREA = getFI_USUARIO_CREA();

		Date FI_FECHA_CREA = getFI_FECHA_CREA();

		if (FI_FECHA_CREA != null) {
			fichaIngresoCacheModel.FI_FECHA_CREA = FI_FECHA_CREA.getTime();
		}
		else {
			fichaIngresoCacheModel.FI_FECHA_CREA = Long.MIN_VALUE;
		}

		fichaIngresoCacheModel.FI_USUARIO_MODIFICA = getFI_USUARIO_MODIFICA();

		Date FI_FECHA_MODIFICA = getFI_FECHA_MODIFICA();

		if (FI_FECHA_MODIFICA != null) {
			fichaIngresoCacheModel.FI_FECHA_MODIFICA = FI_FECHA_MODIFICA.getTime();
		}
		else {
			fichaIngresoCacheModel.FI_FECHA_MODIFICA = Long.MIN_VALUE;
		}

		return fichaIngresoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{FI_ID=");
		sb.append(getFI_ID());
		sb.append(", FI_ESTADO=");
		sb.append(getFI_ESTADO());
		sb.append(", FI_ACTIVO=");
		sb.append(getFI_ACTIVO());
		sb.append(", FI_USUARIO_CREA=");
		sb.append(getFI_USUARIO_CREA());
		sb.append(", FI_FECHA_CREA=");
		sb.append(getFI_FECHA_CREA());
		sb.append(", FI_USUARIO_MODIFICA=");
		sb.append(getFI_USUARIO_MODIFICA());
		sb.append(", FI_FECHA_MODIFICA=");
		sb.append(getFI_FECHA_MODIFICA());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append("com.rec.hitss.layer.model.fichaIngreso");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>FI_ID</column-name><column-value><![CDATA[");
		sb.append(getFI_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>FI_ESTADO</column-name><column-value><![CDATA[");
		sb.append(getFI_ESTADO());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>FI_ACTIVO</column-name><column-value><![CDATA[");
		sb.append(getFI_ACTIVO());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>FI_USUARIO_CREA</column-name><column-value><![CDATA[");
		sb.append(getFI_USUARIO_CREA());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>FI_FECHA_CREA</column-name><column-value><![CDATA[");
		sb.append(getFI_FECHA_CREA());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>FI_USUARIO_MODIFICA</column-name><column-value><![CDATA[");
		sb.append(getFI_USUARIO_MODIFICA());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>FI_FECHA_MODIFICA</column-name><column-value><![CDATA[");
		sb.append(getFI_FECHA_MODIFICA());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = fichaIngreso.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			fichaIngreso.class
		};
	private long _FI_ID;
	private String _FI_ESTADO;
	private String _FI_ACTIVO;
	private long _FI_USUARIO_CREA;
	private Date _FI_FECHA_CREA;
	private long _FI_USUARIO_MODIFICA;
	private Date _FI_FECHA_MODIFICA;
	private fichaIngreso _escapedModel;
}