/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rec.hitss.layer.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.rec.hitss.layer.model.requerimientoPersonal;
import com.rec.hitss.layer.model.requerimientoPersonalModel;
import com.rec.hitss.layer.model.requerimientoPersonalSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the requerimientoPersonal service. Represents a row in the &quot;REQUERIMIENTO_PERSONAL&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.rec.hitss.layer.model.requerimientoPersonalModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link requerimientoPersonalImpl}.
 * </p>
 *
 * @author Crossfire
 * @see requerimientoPersonalImpl
 * @see com.rec.hitss.layer.model.requerimientoPersonal
 * @see com.rec.hitss.layer.model.requerimientoPersonalModel
 * @generated
 */
@JSON(strict = true)
public class requerimientoPersonalModelImpl extends BaseModelImpl<requerimientoPersonal>
	implements requerimientoPersonalModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a requerimiento personal model instance should use the {@link com.rec.hitss.layer.model.requerimientoPersonal} interface instead.
	 */
	public static final String TABLE_NAME = "REQUERIMIENTO_PERSONAL";
	public static final Object[][] TABLE_COLUMNS = {
			{ "REQ_ID", Types.BIGINT },
			{ "REQ_ESTADO", Types.VARCHAR },
			{ "REQ_ACTIVO", Types.VARCHAR },
			{ "REQ_USUARIO_CREA", Types.BIGINT },
			{ "REQ_FECHA_CREA", Types.TIMESTAMP },
			{ "REQ_USUARIO_MODIFICA", Types.BIGINT },
			{ "REQ_FECHA_MODIFICA", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table REQUERIMIENTO_PERSONAL (REQ_ID LONG not null primary key,REQ_ESTADO VARCHAR(75) null,REQ_ACTIVO VARCHAR(75) null,REQ_USUARIO_CREA LONG,REQ_FECHA_CREA DATE null,REQ_USUARIO_MODIFICA LONG,REQ_FECHA_MODIFICA DATE null)";
	public static final String TABLE_SQL_DROP = "drop table REQUERIMIENTO_PERSONAL";
	public static final String ORDER_BY_JPQL = " ORDER BY requerimientoPersonal.REQ_ID ASC";
	public static final String ORDER_BY_SQL = " ORDER BY REQUERIMIENTO_PERSONAL.REQ_ID ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rec.hitss.layer.model.requerimientoPersonal"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rec.hitss.layer.model.requerimientoPersonal"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static requerimientoPersonal toModel(
		requerimientoPersonalSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		requerimientoPersonal model = new requerimientoPersonalImpl();

		model.setREQ_ID(soapModel.getREQ_ID());
		model.setREQ_ESTADO(soapModel.getREQ_ESTADO());
		model.setREQ_ACTIVO(soapModel.getREQ_ACTIVO());
		model.setREQ_USUARIO_CREA(soapModel.getREQ_USUARIO_CREA());
		model.setREQ_FECHA_CREA(soapModel.getREQ_FECHA_CREA());
		model.setREQ_USUARIO_MODIFICA(soapModel.getREQ_USUARIO_MODIFICA());
		model.setREQ_FECHA_MODIFICA(soapModel.getREQ_FECHA_MODIFICA());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<requerimientoPersonal> toModels(
		requerimientoPersonalSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<requerimientoPersonal> models = new ArrayList<requerimientoPersonal>(soapModels.length);

		for (requerimientoPersonalSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.rec.hitss.layer.model.requerimientoPersonal"));

	public requerimientoPersonalModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _REQ_ID;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setREQ_ID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _REQ_ID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return requerimientoPersonal.class;
	}

	@Override
	public String getModelClassName() {
		return requerimientoPersonal.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("REQ_ID", getREQ_ID());
		attributes.put("REQ_ESTADO", getREQ_ESTADO());
		attributes.put("REQ_ACTIVO", getREQ_ACTIVO());
		attributes.put("REQ_USUARIO_CREA", getREQ_USUARIO_CREA());
		attributes.put("REQ_FECHA_CREA", getREQ_FECHA_CREA());
		attributes.put("REQ_USUARIO_MODIFICA", getREQ_USUARIO_MODIFICA());
		attributes.put("REQ_FECHA_MODIFICA", getREQ_FECHA_MODIFICA());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long REQ_ID = (Long)attributes.get("REQ_ID");

		if (REQ_ID != null) {
			setREQ_ID(REQ_ID);
		}

		String REQ_ESTADO = (String)attributes.get("REQ_ESTADO");

		if (REQ_ESTADO != null) {
			setREQ_ESTADO(REQ_ESTADO);
		}

		String REQ_ACTIVO = (String)attributes.get("REQ_ACTIVO");

		if (REQ_ACTIVO != null) {
			setREQ_ACTIVO(REQ_ACTIVO);
		}

		Long REQ_USUARIO_CREA = (Long)attributes.get("REQ_USUARIO_CREA");

		if (REQ_USUARIO_CREA != null) {
			setREQ_USUARIO_CREA(REQ_USUARIO_CREA);
		}

		Date REQ_FECHA_CREA = (Date)attributes.get("REQ_FECHA_CREA");

		if (REQ_FECHA_CREA != null) {
			setREQ_FECHA_CREA(REQ_FECHA_CREA);
		}

		Long REQ_USUARIO_MODIFICA = (Long)attributes.get("REQ_USUARIO_MODIFICA");

		if (REQ_USUARIO_MODIFICA != null) {
			setREQ_USUARIO_MODIFICA(REQ_USUARIO_MODIFICA);
		}

		Date REQ_FECHA_MODIFICA = (Date)attributes.get("REQ_FECHA_MODIFICA");

		if (REQ_FECHA_MODIFICA != null) {
			setREQ_FECHA_MODIFICA(REQ_FECHA_MODIFICA);
		}
	}

	@JSON
	@Override
	public long getREQ_ID() {
		return _REQ_ID;
	}

	@Override
	public void setREQ_ID(long REQ_ID) {
		_REQ_ID = REQ_ID;
	}

	@JSON
	@Override
	public String getREQ_ESTADO() {
		if (_REQ_ESTADO == null) {
			return StringPool.BLANK;
		}
		else {
			return _REQ_ESTADO;
		}
	}

	@Override
	public void setREQ_ESTADO(String REQ_ESTADO) {
		_REQ_ESTADO = REQ_ESTADO;
	}

	@JSON
	@Override
	public String getREQ_ACTIVO() {
		if (_REQ_ACTIVO == null) {
			return StringPool.BLANK;
		}
		else {
			return _REQ_ACTIVO;
		}
	}

	@Override
	public void setREQ_ACTIVO(String REQ_ACTIVO) {
		_REQ_ACTIVO = REQ_ACTIVO;
	}

	@JSON
	@Override
	public long getREQ_USUARIO_CREA() {
		return _REQ_USUARIO_CREA;
	}

	@Override
	public void setREQ_USUARIO_CREA(long REQ_USUARIO_CREA) {
		_REQ_USUARIO_CREA = REQ_USUARIO_CREA;
	}

	@JSON
	@Override
	public Date getREQ_FECHA_CREA() {
		return _REQ_FECHA_CREA;
	}

	@Override
	public void setREQ_FECHA_CREA(Date REQ_FECHA_CREA) {
		_REQ_FECHA_CREA = REQ_FECHA_CREA;
	}

	@JSON
	@Override
	public long getREQ_USUARIO_MODIFICA() {
		return _REQ_USUARIO_MODIFICA;
	}

	@Override
	public void setREQ_USUARIO_MODIFICA(long REQ_USUARIO_MODIFICA) {
		_REQ_USUARIO_MODIFICA = REQ_USUARIO_MODIFICA;
	}

	@JSON
	@Override
	public Date getREQ_FECHA_MODIFICA() {
		return _REQ_FECHA_MODIFICA;
	}

	@Override
	public void setREQ_FECHA_MODIFICA(Date REQ_FECHA_MODIFICA) {
		_REQ_FECHA_MODIFICA = REQ_FECHA_MODIFICA;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			requerimientoPersonal.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public requerimientoPersonal toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (requerimientoPersonal)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		requerimientoPersonalImpl requerimientoPersonalImpl = new requerimientoPersonalImpl();

		requerimientoPersonalImpl.setREQ_ID(getREQ_ID());
		requerimientoPersonalImpl.setREQ_ESTADO(getREQ_ESTADO());
		requerimientoPersonalImpl.setREQ_ACTIVO(getREQ_ACTIVO());
		requerimientoPersonalImpl.setREQ_USUARIO_CREA(getREQ_USUARIO_CREA());
		requerimientoPersonalImpl.setREQ_FECHA_CREA(getREQ_FECHA_CREA());
		requerimientoPersonalImpl.setREQ_USUARIO_MODIFICA(getREQ_USUARIO_MODIFICA());
		requerimientoPersonalImpl.setREQ_FECHA_MODIFICA(getREQ_FECHA_MODIFICA());

		requerimientoPersonalImpl.resetOriginalValues();

		return requerimientoPersonalImpl;
	}

	@Override
	public int compareTo(requerimientoPersonal requerimientoPersonal) {
		int value = 0;

		if (getREQ_ID() < requerimientoPersonal.getREQ_ID()) {
			value = -1;
		}
		else if (getREQ_ID() > requerimientoPersonal.getREQ_ID()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof requerimientoPersonal)) {
			return false;
		}

		requerimientoPersonal requerimientoPersonal = (requerimientoPersonal)obj;

		long primaryKey = requerimientoPersonal.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<requerimientoPersonal> toCacheModel() {
		requerimientoPersonalCacheModel requerimientoPersonalCacheModel = new requerimientoPersonalCacheModel();

		requerimientoPersonalCacheModel.REQ_ID = getREQ_ID();

		requerimientoPersonalCacheModel.REQ_ESTADO = getREQ_ESTADO();

		String REQ_ESTADO = requerimientoPersonalCacheModel.REQ_ESTADO;

		if ((REQ_ESTADO != null) && (REQ_ESTADO.length() == 0)) {
			requerimientoPersonalCacheModel.REQ_ESTADO = null;
		}

		requerimientoPersonalCacheModel.REQ_ACTIVO = getREQ_ACTIVO();

		String REQ_ACTIVO = requerimientoPersonalCacheModel.REQ_ACTIVO;

		if ((REQ_ACTIVO != null) && (REQ_ACTIVO.length() == 0)) {
			requerimientoPersonalCacheModel.REQ_ACTIVO = null;
		}

		requerimientoPersonalCacheModel.REQ_USUARIO_CREA = getREQ_USUARIO_CREA();

		Date REQ_FECHA_CREA = getREQ_FECHA_CREA();

		if (REQ_FECHA_CREA != null) {
			requerimientoPersonalCacheModel.REQ_FECHA_CREA = REQ_FECHA_CREA.getTime();
		}
		else {
			requerimientoPersonalCacheModel.REQ_FECHA_CREA = Long.MIN_VALUE;
		}

		requerimientoPersonalCacheModel.REQ_USUARIO_MODIFICA = getREQ_USUARIO_MODIFICA();

		Date REQ_FECHA_MODIFICA = getREQ_FECHA_MODIFICA();

		if (REQ_FECHA_MODIFICA != null) {
			requerimientoPersonalCacheModel.REQ_FECHA_MODIFICA = REQ_FECHA_MODIFICA.getTime();
		}
		else {
			requerimientoPersonalCacheModel.REQ_FECHA_MODIFICA = Long.MIN_VALUE;
		}

		return requerimientoPersonalCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{REQ_ID=");
		sb.append(getREQ_ID());
		sb.append(", REQ_ESTADO=");
		sb.append(getREQ_ESTADO());
		sb.append(", REQ_ACTIVO=");
		sb.append(getREQ_ACTIVO());
		sb.append(", REQ_USUARIO_CREA=");
		sb.append(getREQ_USUARIO_CREA());
		sb.append(", REQ_FECHA_CREA=");
		sb.append(getREQ_FECHA_CREA());
		sb.append(", REQ_USUARIO_MODIFICA=");
		sb.append(getREQ_USUARIO_MODIFICA());
		sb.append(", REQ_FECHA_MODIFICA=");
		sb.append(getREQ_FECHA_MODIFICA());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append("com.rec.hitss.layer.model.requerimientoPersonal");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>REQ_ID</column-name><column-value><![CDATA[");
		sb.append(getREQ_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>REQ_ESTADO</column-name><column-value><![CDATA[");
		sb.append(getREQ_ESTADO());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>REQ_ACTIVO</column-name><column-value><![CDATA[");
		sb.append(getREQ_ACTIVO());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>REQ_USUARIO_CREA</column-name><column-value><![CDATA[");
		sb.append(getREQ_USUARIO_CREA());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>REQ_FECHA_CREA</column-name><column-value><![CDATA[");
		sb.append(getREQ_FECHA_CREA());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>REQ_USUARIO_MODIFICA</column-name><column-value><![CDATA[");
		sb.append(getREQ_USUARIO_MODIFICA());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>REQ_FECHA_MODIFICA</column-name><column-value><![CDATA[");
		sb.append(getREQ_FECHA_MODIFICA());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = requerimientoPersonal.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			requerimientoPersonal.class
		};
	private long _REQ_ID;
	private String _REQ_ESTADO;
	private String _REQ_ACTIVO;
	private long _REQ_USUARIO_CREA;
	private Date _REQ_FECHA_CREA;
	private long _REQ_USUARIO_MODIFICA;
	private Date _REQ_FECHA_MODIFICA;
	private requerimientoPersonal _escapedModel;
}