/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rec.hitss.layer.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.rec.hitss.layer.model.solicitudReclutamiento;
import com.rec.hitss.layer.model.solicitudReclutamientoModel;
import com.rec.hitss.layer.model.solicitudReclutamientoSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the solicitudReclutamiento service. Represents a row in the &quot;SOLICITUD_RECLUTAMIENTO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.rec.hitss.layer.model.solicitudReclutamientoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link solicitudReclutamientoImpl}.
 * </p>
 *
 * @author Crossfire
 * @see solicitudReclutamientoImpl
 * @see com.rec.hitss.layer.model.solicitudReclutamiento
 * @see com.rec.hitss.layer.model.solicitudReclutamientoModel
 * @generated
 */
@JSON(strict = true)
public class solicitudReclutamientoModelImpl extends BaseModelImpl<solicitudReclutamiento>
	implements solicitudReclutamientoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a solicitud reclutamiento model instance should use the {@link com.rec.hitss.layer.model.solicitudReclutamiento} interface instead.
	 */
	public static final String TABLE_NAME = "SOLICITUD_RECLUTAMIENTO";
	public static final Object[][] TABLE_COLUMNS = {
			{ "SR_ID", Types.BIGINT },
			{ "SR_PL_ID", Types.VARCHAR },
			{ "SR_ESTADO", Types.BIGINT },
			{ "SR_ACTIVO", Types.VARCHAR },
			{ "SR_USUARIO_CREA", Types.BIGINT },
			{ "SR_FECHA_CREA", Types.TIMESTAMP },
			{ "SR_USUARIO_MODIFICA", Types.BIGINT },
			{ "SR_FECHA_MODIFICA", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table SOLICITUD_RECLUTAMIENTO (SR_ID LONG not null primary key,SR_PL_ID VARCHAR(75) null,SR_ESTADO LONG,SR_ACTIVO VARCHAR(75) null,SR_USUARIO_CREA LONG,SR_FECHA_CREA DATE null,SR_USUARIO_MODIFICA LONG,SR_FECHA_MODIFICA DATE null)";
	public static final String TABLE_SQL_DROP = "drop table SOLICITUD_RECLUTAMIENTO";
	public static final String ORDER_BY_JPQL = " ORDER BY solicitudReclutamiento.SR_ID ASC";
	public static final String ORDER_BY_SQL = " ORDER BY SOLICITUD_RECLUTAMIENTO.SR_ID ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rec.hitss.layer.model.solicitudReclutamiento"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rec.hitss.layer.model.solicitudReclutamiento"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static solicitudReclutamiento toModel(
		solicitudReclutamientoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		solicitudReclutamiento model = new solicitudReclutamientoImpl();

		model.setSR_ID(soapModel.getSR_ID());
		model.setSR_PL_ID(soapModel.getSR_PL_ID());
		model.setSR_ESTADO(soapModel.getSR_ESTADO());
		model.setSR_ACTIVO(soapModel.getSR_ACTIVO());
		model.setSR_USUARIO_CREA(soapModel.getSR_USUARIO_CREA());
		model.setSR_FECHA_CREA(soapModel.getSR_FECHA_CREA());
		model.setSR_USUARIO_MODIFICA(soapModel.getSR_USUARIO_MODIFICA());
		model.setSR_FECHA_MODIFICA(soapModel.getSR_FECHA_MODIFICA());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<solicitudReclutamiento> toModels(
		solicitudReclutamientoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<solicitudReclutamiento> models = new ArrayList<solicitudReclutamiento>(soapModels.length);

		for (solicitudReclutamientoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.rec.hitss.layer.model.solicitudReclutamiento"));

	public solicitudReclutamientoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _SR_ID;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSR_ID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _SR_ID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return solicitudReclutamiento.class;
	}

	@Override
	public String getModelClassName() {
		return solicitudReclutamiento.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("SR_ID", getSR_ID());
		attributes.put("SR_PL_ID", getSR_PL_ID());
		attributes.put("SR_ESTADO", getSR_ESTADO());
		attributes.put("SR_ACTIVO", getSR_ACTIVO());
		attributes.put("SR_USUARIO_CREA", getSR_USUARIO_CREA());
		attributes.put("SR_FECHA_CREA", getSR_FECHA_CREA());
		attributes.put("SR_USUARIO_MODIFICA", getSR_USUARIO_MODIFICA());
		attributes.put("SR_FECHA_MODIFICA", getSR_FECHA_MODIFICA());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long SR_ID = (Long)attributes.get("SR_ID");

		if (SR_ID != null) {
			setSR_ID(SR_ID);
		}

		String SR_PL_ID = (String)attributes.get("SR_PL_ID");

		if (SR_PL_ID != null) {
			setSR_PL_ID(SR_PL_ID);
		}

		Long SR_ESTADO = (Long)attributes.get("SR_ESTADO");

		if (SR_ESTADO != null) {
			setSR_ESTADO(SR_ESTADO);
		}

		String SR_ACTIVO = (String)attributes.get("SR_ACTIVO");

		if (SR_ACTIVO != null) {
			setSR_ACTIVO(SR_ACTIVO);
		}

		Long SR_USUARIO_CREA = (Long)attributes.get("SR_USUARIO_CREA");

		if (SR_USUARIO_CREA != null) {
			setSR_USUARIO_CREA(SR_USUARIO_CREA);
		}

		Date SR_FECHA_CREA = (Date)attributes.get("SR_FECHA_CREA");

		if (SR_FECHA_CREA != null) {
			setSR_FECHA_CREA(SR_FECHA_CREA);
		}

		Long SR_USUARIO_MODIFICA = (Long)attributes.get("SR_USUARIO_MODIFICA");

		if (SR_USUARIO_MODIFICA != null) {
			setSR_USUARIO_MODIFICA(SR_USUARIO_MODIFICA);
		}

		Date SR_FECHA_MODIFICA = (Date)attributes.get("SR_FECHA_MODIFICA");

		if (SR_FECHA_MODIFICA != null) {
			setSR_FECHA_MODIFICA(SR_FECHA_MODIFICA);
		}
	}

	@JSON
	@Override
	public long getSR_ID() {
		return _SR_ID;
	}

	@Override
	public void setSR_ID(long SR_ID) {
		_SR_ID = SR_ID;
	}

	@JSON
	@Override
	public String getSR_PL_ID() {
		if (_SR_PL_ID == null) {
			return StringPool.BLANK;
		}
		else {
			return _SR_PL_ID;
		}
	}

	@Override
	public void setSR_PL_ID(String SR_PL_ID) {
		_SR_PL_ID = SR_PL_ID;
	}

	@JSON
	@Override
	public long getSR_ESTADO() {
		return _SR_ESTADO;
	}

	@Override
	public void setSR_ESTADO(long SR_ESTADO) {
		_SR_ESTADO = SR_ESTADO;
	}

	@JSON
	@Override
	public String getSR_ACTIVO() {
		if (_SR_ACTIVO == null) {
			return StringPool.BLANK;
		}
		else {
			return _SR_ACTIVO;
		}
	}

	@Override
	public void setSR_ACTIVO(String SR_ACTIVO) {
		_SR_ACTIVO = SR_ACTIVO;
	}

	@JSON
	@Override
	public long getSR_USUARIO_CREA() {
		return _SR_USUARIO_CREA;
	}

	@Override
	public void setSR_USUARIO_CREA(long SR_USUARIO_CREA) {
		_SR_USUARIO_CREA = SR_USUARIO_CREA;
	}

	@JSON
	@Override
	public Date getSR_FECHA_CREA() {
		return _SR_FECHA_CREA;
	}

	@Override
	public void setSR_FECHA_CREA(Date SR_FECHA_CREA) {
		_SR_FECHA_CREA = SR_FECHA_CREA;
	}

	@JSON
	@Override
	public long getSR_USUARIO_MODIFICA() {
		return _SR_USUARIO_MODIFICA;
	}

	@Override
	public void setSR_USUARIO_MODIFICA(long SR_USUARIO_MODIFICA) {
		_SR_USUARIO_MODIFICA = SR_USUARIO_MODIFICA;
	}

	@JSON
	@Override
	public Date getSR_FECHA_MODIFICA() {
		return _SR_FECHA_MODIFICA;
	}

	@Override
	public void setSR_FECHA_MODIFICA(Date SR_FECHA_MODIFICA) {
		_SR_FECHA_MODIFICA = SR_FECHA_MODIFICA;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			solicitudReclutamiento.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public solicitudReclutamiento toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (solicitudReclutamiento)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		solicitudReclutamientoImpl solicitudReclutamientoImpl = new solicitudReclutamientoImpl();

		solicitudReclutamientoImpl.setSR_ID(getSR_ID());
		solicitudReclutamientoImpl.setSR_PL_ID(getSR_PL_ID());
		solicitudReclutamientoImpl.setSR_ESTADO(getSR_ESTADO());
		solicitudReclutamientoImpl.setSR_ACTIVO(getSR_ACTIVO());
		solicitudReclutamientoImpl.setSR_USUARIO_CREA(getSR_USUARIO_CREA());
		solicitudReclutamientoImpl.setSR_FECHA_CREA(getSR_FECHA_CREA());
		solicitudReclutamientoImpl.setSR_USUARIO_MODIFICA(getSR_USUARIO_MODIFICA());
		solicitudReclutamientoImpl.setSR_FECHA_MODIFICA(getSR_FECHA_MODIFICA());

		solicitudReclutamientoImpl.resetOriginalValues();

		return solicitudReclutamientoImpl;
	}

	@Override
	public int compareTo(solicitudReclutamiento solicitudReclutamiento) {
		int value = 0;

		if (getSR_ID() < solicitudReclutamiento.getSR_ID()) {
			value = -1;
		}
		else if (getSR_ID() > solicitudReclutamiento.getSR_ID()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof solicitudReclutamiento)) {
			return false;
		}

		solicitudReclutamiento solicitudReclutamiento = (solicitudReclutamiento)obj;

		long primaryKey = solicitudReclutamiento.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<solicitudReclutamiento> toCacheModel() {
		solicitudReclutamientoCacheModel solicitudReclutamientoCacheModel = new solicitudReclutamientoCacheModel();

		solicitudReclutamientoCacheModel.SR_ID = getSR_ID();

		solicitudReclutamientoCacheModel.SR_PL_ID = getSR_PL_ID();

		String SR_PL_ID = solicitudReclutamientoCacheModel.SR_PL_ID;

		if ((SR_PL_ID != null) && (SR_PL_ID.length() == 0)) {
			solicitudReclutamientoCacheModel.SR_PL_ID = null;
		}

		solicitudReclutamientoCacheModel.SR_ESTADO = getSR_ESTADO();

		solicitudReclutamientoCacheModel.SR_ACTIVO = getSR_ACTIVO();

		String SR_ACTIVO = solicitudReclutamientoCacheModel.SR_ACTIVO;

		if ((SR_ACTIVO != null) && (SR_ACTIVO.length() == 0)) {
			solicitudReclutamientoCacheModel.SR_ACTIVO = null;
		}

		solicitudReclutamientoCacheModel.SR_USUARIO_CREA = getSR_USUARIO_CREA();

		Date SR_FECHA_CREA = getSR_FECHA_CREA();

		if (SR_FECHA_CREA != null) {
			solicitudReclutamientoCacheModel.SR_FECHA_CREA = SR_FECHA_CREA.getTime();
		}
		else {
			solicitudReclutamientoCacheModel.SR_FECHA_CREA = Long.MIN_VALUE;
		}

		solicitudReclutamientoCacheModel.SR_USUARIO_MODIFICA = getSR_USUARIO_MODIFICA();

		Date SR_FECHA_MODIFICA = getSR_FECHA_MODIFICA();

		if (SR_FECHA_MODIFICA != null) {
			solicitudReclutamientoCacheModel.SR_FECHA_MODIFICA = SR_FECHA_MODIFICA.getTime();
		}
		else {
			solicitudReclutamientoCacheModel.SR_FECHA_MODIFICA = Long.MIN_VALUE;
		}

		return solicitudReclutamientoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{SR_ID=");
		sb.append(getSR_ID());
		sb.append(", SR_PL_ID=");
		sb.append(getSR_PL_ID());
		sb.append(", SR_ESTADO=");
		sb.append(getSR_ESTADO());
		sb.append(", SR_ACTIVO=");
		sb.append(getSR_ACTIVO());
		sb.append(", SR_USUARIO_CREA=");
		sb.append(getSR_USUARIO_CREA());
		sb.append(", SR_FECHA_CREA=");
		sb.append(getSR_FECHA_CREA());
		sb.append(", SR_USUARIO_MODIFICA=");
		sb.append(getSR_USUARIO_MODIFICA());
		sb.append(", SR_FECHA_MODIFICA=");
		sb.append(getSR_FECHA_MODIFICA());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("com.rec.hitss.layer.model.solicitudReclutamiento");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>SR_ID</column-name><column-value><![CDATA[");
		sb.append(getSR_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>SR_PL_ID</column-name><column-value><![CDATA[");
		sb.append(getSR_PL_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>SR_ESTADO</column-name><column-value><![CDATA[");
		sb.append(getSR_ESTADO());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>SR_ACTIVO</column-name><column-value><![CDATA[");
		sb.append(getSR_ACTIVO());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>SR_USUARIO_CREA</column-name><column-value><![CDATA[");
		sb.append(getSR_USUARIO_CREA());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>SR_FECHA_CREA</column-name><column-value><![CDATA[");
		sb.append(getSR_FECHA_CREA());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>SR_USUARIO_MODIFICA</column-name><column-value><![CDATA[");
		sb.append(getSR_USUARIO_MODIFICA());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>SR_FECHA_MODIFICA</column-name><column-value><![CDATA[");
		sb.append(getSR_FECHA_MODIFICA());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = solicitudReclutamiento.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			solicitudReclutamiento.class
		};
	private long _SR_ID;
	private String _SR_PL_ID;
	private long _SR_ESTADO;
	private String _SR_ACTIVO;
	private long _SR_USUARIO_CREA;
	private Date _SR_FECHA_CREA;
	private long _SR_USUARIO_MODIFICA;
	private Date _SR_FECHA_MODIFICA;
	private solicitudReclutamiento _escapedModel;
}