/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.hitss.layer.model.impl;

import com.hitss.layer.model.PrioridadGrupoUsuarios;
import com.hitss.layer.model.PrioridadGrupoUsuariosModel;
import com.hitss.layer.model.PrioridadGrupoUsuariosSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the PrioridadGrupoUsuarios service. Represents a row in the &quot;PrioridadGrupoUsuarios&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.hitss.layer.model.PrioridadGrupoUsuariosModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PrioridadGrupoUsuariosImpl}.
 * </p>
 *
 * @author Danielle Delgado
 * @see PrioridadGrupoUsuariosImpl
 * @see com.hitss.layer.model.PrioridadGrupoUsuarios
 * @see com.hitss.layer.model.PrioridadGrupoUsuariosModel
 * @generated
 */
@JSON(strict = true)
public class PrioridadGrupoUsuariosModelImpl extends BaseModelImpl<PrioridadGrupoUsuarios>
	implements PrioridadGrupoUsuariosModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a prioridad grupo usuarios model instance should use the {@link com.hitss.layer.model.PrioridadGrupoUsuarios} interface instead.
	 */
	public static final String TABLE_NAME = "PrioridadGrupoUsuarios";
	public static final Object[][] TABLE_COLUMNS = {
			{ "prioridadGrupoUsuariosId", Types.BIGINT },
			{ "solicitudEvaluacionDesempennoId", Types.BIGINT },
			{ "responsableGrupo", Types.VARCHAR },
			{ "grupoUsuario", Types.VARCHAR },
			{ "orden", Types.INTEGER },
			{ "activo", Types.BOOLEAN },
			{ "usuariocrea", Types.BIGINT },
			{ "fechacrea", Types.TIMESTAMP },
			{ "usuariomodifica", Types.BIGINT },
			{ "fechacreamodifica", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table PrioridadGrupoUsuarios (prioridadGrupoUsuariosId LONG not null primary key,solicitudEvaluacionDesempennoId LONG,responsableGrupo VARCHAR(75) null,grupoUsuario VARCHAR(75) null,orden INTEGER,activo BOOLEAN,usuariocrea LONG,fechacrea DATE null,usuariomodifica LONG,fechacreamodifica DATE null)";
	public static final String TABLE_SQL_DROP = "drop table PrioridadGrupoUsuarios";
	public static final String ORDER_BY_JPQL = " ORDER BY prioridadGrupoUsuarios.fechacreamodifica ASC";
	public static final String ORDER_BY_SQL = " ORDER BY PrioridadGrupoUsuarios.fechacreamodifica ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.hitss.layer.model.PrioridadGrupoUsuarios"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.hitss.layer.model.PrioridadGrupoUsuarios"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static PrioridadGrupoUsuarios toModel(
		PrioridadGrupoUsuariosSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		PrioridadGrupoUsuarios model = new PrioridadGrupoUsuariosImpl();

		model.setPrioridadGrupoUsuariosId(soapModel.getPrioridadGrupoUsuariosId());
		model.setSolicitudEvaluacionDesempennoId(soapModel.getSolicitudEvaluacionDesempennoId());
		model.setResponsableGrupo(soapModel.getResponsableGrupo());
		model.setGrupoUsuario(soapModel.getGrupoUsuario());
		model.setOrden(soapModel.getOrden());
		model.setActivo(soapModel.getActivo());
		model.setUsuariocrea(soapModel.getUsuariocrea());
		model.setFechacrea(soapModel.getFechacrea());
		model.setUsuariomodifica(soapModel.getUsuariomodifica());
		model.setFechacreamodifica(soapModel.getFechacreamodifica());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<PrioridadGrupoUsuarios> toModels(
		PrioridadGrupoUsuariosSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<PrioridadGrupoUsuarios> models = new ArrayList<PrioridadGrupoUsuarios>(soapModels.length);

		for (PrioridadGrupoUsuariosSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.hitss.layer.model.PrioridadGrupoUsuarios"));

	public PrioridadGrupoUsuariosModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _prioridadGrupoUsuariosId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPrioridadGrupoUsuariosId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _prioridadGrupoUsuariosId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PrioridadGrupoUsuarios.class;
	}

	@Override
	public String getModelClassName() {
		return PrioridadGrupoUsuarios.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("prioridadGrupoUsuariosId", getPrioridadGrupoUsuariosId());
		attributes.put("solicitudEvaluacionDesempennoId",
			getSolicitudEvaluacionDesempennoId());
		attributes.put("responsableGrupo", getResponsableGrupo());
		attributes.put("grupoUsuario", getGrupoUsuario());
		attributes.put("orden", getOrden());
		attributes.put("activo", getActivo());
		attributes.put("usuariocrea", getUsuariocrea());
		attributes.put("fechacrea", getFechacrea());
		attributes.put("usuariomodifica", getUsuariomodifica());
		attributes.put("fechacreamodifica", getFechacreamodifica());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long prioridadGrupoUsuariosId = (Long)attributes.get(
				"prioridadGrupoUsuariosId");

		if (prioridadGrupoUsuariosId != null) {
			setPrioridadGrupoUsuariosId(prioridadGrupoUsuariosId);
		}

		Long solicitudEvaluacionDesempennoId = (Long)attributes.get(
				"solicitudEvaluacionDesempennoId");

		if (solicitudEvaluacionDesempennoId != null) {
			setSolicitudEvaluacionDesempennoId(solicitudEvaluacionDesempennoId);
		}

		String responsableGrupo = (String)attributes.get("responsableGrupo");

		if (responsableGrupo != null) {
			setResponsableGrupo(responsableGrupo);
		}

		String grupoUsuario = (String)attributes.get("grupoUsuario");

		if (grupoUsuario != null) {
			setGrupoUsuario(grupoUsuario);
		}

		Integer orden = (Integer)attributes.get("orden");

		if (orden != null) {
			setOrden(orden);
		}

		Boolean activo = (Boolean)attributes.get("activo");

		if (activo != null) {
			setActivo(activo);
		}

		Long usuariocrea = (Long)attributes.get("usuariocrea");

		if (usuariocrea != null) {
			setUsuariocrea(usuariocrea);
		}

		Date fechacrea = (Date)attributes.get("fechacrea");

		if (fechacrea != null) {
			setFechacrea(fechacrea);
		}

		Long usuariomodifica = (Long)attributes.get("usuariomodifica");

		if (usuariomodifica != null) {
			setUsuariomodifica(usuariomodifica);
		}

		Date fechacreamodifica = (Date)attributes.get("fechacreamodifica");

		if (fechacreamodifica != null) {
			setFechacreamodifica(fechacreamodifica);
		}
	}

	@JSON
	@Override
	public long getPrioridadGrupoUsuariosId() {
		return _prioridadGrupoUsuariosId;
	}

	@Override
	public void setPrioridadGrupoUsuariosId(long prioridadGrupoUsuariosId) {
		_prioridadGrupoUsuariosId = prioridadGrupoUsuariosId;
	}

	@JSON
	@Override
	public long getSolicitudEvaluacionDesempennoId() {
		return _solicitudEvaluacionDesempennoId;
	}

	@Override
	public void setSolicitudEvaluacionDesempennoId(
		long solicitudEvaluacionDesempennoId) {
		_solicitudEvaluacionDesempennoId = solicitudEvaluacionDesempennoId;
	}

	@JSON
	@Override
	public String getResponsableGrupo() {
		if (_responsableGrupo == null) {
			return StringPool.BLANK;
		}
		else {
			return _responsableGrupo;
		}
	}

	@Override
	public void setResponsableGrupo(String responsableGrupo) {
		_responsableGrupo = responsableGrupo;
	}

	@JSON
	@Override
	public String getGrupoUsuario() {
		if (_grupoUsuario == null) {
			return StringPool.BLANK;
		}
		else {
			return _grupoUsuario;
		}
	}

	@Override
	public void setGrupoUsuario(String grupoUsuario) {
		_grupoUsuario = grupoUsuario;
	}

	@JSON
	@Override
	public int getOrden() {
		return _orden;
	}

	@Override
	public void setOrden(int orden) {
		_orden = orden;
	}

	@JSON
	@Override
	public boolean getActivo() {
		return _activo;
	}

	@Override
	public boolean isActivo() {
		return _activo;
	}

	@Override
	public void setActivo(boolean activo) {
		_activo = activo;
	}

	@JSON
	@Override
	public long getUsuariocrea() {
		return _usuariocrea;
	}

	@Override
	public void setUsuariocrea(long usuariocrea) {
		_usuariocrea = usuariocrea;
	}

	@JSON
	@Override
	public Date getFechacrea() {
		return _fechacrea;
	}

	@Override
	public void setFechacrea(Date fechacrea) {
		_fechacrea = fechacrea;
	}

	@JSON
	@Override
	public long getUsuariomodifica() {
		return _usuariomodifica;
	}

	@Override
	public void setUsuariomodifica(long usuariomodifica) {
		_usuariomodifica = usuariomodifica;
	}

	@JSON
	@Override
	public Date getFechacreamodifica() {
		return _fechacreamodifica;
	}

	@Override
	public void setFechacreamodifica(Date fechacreamodifica) {
		_fechacreamodifica = fechacreamodifica;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			PrioridadGrupoUsuarios.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PrioridadGrupoUsuarios toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (PrioridadGrupoUsuarios)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PrioridadGrupoUsuariosImpl prioridadGrupoUsuariosImpl = new PrioridadGrupoUsuariosImpl();

		prioridadGrupoUsuariosImpl.setPrioridadGrupoUsuariosId(getPrioridadGrupoUsuariosId());
		prioridadGrupoUsuariosImpl.setSolicitudEvaluacionDesempennoId(getSolicitudEvaluacionDesempennoId());
		prioridadGrupoUsuariosImpl.setResponsableGrupo(getResponsableGrupo());
		prioridadGrupoUsuariosImpl.setGrupoUsuario(getGrupoUsuario());
		prioridadGrupoUsuariosImpl.setOrden(getOrden());
		prioridadGrupoUsuariosImpl.setActivo(getActivo());
		prioridadGrupoUsuariosImpl.setUsuariocrea(getUsuariocrea());
		prioridadGrupoUsuariosImpl.setFechacrea(getFechacrea());
		prioridadGrupoUsuariosImpl.setUsuariomodifica(getUsuariomodifica());
		prioridadGrupoUsuariosImpl.setFechacreamodifica(getFechacreamodifica());

		prioridadGrupoUsuariosImpl.resetOriginalValues();

		return prioridadGrupoUsuariosImpl;
	}

	@Override
	public int compareTo(PrioridadGrupoUsuarios prioridadGrupoUsuarios) {
		int value = 0;

		value = DateUtil.compareTo(getFechacreamodifica(),
				prioridadGrupoUsuarios.getFechacreamodifica());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof PrioridadGrupoUsuarios)) {
			return false;
		}

		PrioridadGrupoUsuarios prioridadGrupoUsuarios = (PrioridadGrupoUsuarios)obj;

		long primaryKey = prioridadGrupoUsuarios.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<PrioridadGrupoUsuarios> toCacheModel() {
		PrioridadGrupoUsuariosCacheModel prioridadGrupoUsuariosCacheModel = new PrioridadGrupoUsuariosCacheModel();

		prioridadGrupoUsuariosCacheModel.prioridadGrupoUsuariosId = getPrioridadGrupoUsuariosId();

		prioridadGrupoUsuariosCacheModel.solicitudEvaluacionDesempennoId = getSolicitudEvaluacionDesempennoId();

		prioridadGrupoUsuariosCacheModel.responsableGrupo = getResponsableGrupo();

		String responsableGrupo = prioridadGrupoUsuariosCacheModel.responsableGrupo;

		if ((responsableGrupo != null) && (responsableGrupo.length() == 0)) {
			prioridadGrupoUsuariosCacheModel.responsableGrupo = null;
		}

		prioridadGrupoUsuariosCacheModel.grupoUsuario = getGrupoUsuario();

		String grupoUsuario = prioridadGrupoUsuariosCacheModel.grupoUsuario;

		if ((grupoUsuario != null) && (grupoUsuario.length() == 0)) {
			prioridadGrupoUsuariosCacheModel.grupoUsuario = null;
		}

		prioridadGrupoUsuariosCacheModel.orden = getOrden();

		prioridadGrupoUsuariosCacheModel.activo = getActivo();

		prioridadGrupoUsuariosCacheModel.usuariocrea = getUsuariocrea();

		Date fechacrea = getFechacrea();

		if (fechacrea != null) {
			prioridadGrupoUsuariosCacheModel.fechacrea = fechacrea.getTime();
		}
		else {
			prioridadGrupoUsuariosCacheModel.fechacrea = Long.MIN_VALUE;
		}

		prioridadGrupoUsuariosCacheModel.usuariomodifica = getUsuariomodifica();

		Date fechacreamodifica = getFechacreamodifica();

		if (fechacreamodifica != null) {
			prioridadGrupoUsuariosCacheModel.fechacreamodifica = fechacreamodifica.getTime();
		}
		else {
			prioridadGrupoUsuariosCacheModel.fechacreamodifica = Long.MIN_VALUE;
		}

		return prioridadGrupoUsuariosCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{prioridadGrupoUsuariosId=");
		sb.append(getPrioridadGrupoUsuariosId());
		sb.append(", solicitudEvaluacionDesempennoId=");
		sb.append(getSolicitudEvaluacionDesempennoId());
		sb.append(", responsableGrupo=");
		sb.append(getResponsableGrupo());
		sb.append(", grupoUsuario=");
		sb.append(getGrupoUsuario());
		sb.append(", orden=");
		sb.append(getOrden());
		sb.append(", activo=");
		sb.append(getActivo());
		sb.append(", usuariocrea=");
		sb.append(getUsuariocrea());
		sb.append(", fechacrea=");
		sb.append(getFechacrea());
		sb.append(", usuariomodifica=");
		sb.append(getUsuariomodifica());
		sb.append(", fechacreamodifica=");
		sb.append(getFechacreamodifica());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("com.hitss.layer.model.PrioridadGrupoUsuarios");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>prioridadGrupoUsuariosId</column-name><column-value><![CDATA[");
		sb.append(getPrioridadGrupoUsuariosId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>solicitudEvaluacionDesempennoId</column-name><column-value><![CDATA[");
		sb.append(getSolicitudEvaluacionDesempennoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>responsableGrupo</column-name><column-value><![CDATA[");
		sb.append(getResponsableGrupo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>grupoUsuario</column-name><column-value><![CDATA[");
		sb.append(getGrupoUsuario());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>orden</column-name><column-value><![CDATA[");
		sb.append(getOrden());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>activo</column-name><column-value><![CDATA[");
		sb.append(getActivo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>usuariocrea</column-name><column-value><![CDATA[");
		sb.append(getUsuariocrea());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fechacrea</column-name><column-value><![CDATA[");
		sb.append(getFechacrea());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>usuariomodifica</column-name><column-value><![CDATA[");
		sb.append(getUsuariomodifica());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fechacreamodifica</column-name><column-value><![CDATA[");
		sb.append(getFechacreamodifica());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = PrioridadGrupoUsuarios.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			PrioridadGrupoUsuarios.class
		};
	private long _prioridadGrupoUsuariosId;
	private long _solicitudEvaluacionDesempennoId;
	private String _responsableGrupo;
	private String _grupoUsuario;
	private int _orden;
	private boolean _activo;
	private long _usuariocrea;
	private Date _fechacrea;
	private long _usuariomodifica;
	private Date _fechacreamodifica;
	private PrioridadGrupoUsuarios _escapedModel;
}