/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.hitss.layer.model;

import com.hitss.layer.service.persistence.ActividadCronogramaPK;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ActividadCronograma service. Represents a row in the &quot;ActividadCronograma&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.hitss.layer.model.impl.ActividadCronogramaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.hitss.layer.model.impl.ActividadCronogramaImpl}.
 * </p>
 *
 * @author Danielle Delgado
 * @see ActividadCronograma
 * @see com.hitss.layer.model.impl.ActividadCronogramaImpl
 * @see com.hitss.layer.model.impl.ActividadCronogramaModelImpl
 * @generated
 */
public interface ActividadCronogramaModel extends BaseModel<ActividadCronograma> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a actividad cronograma model instance should use the {@link ActividadCronograma} interface instead.
	 */

	/**
	 * Returns the primary key of this actividad cronograma.
	 *
	 * @return the primary key of this actividad cronograma
	 */
	public ActividadCronogramaPK getPrimaryKey();

	/**
	 * Sets the primary key of this actividad cronograma.
	 *
	 * @param primaryKey the primary key of this actividad cronograma
	 */
	public void setPrimaryKey(ActividadCronogramaPK primaryKey);

	/**
	 * Returns the actividad cronograma ID of this actividad cronograma.
	 *
	 * @return the actividad cronograma ID of this actividad cronograma
	 */
	public long getActividadCronogramaId();

	/**
	 * Sets the actividad cronograma ID of this actividad cronograma.
	 *
	 * @param actividadCronogramaId the actividad cronograma ID of this actividad cronograma
	 */
	public void setActividadCronogramaId(long actividadCronogramaId);

	/**
	 * Returns the cronograma ID of this actividad cronograma.
	 *
	 * @return the cronograma ID of this actividad cronograma
	 */
	public long getCronogramaId();

	/**
	 * Sets the cronograma ID of this actividad cronograma.
	 *
	 * @param cronogramaId the cronograma ID of this actividad cronograma
	 */
	public void setCronogramaId(long cronogramaId);

	/**
	 * Returns the grupo usuario of this actividad cronograma.
	 *
	 * @return the grupo usuario of this actividad cronograma
	 */
	public long getGrupoUsuario();

	/**
	 * Sets the grupo usuario of this actividad cronograma.
	 *
	 * @param grupoUsuario the grupo usuario of this actividad cronograma
	 */
	public void setGrupoUsuario(long grupoUsuario);

	/**
	 * Returns the descripcion of this actividad cronograma.
	 *
	 * @return the descripcion of this actividad cronograma
	 */
	@AutoEscape
	public String getDescripcion();

	/**
	 * Sets the descripcion of this actividad cronograma.
	 *
	 * @param descripcion the descripcion of this actividad cronograma
	 */
	public void setDescripcion(String descripcion);

	/**
	 * Returns the fecha inicio of this actividad cronograma.
	 *
	 * @return the fecha inicio of this actividad cronograma
	 */
	public Date getFechaInicio();

	/**
	 * Sets the fecha inicio of this actividad cronograma.
	 *
	 * @param fechaInicio the fecha inicio of this actividad cronograma
	 */
	public void setFechaInicio(Date fechaInicio);

	/**
	 * Returns the fecha fin of this actividad cronograma.
	 *
	 * @return the fecha fin of this actividad cronograma
	 */
	public Date getFechaFin();

	/**
	 * Sets the fecha fin of this actividad cronograma.
	 *
	 * @param fechaFin the fecha fin of this actividad cronograma
	 */
	public void setFechaFin(Date fechaFin);

	/**
	 * Returns the cumplido evaluacion of this actividad cronograma.
	 *
	 * @return the cumplido evaluacion of this actividad cronograma
	 */
	public boolean getCumplidoEvaluacion();

	/**
	 * Returns <code>true</code> if this actividad cronograma is cumplido evaluacion.
	 *
	 * @return <code>true</code> if this actividad cronograma is cumplido evaluacion; <code>false</code> otherwise
	 */
	public boolean isCumplidoEvaluacion();

	/**
	 * Sets whether this actividad cronograma is cumplido evaluacion.
	 *
	 * @param cumplidoEvaluacion the cumplido evaluacion of this actividad cronograma
	 */
	public void setCumplidoEvaluacion(boolean cumplidoEvaluacion);

	/**
	 * Returns the estado of this actividad cronograma.
	 *
	 * @return the estado of this actividad cronograma
	 */
	public long getEstado();

	/**
	 * Sets the estado of this actividad cronograma.
	 *
	 * @param estado the estado of this actividad cronograma
	 */
	public void setEstado(long estado);

	/**
	 * Returns the fecha inicio evaluacion of this actividad cronograma.
	 *
	 * @return the fecha inicio evaluacion of this actividad cronograma
	 */
	public Date getFechaInicioEvaluacion();

	/**
	 * Sets the fecha inicio evaluacion of this actividad cronograma.
	 *
	 * @param fechaInicioEvaluacion the fecha inicio evaluacion of this actividad cronograma
	 */
	public void setFechaInicioEvaluacion(Date fechaInicioEvaluacion);

	/**
	 * Returns the fecha fin evaluacion of this actividad cronograma.
	 *
	 * @return the fecha fin evaluacion of this actividad cronograma
	 */
	public Date getFechaFinEvaluacion();

	/**
	 * Sets the fecha fin evaluacion of this actividad cronograma.
	 *
	 * @param fechaFinEvaluacion the fecha fin evaluacion of this actividad cronograma
	 */
	public void setFechaFinEvaluacion(Date fechaFinEvaluacion);

	/**
	 * Returns the aprobado colaborador of this actividad cronograma.
	 *
	 * @return the aprobado colaborador of this actividad cronograma
	 */
	public long getAprobadoColaborador();

	/**
	 * Sets the aprobado colaborador of this actividad cronograma.
	 *
	 * @param aprobadoColaborador the aprobado colaborador of this actividad cronograma
	 */
	public void setAprobadoColaborador(long aprobadoColaborador);

	/**
	 * Returns the aprobado lider of this actividad cronograma.
	 *
	 * @return the aprobado lider of this actividad cronograma
	 */
	public long getAprobadoLider();

	/**
	 * Sets the aprobado lider of this actividad cronograma.
	 *
	 * @param aprobadoLider the aprobado lider of this actividad cronograma
	 */
	public void setAprobadoLider(long aprobadoLider);

	/**
	 * Returns the usuario gerente ID of this actividad cronograma.
	 *
	 * @return the usuario gerente ID of this actividad cronograma
	 */
	public long getUsuarioGerenteId();

	/**
	 * Sets the usuario gerente ID of this actividad cronograma.
	 *
	 * @param usuarioGerenteId the usuario gerente ID of this actividad cronograma
	 */
	public void setUsuarioGerenteId(long usuarioGerenteId);

	/**
	 * Returns the usuario lider ID of this actividad cronograma.
	 *
	 * @return the usuario lider ID of this actividad cronograma
	 */
	public long getUsuarioLiderId();

	/**
	 * Sets the usuario lider ID of this actividad cronograma.
	 *
	 * @param usuarioLiderId the usuario lider ID of this actividad cronograma
	 */
	public void setUsuarioLiderId(long usuarioLiderId);

	/**
	 * Returns the activo of this actividad cronograma.
	 *
	 * @return the activo of this actividad cronograma
	 */
	public boolean getActivo();

	/**
	 * Returns <code>true</code> if this actividad cronograma is activo.
	 *
	 * @return <code>true</code> if this actividad cronograma is activo; <code>false</code> otherwise
	 */
	public boolean isActivo();

	/**
	 * Sets whether this actividad cronograma is activo.
	 *
	 * @param activo the activo of this actividad cronograma
	 */
	public void setActivo(boolean activo);

	/**
	 * Returns the usuariocrea of this actividad cronograma.
	 *
	 * @return the usuariocrea of this actividad cronograma
	 */
	public long getUsuariocrea();

	/**
	 * Sets the usuariocrea of this actividad cronograma.
	 *
	 * @param usuariocrea the usuariocrea of this actividad cronograma
	 */
	public void setUsuariocrea(long usuariocrea);

	/**
	 * Returns the fechacrea of this actividad cronograma.
	 *
	 * @return the fechacrea of this actividad cronograma
	 */
	public Date getFechacrea();

	/**
	 * Sets the fechacrea of this actividad cronograma.
	 *
	 * @param fechacrea the fechacrea of this actividad cronograma
	 */
	public void setFechacrea(Date fechacrea);

	/**
	 * Returns the usuariomodifica of this actividad cronograma.
	 *
	 * @return the usuariomodifica of this actividad cronograma
	 */
	public long getUsuariomodifica();

	/**
	 * Sets the usuariomodifica of this actividad cronograma.
	 *
	 * @param usuariomodifica the usuariomodifica of this actividad cronograma
	 */
	public void setUsuariomodifica(long usuariomodifica);

	/**
	 * Returns the fechamodifica of this actividad cronograma.
	 *
	 * @return the fechamodifica of this actividad cronograma
	 */
	public Date getFechamodifica();

	/**
	 * Sets the fechamodifica of this actividad cronograma.
	 *
	 * @param fechamodifica the fechamodifica of this actividad cronograma
	 */
	public void setFechamodifica(Date fechamodifica);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.hitss.layer.model.ActividadCronograma actividadCronograma);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.hitss.layer.model.ActividadCronograma> toCacheModel();

	@Override
	public com.hitss.layer.model.ActividadCronograma toEscapedModel();

	@Override
	public com.hitss.layer.model.ActividadCronograma toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}