/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.hitss.layer.model;

import com.hitss.layer.service.persistence.ActividadPlanPK;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ActividadPlan service. Represents a row in the &quot;ActividadPlan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.hitss.layer.model.impl.ActividadPlanModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.hitss.layer.model.impl.ActividadPlanImpl}.
 * </p>
 *
 * @author Danielle Delgado
 * @see ActividadPlan
 * @see com.hitss.layer.model.impl.ActividadPlanImpl
 * @see com.hitss.layer.model.impl.ActividadPlanModelImpl
 * @generated
 */
public interface ActividadPlanModel extends BaseModel<ActividadPlan> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a actividad plan model instance should use the {@link ActividadPlan} interface instead.
	 */

	/**
	 * Returns the primary key of this actividad plan.
	 *
	 * @return the primary key of this actividad plan
	 */
	public ActividadPlanPK getPrimaryKey();

	/**
	 * Sets the primary key of this actividad plan.
	 *
	 * @param primaryKey the primary key of this actividad plan
	 */
	public void setPrimaryKey(ActividadPlanPK primaryKey);

	/**
	 * Returns the actividad plan ID of this actividad plan.
	 *
	 * @return the actividad plan ID of this actividad plan
	 */
	public long getActividadPlanId();

	/**
	 * Sets the actividad plan ID of this actividad plan.
	 *
	 * @param actividadPlanId the actividad plan ID of this actividad plan
	 */
	public void setActividadPlanId(long actividadPlanId);

	/**
	 * Returns the actividad cronograma ID of this actividad plan.
	 *
	 * @return the actividad cronograma ID of this actividad plan
	 */
	public long getActividadCronogramaId();

	/**
	 * Sets the actividad cronograma ID of this actividad plan.
	 *
	 * @param actividadCronogramaId the actividad cronograma ID of this actividad plan
	 */
	public void setActividadCronogramaId(long actividadCronogramaId);

	/**
	 * Returns the plan accion ID of this actividad plan.
	 *
	 * @return the plan accion ID of this actividad plan
	 */
	public long getPlanAccionId();

	/**
	 * Sets the plan accion ID of this actividad plan.
	 *
	 * @param planAccionId the plan accion ID of this actividad plan
	 */
	public void setPlanAccionId(long planAccionId);

	/**
	 * Returns the actividad of this actividad plan.
	 *
	 * @return the actividad of this actividad plan
	 */
	@AutoEscape
	public String getActividad();

	/**
	 * Sets the actividad of this actividad plan.
	 *
	 * @param actividad the actividad of this actividad plan
	 */
	public void setActividad(String actividad);

	/**
	 * Returns the evidencia of this actividad plan.
	 *
	 * @return the evidencia of this actividad plan
	 */
	@AutoEscape
	public String getEvidencia();

	/**
	 * Sets the evidencia of this actividad plan.
	 *
	 * @param evidencia the evidencia of this actividad plan
	 */
	public void setEvidencia(String evidencia);

	/**
	 * Returns the activo of this actividad plan.
	 *
	 * @return the activo of this actividad plan
	 */
	public boolean getActivo();

	/**
	 * Returns <code>true</code> if this actividad plan is activo.
	 *
	 * @return <code>true</code> if this actividad plan is activo; <code>false</code> otherwise
	 */
	public boolean isActivo();

	/**
	 * Sets whether this actividad plan is activo.
	 *
	 * @param activo the activo of this actividad plan
	 */
	public void setActivo(boolean activo);

	/**
	 * Returns the usuariocrea of this actividad plan.
	 *
	 * @return the usuariocrea of this actividad plan
	 */
	public long getUsuariocrea();

	/**
	 * Sets the usuariocrea of this actividad plan.
	 *
	 * @param usuariocrea the usuariocrea of this actividad plan
	 */
	public void setUsuariocrea(long usuariocrea);

	/**
	 * Returns the fechacrea of this actividad plan.
	 *
	 * @return the fechacrea of this actividad plan
	 */
	public Date getFechacrea();

	/**
	 * Sets the fechacrea of this actividad plan.
	 *
	 * @param fechacrea the fechacrea of this actividad plan
	 */
	public void setFechacrea(Date fechacrea);

	/**
	 * Returns the usuariomodifica of this actividad plan.
	 *
	 * @return the usuariomodifica of this actividad plan
	 */
	public long getUsuariomodifica();

	/**
	 * Sets the usuariomodifica of this actividad plan.
	 *
	 * @param usuariomodifica the usuariomodifica of this actividad plan
	 */
	public void setUsuariomodifica(long usuariomodifica);

	/**
	 * Returns the fechamodifica of this actividad plan.
	 *
	 * @return the fechamodifica of this actividad plan
	 */
	public Date getFechamodifica();

	/**
	 * Sets the fechamodifica of this actividad plan.
	 *
	 * @param fechamodifica the fechamodifica of this actividad plan
	 */
	public void setFechamodifica(Date fechamodifica);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.hitss.layer.model.ActividadPlan actividadPlan);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.hitss.layer.model.ActividadPlan> toCacheModel();

	@Override
	public com.hitss.layer.model.ActividadPlan toEscapedModel();

	@Override
	public com.hitss.layer.model.ActividadPlan toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}