/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.hitss.layer.model;

import com.hitss.layer.service.persistence.DetalleRepuestaEvaluacionPK;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the DetalleRepuestaEvaluacion service. Represents a row in the &quot;DetalleRepuestaEvaluacion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.hitss.layer.model.impl.DetalleRepuestaEvaluacionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.hitss.layer.model.impl.DetalleRepuestaEvaluacionImpl}.
 * </p>
 *
 * @author Danielle Delgado
 * @see DetalleRepuestaEvaluacion
 * @see com.hitss.layer.model.impl.DetalleRepuestaEvaluacionImpl
 * @see com.hitss.layer.model.impl.DetalleRepuestaEvaluacionModelImpl
 * @generated
 */
public interface DetalleRepuestaEvaluacionModel extends BaseModel<DetalleRepuestaEvaluacion> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a detalle repuesta evaluacion model instance should use the {@link DetalleRepuestaEvaluacion} interface instead.
	 */

	/**
	 * Returns the primary key of this detalle repuesta evaluacion.
	 *
	 * @return the primary key of this detalle repuesta evaluacion
	 */
	public DetalleRepuestaEvaluacionPK getPrimaryKey();

	/**
	 * Sets the primary key of this detalle repuesta evaluacion.
	 *
	 * @param primaryKey the primary key of this detalle repuesta evaluacion
	 */
	public void setPrimaryKey(DetalleRepuestaEvaluacionPK primaryKey);

	/**
	 * Returns the detalle repuesta evaluacion ID of this detalle repuesta evaluacion.
	 *
	 * @return the detalle repuesta evaluacion ID of this detalle repuesta evaluacion
	 */
	public long getDetalleRepuestaEvaluacionId();

	/**
	 * Sets the detalle repuesta evaluacion ID of this detalle repuesta evaluacion.
	 *
	 * @param detalleRepuestaEvaluacionId the detalle repuesta evaluacion ID of this detalle repuesta evaluacion
	 */
	public void setDetalleRepuestaEvaluacionId(long detalleRepuestaEvaluacionId);

	/**
	 * Returns the evaluacion ID of this detalle repuesta evaluacion.
	 *
	 * @return the evaluacion ID of this detalle repuesta evaluacion
	 */
	public long getEvaluacionId();

	/**
	 * Sets the evaluacion ID of this detalle repuesta evaluacion.
	 *
	 * @param evaluacionId the evaluacion ID of this detalle repuesta evaluacion
	 */
	public void setEvaluacionId(long evaluacionId);

	/**
	 * Returns the usuario ID of this detalle repuesta evaluacion.
	 *
	 * @return the usuario ID of this detalle repuesta evaluacion
	 */
	public long getUsuarioId();

	/**
	 * Sets the usuario ID of this detalle repuesta evaluacion.
	 *
	 * @param usuarioId the usuario ID of this detalle repuesta evaluacion
	 */
	public void setUsuarioId(long usuarioId);

	/**
	 * Returns the descripcion of this detalle repuesta evaluacion.
	 *
	 * @return the descripcion of this detalle repuesta evaluacion
	 */
	@AutoEscape
	public String getDescripcion();

	/**
	 * Sets the descripcion of this detalle repuesta evaluacion.
	 *
	 * @param descripcion the descripcion of this detalle repuesta evaluacion
	 */
	public void setDescripcion(String descripcion);

	/**
	 * Returns the respuesta seleccionada of this detalle repuesta evaluacion.
	 *
	 * @return the respuesta seleccionada of this detalle repuesta evaluacion
	 */
	public long getRespuestaSeleccionada();

	/**
	 * Sets the respuesta seleccionada of this detalle repuesta evaluacion.
	 *
	 * @param respuestaSeleccionada the respuesta seleccionada of this detalle repuesta evaluacion
	 */
	public void setRespuestaSeleccionada(long respuestaSeleccionada);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.hitss.layer.model.DetalleRepuestaEvaluacion detalleRepuestaEvaluacion);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.hitss.layer.model.DetalleRepuestaEvaluacion> toCacheModel();

	@Override
	public com.hitss.layer.model.DetalleRepuestaEvaluacion toEscapedModel();

	@Override
	public com.hitss.layer.model.DetalleRepuestaEvaluacion toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}