/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.hitss.layer.model;

import com.hitss.layer.service.persistence.ExperienciaPK;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Experiencia service. Represents a row in the &quot;Experiencia&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.hitss.layer.model.impl.ExperienciaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.hitss.layer.model.impl.ExperienciaImpl}.
 * </p>
 *
 * @author Danielle Delgado
 * @see Experiencia
 * @see com.hitss.layer.model.impl.ExperienciaImpl
 * @see com.hitss.layer.model.impl.ExperienciaModelImpl
 * @generated
 */
public interface ExperienciaModel extends BaseModel<Experiencia> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a experiencia model instance should use the {@link Experiencia} interface instead.
	 */

	/**
	 * Returns the primary key of this experiencia.
	 *
	 * @return the primary key of this experiencia
	 */
	public ExperienciaPK getPrimaryKey();

	/**
	 * Sets the primary key of this experiencia.
	 *
	 * @param primaryKey the primary key of this experiencia
	 */
	public void setPrimaryKey(ExperienciaPK primaryKey);

	/**
	 * Returns the experiencia ID of this experiencia.
	 *
	 * @return the experiencia ID of this experiencia
	 */
	public long getExperienciaId();

	/**
	 * Sets the experiencia ID of this experiencia.
	 *
	 * @param experienciaId the experiencia ID of this experiencia
	 */
	public void setExperienciaId(long experienciaId);

	/**
	 * Returns the usuario ID of this experiencia.
	 *
	 * @return the usuario ID of this experiencia
	 */
	public long getUsuarioId();

	/**
	 * Sets the usuario ID of this experiencia.
	 *
	 * @param usuarioId the usuario ID of this experiencia
	 */
	public void setUsuarioId(long usuarioId);

	/**
	 * Returns the descripcion of this experiencia.
	 *
	 * @return the descripcion of this experiencia
	 */
	@AutoEscape
	public String getDescripcion();

	/**
	 * Sets the descripcion of this experiencia.
	 *
	 * @param descripcion the descripcion of this experiencia
	 */
	public void setDescripcion(String descripcion);

	/**
	 * Returns the empresa of this experiencia.
	 *
	 * @return the empresa of this experiencia
	 */
	@AutoEscape
	public String getEmpresa();

	/**
	 * Sets the empresa of this experiencia.
	 *
	 * @param empresa the empresa of this experiencia
	 */
	public void setEmpresa(String empresa);

	/**
	 * Returns the tipo negocio of this experiencia.
	 *
	 * @return the tipo negocio of this experiencia
	 */
	public long getTipoNegocio();

	/**
	 * Sets the tipo negocio of this experiencia.
	 *
	 * @param tipoNegocio the tipo negocio of this experiencia
	 */
	public void setTipoNegocio(long tipoNegocio);

	/**
	 * Returns the proyecto of this experiencia.
	 *
	 * @return the proyecto of this experiencia
	 */
	@AutoEscape
	public String getProyecto();

	/**
	 * Sets the proyecto of this experiencia.
	 *
	 * @param proyecto the proyecto of this experiencia
	 */
	public void setProyecto(String proyecto);

	/**
	 * Returns the fecha inicio of this experiencia.
	 *
	 * @return the fecha inicio of this experiencia
	 */
	public Date getFechaInicio();

	/**
	 * Sets the fecha inicio of this experiencia.
	 *
	 * @param fechaInicio the fecha inicio of this experiencia
	 */
	public void setFechaInicio(Date fechaInicio);

	/**
	 * Returns the fecha fin of this experiencia.
	 *
	 * @return the fecha fin of this experiencia
	 */
	public Date getFechaFin();

	/**
	 * Sets the fecha fin of this experiencia.
	 *
	 * @param fechaFin the fecha fin of this experiencia
	 */
	public void setFechaFin(Date fechaFin);

	/**
	 * Returns the activo of this experiencia.
	 *
	 * @return the activo of this experiencia
	 */
	public boolean getActivo();

	/**
	 * Returns <code>true</code> if this experiencia is activo.
	 *
	 * @return <code>true</code> if this experiencia is activo; <code>false</code> otherwise
	 */
	public boolean isActivo();

	/**
	 * Sets whether this experiencia is activo.
	 *
	 * @param activo the activo of this experiencia
	 */
	public void setActivo(boolean activo);

	/**
	 * Returns the usuariocrea of this experiencia.
	 *
	 * @return the usuariocrea of this experiencia
	 */
	public long getUsuariocrea();

	/**
	 * Sets the usuariocrea of this experiencia.
	 *
	 * @param usuariocrea the usuariocrea of this experiencia
	 */
	public void setUsuariocrea(long usuariocrea);

	/**
	 * Returns the fechacrea of this experiencia.
	 *
	 * @return the fechacrea of this experiencia
	 */
	public Date getFechacrea();

	/**
	 * Sets the fechacrea of this experiencia.
	 *
	 * @param fechacrea the fechacrea of this experiencia
	 */
	public void setFechacrea(Date fechacrea);

	/**
	 * Returns the usuariomodifica of this experiencia.
	 *
	 * @return the usuariomodifica of this experiencia
	 */
	public long getUsuariomodifica();

	/**
	 * Sets the usuariomodifica of this experiencia.
	 *
	 * @param usuariomodifica the usuariomodifica of this experiencia
	 */
	public void setUsuariomodifica(long usuariomodifica);

	/**
	 * Returns the fechamodifica of this experiencia.
	 *
	 * @return the fechamodifica of this experiencia
	 */
	public Date getFechamodifica();

	/**
	 * Sets the fechamodifica of this experiencia.
	 *
	 * @param fechamodifica the fechamodifica of this experiencia
	 */
	public void setFechamodifica(Date fechamodifica);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.hitss.layer.model.Experiencia experiencia);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.hitss.layer.model.Experiencia> toCacheModel();

	@Override
	public com.hitss.layer.model.Experiencia toEscapedModel();

	@Override
	public com.hitss.layer.model.Experiencia toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}