/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.hitss.layer.model;

import com.hitss.layer.service.persistence.FasePostulacionPuestoEvaluacionPK;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the FasePostulacionPuestoEvaluacion service. Represents a row in the &quot;FasePostulacionPuestoEvaluacion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.hitss.layer.model.impl.FasePostulacionPuestoEvaluacionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.hitss.layer.model.impl.FasePostulacionPuestoEvaluacionImpl}.
 * </p>
 *
 * @author Danielle Delgado
 * @see FasePostulacionPuestoEvaluacion
 * @see com.hitss.layer.model.impl.FasePostulacionPuestoEvaluacionImpl
 * @see com.hitss.layer.model.impl.FasePostulacionPuestoEvaluacionModelImpl
 * @generated
 */
public interface FasePostulacionPuestoEvaluacionModel extends BaseModel<FasePostulacionPuestoEvaluacion> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a fase postulacion puesto evaluacion model instance should use the {@link FasePostulacionPuestoEvaluacion} interface instead.
	 */

	/**
	 * Returns the primary key of this fase postulacion puesto evaluacion.
	 *
	 * @return the primary key of this fase postulacion puesto evaluacion
	 */
	public FasePostulacionPuestoEvaluacionPK getPrimaryKey();

	/**
	 * Sets the primary key of this fase postulacion puesto evaluacion.
	 *
	 * @param primaryKey the primary key of this fase postulacion puesto evaluacion
	 */
	public void setPrimaryKey(FasePostulacionPuestoEvaluacionPK primaryKey);

	/**
	 * Returns the fase postulacion ID of this fase postulacion puesto evaluacion.
	 *
	 * @return the fase postulacion ID of this fase postulacion puesto evaluacion
	 */
	public long getFasePostulacionId();

	/**
	 * Sets the fase postulacion ID of this fase postulacion puesto evaluacion.
	 *
	 * @param fasePostulacionId the fase postulacion ID of this fase postulacion puesto evaluacion
	 */
	public void setFasePostulacionId(long fasePostulacionId);

	/**
	 * Returns the solicitud funcion ID of this fase postulacion puesto evaluacion.
	 *
	 * @return the solicitud funcion ID of this fase postulacion puesto evaluacion
	 */
	public long getSolicitudFuncionId();

	/**
	 * Sets the solicitud funcion ID of this fase postulacion puesto evaluacion.
	 *
	 * @param solicitudFuncionId the solicitud funcion ID of this fase postulacion puesto evaluacion
	 */
	public void setSolicitudFuncionId(long solicitudFuncionId);

	/**
	 * Returns the evaluacion ID of this fase postulacion puesto evaluacion.
	 *
	 * @return the evaluacion ID of this fase postulacion puesto evaluacion
	 */
	public long getEvaluacionId();

	/**
	 * Sets the evaluacion ID of this fase postulacion puesto evaluacion.
	 *
	 * @param evaluacionId the evaluacion ID of this fase postulacion puesto evaluacion
	 */
	public void setEvaluacionId(long evaluacionId);

	/**
	 * Returns the resultado of this fase postulacion puesto evaluacion.
	 *
	 * @return the resultado of this fase postulacion puesto evaluacion
	 */
	public double getResultado();

	/**
	 * Sets the resultado of this fase postulacion puesto evaluacion.
	 *
	 * @param resultado the resultado of this fase postulacion puesto evaluacion
	 */
	public void setResultado(double resultado);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.hitss.layer.model.FasePostulacionPuestoEvaluacion fasePostulacionPuestoEvaluacion);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.hitss.layer.model.FasePostulacionPuestoEvaluacion> toCacheModel();

	@Override
	public com.hitss.layer.model.FasePostulacionPuestoEvaluacion toEscapedModel();

	@Override
	public com.hitss.layer.model.FasePostulacionPuestoEvaluacion toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}