/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.hitss.layer.model;

import com.hitss.layer.service.persistence.FichaIngresoPK;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the FichaIngreso service. Represents a row in the &quot;FichaIngreso&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.hitss.layer.model.impl.FichaIngresoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.hitss.layer.model.impl.FichaIngresoImpl}.
 * </p>
 *
 * @author Danielle Delgado
 * @see FichaIngreso
 * @see com.hitss.layer.model.impl.FichaIngresoImpl
 * @see com.hitss.layer.model.impl.FichaIngresoModelImpl
 * @generated
 */
public interface FichaIngresoModel extends BaseModel<FichaIngreso> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ficha ingreso model instance should use the {@link FichaIngreso} interface instead.
	 */

	/**
	 * Returns the primary key of this ficha ingreso.
	 *
	 * @return the primary key of this ficha ingreso
	 */
	public FichaIngresoPK getPrimaryKey();

	/**
	 * Sets the primary key of this ficha ingreso.
	 *
	 * @param primaryKey the primary key of this ficha ingreso
	 */
	public void setPrimaryKey(FichaIngresoPK primaryKey);

	/**
	 * Returns the fichaingreso ID of this ficha ingreso.
	 *
	 * @return the fichaingreso ID of this ficha ingreso
	 */
	public long getFichaingresoId();

	/**
	 * Sets the fichaingreso ID of this ficha ingreso.
	 *
	 * @param fichaingresoId the fichaingreso ID of this ficha ingreso
	 */
	public void setFichaingresoId(long fichaingresoId);

	/**
	 * Returns the solicitud requerimiento ID of this ficha ingreso.
	 *
	 * @return the solicitud requerimiento ID of this ficha ingreso
	 */
	public long getSolicitudRequerimientoId();

	/**
	 * Sets the solicitud requerimiento ID of this ficha ingreso.
	 *
	 * @param solicitudRequerimientoId the solicitud requerimiento ID of this ficha ingreso
	 */
	public void setSolicitudRequerimientoId(long solicitudRequerimientoId);

	/**
	 * Returns the user ID of this ficha ingreso.
	 *
	 * @return the user ID of this ficha ingreso
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this ficha ingreso.
	 *
	 * @param userId the user ID of this ficha ingreso
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this ficha ingreso.
	 *
	 * @return the user uuid of this ficha ingreso
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this ficha ingreso.
	 *
	 * @param userUuid the user uuid of this ficha ingreso
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the requiero equipo tecnico of this ficha ingreso.
	 *
	 * @return the requiero equipo tecnico of this ficha ingreso
	 */
	public boolean getRequieroEquipoTecnico();

	/**
	 * Returns <code>true</code> if this ficha ingreso is requiero equipo tecnico.
	 *
	 * @return <code>true</code> if this ficha ingreso is requiero equipo tecnico; <code>false</code> otherwise
	 */
	public boolean isRequieroEquipoTecnico();

	/**
	 * Sets whether this ficha ingreso is requiero equipo tecnico.
	 *
	 * @param requieroEquipoTecnico the requiero equipo tecnico of this ficha ingreso
	 */
	public void setRequieroEquipoTecnico(boolean requieroEquipoTecnico);

	/**
	 * Returns the reemplazo of this ficha ingreso.
	 *
	 * @return the reemplazo of this ficha ingreso
	 */
	public boolean getReemplazo();

	/**
	 * Returns <code>true</code> if this ficha ingreso is reemplazo.
	 *
	 * @return <code>true</code> if this ficha ingreso is reemplazo; <code>false</code> otherwise
	 */
	public boolean isReemplazo();

	/**
	 * Sets whether this ficha ingreso is reemplazo.
	 *
	 * @param reemplazo the reemplazo of this ficha ingreso
	 */
	public void setReemplazo(boolean reemplazo);

	/**
	 * Returns the aprobacion ficha ingreso capital humano of this ficha ingreso.
	 *
	 * @return the aprobacion ficha ingreso capital humano of this ficha ingreso
	 */
	public boolean getAprobacionFichaIngresoCapitalHumano();

	/**
	 * Returns <code>true</code> if this ficha ingreso is aprobacion ficha ingreso capital humano.
	 *
	 * @return <code>true</code> if this ficha ingreso is aprobacion ficha ingreso capital humano; <code>false</code> otherwise
	 */
	public boolean isAprobacionFichaIngresoCapitalHumano();

	/**
	 * Sets whether this ficha ingreso is aprobacion ficha ingreso capital humano.
	 *
	 * @param aprobacionFichaIngresoCapitalHumano the aprobacion ficha ingreso capital humano of this ficha ingreso
	 */
	public void setAprobacionFichaIngresoCapitalHumano(
		boolean aprobacionFichaIngresoCapitalHumano);

	/**
	 * Returns the aprobacion ficha ingreso operaciones of this ficha ingreso.
	 *
	 * @return the aprobacion ficha ingreso operaciones of this ficha ingreso
	 */
	public boolean getAprobacionFichaIngresoOperaciones();

	/**
	 * Returns <code>true</code> if this ficha ingreso is aprobacion ficha ingreso operaciones.
	 *
	 * @return <code>true</code> if this ficha ingreso is aprobacion ficha ingreso operaciones; <code>false</code> otherwise
	 */
	public boolean isAprobacionFichaIngresoOperaciones();

	/**
	 * Sets whether this ficha ingreso is aprobacion ficha ingreso operaciones.
	 *
	 * @param aprobacionFichaIngresoOperaciones the aprobacion ficha ingreso operaciones of this ficha ingreso
	 */
	public void setAprobacionFichaIngresoOperaciones(
		boolean aprobacionFichaIngresoOperaciones);

	/**
	 * Returns the activo of this ficha ingreso.
	 *
	 * @return the activo of this ficha ingreso
	 */
	public boolean getActivo();

	/**
	 * Returns <code>true</code> if this ficha ingreso is activo.
	 *
	 * @return <code>true</code> if this ficha ingreso is activo; <code>false</code> otherwise
	 */
	public boolean isActivo();

	/**
	 * Sets whether this ficha ingreso is activo.
	 *
	 * @param activo the activo of this ficha ingreso
	 */
	public void setActivo(boolean activo);

	/**
	 * Returns the usuariocrea of this ficha ingreso.
	 *
	 * @return the usuariocrea of this ficha ingreso
	 */
	public long getUsuariocrea();

	/**
	 * Sets the usuariocrea of this ficha ingreso.
	 *
	 * @param usuariocrea the usuariocrea of this ficha ingreso
	 */
	public void setUsuariocrea(long usuariocrea);

	/**
	 * Returns the fechacrea of this ficha ingreso.
	 *
	 * @return the fechacrea of this ficha ingreso
	 */
	public Date getFechacrea();

	/**
	 * Sets the fechacrea of this ficha ingreso.
	 *
	 * @param fechacrea the fechacrea of this ficha ingreso
	 */
	public void setFechacrea(Date fechacrea);

	/**
	 * Returns the usuariomodifica of this ficha ingreso.
	 *
	 * @return the usuariomodifica of this ficha ingreso
	 */
	public long getUsuariomodifica();

	/**
	 * Sets the usuariomodifica of this ficha ingreso.
	 *
	 * @param usuariomodifica the usuariomodifica of this ficha ingreso
	 */
	public void setUsuariomodifica(long usuariomodifica);

	/**
	 * Returns the fechamodifica of this ficha ingreso.
	 *
	 * @return the fechamodifica of this ficha ingreso
	 */
	public Date getFechamodifica();

	/**
	 * Sets the fechamodifica of this ficha ingreso.
	 *
	 * @param fechamodifica the fechamodifica of this ficha ingreso
	 */
	public void setFechamodifica(Date fechamodifica);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.hitss.layer.model.FichaIngreso fichaIngreso);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.hitss.layer.model.FichaIngreso> toCacheModel();

	@Override
	public com.hitss.layer.model.FichaIngreso toEscapedModel();

	@Override
	public com.hitss.layer.model.FichaIngreso toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}