/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.hitss.layer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Pregunta service. Represents a row in the &quot;Pregunta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.hitss.layer.model.impl.PreguntaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.hitss.layer.model.impl.PreguntaImpl}.
 * </p>
 *
 * @author Danielle Delgado
 * @see Pregunta
 * @see com.hitss.layer.model.impl.PreguntaImpl
 * @see com.hitss.layer.model.impl.PreguntaModelImpl
 * @generated
 */
public interface PreguntaModel extends BaseModel<Pregunta> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a pregunta model instance should use the {@link Pregunta} interface instead.
	 */

	/**
	 * Returns the primary key of this pregunta.
	 *
	 * @return the primary key of this pregunta
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this pregunta.
	 *
	 * @param primaryKey the primary key of this pregunta
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the pregunta ID of this pregunta.
	 *
	 * @return the pregunta ID of this pregunta
	 */
	public long getPreguntaId();

	/**
	 * Sets the pregunta ID of this pregunta.
	 *
	 * @param preguntaId the pregunta ID of this pregunta
	 */
	public void setPreguntaId(long preguntaId);

	/**
	 * Returns the descripcion of this pregunta.
	 *
	 * @return the descripcion of this pregunta
	 */
	@AutoEscape
	public String getDescripcion();

	/**
	 * Sets the descripcion of this pregunta.
	 *
	 * @param descripcion the descripcion of this pregunta
	 */
	public void setDescripcion(String descripcion);

	/**
	 * Returns the activo of this pregunta.
	 *
	 * @return the activo of this pregunta
	 */
	public boolean getActivo();

	/**
	 * Returns <code>true</code> if this pregunta is activo.
	 *
	 * @return <code>true</code> if this pregunta is activo; <code>false</code> otherwise
	 */
	public boolean isActivo();

	/**
	 * Sets whether this pregunta is activo.
	 *
	 * @param activo the activo of this pregunta
	 */
	public void setActivo(boolean activo);

	/**
	 * Returns the usuariocrea of this pregunta.
	 *
	 * @return the usuariocrea of this pregunta
	 */
	public long getUsuariocrea();

	/**
	 * Sets the usuariocrea of this pregunta.
	 *
	 * @param usuariocrea the usuariocrea of this pregunta
	 */
	public void setUsuariocrea(long usuariocrea);

	/**
	 * Returns the fechacrea of this pregunta.
	 *
	 * @return the fechacrea of this pregunta
	 */
	public Date getFechacrea();

	/**
	 * Sets the fechacrea of this pregunta.
	 *
	 * @param fechacrea the fechacrea of this pregunta
	 */
	public void setFechacrea(Date fechacrea);

	/**
	 * Returns the usuariomodifica of this pregunta.
	 *
	 * @return the usuariomodifica of this pregunta
	 */
	public long getUsuariomodifica();

	/**
	 * Sets the usuariomodifica of this pregunta.
	 *
	 * @param usuariomodifica the usuariomodifica of this pregunta
	 */
	public void setUsuariomodifica(long usuariomodifica);

	/**
	 * Returns the fechacreamodifica of this pregunta.
	 *
	 * @return the fechacreamodifica of this pregunta
	 */
	public Date getFechacreamodifica();

	/**
	 * Sets the fechacreamodifica of this pregunta.
	 *
	 * @param fechacreamodifica the fechacreamodifica of this pregunta
	 */
	public void setFechacreamodifica(Date fechacreamodifica);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.hitss.layer.model.Pregunta pregunta);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.hitss.layer.model.Pregunta> toCacheModel();

	@Override
	public com.hitss.layer.model.Pregunta toEscapedModel();

	@Override
	public com.hitss.layer.model.Pregunta toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}