/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.hitss.layer.model;

import com.hitss.layer.service.persistence.PuestoEvaluacionPK;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the PuestoEvaluacion service. Represents a row in the &quot;PuestoEvaluacion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.hitss.layer.model.impl.PuestoEvaluacionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.hitss.layer.model.impl.PuestoEvaluacionImpl}.
 * </p>
 *
 * @author Danielle Delgado
 * @see PuestoEvaluacion
 * @see com.hitss.layer.model.impl.PuestoEvaluacionImpl
 * @see com.hitss.layer.model.impl.PuestoEvaluacionModelImpl
 * @generated
 */
public interface PuestoEvaluacionModel extends BaseModel<PuestoEvaluacion> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a puesto evaluacion model instance should use the {@link PuestoEvaluacion} interface instead.
	 */

	/**
	 * Returns the primary key of this puesto evaluacion.
	 *
	 * @return the primary key of this puesto evaluacion
	 */
	public PuestoEvaluacionPK getPrimaryKey();

	/**
	 * Sets the primary key of this puesto evaluacion.
	 *
	 * @param primaryKey the primary key of this puesto evaluacion
	 */
	public void setPrimaryKey(PuestoEvaluacionPK primaryKey);

	/**
	 * Returns the solicitud funcion ID of this puesto evaluacion.
	 *
	 * @return the solicitud funcion ID of this puesto evaluacion
	 */
	public long getSolicitudFuncionId();

	/**
	 * Sets the solicitud funcion ID of this puesto evaluacion.
	 *
	 * @param solicitudFuncionId the solicitud funcion ID of this puesto evaluacion
	 */
	public void setSolicitudFuncionId(long solicitudFuncionId);

	/**
	 * Returns the evaluacion ID of this puesto evaluacion.
	 *
	 * @return the evaluacion ID of this puesto evaluacion
	 */
	public long getEvaluacionId();

	/**
	 * Sets the evaluacion ID of this puesto evaluacion.
	 *
	 * @param evaluacionId the evaluacion ID of this puesto evaluacion
	 */
	public void setEvaluacionId(long evaluacionId);

	/**
	 * Returns the rango superior of this puesto evaluacion.
	 *
	 * @return the rango superior of this puesto evaluacion
	 */
	public double getRangoSuperior();

	/**
	 * Sets the rango superior of this puesto evaluacion.
	 *
	 * @param rangoSuperior the rango superior of this puesto evaluacion
	 */
	public void setRangoSuperior(double rangoSuperior);

	/**
	 * Returns the rango inferior of this puesto evaluacion.
	 *
	 * @return the rango inferior of this puesto evaluacion
	 */
	public double getRangoInferior();

	/**
	 * Sets the rango inferior of this puesto evaluacion.
	 *
	 * @param rangoInferior the rango inferior of this puesto evaluacion
	 */
	public void setRangoInferior(double rangoInferior);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.hitss.layer.model.PuestoEvaluacion puestoEvaluacion);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.hitss.layer.model.PuestoEvaluacion> toCacheModel();

	@Override
	public com.hitss.layer.model.PuestoEvaluacion toEscapedModel();

	@Override
	public com.hitss.layer.model.PuestoEvaluacion toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}