/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.hitss.layer.model;

import com.hitss.layer.service.persistence.RegistrarActividadPlanUsuarioPK;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the RegistrarActividadPlanUsuario service. Represents a row in the &quot;RegisitrarActividadPlanUsuario&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.hitss.layer.model.impl.RegistrarActividadPlanUsuarioModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.hitss.layer.model.impl.RegistrarActividadPlanUsuarioImpl}.
 * </p>
 *
 * @author Danielle Delgado
 * @see RegistrarActividadPlanUsuario
 * @see com.hitss.layer.model.impl.RegistrarActividadPlanUsuarioImpl
 * @see com.hitss.layer.model.impl.RegistrarActividadPlanUsuarioModelImpl
 * @generated
 */
public interface RegistrarActividadPlanUsuarioModel extends BaseModel<RegistrarActividadPlanUsuario> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a registrar actividad plan usuario model instance should use the {@link RegistrarActividadPlanUsuario} interface instead.
	 */

	/**
	 * Returns the primary key of this registrar actividad plan usuario.
	 *
	 * @return the primary key of this registrar actividad plan usuario
	 */
	public RegistrarActividadPlanUsuarioPK getPrimaryKey();

	/**
	 * Sets the primary key of this registrar actividad plan usuario.
	 *
	 * @param primaryKey the primary key of this registrar actividad plan usuario
	 */
	public void setPrimaryKey(RegistrarActividadPlanUsuarioPK primaryKey);

	/**
	 * Returns the actividad plan ID of this registrar actividad plan usuario.
	 *
	 * @return the actividad plan ID of this registrar actividad plan usuario
	 */
	public long getActividadPlanId();

	/**
	 * Sets the actividad plan ID of this registrar actividad plan usuario.
	 *
	 * @param actividadPlanId the actividad plan ID of this registrar actividad plan usuario
	 */
	public void setActividadPlanId(long actividadPlanId);

	/**
	 * Returns the regisitrar actividad plan usuarioco ID of this registrar actividad plan usuario.
	 *
	 * @return the regisitrar actividad plan usuarioco ID of this registrar actividad plan usuario
	 */
	public long getRegisitrarActividadPlanUsuariocoId();

	/**
	 * Sets the regisitrar actividad plan usuarioco ID of this registrar actividad plan usuario.
	 *
	 * @param regisitrarActividadPlanUsuariocoId the regisitrar actividad plan usuarioco ID of this registrar actividad plan usuario
	 */
	public void setRegisitrarActividadPlanUsuariocoId(
		long regisitrarActividadPlanUsuariocoId);

	/**
	 * Returns the usuario ID of this registrar actividad plan usuario.
	 *
	 * @return the usuario ID of this registrar actividad plan usuario
	 */
	public long getUsuarioId();

	/**
	 * Sets the usuario ID of this registrar actividad plan usuario.
	 *
	 * @param usuarioId the usuario ID of this registrar actividad plan usuario
	 */
	public void setUsuarioId(long usuarioId);

	/**
	 * Returns the cumplio of this registrar actividad plan usuario.
	 *
	 * @return the cumplio of this registrar actividad plan usuario
	 */
	public long getCumplio();

	/**
	 * Sets the cumplio of this registrar actividad plan usuario.
	 *
	 * @param cumplio the cumplio of this registrar actividad plan usuario
	 */
	public void setCumplio(long cumplio);

	/**
	 * Returns the actividad of this registrar actividad plan usuario.
	 *
	 * @return the actividad of this registrar actividad plan usuario
	 */
	@AutoEscape
	public String getActividad();

	/**
	 * Sets the actividad of this registrar actividad plan usuario.
	 *
	 * @param actividad the actividad of this registrar actividad plan usuario
	 */
	public void setActividad(String actividad);

	/**
	 * Returns the puntuacion of this registrar actividad plan usuario.
	 *
	 * @return the puntuacion of this registrar actividad plan usuario
	 */
	public int getPuntuacion();

	/**
	 * Sets the puntuacion of this registrar actividad plan usuario.
	 *
	 * @param puntuacion the puntuacion of this registrar actividad plan usuario
	 */
	public void setPuntuacion(int puntuacion);

	/**
	 * Returns the activo of this registrar actividad plan usuario.
	 *
	 * @return the activo of this registrar actividad plan usuario
	 */
	public boolean getActivo();

	/**
	 * Returns <code>true</code> if this registrar actividad plan usuario is activo.
	 *
	 * @return <code>true</code> if this registrar actividad plan usuario is activo; <code>false</code> otherwise
	 */
	public boolean isActivo();

	/**
	 * Sets whether this registrar actividad plan usuario is activo.
	 *
	 * @param activo the activo of this registrar actividad plan usuario
	 */
	public void setActivo(boolean activo);

	/**
	 * Returns the usuariocrea of this registrar actividad plan usuario.
	 *
	 * @return the usuariocrea of this registrar actividad plan usuario
	 */
	public long getUsuariocrea();

	/**
	 * Sets the usuariocrea of this registrar actividad plan usuario.
	 *
	 * @param usuariocrea the usuariocrea of this registrar actividad plan usuario
	 */
	public void setUsuariocrea(long usuariocrea);

	/**
	 * Returns the fechacrea of this registrar actividad plan usuario.
	 *
	 * @return the fechacrea of this registrar actividad plan usuario
	 */
	public Date getFechacrea();

	/**
	 * Sets the fechacrea of this registrar actividad plan usuario.
	 *
	 * @param fechacrea the fechacrea of this registrar actividad plan usuario
	 */
	public void setFechacrea(Date fechacrea);

	/**
	 * Returns the usuariomodifica of this registrar actividad plan usuario.
	 *
	 * @return the usuariomodifica of this registrar actividad plan usuario
	 */
	public long getUsuariomodifica();

	/**
	 * Sets the usuariomodifica of this registrar actividad plan usuario.
	 *
	 * @param usuariomodifica the usuariomodifica of this registrar actividad plan usuario
	 */
	public void setUsuariomodifica(long usuariomodifica);

	/**
	 * Returns the fechamodifica of this registrar actividad plan usuario.
	 *
	 * @return the fechamodifica of this registrar actividad plan usuario
	 */
	public Date getFechamodifica();

	/**
	 * Sets the fechamodifica of this registrar actividad plan usuario.
	 *
	 * @param fechamodifica the fechamodifica of this registrar actividad plan usuario
	 */
	public void setFechamodifica(Date fechamodifica);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.hitss.layer.model.RegistrarActividadPlanUsuario registrarActividadPlanUsuario);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.hitss.layer.model.RegistrarActividadPlanUsuario> toCacheModel();

	@Override
	public com.hitss.layer.model.RegistrarActividadPlanUsuario toEscapedModel();

	@Override
	public com.hitss.layer.model.RegistrarActividadPlanUsuario toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}