/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.hitss.layer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SolicitudEvaluacionDesempenno service. Represents a row in the &quot;SolicitudEvaluacionDesempenno&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.hitss.layer.model.impl.SolicitudEvaluacionDesempennoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.hitss.layer.model.impl.SolicitudEvaluacionDesempennoImpl}.
 * </p>
 *
 * @author Danielle Delgado
 * @see SolicitudEvaluacionDesempenno
 * @see com.hitss.layer.model.impl.SolicitudEvaluacionDesempennoImpl
 * @see com.hitss.layer.model.impl.SolicitudEvaluacionDesempennoModelImpl
 * @generated
 */
public interface SolicitudEvaluacionDesempennoModel extends BaseModel<SolicitudEvaluacionDesempenno> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a solicitud evaluacion desempenno model instance should use the {@link SolicitudEvaluacionDesempenno} interface instead.
	 */

	/**
	 * Returns the primary key of this solicitud evaluacion desempenno.
	 *
	 * @return the primary key of this solicitud evaluacion desempenno
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this solicitud evaluacion desempenno.
	 *
	 * @param primaryKey the primary key of this solicitud evaluacion desempenno
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the solicitud evaluacion desempenno ID of this solicitud evaluacion desempenno.
	 *
	 * @return the solicitud evaluacion desempenno ID of this solicitud evaluacion desempenno
	 */
	public long getSolicitudEvaluacionDesempennoId();

	/**
	 * Sets the solicitud evaluacion desempenno ID of this solicitud evaluacion desempenno.
	 *
	 * @param solicitudEvaluacionDesempennoId the solicitud evaluacion desempenno ID of this solicitud evaluacion desempenno
	 */
	public void setSolicitudEvaluacionDesempennoId(
		long solicitudEvaluacionDesempennoId);

	/**
	 * Returns the descripcion of this solicitud evaluacion desempenno.
	 *
	 * @return the descripcion of this solicitud evaluacion desempenno
	 */
	@AutoEscape
	public String getDescripcion();

	/**
	 * Sets the descripcion of this solicitud evaluacion desempenno.
	 *
	 * @param descripcion the descripcion of this solicitud evaluacion desempenno
	 */
	public void setDescripcion(String descripcion);

	/**
	 * Returns the fecha inicio of this solicitud evaluacion desempenno.
	 *
	 * @return the fecha inicio of this solicitud evaluacion desempenno
	 */
	public Date getFechaInicio();

	/**
	 * Sets the fecha inicio of this solicitud evaluacion desempenno.
	 *
	 * @param fechaInicio the fecha inicio of this solicitud evaluacion desempenno
	 */
	public void setFechaInicio(Date fechaInicio);

	/**
	 * Returns the estado of this solicitud evaluacion desempenno.
	 *
	 * @return the estado of this solicitud evaluacion desempenno
	 */
	public long getEstado();

	/**
	 * Sets the estado of this solicitud evaluacion desempenno.
	 *
	 * @param estado the estado of this solicitud evaluacion desempenno
	 */
	public void setEstado(long estado);

	/**
	 * Returns the activo of this solicitud evaluacion desempenno.
	 *
	 * @return the activo of this solicitud evaluacion desempenno
	 */
	public boolean getActivo();

	/**
	 * Returns <code>true</code> if this solicitud evaluacion desempenno is activo.
	 *
	 * @return <code>true</code> if this solicitud evaluacion desempenno is activo; <code>false</code> otherwise
	 */
	public boolean isActivo();

	/**
	 * Sets whether this solicitud evaluacion desempenno is activo.
	 *
	 * @param activo the activo of this solicitud evaluacion desempenno
	 */
	public void setActivo(boolean activo);

	/**
	 * Returns the usuariocrea of this solicitud evaluacion desempenno.
	 *
	 * @return the usuariocrea of this solicitud evaluacion desempenno
	 */
	public long getUsuariocrea();

	/**
	 * Sets the usuariocrea of this solicitud evaluacion desempenno.
	 *
	 * @param usuariocrea the usuariocrea of this solicitud evaluacion desempenno
	 */
	public void setUsuariocrea(long usuariocrea);

	/**
	 * Returns the fechacrea of this solicitud evaluacion desempenno.
	 *
	 * @return the fechacrea of this solicitud evaluacion desempenno
	 */
	public Date getFechacrea();

	/**
	 * Sets the fechacrea of this solicitud evaluacion desempenno.
	 *
	 * @param fechacrea the fechacrea of this solicitud evaluacion desempenno
	 */
	public void setFechacrea(Date fechacrea);

	/**
	 * Returns the usuariomodifica of this solicitud evaluacion desempenno.
	 *
	 * @return the usuariomodifica of this solicitud evaluacion desempenno
	 */
	public long getUsuariomodifica();

	/**
	 * Sets the usuariomodifica of this solicitud evaluacion desempenno.
	 *
	 * @param usuariomodifica the usuariomodifica of this solicitud evaluacion desempenno
	 */
	public void setUsuariomodifica(long usuariomodifica);

	/**
	 * Returns the fechamodifica of this solicitud evaluacion desempenno.
	 *
	 * @return the fechamodifica of this solicitud evaluacion desempenno
	 */
	public Date getFechamodifica();

	/**
	 * Sets the fechamodifica of this solicitud evaluacion desempenno.
	 *
	 * @param fechamodifica the fechamodifica of this solicitud evaluacion desempenno
	 */
	public void setFechamodifica(Date fechamodifica);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.hitss.layer.model.SolicitudEvaluacionDesempenno solicitudEvaluacionDesempenno);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.hitss.layer.model.SolicitudEvaluacionDesempenno> toCacheModel();

	@Override
	public com.hitss.layer.model.SolicitudEvaluacionDesempenno toEscapedModel();

	@Override
	public com.hitss.layer.model.SolicitudEvaluacionDesempenno toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}