/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.hitss.layer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SolicitudRequerimiento service. Represents a row in the &quot;SolicitudRequerimiento&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.hitss.layer.model.impl.SolicitudRequerimientoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.hitss.layer.model.impl.SolicitudRequerimientoImpl}.
 * </p>
 *
 * @author Danielle Delgado
 * @see SolicitudRequerimiento
 * @see com.hitss.layer.model.impl.SolicitudRequerimientoImpl
 * @see com.hitss.layer.model.impl.SolicitudRequerimientoModelImpl
 * @generated
 */
public interface SolicitudRequerimientoModel extends BaseModel<SolicitudRequerimiento> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a solicitud requerimiento model instance should use the {@link SolicitudRequerimiento} interface instead.
	 */

	/**
	 * Returns the primary key of this solicitud requerimiento.
	 *
	 * @return the primary key of this solicitud requerimiento
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this solicitud requerimiento.
	 *
	 * @param primaryKey the primary key of this solicitud requerimiento
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the solicitud requerimiento ID of this solicitud requerimiento.
	 *
	 * @return the solicitud requerimiento ID of this solicitud requerimiento
	 */
	public long getSolicitudRequerimientoId();

	/**
	 * Sets the solicitud requerimiento ID of this solicitud requerimiento.
	 *
	 * @param solicitudRequerimientoId the solicitud requerimiento ID of this solicitud requerimiento
	 */
	public void setSolicitudRequerimientoId(long solicitudRequerimientoId);

	/**
	 * Returns the area solicitante of this solicitud requerimiento.
	 *
	 * @return the area solicitante of this solicitud requerimiento
	 */
	public long getAreaSolicitante();

	/**
	 * Sets the area solicitante of this solicitud requerimiento.
	 *
	 * @param areaSolicitante the area solicitante of this solicitud requerimiento
	 */
	public void setAreaSolicitante(long areaSolicitante);

	/**
	 * Returns the cantidad recursos of this solicitud requerimiento.
	 *
	 * @return the cantidad recursos of this solicitud requerimiento
	 */
	public int getCantidadRecursos();

	/**
	 * Sets the cantidad recursos of this solicitud requerimiento.
	 *
	 * @param cantidadRecursos the cantidad recursos of this solicitud requerimiento
	 */
	public void setCantidadRecursos(int cantidadRecursos);

	/**
	 * Returns the responsable r r h h of this solicitud requerimiento.
	 *
	 * @return the responsable r r h h of this solicitud requerimiento
	 */
	public long getResponsableRRHH();

	/**
	 * Sets the responsable r r h h of this solicitud requerimiento.
	 *
	 * @param responsableRRHH the responsable r r h h of this solicitud requerimiento
	 */
	public void setResponsableRRHH(long responsableRRHH);

	/**
	 * Returns the fecha limite of this solicitud requerimiento.
	 *
	 * @return the fecha limite of this solicitud requerimiento
	 */
	public Date getFechaLimite();

	/**
	 * Sets the fecha limite of this solicitud requerimiento.
	 *
	 * @param fechaLimite the fecha limite of this solicitud requerimiento
	 */
	public void setFechaLimite(Date fechaLimite);

	/**
	 * Returns the tiempo contrato of this solicitud requerimiento.
	 *
	 * @return the tiempo contrato of this solicitud requerimiento
	 */
	public long getTiempoContrato();

	/**
	 * Sets the tiempo contrato of this solicitud requerimiento.
	 *
	 * @param tiempoContrato the tiempo contrato of this solicitud requerimiento
	 */
	public void setTiempoContrato(long tiempoContrato);

	/**
	 * Returns the tipo negocio of this solicitud requerimiento.
	 *
	 * @return the tipo negocio of this solicitud requerimiento
	 */
	public long getTipoNegocio();

	/**
	 * Sets the tipo negocio of this solicitud requerimiento.
	 *
	 * @param tipoNegocio the tipo negocio of this solicitud requerimiento
	 */
	public void setTipoNegocio(long tipoNegocio);

	/**
	 * Returns the presupuesto maximo of this solicitud requerimiento.
	 *
	 * @return the presupuesto maximo of this solicitud requerimiento
	 */
	public long getPresupuestoMaximo();

	/**
	 * Sets the presupuesto maximo of this solicitud requerimiento.
	 *
	 * @param presupuestoMaximo the presupuesto maximo of this solicitud requerimiento
	 */
	public void setPresupuestoMaximo(long presupuestoMaximo);

	/**
	 * Returns the presupuesto minimo of this solicitud requerimiento.
	 *
	 * @return the presupuesto minimo of this solicitud requerimiento
	 */
	public long getPresupuestoMinimo();

	/**
	 * Sets the presupuesto minimo of this solicitud requerimiento.
	 *
	 * @param presupuestoMinimo the presupuesto minimo of this solicitud requerimiento
	 */
	public void setPresupuestoMinimo(long presupuestoMinimo);

	/**
	 * Returns the cliente of this solicitud requerimiento.
	 *
	 * @return the cliente of this solicitud requerimiento
	 */
	public long getCliente();

	/**
	 * Sets the cliente of this solicitud requerimiento.
	 *
	 * @param cliente the cliente of this solicitud requerimiento
	 */
	public void setCliente(long cliente);

	/**
	 * Returns the especialidad of this solicitud requerimiento.
	 *
	 * @return the especialidad of this solicitud requerimiento
	 */
	@AutoEscape
	public String getEspecialidad();

	/**
	 * Sets the especialidad of this solicitud requerimiento.
	 *
	 * @param especialidad the especialidad of this solicitud requerimiento
	 */
	public void setEspecialidad(String especialidad);

	/**
	 * Returns the meta of this solicitud requerimiento.
	 *
	 * @return the meta of this solicitud requerimiento
	 */
	@AutoEscape
	public String getMeta();

	/**
	 * Sets the meta of this solicitud requerimiento.
	 *
	 * @param meta the meta of this solicitud requerimiento
	 */
	public void setMeta(String meta);

	/**
	 * Returns the fechameta of this solicitud requerimiento.
	 *
	 * @return the fechameta of this solicitud requerimiento
	 */
	public Date getFechameta();

	/**
	 * Sets the fechameta of this solicitud requerimiento.
	 *
	 * @param fechameta the fechameta of this solicitud requerimiento
	 */
	public void setFechameta(Date fechameta);

	/**
	 * Returns the prioridad of this solicitud requerimiento.
	 *
	 * @return the prioridad of this solicitud requerimiento
	 */
	public long getPrioridad();

	/**
	 * Sets the prioridad of this solicitud requerimiento.
	 *
	 * @param prioridad the prioridad of this solicitud requerimiento
	 */
	public void setPrioridad(long prioridad);

	/**
	 * Returns the contenido ID of this solicitud requerimiento.
	 *
	 * @return the contenido ID of this solicitud requerimiento
	 */
	@AutoEscape
	public String getContenidoId();

	/**
	 * Sets the contenido ID of this solicitud requerimiento.
	 *
	 * @param contenidoId the contenido ID of this solicitud requerimiento
	 */
	public void setContenidoId(String contenidoId);

	/**
	 * Returns the modalidadjornada of this solicitud requerimiento.
	 *
	 * @return the modalidadjornada of this solicitud requerimiento
	 */
	public long getModalidadjornada();

	/**
	 * Sets the modalidadjornada of this solicitud requerimiento.
	 *
	 * @param modalidadjornada the modalidadjornada of this solicitud requerimiento
	 */
	public void setModalidadjornada(long modalidadjornada);

	/**
	 * Returns the modalidadcontrato of this solicitud requerimiento.
	 *
	 * @return the modalidadcontrato of this solicitud requerimiento
	 */
	public long getModalidadcontrato();

	/**
	 * Sets the modalidadcontrato of this solicitud requerimiento.
	 *
	 * @param modalidadcontrato the modalidadcontrato of this solicitud requerimiento
	 */
	public void setModalidadcontrato(long modalidadcontrato);

	/**
	 * Returns the lugar trabajo of this solicitud requerimiento.
	 *
	 * @return the lugar trabajo of this solicitud requerimiento
	 */
	@AutoEscape
	public String getLugarTrabajo();

	/**
	 * Sets the lugar trabajo of this solicitud requerimiento.
	 *
	 * @param lugarTrabajo the lugar trabajo of this solicitud requerimiento
	 */
	public void setLugarTrabajo(String lugarTrabajo);

	/**
	 * Returns the categoria puesto ID of this solicitud requerimiento.
	 *
	 * @return the categoria puesto ID of this solicitud requerimiento
	 */
	public long getCategoriaPuestoId();

	/**
	 * Sets the categoria puesto ID of this solicitud requerimiento.
	 *
	 * @param categoriaPuestoId the categoria puesto ID of this solicitud requerimiento
	 */
	public void setCategoriaPuestoId(long categoriaPuestoId);

	/**
	 * Returns the proyecto of this solicitud requerimiento.
	 *
	 * @return the proyecto of this solicitud requerimiento
	 */
	@AutoEscape
	public String getProyecto();

	/**
	 * Sets the proyecto of this solicitud requerimiento.
	 *
	 * @param proyecto the proyecto of this solicitud requerimiento
	 */
	public void setProyecto(String proyecto);

	/**
	 * Returns the tiporeclutamiento of this solicitud requerimiento.
	 *
	 * @return the tiporeclutamiento of this solicitud requerimiento
	 */
	public long getTiporeclutamiento();

	/**
	 * Sets the tiporeclutamiento of this solicitud requerimiento.
	 *
	 * @param tiporeclutamiento the tiporeclutamiento of this solicitud requerimiento
	 */
	public void setTiporeclutamiento(long tiporeclutamiento);

	/**
	 * Returns the estado of this solicitud requerimiento.
	 *
	 * @return the estado of this solicitud requerimiento
	 */
	public long getEstado();

	/**
	 * Sets the estado of this solicitud requerimiento.
	 *
	 * @param estado the estado of this solicitud requerimiento
	 */
	public void setEstado(long estado);

	/**
	 * Returns the activo of this solicitud requerimiento.
	 *
	 * @return the activo of this solicitud requerimiento
	 */
	public boolean getActivo();

	/**
	 * Returns <code>true</code> if this solicitud requerimiento is activo.
	 *
	 * @return <code>true</code> if this solicitud requerimiento is activo; <code>false</code> otherwise
	 */
	public boolean isActivo();

	/**
	 * Sets whether this solicitud requerimiento is activo.
	 *
	 * @param activo the activo of this solicitud requerimiento
	 */
	public void setActivo(boolean activo);

	/**
	 * Returns the usuariocrea of this solicitud requerimiento.
	 *
	 * @return the usuariocrea of this solicitud requerimiento
	 */
	public long getUsuariocrea();

	/**
	 * Sets the usuariocrea of this solicitud requerimiento.
	 *
	 * @param usuariocrea the usuariocrea of this solicitud requerimiento
	 */
	public void setUsuariocrea(long usuariocrea);

	/**
	 * Returns the fechacrea of this solicitud requerimiento.
	 *
	 * @return the fechacrea of this solicitud requerimiento
	 */
	public Date getFechacrea();

	/**
	 * Sets the fechacrea of this solicitud requerimiento.
	 *
	 * @param fechacrea the fechacrea of this solicitud requerimiento
	 */
	public void setFechacrea(Date fechacrea);

	/**
	 * Returns the usuariomodifica of this solicitud requerimiento.
	 *
	 * @return the usuariomodifica of this solicitud requerimiento
	 */
	public long getUsuariomodifica();

	/**
	 * Sets the usuariomodifica of this solicitud requerimiento.
	 *
	 * @param usuariomodifica the usuariomodifica of this solicitud requerimiento
	 */
	public void setUsuariomodifica(long usuariomodifica);

	/**
	 * Returns the fechamodifica of this solicitud requerimiento.
	 *
	 * @return the fechamodifica of this solicitud requerimiento
	 */
	public Date getFechamodifica();

	/**
	 * Sets the fechamodifica of this solicitud requerimiento.
	 *
	 * @param fechamodifica the fechamodifica of this solicitud requerimiento
	 */
	public void setFechamodifica(Date fechamodifica);

	/**
	 * Returns the cantidad annos rubro of this solicitud requerimiento.
	 *
	 * @return the cantidad annos rubro of this solicitud requerimiento
	 */
	public int getCantidadAnnosRubro();

	/**
	 * Sets the cantidad annos rubro of this solicitud requerimiento.
	 *
	 * @param cantidadAnnosRubro the cantidad annos rubro of this solicitud requerimiento
	 */
	public void setCantidadAnnosRubro(int cantidadAnnosRubro);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.hitss.layer.model.SolicitudRequerimiento solicitudRequerimiento);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.hitss.layer.model.SolicitudRequerimiento> toCacheModel();

	@Override
	public com.hitss.layer.model.SolicitudRequerimiento toEscapedModel();

	@Override
	public com.hitss.layer.model.SolicitudRequerimiento toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}