/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.hitss.layer.model;

import com.hitss.layer.service.persistence.UsuarioFuncionPK;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the UsuarioFuncion service. Represents a row in the &quot;UsuarioFuncion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.hitss.layer.model.impl.UsuarioFuncionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.hitss.layer.model.impl.UsuarioFuncionImpl}.
 * </p>
 *
 * @author Danielle Delgado
 * @see UsuarioFuncion
 * @see com.hitss.layer.model.impl.UsuarioFuncionImpl
 * @see com.hitss.layer.model.impl.UsuarioFuncionModelImpl
 * @generated
 */
public interface UsuarioFuncionModel extends BaseModel<UsuarioFuncion> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a usuario funcion model instance should use the {@link UsuarioFuncion} interface instead.
	 */

	/**
	 * Returns the primary key of this usuario funcion.
	 *
	 * @return the primary key of this usuario funcion
	 */
	public UsuarioFuncionPK getPrimaryKey();

	/**
	 * Sets the primary key of this usuario funcion.
	 *
	 * @param primaryKey the primary key of this usuario funcion
	 */
	public void setPrimaryKey(UsuarioFuncionPK primaryKey);

	/**
	 * Returns the user ID of this usuario funcion.
	 *
	 * @return the user ID of this usuario funcion
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this usuario funcion.
	 *
	 * @param userId the user ID of this usuario funcion
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this usuario funcion.
	 *
	 * @return the user uuid of this usuario funcion
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this usuario funcion.
	 *
	 * @param userUuid the user uuid of this usuario funcion
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the funcion ID of this usuario funcion.
	 *
	 * @return the funcion ID of this usuario funcion
	 */
	public long getFuncionId();

	/**
	 * Sets the funcion ID of this usuario funcion.
	 *
	 * @param funcionId the funcion ID of this usuario funcion
	 */
	public void setFuncionId(long funcionId);

	/**
	 * Returns the exigible of this usuario funcion.
	 *
	 * @return the exigible of this usuario funcion
	 */
	public boolean getExigible();

	/**
	 * Returns <code>true</code> if this usuario funcion is exigible.
	 *
	 * @return <code>true</code> if this usuario funcion is exigible; <code>false</code> otherwise
	 */
	public boolean isExigible();

	/**
	 * Sets whether this usuario funcion is exigible.
	 *
	 * @param exigible the exigible of this usuario funcion
	 */
	public void setExigible(boolean exigible);

	/**
	 * Returns the activo of this usuario funcion.
	 *
	 * @return the activo of this usuario funcion
	 */
	public boolean getActivo();

	/**
	 * Returns <code>true</code> if this usuario funcion is activo.
	 *
	 * @return <code>true</code> if this usuario funcion is activo; <code>false</code> otherwise
	 */
	public boolean isActivo();

	/**
	 * Sets whether this usuario funcion is activo.
	 *
	 * @param activo the activo of this usuario funcion
	 */
	public void setActivo(boolean activo);

	/**
	 * Returns the usuariocrea of this usuario funcion.
	 *
	 * @return the usuariocrea of this usuario funcion
	 */
	public long getUsuariocrea();

	/**
	 * Sets the usuariocrea of this usuario funcion.
	 *
	 * @param usuariocrea the usuariocrea of this usuario funcion
	 */
	public void setUsuariocrea(long usuariocrea);

	/**
	 * Returns the fechacrea of this usuario funcion.
	 *
	 * @return the fechacrea of this usuario funcion
	 */
	public Date getFechacrea();

	/**
	 * Sets the fechacrea of this usuario funcion.
	 *
	 * @param fechacrea the fechacrea of this usuario funcion
	 */
	public void setFechacrea(Date fechacrea);

	/**
	 * Returns the usuariomodifica of this usuario funcion.
	 *
	 * @return the usuariomodifica of this usuario funcion
	 */
	public long getUsuariomodifica();

	/**
	 * Sets the usuariomodifica of this usuario funcion.
	 *
	 * @param usuariomodifica the usuariomodifica of this usuario funcion
	 */
	public void setUsuariomodifica(long usuariomodifica);

	/**
	 * Returns the fechamodifica of this usuario funcion.
	 *
	 * @return the fechamodifica of this usuario funcion
	 */
	public Date getFechamodifica();

	/**
	 * Sets the fechamodifica of this usuario funcion.
	 *
	 * @param fechamodifica the fechamodifica of this usuario funcion
	 */
	public void setFechamodifica(Date fechamodifica);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.hitss.layer.model.UsuarioFuncion usuarioFuncion);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.hitss.layer.model.UsuarioFuncion> toCacheModel();

	@Override
	public com.hitss.layer.model.UsuarioFuncion toEscapedModel();

	@Override
	public com.hitss.layer.model.UsuarioFuncion toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}