/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.hitss.layer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the EtiquetaRelacionada service. Represents a row in the &quot;EtiquetaRelacionada&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.hitss.layer.model.impl.EtiquetaRelacionadaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.hitss.layer.model.impl.EtiquetaRelacionadaImpl}.
 * </p>
 *
 * @author Danielle Delgado
 * @see EtiquetaRelacionada
 * @see com.hitss.layer.model.impl.EtiquetaRelacionadaImpl
 * @see com.hitss.layer.model.impl.EtiquetaRelacionadaModelImpl
 * @generated
 */
public interface EtiquetaRelacionadaModel extends BaseModel<EtiquetaRelacionada> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a etiqueta relacionada model instance should use the {@link EtiquetaRelacionada} interface instead.
	 */

	/**
	 * Returns the primary key of this etiqueta relacionada.
	 *
	 * @return the primary key of this etiqueta relacionada
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this etiqueta relacionada.
	 *
	 * @param primaryKey the primary key of this etiqueta relacionada
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the etiqueta relacionada ID of this etiqueta relacionada.
	 *
	 * @return the etiqueta relacionada ID of this etiqueta relacionada
	 */
	public long getEtiquetaRelacionadaId();

	/**
	 * Sets the etiqueta relacionada ID of this etiqueta relacionada.
	 *
	 * @param etiquetaRelacionadaId the etiqueta relacionada ID of this etiqueta relacionada
	 */
	public void setEtiquetaRelacionadaId(long etiquetaRelacionadaId);

	/**
	 * Returns the tabla of this etiqueta relacionada.
	 *
	 * @return the tabla of this etiqueta relacionada
	 */
	@AutoEscape
	public String getTabla();

	/**
	 * Sets the tabla of this etiqueta relacionada.
	 *
	 * @param tabla the tabla of this etiqueta relacionada
	 */
	public void setTabla(String tabla);

	/**
	 * Returns the registro ID of this etiqueta relacionada.
	 *
	 * @return the registro ID of this etiqueta relacionada
	 */
	public long getRegistroId();

	/**
	 * Sets the registro ID of this etiqueta relacionada.
	 *
	 * @param registroId the registro ID of this etiqueta relacionada
	 */
	public void setRegistroId(long registroId);

	/**
	 * Returns the etiqueta of this etiqueta relacionada.
	 *
	 * @return the etiqueta of this etiqueta relacionada
	 */
	public long getEtiqueta();

	/**
	 * Sets the etiqueta of this etiqueta relacionada.
	 *
	 * @param etiqueta the etiqueta of this etiqueta relacionada
	 */
	public void setEtiqueta(long etiqueta);

	/**
	 * Returns the tag ID of this etiqueta relacionada.
	 *
	 * @return the tag ID of this etiqueta relacionada
	 */
	public long getTagId();

	/**
	 * Sets the tag ID of this etiqueta relacionada.
	 *
	 * @param tagId the tag ID of this etiqueta relacionada
	 */
	public void setTagId(long tagId);

	/**
	 * Returns the group ID of this etiqueta relacionada.
	 *
	 * @return the group ID of this etiqueta relacionada
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this etiqueta relacionada.
	 *
	 * @param groupId the group ID of this etiqueta relacionada
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this etiqueta relacionada.
	 *
	 * @return the company ID of this etiqueta relacionada
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this etiqueta relacionada.
	 *
	 * @param companyId the company ID of this etiqueta relacionada
	 */
	public void setCompanyId(long companyId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.hitss.layer.model.EtiquetaRelacionada etiquetaRelacionada);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.hitss.layer.model.EtiquetaRelacionada> toCacheModel();

	@Override
	public com.hitss.layer.model.EtiquetaRelacionada toEscapedModel();

	@Override
	public com.hitss.layer.model.EtiquetaRelacionada toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}